#+TITLE:     H
#+AUTHOR:    Hao Ruan
#+EMAIL:     haoru@cisco.com
#+LANGUAGE:  en
#+LINK_HOME: http://www.github.com/ruanhao
#+OPTIONS:   h:6 html-postamble:nil html-preamble:t tex:t f:t ^:nil
#+STARTUP:   showall
#+TOC:       headlines 3
#+HTML_DOCTYPE: <!DOCTYPE html>
#+HTML_HEAD: <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Inconsolata:400,700" rel="stylesheet" type="text/css" />
#+HTML_HEAD: <link href="../org-html-themes/solarized/style.css" rel="stylesheet" type="text/css" />
 #+HTML: <div class="outline-2" id="meta">
| Author   | {{{author}}} ({{{email}}})    |
| Date     | {{{time(%Y-%m-%d %H:%M:%S)}}} |
#+HTML: <a href="#bottom">⇩</a>
#+HTML: <a id="top"/>
#+HTML: </div>


* [[https://wordsinasentence.com/hackneyed-in-a-sentence/][Hackneyed]]

  =repeated too often; overused=

  - Too often used by young girls, the word “like” has become hackneyed.
  - Every time my internet goes down, the cable company gives me a hackneyed explanation.
  - Although I like him as a talk show host, his hackneyed *catchphrase* =口头禅= is starting to get on my nerves!
  - The *impersonator’s* performance was made worse by his hackneyed impressions.
  - Since dyeing your hair purple has become a hackneyed style, I am dyeing my hair green!
  - When it comes to writing, teachers frown against students using hackneyed phrases.
  - “A hackneyed version of her previous works” is how the critics described the author’s new novel.



* [[https://wordsinasentence.com/haggle-in-a-sentence/][Haggle]]

  =to engage in conversation to reach a deal=

  - To get a good bargain, Jake will haggle with the flea market vendors.
  - The car dealership advertises itself as a “no haggle” business where a customer does not have to argue for a great deal.
  - During the investment meeting, the company CEO and the potential investor will haggle over the value of the organization.
  - I’ll pay the *sticker price* =标价= because I do not want to haggle with the trader.



* [[https://wordsinasentence.com/hamper-in-a-sentence/][Hamper]]

  =to delay progress=

  - This awful traffic is definitely going to hamper our trip to the beach.
  - According to economists, the high rate of unemployment will continue to hamper economic growth.
  - The stormy weather will hamper rescue efforts in the mountains.
  - In her notes, the mediator wrote how the lack of communication seemed to hamper the creation of a settlement.
  - The school district’s severe budget cuts may hamper the flow of education in our schools.
  - Even though I would like to fly to Paris with my friends, my lack of funds is going to hamper my journey.
  - Your heavy costume is sure to hamper your movements.



* [[https://wordsinasentence.com/haphazard-in-a-sentence/][Haphazard]]

  =random, chaotic, incomplete=

  - Compared to her mother’s organized system, Jen’s approach to housekeeping was haphazard, at best.
  - The haphazard arrangement of different types of flowers created a surprisingly beautiful bouquet.
  - Because of the haphazard mixture of fabric pieces and the way they’re laid out, they call this a crazy quilt.
  - Steven’s notes were a haphazard jumble of thoughts and I couldn’t make any sense out of them.
  - Her haphazard method of arranging the furniture made the den look cluttered and somewhat disturbing.
  - While her life had been characterized by a series of haphazard events, Cynthia somehow managed to develop into a very organized, structured businesswoman.
  - If you notice haphazard circles on the surface of the ocean, keep watching because it means whales have been jumping in the area.



* [[https://wordsinasentence.com/hatch-in-a-sentence/][Hatch]]

  =a small opening in a wall, roof, or floor=

  - Ship workers opened the hatch and climbed down into the cargo hold area.
  - The hatch in the floor led to a damp basement.
  - As the fire raged, the homeowners escaped through a hatch in the roof.
  - A small hatch in the library wall led to a secret room.



* [[https://wordsinasentence.com/haughty-in-a-sentence/][Haughty]]

  =proud and unfriendly=

  - Because she was not nice, the haughty girl had few friends.
  - The principal at my school is haughty and considers herself to be above everyone else.
  - When the haughty CEO ignored the stockholders at the annual conference, the board of directors gave him a stern lecture.
  - Everyone likes Jenna because she is down-to-earth and not haughty.
  - Beneath Cathy’s haughty appearance, the psychiatrist saw a scared little girl who simply wanted to be loved.
  - The diva’s distant and haughty behavior made people forget just how talented she was.
  - In order to be a great waitress, you should be humble and not haughty.



* [[https://wordsinasentence.com/hearten-in-a-sentence/][Hearten]]

  =to encourage; give strength=

  - I tried to hearten my depressed classmate with encouraging words.
  - The pastor’s sermon seemed to hearten those who were going through trials and tribulations.
  - There seemed to be no way to hearten the disappointed group of hikers after their trip was cancelled.
  - A homemade card could hearten my mother even on her darkest day.



* [[https://wordsinasentence.com/heartfelt-in-a-sentence/][Heartfelt]]

  =honestly meant; sincere=

  - The heartfelt card brought tears to my eyes.
  - Because the apology was heartfelt, I accepted it without hesitation.
  - The person who saved my life has my heartfelt thanks.
  - After winning the award, the actress expressed her heartfelt gratitude to her parents.



* [[https://wordsinasentence.com/hedonist-in-a-sentence/][Hedonist]]

  =one who believes the pursuit of pleasure is the most important thing in life=

  - My neighbor is a hedonist who likes to party all night.
  - While Janice was on the cruise ship, she lived the life of a hedonist and spent most of her days in search of pleasure.
  - Carol’s aunt is a hedonist who pursues her own pleasures outside of her marriage.
  - Because he is a hedonist, Henry never does anything which does not give him joy.
  - When the actor used drugs, he became a hedonist and refused to go on set unless his trailer was filled with booze and women.
  - My cousin Joyce is a hedonist who enjoys having fun so much she cannot keep a regular job.
  - Even though Alan makes jokes about being a hedonist, he has taken a religious vow to help those in need.



* [[https://wordsinasentence.com/heed-in-a-sentence/][Heed]]

  =to mind someone’s advice or suggestion=

  - My sister is always in need of cash because she is unwilling to heed my financial advice.
  - Since James is a swimming champion, it would do you well to heed his advice on refining your stroke.
  - John lost his entire life savings because he was too arrogant to heed my tips on the stock market.
  - If you have a weak stomach, take heed and do not watch the horror film because it has some really gruesome scenes.
  - The foolish boy suffered a great deal of pain when he chose not to heed the cautionary note on the electric fence.
  - When you are worried about something, you simply need to heed your inner voice and let it guide you.
  - The basketball player was ejected from the game when he did not heed the referee’s warning.



* [[https://wordsinasentence.com/heinous-in-a-sentence/][Heinous]]

  =hatefully or shockingly evil=

  - The criminal received the death penalty for his heinous crime.
  - When I forgot my wedding anniversary, my wife told me I had committed a heinous act.
  - The priest told the man that only God could forgive him for his heinous actions.
  - For the right amount, the *sleazy* lawyer will represent even the most heinous criminals.
  - Do you believe individuals who experienced troubled childhoods are more likely to commit heinous crimes than their counterparts who had healthy childhoods?
  - The president promised the public that the people who performed the heinous act of violence against the school children would be punished to the fullest extent of the law.
  - Even as the death row inmate prepared to take his final breath, he still refused to apologize for his heinous deeds.



* [[https://wordsinasentence.com/herald-in-a-sentence/][Herald]]

  =a messenger, especially one bringing important news=

  - Because he was always up-to-date on the latest information, we referred to our friend as a herald.
  - The herald was to announce the name of the new baby Prince later that afternoon.
  - The office herald came to everyone’s office to bring us news of the impending merger.
  - Our school herald delivered the announcements every morning.



* [[https://wordsinasentence.com/herbaceous-in-a-sentence/][Herbaceous]]

  =related to herbs any plant used for flavoring, food, medicine, or perfume=

  - The chef crafted an herbaceous *paste* =面团= and *spiked* the dish with a hint of mint and lemon.
  - With one bite of the sage-filled soup, the taste of the earthy dish overpowered my taste buds with its herbaceous wonder.
  - Herbaceous odors filled the kitchen as my mother cooked her signature dish using both basil and cilantro.
  - Herbaceous flavors were used in the medicine, helping the *aftertaste* =回味= be more plantlike rather than fishy.



* [[https://wordsinasentence.com/heterodox-in-a-sentence/][Heterodox]]

  =different from what is considered the norm=

  - The church will excommunicate anyone who preaches heterodox beliefs.
  - When the dictator took power, he ordered the death of anyone who held ideas heterodox to his own.
  - Many of the old professors did not like the heterodox teaching strategies proposed by their young colleague.
  - Whoever would have thought the heterodox coaching strategy would turn the worse team in the county into the state champions?



* [[https://wordsinasentence.com/hiatus-in-a-sentence/][Hiatus]]

  =a period of time when something is stopped=

  - After Mary had a baby, she took a brief hiatus from work.
  - The professor will take his family on a long vacation during his hiatus.
  - Although the singer took a two-year hiatus from touring, she has not lost her ability to entertain a crowd.
  - My doctor suggests I take a hiatus from my job while I am recovering from knee surgery.
  - While my husband is stationed overseas in an isolated area, our nightly phone chats will be on a temporary hiatus.
  - When the school reopens after the holiday hiatus, the entire building will have been repainted.
  - My boss gave me a paid hiatus after I closed a huge deal.



* [[https://wordsinasentence.com/hieroglyphic-in-a-sentence/][Hieroglyphic]]

  =writing that is done in hieroglyphics=

  - The writings of the ancient Egyptians was almost entirely hieroglyphic, based on pictures and drawings.
  - Hieroglyphic languages do not use written letters like we are used to, but pictures and drawn images.
  - The cave paintings of ancient cavemen could be considered hieroglyphic since they are based on imagery.
  - Hieroglyphic writing is based on visual drawings and pictures instead of a written language like most are used to.



* [[https://wordsinasentence.com/hilarity-in-a-sentence/][Hilarity]]

  =loud laughter or fun=

  - The hilarity of the comedy show was interrupted by a brawl in the audience.
  - Since the movie is supposed to be a really funny comedy, my friend and I are expecting a night of hilarity.
  - The comedian was pleased when the audience responded with hilarity to his jokes.
  - Before going to bed each night, the children enjoy thirty minutes of hilarity by watching their favorite cartoon.



* [[https://wordsinasentence.com/histrionic-in-a-sentence/][Histrionic]]

  =over the top with emotional responses=

  - When John does not take his psychiatric medicine, he might have a histrionic outburst about the smallest of things.
  - The widow’s histrionic screaming made the detectives suspicious.
  - Whenever the spoiled toddler does not get her way, she begins to yell in a histrionic manner.
  - Everyone wanted to know why the actor performed the dramatic role in a histrionic way.



* [[https://wordsinasentence.com/hitherto-in-a-sentence/][Hitherto]]

  =up until this time or point=

  - Hitherto Jim got married and became a devoted spouse, his greatest pleasure had been *picking up women*.
  - Before John learned to fly an airplane, he had hitherto been afraid of heights.
  - Hitherto Carmelo was thought a suspect in his wife’s murder and forbidden to leave town.
  - When Candace moved out of her parents’ house, she began to enjoy all of the freedoms that hitherto had been denied her.



* [[https://wordsinasentence.com/hospitable-in-a-sentence/][Hospitable]]

  =welcoming and warm to visitors=

  - The hospitable host of the bed and breakfast opens the front door for each of her guests.
  - Because John was having a bad day, he was not very hospitable to his friends when they came to visit.
  - The hospitable doorman offered Ann a cold bottle of water as soon as she stepped out the door.
  - Although the restaurant does not have the best food, I go there often because the hospitable staff treats me like family.



* [[https://wordsinasentence.com/hostile-in-a-sentence/][Hostile]]

  =unfriendly; menacing=

  - When the police officer pointed the gun at me, he looked quite hostile.
  - April left her job because of the hostile work environment.
  - When I saw the hostile man approaching my car, I immediately locked my doors.
  - The hostile dog growled at me.



* [[https://wordsinasentence.com/huddle-in-a-sentence/][Huddle]]

  =to crowd together, typically for warmth or privacy=

  - A football team will often huddle together so they can discuss their game plan without the other team seeing or hearing it.
  - Penguins like to huddle together so they can share their body warmth in the cold wastelands of their home.
  - My two young children decided to huddle together when the lightning and thunder from the storm above our house frightened them.
  - The soccer team decided to huddle together at the end of the game and congratulate the coach and each other on their victory.



* [[https://wordsinasentence.com/humdrum-in-a-sentence/][Humdrum]]

  =without excitement or variety; boring=

  - An exciting vacation would give me time away from my humdrum job.
  - When I saw everyone sitting down at the humdrum event, I knew the evening was going to be boring.
  - With so many fights on the field, the game was far from humdrum.
  - Jack fell asleep during the professor’s humdrum speech.



* [[https://wordsinasentence.com/hurl-in-a-sentence/][Hurl]]

  =to fling or toss something powerfully=

  - When Sarah teased her little brother, he took the book in his hand and decided to hurl it at her breaking her nose.
  - Riots broke out in the city causing rioters to hurl *Molotov cocktails* =燃烧瓶= at the approaching police.
  - When people get mad at their computers, they will often think they want to hurl it out the window causing it to smash on the ground.
  - *Pitchers* will hurl the baseball at the *catchers* in a baseball game which will usually get *clocked* =测...的速度= at a 100 miles per hour.



* [[https://wordsinasentence.com/hyperbole-in-a-sentence/][Hyperbole]]

  =an extravagant exaggeration=

  - The main element of the product’s commercial was a hyperbole describing rapid weight loss.
  - Although what I said may sound like a hyperbole, it really is the truth.
  - The author used one hyperbole after another to get his point across to his readers.
  - Because Janice was a drama queen, she used a hyperbole in practically every sentence.
  - During the hurricane, it seemed as though the hyperbole, “raining cats and dogs”, was almost accurate.
  - It would be great if you could simply tell me the basic facts without including a hyperbole of any sort.
  - If the politician uses one more hyperbole in his speech, I will know he is exaggerating about all his claims.



* [[https://wordsinasentence.com/hypnotic-in-a-sentence/][Hypnotic]]

  =tending to induce sleep=

  - If I take too high a dosage of the medication, its hypnotic affect will cause me to drift into a deep sleep.
  - Melatonin is a natural hormone that is used as a sleep aid because of its hypnotic affect.
  - After taking a bite of the hypnotic apple provided by the Evil Queen, Aurora fell under a sleeping spell.
  - Falling into a hypnotic trance, the patient woke up only after the psychiatrist snapped three times.



* [[https://wordsinasentence.com/hypochondriac-in-a-sentence/][Hypochondriac]]

  =one who believes he or she is always ill=

  - Because my uncle is a hypochondriac, he is quick to diagnose himself with a life-threatening illness.
  - My college roommate was a hypochondriac who wore a facial mask to avoid inhaling germs.
  - Being a hypochondriac, Gina will go to the emergency room after sneezing only once.
  - The hypochondriac does not realize his doctor is giving him sugar pills for his imaginary *ailments*.



* [[https://wordsinasentence.com/haggard-in-a-sentence/][Haggard]]

  =appearing in poor health or spirits=

  - The woman looked haggard after sitting up for a week with her dying husband.
  - Using makeup, the artist turned the young actress into a haggard old woman.
  - The soldiers looked exhausted and haggard after walking forty miles through the desert.
  - From Jared’s haggard appearance, it is obvious he had way too much to drink last night.
  - The soldier was haggard after watching many of his friends die in battle.
  - Upon news of my mother’s death, my once vibrant father suddenly appeared haggard.
  - The haggard peasant looked as though he had not eaten in weeks.



* [[https://wordsinasentence.com/halcyon-in-a-sentence/][Halcyon]]

  =calm and undisturbed=

  - I was very content during the halcyon days of my childhood.
  - Because the waters are halcyon, today is a great day for a boat trip.
  - The isolated cabin is sure to provide me with a halcyon escape from the noise of the crowded city.
  - After three months, the celebrity couple’s halcyon marriage transformed into a path to divorce.
  - The building of the noisy multi-lane highway is sure to destroy the halcyon nature of the small town.
  - After we survived the weekend storms, we were gifted with halcyon weather.
  - With all the wars on this planet, we are definitely not living in halcyon times.



* [[https://wordsinasentence.com/hanker-in-a-sentence/][Hanker]]

  =to yearn or pine to do something=

  - After years of an unhappy marriage, the man begin to hanker to have an affair.
  - The homesick woman began to hanker for a trip to see her parents.
  - After a year away from the shore, the *beach bum* =海滩迷= began to hanker for a day he could spend surfing.
  - Should you hanker for room service in the middle of the night, be prepared to pay steep prices for the food you long for.



* [[https://wordsinasentence.com/hankering-in-a-sentence/][Hankering]]

  =to have an endless craving for or to do something=

  - I hope my husband has a hankering for fried chicken since that’s what we’re having for dinner.
  - Because I hate being hot, I never have a hankering to go to the beach.
  - Watching the woman make the vase gave me a hankering to take a pottery class.
  - If you have a hankering for the best ribs in town, then you have to go to Fat Matt’s Rib Shack.




* [[https://wordsinasentence.com/harangue-in-a-sentence/][Harangue]]

  =a loud and aggressive speech; verbal attack=

  - Even though the members of the church were falling asleep, the minister continued his harangue on the evils of society.
  - During last month’s meeting, the PTA president gave a harangue against the new superintendent.
  - While I met with Joe to have a friendly chat, he wanted to deliver another harangue about his dissatisfaction with life.
  - As usual, the priest made his usual harangue about the dangers of listening to rap music.
  - Because I spent the rent money on clothes, I will have to endure a harangue from my husband.
  - The comedian does a hilarious harangue about obnoxious celebrities.
  - Although the student council president made a passionate harangue, no one believed the students would be allowed to have a dance.



* [[https://wordsinasentence.com/harbinger-in-a-sentence/][Harbinger]]

  =one that pioneers in or initiates a major change=

  - Everyone knows the groundhog is the harbinger of a change in seasons.
  - Whenever I see clouds, I know they are a harbinger of an approaching storm.
  - The surprisingly chilly day in September is a harbinger of all that winter has to offer.
  - When the two enemies called a truce, everyone saw this action as a harbinger in their relationship.
  - Sadly I realize my persistent headache is a harbinger of the flu virus that has attacked me.
  - The birth of the young prince is a harbinger of the country’s bright future.
  - In many movies, the harbinger of death is portrayed as the grim reaper.



* [[https://wordsinasentence.com/hardihood-in-a-sentence/][Hardihood]]

  =bravery; confidence to take action=

  - The volunteer firefighter’s hardihood shined through as he burst into the burning home and saved the trapped residents.
  - Confident in his actions, the *whistleblower* =告密者= showed hardihood when he reported the illegal activities of his superiors.
  - The hardihood of the solider helped him survive while lost in the jungle while never giving up.
  - Known for his hardihood, the self-made millionaire was not afraid to take risks in business.



* [[https://wordsinasentence.com/hardy-in-a-sentence/][Hardy]]

  =tough; resilient=

  - Trees in the woodland are hardy, withstanding cold winters and severe weather in the spring.
  - Country boys are hardy and never cry when they fall or whine when they get hurt outside.
  - Although he was toughly criticized, Dr. Martin Luther King was hardy and never gave in to mounting pressure against his movement.
  - The hardy flowers bloomed year after year, even after facing icy storms that would kill most plants.



* [[https://wordsinasentence.com/harness-in-a-sentence/][Harness]]

  =straps or fittings used to hold something in place=

  - The tightrope walker was fitted with a harness to stop him from plummeting to his death if he slipped.
  - A harness was needed to insure that the rollercoaster riders did not slip out the seatbelt while upside down.
  - Each horse was fitted with a harness before being led through the children’s parade.
  - The caving adventurer was lowered into the abyss while wearing a harness to protect him from a steep fall.



* [[https://wordsinasentence.com/harrow-in-a-sentence/][Harrow]]

  =a farming device with sharp metal blades that is dragged across land to smooth or break up the soil=

  - Once the harrow broke up the *clods* of dirt on the farm, the farmer was able to plant the seeds.
  - Purchasing a harrow will allow any farmer to prepare their soil more quickly for production.
  - At the farm equipment auction, a harrow was bought by someone who realized the value in this equipment on his hard clay dirt.
  - Without having access to a harrow, the pioneer could only harvest his soil by hand.



* [[https://wordsinasentence.com/hasten-in-a-sentence/][Hasten]]

  =to move in a quick fashion=

  - Marilyn made an attempt to hasten the death of her elderly husband by putting *arsenic* in his food.
  - Sadly, the new tax law will hasten the closure of many small businesses.
  - Failing to wash your hands properly will hasten the spread of the flu virus.
  - When I was a kid, I would often try to hasten the arrival of Christmas by going to bed early on Christmas Eve.
  - Chewing the medication will not hasten the drug’s *onset* =发作= and cause it to act faster.
  - When the store manager saw the long lines at the registers, he called for more cashiers to hasten customer checkouts.
  - The evil *slumlord* =平民窟房东= was convicted of taking illegal actions to hasten his tenants’ evictions.



* [[https://wordsinasentence.com/hasty-in-a-sentence/][Hasty]]

  =speedy; hurried=

  - The professor’s hasty speech confused the students as they had no clue what he had said.
  - After making several hasty purchases in one day, the shopper felt guilty.
  - The thief made a hasty exit out the door after stealing several diamond rings.
  - Though they had only dated for a month, the couple *made a hasty rush to the altar*.



* [[https://wordsinasentence.com/hazy-in-a-sentence/][Hazy]]

  =cloudy; foggy=

  - Because the windshield was so fogged up, everything along the highway looked hazy.
  - The hazy trees blocked the western view of the river.
  - After his accident, the man’s memory of the events was blurred and hazy.
  - Clouds of smoke that filled the bar made for a hazy atmosphere.



* [[https://wordsinasentence.com/headlong-in-a-sentence/][Headlong]]

  =done rashly and without thinking=

  - The teenagers jumped headlong into a committed relationship.
  - She signed the document headlong without considering the *implications*.
  - The adventurous man had a habit of diving headlong into new risky business ventures.
  - Without thinking, the good samaritan had rushed headlong into the fire.



* [[https://wordsinasentence.com/headway-in-a-sentence/][Headway]]

  =progress or forward movement=

  - Just when then counselor thought they were making headway, the couple decided to end their therapy sessions.
  - The student’s grades were improving, but he did not make as much headway as his teacher had.
  - Little headway was made by the troop against enemy forces.
  - The prosecutor made no headway in trying to convince the judge to postpone bail.



* [[https://wordsinasentence.com/heady-in-a-sentence/][Heady]]

  =a strong, intense, or exhilarating effect=

  - Many pilots find supersonic flight to be a heady experience, providing them with exhilaration that can’t be matched by anything else.
  - The reason people find it so easy to become addicted to alcohol is because the heady experience it provides makes them come back for more, especially when they are stressed.
  - A heady experience can best be described as one that is so exciting or exhilarating that you want even more of it.
  - I do not see why people get so attached to drugs, but apparently the high is heady enough to make them do anything for more.



* [[https://wordsinasentence.com/hearken-in-a-sentence/][Hearken]]

  =to listen=

  - Confident and proud, the young man refused to hearken his parents’ advice.
  - The boy was confused about the directions because he did not hearken his teacher’s lecture.
  - An inability to hearken simple instructions caused the distracted passenger to miss his stop.
  - If my brother would hearken my advice, he would make much better grades in school.



* [[https://wordsinasentence.com/hearsay-in-a-sentence/][Hearsay]]

  =information gained from a source that was not directly involved and cannot be proved accurate=

  - Without a witness, the police could not prove that the hearsay was anything more than fiction.
  - Don't believe the teacher's hearsay about school being closed tomorrow due to the snowstorm unless you hear it directly from the news.
  - I would regard the layoff rumors as hearsay, because they've been swirling around for months and our company has been growing.
  - Court officials dismissed the witness’s testimony as hearsay.



* [[https://wordsinasentence.com/heave-in-a-sentence/][Heave]]

  =to use a lot of effort while moving something=

  - A half-court heave of the ball ended in a surprising *buzzer beater* =绝杀= win for the underdogs.
  - With each heave of the *spade*, the man shoveled more and more snow out of the driveway.
  - After he tried to heave the heavy weight above his head for a third time, the weak lifter decided to give up.
- Because we were in a rush to get on the road, my brother and I quickly began to heave our clothes into a suitcase.



* [[https://wordsinasentence.com/heckle-in-a-sentence/][Heckle]]

  =to interrupt a speaker with insulting or rude comments=

  - As they began to heckle the speaker with insulting gestures, the two protesters were escorted from the building.
  - The crowd began to boo and heckle the comedian as he bombed his comedy set.
  - A group of pranksters stood outside of the school so that they could heckle the principal.
  - Hurling insults from the *bleachers* =体育场馆的廉价露天座位= , a few parents from the opposing team began to heckle the batter stepping up to the plate.



* [[https://wordsinasentence.com/hectic-in-a-sentence/][Hectic]]

  =quite busy with goings-on and uncertainty=

  - Since I have a lot to do this week, my schedule is going to be very hectic.
  - Candace’s life became hectic after she learned she had to plan a wedding in two days.
  - Despite my father’s hectic travel schedule, he still manages to get home every weekend.
  - The processing pace is hectic, but once you find the right rhythm, you should be able to keep up on the assembly line.



* [[https://wordsinasentence.com/hedge-in-a-sentence/][Hedge]]

  =bushes or shrubs that form a boundary as they grow closely together in a row=

  - An ever-growing hedge stops nosy neighbors from being able to see into the back yard.
  - Trimming the tall hedge, the lawn maintenance worker made sure to keep the bush looking neat.
  - Forming a hedge around the moat, the *prickly* *shrubs* provided even more protection for the king’s castle.
  - My mother insisted my father remove the hedge that circled around our house since she preferred trees over bushes.



* [[https://wordsinasentence.com/hermetic-in-a-sentence/][Hermetic]]

  =associated with a lifestyle in which a person or group is isolated from others=

  - As a freelance writer who rarely leaves her house, Kate lives a hermetic lifestyle.
  - The billionaire bought a private island so he could raise his kids in a hermetic environment.
  - Because the monk maintained a hermetic lifestyle for twenty years, he was overwhelmed when he moved to a crowded city.
  - The hermetic tribe lives in an isolated part of the continent and has little contact with people outside of its group.



* [[https://wordsinasentence.com/hew-in-a-sentence/][Hew]]

  =using heavy blows to hack with a tool or instrument=

  - When my father got angry with my mother, he would go in the backyard and hew wood with his axe.
  - The man used a *scythe* to hew his way through the field of grass.
  - While the little boy wanted to hew trees with his big brother, he was too small to wield an axe.
  - The jeweler has tools that allow him to hew precious stones so they will fit in specific ring bases.



* [[https://wordsinasentence.com/hidebound-in-a-sentence/][Hidebound]]

  =rigidly opposed to change=

  - The hidebound politician refused to change his position on the abortion bill.
  - Because my grandmother is hidebound, she does not believe in interracial marriage.
  - The older members of the club are hidebound and will not consider changing the group’s membership requirements.
  - In some cultures, men remain hidebound to the belief women should not show their faces in public.



* [[https://wordsinasentence.com/hinder-in-a-sentence/][Hinder]]

  =to hold back or to make difficult to accomplish=

  - Tight, restrictive clothing will work to hinder your athletic performance.
  - Having misaligned tires is a sure way to hinder your driving.
  - If you do not rest enough, you will actually hinder your workout progress.
  - Drinking alcohol after you exercise is sure to hinder your progress.
  - The power outage hindered his ability to get his research done.
  - If you fail to tie your shoes, you will hinder your ability to run.
  - An ankle injury will greatly hinder your ability to exercise.



* [[https://wordsinasentence.com/hoarse-in-a-sentence/][Hoarse]]

  =afflicted by a dry, quite harsh voice=

  - Jessica was unable to sing with the choir because her voice sounded hoarse.
  - When I had my tonsils taken out, I was so hoarse I could only whisper for days.
  - Kason yelled so much at the basketball game that he woke up hoarse the next morning.
  - Drinking hot tea with honey and lemon is supposed to help a person who is feeling hoarse.



* [[https://wordsinasentence.com/hoary-in-a-sentence/][Hoary]]

  =incredibly old=

  - The hoary house was built in the eighteenth century and is now part of a museum.
  - When someone told me Jeff’s girlfriend was hoary, I could not believe my pal would date a woman three times his age.
  - The hoary tree has been living in the field for over two centuries.
  - Because the computer is hoary, it is doubtful it will function after being in a closet for nearly twenty years.



* [[https://wordsinasentence.com/hoax-in-a-sentence/][Hoax]]

  =a ploy or story used to trick a person or group=

  - The woman used a pregnancy hoax to trick her boyfriend into marrying her.
  - If the magazine editor believes the picture is a hoax, he will not publish it.
  - The hoax about the bomb was enough to get the prankster arrested.
  - Before the insurance company pays the claim, they will send an investigator to ensure the man’s injury is not a hoax.



* [[https://wordsinasentence.com/hoist-in-a-sentence/][Hoist]]

  =to lift up or elevate=

  - We grabbed the flag and began to hoist it up the flagpole.
  - A crane was needed to hoist Jessica’s car out of the river.
  - We helped Mike hoist the groom onto his shoulders.
  - John will hoist up his banner and wave it to get attention.



* [[https://wordsinasentence.com/homage-in-a-sentence/][Homage]]

  =an act performed to show respect=

  - As a sign of homage for the *late president*, government flags will be flown half-mast today.
  - To show homage, the poor people brought gifts to the god's temple.
  - The soldiers displayed homage to their fallen comrade by saluting his coffin.
  - When the singer accepted his award, he paid homage to all of his musical inspirations by thanking them in his speech.



* [[https://wordsinasentence.com/homely-in-a-sentence/][Homely]]

  =unattractive and plain in appearance=

  - The homely girl’s classmates thought she needed a makeover to make her more attractive.
  - Homely and plain, the woman was known for her delicious cooking but not her looks.
  - If modest Martha would put on makeup and a party dress, he might appear less homely.
  - Embarrassed by her homely appearance, Lily tried to make herself appear less attractive.



* [[https://wordsinasentence.com/hone-in-a-sentence/][Hone]]

  =to perfect a talent or skill=

  - The tennis player practices several hours a day to hone her skills.
  - Because Jessica wants to hone her cake baking ability, she can usually be found in the kitchen.
  - The apprentice will hone his mechanical expertise under a mentor and then open his own garage.
  - To stand a chance at winning the ice sculpting contest, Mark will need to hone his carving skills.



* [[https://wordsinasentence.com/hoodwink-in-a-sentence/][Hoodwink]]

  =to trick or deceive someone=

  - In an attempt to hoodwink the woman into opening the front door, the rapist pretended to be a police officer.
  - Car dealerships often hoodwink customers into coming to their lots by making promises of incredibly low payments.
  - In the shady bar, the bartender is known for trying to hoodwink customers by passing off cheap whiskey as a premium brand.
  - The con artist was arrested when he tried to hoodwink the undercover police officer.
  - Since Jed does not want a bachelor party, it is my job to hoodwink him into attending the celebration I have secretly planned.
  - Stores hoodwink customers by increasing prices on items and then offering special discounts on the same products.
  - As Patrick read the suspicious email, he realized someone was trying to hoodwink him into sharing his financial information.



* [[https://wordsinasentence.com/horrendous-in-a-sentence/][Horrendous]]

  =horrific; terrible=

  - The villagers were shocked that a boy so young could commit such a horrendous crime with no regard for human life.
  - At the site of the horrendous traffic accident, people rushed to help free the children from the burning bus.
  - The state of the rental house was horrendous, with the previous renters having completely destroyed the property.
  - Life in the poverty-stricken city is horrendous since most people there are living in terrible conditions without food or water.



* [[https://wordsinasentence.com/horticulture-in-a-sentence/][Horticulture]]

  =the science of caring for gardens; gardening=

  - Bob enrolled in a class that teaches horticulture so that he can cultivate his garden.
  - Horticulture is an art that requires getting your hands dirty, although being able to create a great garden is very rewarding.
  - We are experiencing a drought which will have a lasting effect on the horticulture industry.
  - The government is offering incentives for people to take up horticulture in the hope that it will make our city more pretty than it already is.


* [[https://wordsinasentence.com/hubris-in-a-sentence/][Hubris]]

  =an excess of confidence; having too much pride and personal worth=

  - The leader of the cult had so much hubris he believed the government would never be able to capture him.
  - Although the priest had taken a vow to help others, his own personal judgment was blinded by hubris.
  - Since Cynthia won the beauty pageant, she has allowed her hubris to turn into arrogance.
  - Most politicians are so inflated by their own hubris they cannot understand the needs of their communities.
  - Feeling unbeatable because of her hubris, Carolyn did not prepare well for the contest and lost.
  - Don’t let your hubris cost you friends!
  - Although Michael won over twenty Olympic medals, his hubris did not isolate him from the other athletes.



* [[https://wordsinasentence.com/hue-in-a-sentence/][Hue]]

  =a shade of color=

  - Placing the cloth over the lamp produced a blue hue in our bedroom.
  - Can anyone tell me why there is a strange purple hue in the background of my pictures?
  - The pale hue of the patient’s skin was a sign of anemia.
  - As I stood on the balcony, I tried to take a photo of the hue of the setting sun.



* [[https://wordsinasentence.com/hurtle-in-a-sentence/][Hurtle]]

  =move at a rapid pace in a wild manner=

  - The force of the truck caused the car to hurtle over the bridge.
  - If you live in a trailer, you should evacuate at once because the hurricane could cause your home  to hurtle through the air.
  - Throwing the glass vase against the wall will cause pieces of it to hurtle in random directions.
  - Even under the pilot’s control, the damaged plane seemed to hurtle towards the runway.



* [[https://wordsinasentence.com/husbandry-in-a-sentence/][Husbandry]]

  =the breeding and/or cultivation of animals and/or crops=

  - Because we engage in husbandry and produce our own food, we do not have huge grocery store bills.
  - Elena studied animal husbandry in school so she could take over the family business of sheep farming.
  - With many years of husbandry experience to his credit, Dr. Marks is viewed as an expert on the subject of breeding cattle.
  - If you do not plant your crops on fertile soil, your efforts in husbandry will be futile.
  - During my week on a pig farm, I learned about every aspect of husbandry from producing crops to caring for animals.
  - Technological tools such as mechanical vegetable pickers have greatly changed the way husbandry is conducted.
  - Although Bill has always wanted to be a horse breeder, he chose a major in business instead of husbandry.



#+HTML: <a id="bottom"/>
#+HTML: <a href="#top">⇧</a>