#+TITLE:     Q
#+AUTHOR:    Hao Ruan
#+EMAIL:     haoru@cisco.com
#+LANGUAGE:  en
#+LINK_HOME: http://www.github.com/ruanhao
#+OPTIONS:   h:6 html-postamble:nil html-preamble:t tex:t f:t ^:nil
#+STARTUP:   showall
#+TOC:       headlines 3
#+HTML_DOCTYPE: <!DOCTYPE html>
#+HTML_HEAD: <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Inconsolata:400,700" rel="stylesheet" type="text/css" />
#+HTML_HEAD: <link href="../org-html-themes/solarized/style.css" rel="stylesheet" type="text/css" />
 #+HTML: <div class="outline-2" id="meta">
| Author   | {{{author}}} ({{{email}}})    |
| Date     | {{{time(%Y-%m-%d %H:%M:%S)}}} |
#+HTML: </div>


* [[https://wordsinasentence.com/quagmire-in-a-sentence/][Quagmire]]

  =a situation from which it is hard to escape=

  - Many young people do not realize the quagmire to which occasional drug use can lead.
  - Since Jim lost all of his money gambling, he is stuck in a financial quagmire.
  - When Hank called me from jail, I knew he was in a quagmire.
  - When Marie’s car broke down, getting to work became a quagmire for her.

* [[https://wordsinasentence.com/quaint-in-a-sentence/][Quaint]]

  =appearing old-fashioned in an appealing way=

  - My grandmother’s quaint home is filled with knick-knacks from her childhood.
  - As I walked through the quaint shop, I felt as though I was transported back in time.
  - The quaint village does not appear to have changed since it was first settled in the early 1900s.
  - Before I left the old house, I had to sit in the quaint rocking chairs on the front porch.
  - The antebellum mansion looks very quaint under the moss-covered trees.
  - As soon as we entered the quaint home, we noticed it was filled with charming antiques.
  - Tabitha looked adorable in her quaint homemade dress.


* [[https://wordsinasentence.com/qualm-in-a-sentence/][Qualm]]

  =a feeling of doubt or uncertainty about whether you are doing the right thing=

  - Under the influence of drugs, Matt had no qualm whatsoever about spending all of his money at the casino.
  - I have a serious qualm about my teenage daughter dating an older man.
  - Without any qualm, the killer shot the young woman in the face.
  - My qualm with this company is their lack of contributions to local charities.
  - The crooked businessman appeared to have no qualm about tearing down the nursing home to build a parking lot.
  - As Jenna walked down the aisle to meet her future husband, she experienced a qualm that almost made her change her mind about getting married.
  - When Margaret desperately needed money, she seemed to have no qualm about robbing others.


* [[https://wordsinasentence.com/quantifiable-in-a-sentence/][Quantifiable]]

  =able to be measured=

  - Scientists used a calculator to average the quantifiable data gathered during the experiment.
  - Although the teacher tried to determine which children were the best readers from the assessment, the results were not quantifiable.
  - After grading all of the quantifiable tests, the teacher wrote letter grades on each one.
  - Quantifiable surveys were conducted to gauge the number of employees who were unhappy with current insurance options.


* [[https://wordsinasentence.com/quantum-in-a-sentence/][Quantum]]

  =The smallest amount of something, specifically energy=

  - Measuring the quantum amount of the object essentially destroyed it.
  - Quantum complexities are just a small part of the make-up of the human brain.
  - Quantum mechanics was used to explain properties of several energy forms.
  - While quantum energy could not be measured fully, the scientist continued to work on the experiment.




* [[https://wordsinasentence.com/quash-in-a-sentence/][Quash]]

  =to put an end to something=

  - Refusing to give in to the toddler’s demands, the exasperated mother was hell-bent on coming up with a plan to quash the tantrums.
  - My defense team tried to quash the subpoena but it was served anyway.
  - Tired of squabbling, the exhausted husband agreed to quash the argument and go shopping with his wife.
  - Scientists were able to quickly quash the outbreak through a new immunization.


* [[https://wordsinasentence.com/querulous-in-a-sentence/][Querulous]]

  =full of complaints; complaining=

  - If there was an award for being querulous, my aunt would win because she is always complaining about something.
  - I don’t mean to be querulous, but I do believe I should get my money’s worth at all times.
  - Forgive me for sounding querulous, but there is a bug in my soup.
  - Whenever my father had too many drinks, he would become querulous and complain about everything.
  - During the plane trip, I had to sit next to a querulous lady who did nothing but criticize the flight attendants.
  - If my little boy does not take his nap on time, he becomes querulous and finds fault with everything.
  - I was a querulous kid who always argued with my mother when she put vegetables on my dinner plate.


* [[https://wordsinasentence.com/quiescent-in-a-sentence/][Quiescent]]

  =not active; quiet=

  - For once, our hyperactive Great Dane is quiescent and resting on the rug.
  - Now that school has started back, my neighborhood is pretty quiescent during the day.
  - While the bees are quiescent early in the morning and in the evening, they are overactive in the middle of the day.
  - During the quiescent phase of the lab, we simply observe and note the growth of the cells.
  - After the mediation between the two warring countries, the region became quiescent.
  - You have no reason to be concerned about the quiescent volcano.
  - As long as the protest remains quiescent, the police will not be called.


* [[https://wordsinasentence.com/quixotic-in-a-sentence/][Quixotic]]

  =unrealistic and impractical=

  - Although Jack’s plan for killing the giant was quixotic, it was the village’s only hope.
  - Henry knew running for class president was a quixotic idea, but he was not going to let his enemy run unopposed.
  - It is quixotic to think you can get away with walking into the prison and breaking out your boyfriend.
  - While the knight’s quest sounded noble, in reality it was a quixotic plot which could only end in the young man’s death.
  - Everyone told Jennifer her dream of being a Hollywood star was quixotic, but she proved them wrong when she became a ten million dollar actress.
  - Because reality does not always have a happy ending, most women prefer to watch quixotic romantic-comedies that normally end with the girl getting her guy.
  - Nobody believed the tiny boy would achieve his quixotic goal of making the football team.


* [[https://wordsinasentence.com/quaff-in-a-sentence/][Quaff]]

  =to hastily consume a beverage=

  - The huge athlete was able to quaff down a gallon of water in less than two minutes.
  - On any college campus, you can find at least one frat boy who will quaff any beverage given to him.
  - My husband always has to quaff a pot of coffee before leaving for work.
  - When the thirsty sailors were on leave, they would quaff as much beer as they could hold.
  - The intoxicated girl tried to quaff the entire keg.
  - When the man was rescued from the desert, he wanted to quaff the entire bottle of water.
  - After the last final exam, my friends and I went to the pub to quaff a few drinks.


* [[https://wordsinasentence.com/quail-in-a-sentence/][Quail]]

  =a small, short-tailed, commonly hunted bird=

  - Known as a gourmet chef, Emeril Lagasse created a masterpiece of flavors by snipping off the wings and removing the feathers off the quail before roasting and serving it to the queen.
  - For the experienced hunters, hunting quail proved difficult due to its high flying abilities and its brown feathers allowing it to camouflage into nature.
  - When I visited the local park, a quail darted near the pond and pecked with its beak at the bread crumbs lying around.
  - The only artwork I was interested in at the art sale was a watercolor picture of a brown quail perched with its short tail dangling over the tree limb.

* [[https://wordsinasentence.com/quandary-in-a-sentence/][Quandary]]

  =a state of doubt about what to do in a certain situation; a difficult situation=

  - Mark is in a quandary about whether or not he should keep the money he found in the park.
  - When the lawyer told us our lawsuit options, we realized we were in a quandary about which legal path to take.
  - I find myself in a moral quandary about whether or not I should tell my wife the truth about my affair.
  - Because you are in a quandary and doubting your ability to make a decision, I suggest you talk to one of your friends about your problem.
  - Since I am always honest with my parents, I found myself in a quandary when my best friend asked me to lie to my father about my whereabouts.
  - The decline of the housing market has put many real estate agents into a financial quandary.
  - When my husband and I were debating our vacation plans, we were in a quandary between going on a cruise and flying to New York City.

* [[https://wordsinasentence.com/queer-in-a-sentence/][Queer]]

  =strange; odd=

  - Peering into the queer little house, Georgia couldn’t understand why all the unusually shaped furniture was painted pink and blue.
  - Because of his queer habits, the recluse was seen as strange by his fellow townspeople.
  - Lily found it queer that her sister had pet monkey’s but accepted her odd obsession all the same.
  - The queer little object looked like something out of a science fiction movie.


* [[https://wordsinasentence.com/quell-in-a-sentence/][Quell]]

  =to calm or reduce=

  - Before Sarah gives a speech, she always drinks a shot of whiskey to quell her nerves.
  - The old man drinks warm milk to quell his upset stomach.
  - During the riots, over five hundred policemen worked to quell the uproar.
  - The principal tapped the microphone to quell the noise in the auditorium.
  - In order to quell unemployment, the government is giving more business loans.
  - Troops are being deployed to quell the threat of violence from the terrorist nation.
  - Because Hiriam wants to quell his urge to smoke, he is now using nicotine patches.


* [[https://wordsinasentence.com/quench-in-a-sentence/][Quench]]

  =to satisfy an actual or figurative thirst, or to put out a fire=

  - Aiming to quench her thirst, the runner guzzled down the water at full speed.
  - When they were finally able to quench the flames of the fire, the firefighters breathed a sigh of relief.
  - Although it failed to quench her thirst for a summer road trip, the mini-vacation at the lake was a distraction for the avid traveler.
  - Unable to quench the flame on by blowing, the birthday girl laughed as she realized that her parents had bought a prank candle.


* [[https://wordsinasentence.com/quibble-in-a-sentence/][Quibble]]

  =to quarrel about minor matters=

  - It is normal for married couples to quibble over small things like who controls the television remote.
  - Whenever the two historians meet, they quibble over historical facts before drinking a pitcher of beer.
  - We should not quibble over a small detail like borrowed money before your surgery.
  - When my ex-husband and I are together, all we do is quibble over the lack of support he gives me.
  - The billionaire did not quibble over the five-dollar service charge.
  - As usual the city council members chose to quibble over holiday party details rather than deal with the city’s issues.
  - How long do you think the politicians will quibble over the budget proposals before they finally select one?


* [[https://wordsinasentence.com/quirk-in-a-sentence/][Quirk]]

  =an odd behavior or different way of acting=

  - Janice has this irritating quirk of rolling her eyes whenever she speaks.
  - According to Ken, his habit of constantly wringing his hands is just an uncontrollable quirk.
  - Wearing only pink socks is Greg’s oddest quirk.
  - In the film, the killer’s quirk of styling his victims’ hair led the police to the salon where he worked.


* [[https://wordsinasentence.com/quondam-in-a-sentence/][Quondam]]

  =former; previous=

  - The quondam beauty queen was much more exotic than the one currently being crowned.
  - Before retiring, the quondam editor trained me to take over his position.
  - Readers were surprised that the quondam CEO was speaking out against the company that he helped build from the ground up.
  - The quondam lovers could barely look at each other after they ended their relationship.



* [[https://wordsinasentence.com/quotidian-in-a-sentence/][Quotidian]]

  =everyday events that are normal and not that exciting=

  - As the days of celebration wore on, the formerly spectacular events began to seem more quotidian, and the king found himself yawning at the chariot races.
  - There is a precise schedule for taking care of quotidian tasks, but all your time is your own once you have completed them.
  - Every year Mrs. Anderson is faced with the task of taking quotidian assignments from the curriculum and trying to make them stimulating for her students.
  - Even though the life of rock stars may seem exciting and glamorous, the days they spend traveling while on tour are as quotidian as yours and mine.
  - Compared to the process of shopping for their time share, the couple found it difficult to sit through the quotidian necessity of ironing out the details in the contract.
  - Because Arthur has a simple quotidian talent for painting, he prefers to create art for his own enjoyment rather than exhibiting it to the public.
  - Emily has an admirable enthusiasm for life, and she attacks even the most quotidian of chores with energy and passion.
