#+TITLE:     W
#+AUTHOR:    Hao Ruan
#+EMAIL:     haoru@cisco.com
#+LANGUAGE:  en
#+LINK_HOME: http://www.github.com/ruanhao
#+OPTIONS:   h:6 html-postamble:nil html-preamble:t tex:t f:t ^:nil
#+STARTUP:   showall
#+TOC:       headlines 3
#+HTML_DOCTYPE: <!DOCTYPE html>
#+HTML_HEAD: <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Inconsolata:400,700" rel="stylesheet" type="text/css" />
#+HTML_HEAD: <link href="../org-html-themes/solarized/style.css" rel="stylesheet" type="text/css" />
#+HTML: <div class="outline-2" id="meta">
| Author   | {{{author}}} ({{{email}}})    |
| Date     | {{{time(%Y-%m-%d %H:%M:%S)}}} |
#+HTML: <a href="#bottom">⇩</a>
#+HTML: <a id="top"/>
#+HTML: </div>



* [[https://wordsinasentence.com/wane-in-a-sentence/][Wane]]

  =to gradually decrease in value or intensity=

  - When the investigators ran out of leads, the intensity of the murder investigation started to wane.
  - John asked his wife for a divorce when his feelings for her started to wane.
  - Since sales have started to wane, the store is in danger of becoming unprofitable.
  - Hopefully my daughter’s interest in the tuba will soon wane so my house can be quiet again.
  - Ben knows his financial woes will wane as soon as he gets a job.
  - Due to budget cuts, the nonessential services offered by the county will begin to wane in December.
  - If Colin is not winning a game, his interest will wane to the point he no longer wants to play.

* [[https://wordsinasentence.com/warp-in-a-sentence/][Warp]]

  =to twist into a different or abnormal shape=

  - If the chair gets wet, the wood will warp and make the furniture uncomfortable for sitting.
  - The hot temperature in the car may warp the movie disc and make it unplayable.
  - As a result of the scorching heat, the plastic lawn furniture has started to warp into an abnormal form.
  - The sculptor uses tools to warp scrap metal into unique works of art.

* [[https://wordsinasentence.com/wary-in-a-sentence/][Wary]]

  =caution; guarded; careful=

  - One of the most important lessons that parents must teach young children is to always be wary of strangers.
  - Fluffy gave her owners a wary look when they walked in the door with a new puppy.
  - Despite their employer’s assurances, the workers were wary of the changes he was requiring in their contracts.
  - After they had lost one horse to a rattlesnake bite, the riders remained wary of their surroundings as they made their way through the desert.
  - I’ve told my mother to be wary of telemarketers because so many of them prey on elderly widows.
  - Despite my warning for the children to be gentle with the baby rabbits, their rowdy behavior has made the poor bunnies wary and nervous.
  - He could tell that she didn’t trust him from the wary expression on her face.

* [[https://wordsinasentence.com/weather-in-a-sentence/][Weather]]

  =the state of the air and atmosphere in a specific place and time=

  - Rainy weather ruined our family picnic soon after we arrived at the park.
  - Because of the stormy weather, the children must play indoors only.
  - The newsman gave a weather report that called for over two inches of snow over the next twelve hours.
  - Florida’s sunny weather makes it the perfect place to go on a vacation.

* [[https://wordsinasentence.com/welter-in-a-sentence/][Welter]]

  =wild disorder=

  - The classroom was in a welter when the teacher did not show up for class.
  - The frenzied football fans were in the throes of a welter during the final few moments of the game.
  - Because she has an issue with hoarding, my grandma’s house is always in a welter.
  - The animals at the zoo were always in a welter right before feeding time.

* [[https://wordsinasentence.com/whimsical-in-a-sentence/][Whimsical]]

  =in an amusing or playful manner=

  - The whimsical music made me feel like a little kid again.
  - During the party, our host asked us to join him in a whimsical game of make-believe.
  - The author turned out to be just as whimsical as the magical characters in her children’s book.
  - When we went into the interactive candy store, we felt as though we were in a whimsical world made of chocolate.
  - It will be interesting to see how my serious mother-in-law responds to the whimsical present I am giving her for her birthday.
  - After being stuck in my accountant’s office all day, I looked forward to escaping to the whimsical fantasy game I played with my friends.
  - The portrait of the dogs and cats playing cards together is one of the painter’s most whimsical pieces.

* [[https://wordsinasentence.com/whimsy-in-a-sentence/][Whimsy]]

  =the quality of being amazing or fantastic=

  - There is a touch of whimsy to this metal sculpture, a certain magical and inspired aura to it that shows how passionate the artist was.
  - There is a sense of whimsy when you get to see the Northern Lights for the first time, as the view is so rare and picturesque it almost seems surreal.
  - I felt a sense of whimsy as we gazed at the stars above us, the hundreds of little lights not diminished by any city lights whatsoever.
  - I felt a great deal of whimsy when I went scuba diving the first time, as the world beneath the waves was almost completely foreign and magical to me.

* [[https://wordsinasentence.com/whittle-in-a-sentence/][Whittle]]

  =to reduce or gradually eliminate something=

  - Her patience began to whittle when the students would not stop talking.
  - Our hiring manager will whittle the number of job applicants from 90 to 3.
  - After the race on the hot day, the store’s stock of bottled waters started to whittle.
  - Due to budget restrictions, Dana’s had to whittle down the list of party invitees.

* [[https://wordsinasentence.com/willful-in-a-sentence/][Willful]]

  =declining to alter one’s behavior or opinions=

  - The willful boy refused to take his seat in class.
  - Because the defendant has a willful disdain for human life, the judge has sentenced him to twenty years in prison.
  - The willful man continued to chase after the happily married woman.
  - Since willful neglect produced the environment in which the customer was mugged, the store owner is facing a huge lawsuit.

* [[https://wordsinasentence.com/wilt-in-a-sentence/][Wilt]]

  =to droop or become limp and soft=

  - I placed an excessive amount of water into the vase on my breakfront because of how quickly the flowers tend to wilt.
  - We worried that the long hours of my new job would cause our relationship to wilt.
  - Although Sam loves expensive flowers, he won’t buy them because they wilt so quickly.
  - Aunt Bella’s daughter does not want her to enter a senior citizens home because she is afraid that it will cause her youthful nature to wilt prematurely.

* [[https://wordsinasentence.com/wistful-in-a-sentence/][Wistful]]

  =sad and reflective=

  - When I visit my mother’s grave, I feel wistful.
  - I became wistful when I saw my ex-boyfriend with his new love.
  - At the end of the dramatic movie, the wistful audience sat in silence as they all pondered the tragedy they had just witnessed.
  - Listening to the sorrows of the blues music always puts Dean in a wistful mood.
  - The wistful song on the radio makes me think of my dead husband.
  - As Henry looked at his old school, he could not help but be wistful as he thought about all the friends he had lost over the years.
  - When my grandmother is feeling wistful, she likes to talk about her years as a teenage girl.

* [[https://wordsinasentence.com/withstood-in-a-sentence/][Withstood]]

  =having resisted or stood firm against some force=

  - The trees withstood the hurricane even though the winds were very strong.
  - Most thought the couple would divorce, but their marriage has withstood the test of time.
  - The metal withstood the first strength test but collapsed during the second trial.
  - Settlers withstood several challenges including a harsh winter and lack of food.

* [[https://wordsinasentence.com/witty-in-a-sentence/][Witty]]

  =using words in a clever and humorous way=

  - Robert’s attempt at a witty comeback fell flat, without evoking any kind of laughter.
  - Although the comic views himself as a witty and clever professional, we all consider him a buffoon.
  - Peter is an elegant, charming and witty person who would make a great master of ceremonies.
  - Eric is a great debater who employs his witty sense of humor when deflecting an attack.

* [[https://wordsinasentence.com/waddle-in-a-sentence/][Waddle]]

  =to take small steps while walking in a stumbling way=

  - As the duck would waddle to the pond, its webbed feet would move back and forth along the path in bobbing motion.
  - When the penguins at the zoo would waddle, children would frequently laugh as their plump bodies would shift from side to side in the enclosure.
  - Being nine months pregnant with triplets, the woman could only waddle slowly around the house due to her protruding stomach.
  - With weak legs, elderly people will often waddle gradually to their destination by planting one foot down on the ground before moving the other.


* [[https://wordsinasentence.com/waggish-in-a-sentence/][Waggish]]

  =acting in a mischievous manner=

  - The waggish teenage boys kept tripping on the ground in hopes of attracting the attention of the pretty girls.
  - At his age, Phil needs to stop behaving in a waggish manner and assume the serious responsibilities of being a husband and father.
  - The waggish employees played computer games and completed very little work when their boss was out of the office.
  - Because the teacher had to maintain her stern reputation, she never let her students know she was amused by their waggish behavior.

* [[https://wordsinasentence.com/waive-in-a-sentence/][Waive]]

  =to give up one’s rights or claims=

  - Because Bill knows he is innocent, he is going to waive his right to an attorney.
  - Some insurance companies will waive rate increases for drivers who have excellent driving records.
  - Since the woman exceeded the speed limit only because she needed medical aid, the police officer chose to waive her speeding ticket.
  - The bank will waive the monthly account fee if I use my debit card five times in a thirty-day period.

* [[https://wordsinasentence.com/wallop-in-a-sentence/][Wallop]]

  =to hit hard=

  - Boxers wallop each other with jabs and punches.
  - The bullies wallop their victim until he's covered with bruises.
  - The golfer hit the ball with a powerful wallop and it flew past the hole into the sand several meters away.
  - During the hail storm, large pieces of ice wallop the cars.

* [[https://wordsinasentence.com/wallow-in-a-sentence/][Wallow]]

  =to indulge in one’s emotions=

  - Ever since April lost her job, she has done nothing but wallow in self-pity.
  - Becky is a strong woman and not the type of person to wallow in gloom.
  - When Marie is depressed, she tends to do nothing but cry and wallow in misery.
  - Justin has done nothing but wallow in sorrow since his girlfriend dumped him.

* [[https://wordsinasentence.com/wan-in-a-sentence/][Wan]]

  =weak or pale in quality or appearance=

  - Although the toddler was quite ill, he still managed to give his mother a wan smile.
  - Bill’s parents thought he was abusing drugs because of his wan complexion.
  - After a night of heavy drinking, Brian returned home looking wan and tired.
  - The wan glow from the tiny candle was not enough to fully light up the room.

* [[https://wordsinasentence.com/wanton-in-a-sentence/][Wanton]]

  =having no concern for the rights, feelings, or safety of others=

  - Jim’s wanton disregard for others was obvious when he drove home drunk.
  - Although Harold is not a nice boy, I cannot believe he has been accused of wanton cruelty toward his neighbor’s dog.
  - The judge sentenced the teenage boy to two hundred hours of community service for his wanton acts of vandalism.
  - After surveillance cameras failed to pick up the wanton destruction of the library, the county hired a security guard to patrol the building.
  - The wanton destruction of the historic church drew outrage from all over the country.
  - Although Frank is usually a caring person, he exhibits a wanton personality and overlooks the feelings of others when he drinks too much beer.
  - Alice’s wanton nature led her to believe the laws that governed others did not apply to her.


* [[https://wordsinasentence.com/wastrel-in-a-sentence/][Wastrel]]

  =an individual with a tendency to waste resources and time=

  - Since Bill is a wastrel, he spends most of the day in bed.
  - Claire has the habits of a wastrel and often finds herself in debt as a result of spending money on unnecessary things.
  - After Kate married a wastrel, she learned she would have to be the smart shopper in the family.
  - My son is a wastrel who usually throws his school lunch in the trashcan.

* [[https://wordsinasentence.com/waver-in-a-sentence/][Waver]]

  =to be uncertain=

  - I am certain of my selection so my decision will not waver.
  - Because Mary knew her father would not waver on his decision, she did not bother to ask him again.
  - Mike was not afraid of the bully and showed it by not letting his eyes waver from those of his enemy.
  - Although John thought he wanted to attend a local college, he has started to waver on his choice and is now considering other schools.

* [[https://wordsinasentence.com/waylay-in-a-sentence/][Waylay]]

  =to actively block an individual’s path in order to interrogate, detain, etc.=

  - Reporters attempted to waylay the celebrity at the airport and bombard him with questions, but his security team intervened.
  - The boxer's opponent made to waylay and provoke him before the match, but he stormed through his defenses and into the ring.
  - The police officer stepped in front of the distraught woman to waylay her before she reached the crime scene.
  - Her nosy grandmother often tried to waylay her with pointless conversations about her love life before she left the house.

* [[https://wordsinasentence.com/wean-in-a-sentence/][Wean]]

  =to gradually eliminate a thing from your life=

  - I’m trying to wean myself off soda by drinking fewer each day.
  - The kitten will need to wean off of its mother’s milk and start drinking out of a bowl.
  - We are trying to wean my toddler from sucking a pacifier, but she hasn’t let go yet.
  - The patient must wean his body off alcohol before he can leave the hospital.

* [[https://wordsinasentence.com/weary-in-a-sentence/][Weary]]

  =worn out; exhausted=

  - After the long road trip, we were all so weary we fell asleep in our clothes.
  - Warren was very weary after his cancer treatments.
  - When my eyes grew weary, I closed the book I was reading and took a nap.
  - The sixteen-hour plane trip left Heather feeling rather weary.

* [[https://wordsinasentence.com/wend-in-a-sentence/][Wend]]

  =to follow a set direction or path=

  - Miles of trails wend their way through the trees and meadows.
  - I need to wend my way back to the cabin before night falls.
  - Although the charges were eventually dropped, it took the defendant years to wend himself through the legal system.
  - The law must wend its way through congress before getting full approval.

* [[https://wordsinasentence.com/wheedle-in-a-sentence/][Wheedle]]

  =to try and persuade using flattery=

  - After Bill forgot his wedding anniversary, he attempted to wheedle his way back into his wife’s heart by surprising her with a romantic getaway.
  - My daughter will pretend to cry if she thinks it will allow her to wheedle out of a consequence.
  - When my sister could not pay her light bill, she batted her eyelashes at the clerk in an attempt to wheedle an extension.
  - It was so easy for the model to wheedle her way out of a ticket by smiling at the patrolman.
  - Although I would love to get into the exclusive area of the club, I am not willing to wheedle my way in by flirting with the unattractive security guard.
  - Credit card companies try to wheedle money out of their customers by rewarding them with credit increases.
  - When Elaine wanted free drinks, she would wheedle them by flirting with intoxicated men.

* [[https://wordsinasentence.com/wheeze-in-a-sentence/][Wheeze]]

  =to breathe with a whistling or rattling sound in the chest=

  - Because of an infection in his lungs, the patient will wheeze anytime he breathes in air too deeply.
  - Bacteria in the air can make a person who breathes normally sniffle and wheeze.
  - Studies show that kids who eat nuts at least three times a week are less like to wheeze or rattle when they breathe.
  - An allergic reaction to something she ate caused the little girl to wheeze and rasp every time she took a breath.

* [[https://wordsinasentence.com/whet-in-a-sentence/][Whet]]

  =to trigger or make desire=

  - The mobile phone company uses celebrity endorsements to make consumers whet their phones.
  - As I walked up my grandmother’s steps, I realized the smell of her food was enough to whet my appetite.
  - The president gave the journalists just enough information to whet their curiosities.
  - While I was at work, my wife sent me pictures of her new lingerie in order to whet my desire.

* [[https://wordsinasentence.com/whiff-in-a-sentence/][Whiff]]

  =a smell or aroma=

  - The children came running as soon as they got a whiff of the fresh pizza.
  - A whiff of urine filled my nose and let me know that the dog had peed on the carpet.
  - Only one whiff in the kitchen let me know that my mother was preparing her famous meatloaf.
  - If you get a whiff of grandma’s delicious cherry pie, you won’t be able to believe your nose.

* [[https://wordsinasentence.com/whim-in-a-sentence/][Whim]]

  =a sudden desire to do something unplanned=

  - The police officer acted on a whim, not thinking before he violently slammed the suspect to the ground.
  - When asked why he decided to run, the criminal replied by saying he had done it on a whim.
  - After realizing he had exhausted his money, it occurred to him that he should not have gambled so much on a whim.
  - The man’s instinct paid off as he picked the winning horse on a whim.
  - Thanks to his training as a solider, the man acted on a whim and was able to save his wife from the explosion.
  - For some reason, he felt a strange whim to shove his face into the ice cream and forget about using a spoon.
  - They say a father has a sixth sense about his child’s safety, and when the man reached out and caught his son on a whim, he felt it was true.

* [[https://wordsinasentence.com/whimper-in-a-sentence/][Whimper]]

  =a low cry that is used to express pain or unhappiness=

  - The puppy let out a quiet whimper while licking its injured paw.
  - We were surprised that the usually stubborn child went to bed without a whimper.
  - Because it continued to whimper and cry, the vet knew that something was wrong with the animal’s hind leg.
  - Spoiled and bratty, the toddler gave off a pouty whimper to get her way with her parents.

* [[https://wordsinasentence.com/whine-in-a-sentence/][Whine]]

  =a long, high-pitched sound=

  - The toddler’s high-pitched whine annoyed everyone in her house.
  - Letting out a shrill whine, the car engine sounded like it needed a tune-up.
  - My little girl will whine to get her way, letting out a piercing scream every time someone tells says “no.”
  - The radio gives off a high-pitched whine when you tune it to a channel that isn’t available.

* [[https://wordsinasentence.com/wholesome-in-a-sentence/][Wholesome]]

  =considered ethical or of good moral standing=

  - Though he put on a wholesome persona, the mayor was really a gambler who stole money from the city.
  - Most of the books in the library are wholesome, but a few of them would even make adult film stars blush.
  - The pastor stated that wholesome girls of good moral standing wouldn’t wear the provocative clothing that is fashionable today.
  - Naïve and wholesome, the innocent girl had never sinned in her life.

* [[https://wordsinasentence.com/wield-in-a-sentence/][Wield]]

  =To control an item with competence, in particularly a tool or weapon=

  - Do you wish you could wield a sword like a valiant knight?
  - The lumberjack could wield his axe with great skill.
  - When the soldier started to wield the bat like a weapon, his attacker fled in fear.
  - The champion ice sculptor is known for his ability to skillfully wield a chisel.

* [[https://wordsinasentence.com/wily-in-a-sentence/][Wily]]

  =sneaky and calculating=

  - The wily cartoon character was always thinking of ways to steal food.
  - As a wily con artist, Chris was able to take advantage of a large number of people.
  - The casino manager banned the wily gambler for counting cards.
  - Unfortunately the young chess player was no match for the wily man who had been playing the game for over thirty-five years.
  - The wily prosecutor is a very calculating man who hates to lose a case.
  - Is anyone surprised the wily politician was involved in the prostitution scandal?
  - The wily mouse was able to easily remove the cheese from the trap.

* [[https://wordsinasentence.com/wince-in-a-sentence/][Wince]]

  =to make a tensing movement as a result of distress or pain=

  - The electric shock made the dog wince.
  - When Frank’s boss told him he had to work late, he could not help but wince.
  - Did you see the horse wince when its rider struck it?
  - As soon as the coach saw his star football player wince, he removed him from the game.
  - The awful movie made the critic wince.
  - Because I do not like snakes, I wince every time I see one on television.
  - Hiring managers wince when they receive resumes filled with spelling errors.

* [[https://wordsinasentence.com/windfall-in-a-sentence/][Windfall]]

  =an unanticipated benefit, usually monetary in nature=

  - With her lottery windfall, Gail eliminated all her financial debt.
  - Hopefully my accountant will help me get a windfall when he completes my tax paperwork.
  - On Will’s eighteenth birthday he will receive a cash windfall as part of his inheritance.
  - As a shareholder, I am very pleased with my dividend windfall this year.

* Winnow
  - The warm summer breeze slowly winnowed the sand across their beach towel.
  - With his makeshift fan, the adventurer was able to winnow the sweat from his face.
  - As the bird took off, it acted to winnow the dirt around it.
  - While the mouse scurried across the sand its legs acted to winnow the dirt around it.
  - Thanks to his years of experience, the police officer was able to winnow the truth from the many lies.
  - The warm summer breeze slowly winnowed the sand across their beach towel.
  - The polling data helped them to winnow down the options and make the most popular selection.


* [[https://wordsinasentence.com/wiry-in-a-sentence/][Wiry]]

  =strong and muscular yet thin and long=

  - The wiry basketball player moved his slim frame down the court and scored a goal as the buzzer sounded.
  - Placing the new design on her wiry frame, the fitness model prepared to show her body off on the runway.
  - Six-foot-two and 160 pounds, the wrestler was known for his wiry frame.
  - The man’s lean and wiry body type made him stand out from the rest of the actors at the audition.

* [[https://wordsinasentence.com/wispy-in-a-sentence/][Wispy]]

  =describes objects that are thin and fine=

  - The soft-spoken woman’s wispy voice could barely be heard in the crowd.
  - Wispy clouds, fine and thin, bounced around in the air.
  - Because the spaghetti was wispy and thin, a sauce was needed to thicken it up.
  - The reedy, wispy grass flapped back and forth in the wind.

* [[https://wordsinasentence.com/wither-in-a-sentence/][Wither]]

  =dry up or shrivel=

  - The gardener’s plants began to wither in the heat of the sun.
  - My grandfather said that he would wither away if my mother wasn’t there to take care of him.
  - The drought caused our crops to wither.
  - Because I colored my hair so often, it began to wither from the dye.

* [[https://wordsinasentence.com/wizened-in-a-sentence/][Wizened]]

  =wrinkly from sickness or old age=

  - While the flowers arrived looking fresh and beautiful, they have grown wizened over the past few days.
  - My grandmother’s wizened face broke into a smile when I placed my newborn daughter in her arms.
  - Even though Will looks like a wizened old man who cannot care for himself, he is actually an active senior who enjoys skydiving.
  - As a singer mother with eight difficult children, Jane was not surprised when her appearance became wizened in her early fifties.

* [[https://wordsinasentence.com/wobble-in-a-sentence/][Wobble]]

  =to move unsteadily from side to side=

  - While learning to walk, the toddler would wobble from side to side.
  - Because one of its legs is lose, the table might wobble if something is placed on it.
  - The runner was so weak after his marathon that his legs began to wobble and shake.
  - As Ed pushed the wheelbarrow down the hill, its loose wheel began to wobble back and forth.

* [[https://wordsinasentence.com/wrath-in-a-sentence/][Wrath]]

  =intense anger=

  - In mythology mortals generally feared the wrath of the powerful gods.
  - The man earned the wrath of an entire nation when he assassinated the president.
  - Since the police have not arrested the crooked officers on the force, they now have to deal with the public’s wrath.
  - I will not testify against the gangster because I am afraid of his wrath.
  - During parent-teacher conferences, teachers often have to deal with the wrath of dissatisfied parents.
  - All the cheerleaders knew to agree with their captain or else they would incur her wrath.
  - During the vote, the senator from Georgia voted against the tax increase in order to avoid the wrath of his voters.

* [[https://wordsinasentence.com/wreak-in-a-sentence/][Wreak]]

  =cause a lot of damage or harm=

  - If the internet goes down, it will wreak havoc with our ability to communicate and continue doing any kind of business.
  - The storm will wreak terrible damage on Phil’s home if he does not place sandbags everywhere.
  - Budget uncertainty will wreak further havoc, so please make sure to have all your numbers ready for the meeting.
  - Given the havoc that a fire can wreak, the fire department urges everyone to have a family plan in place, in case of an emergency.

* [[https://wordsinasentence.com/wrenching-in-a-sentence/][Wrenching]]

  =forcefully pulling away from something or someone=

  - The football player tried wrenching the ball from the other team member’s hands, but his grip was too strong.
  - Wrenching the door open with enough force that it slammed against the wall, Bridget stormed into the house to confront her lying best friend.
  - Large gusts of wind from the hurricane were wrenching the patio doors open with such force that they were pulled off the hinges.
  - The wrestler tried wrenching himself from his opponent’s headlock by twisting and pulling on his arms.

* [[https://wordsinasentence.com/wrest-in-a-sentence/][Wrest]]

  =to forcefully take something away=

  - My wife had to wrest the candy bar from my hands in order for me to stop eating it.
  - Rita felt she had to wrest the weapon from the hostage-taker for the sake of her safety.
  - Sally did not give up her phone easily as her father had to wrest it from her hands.
  - He had to wrest himself free from ropes to escape.

* [[https://wordsinasentence.com/wretched-in-a-sentence/][Wretched]]

  =incredibly miserable=

  - After a night of overindulging in rich foods and alcoholic drinks, I am wretched.
  - The migraine made Cathy feel wretched.
  - Despite Bill’s wretched childhood, he grew up to be a successful well-adjusted man.
  - The people on the stranded cruise ship became wretched after a couple of days.

* [[https://wordsinasentence.com/writ-in-a-sentence/][Writ]]

  =the power to enforce submission and compliance=

  - It is beyond the writ of adults to punish children that are not their own for misbehavior regardless of how bad it is.
  - Enforcing justice is something beyond the writ of the average citizen, which is why they are not allowed to take the law into their own hands.
  - Some people believe that no one has the writ to enforce their will over others, but without that we have no government and no order.
  - Rebellious teenagers like to think that being forced to follow their parent’s rules is beyond their writ even though their parents have that right and power.

* [[https://wordsinasentence.com/wrought-in-a-sentence/][Wrought]]

  =prepared in some manner, usually by hammering or applying another type of pressure=

  - As we stared at the wrought iron gate, we could not help but wonder about the craftsman who had created the masterpiece.
  - The wrought metal will soon be used to construct the new bridge.
  - Because the wrought iron gates are massive in size, it takes a while for them to open.
  - My wife will not be satisfied if I do not purchase the wrought iron furniture for the patio.

* [[https://wordsinasentence.com/wry-in-a-sentence/][Wry]]

  =describes something sarcastic or a bit humorous=

  - Bill's wry sense of humor made it difficult to be taken seriously at the office.
  - When I asked Lauren "What's up?" she gave me this wry response "The sky!"
  - Realizing that he had been found, the hiding boy gave a wry smile.
  - The girl’s wry sense of humor causes her to laugh in the most inappropriate situations.
  - When I was driving, I saw a wry bumper sticker that read, "4 out of 3 people have trouble with fractions."
  - The wry man said he stops looking for work when he finds a job.
  - "An apple a day keeps the doctor away, especially if you throw it at him," said the wry Grandmother, known for her witty sayings.








#+HTML: <a id="bottom"/>
#+HTML: <a href="#top">⇧</a>