#+TITLE:     English Pod
#+AUTHOR:    Hao Ruan
#+EMAIL:     ruanhao1116@gmail.com
#+LANGUAGE:  en
#+LINK_HOME: http://www.github.com/ruanhao
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/style.css" />
#+OPTIONS:   H:2 num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+STARTUP:   showall


* 001 - Difficult Customer

- still working on
- coke and fries
- complimentary (free)
- go with (to choose)
- grab (get sth quickly)

* 002 - Calling in Sick

- feel ill today
- coming down with the flu
- calling in sick
- was hoping to do stm
- feeling slightly feverish

* 003 - Hotel Upgrade

- reservation under the name Ryan
- mix-up (sth wrong)
- concierge (hotel employee that helps guests)

* 004 - I Need an Assistant

- understaffed (short staffed)
- overstaffed
- take on new staff
- the timing is just not right
- take weight off someone's shoulders
- give me a hand
- deep voice

* 005 - Cut in Line

- says who?
- so sue me
- jump the queue
- stand in line (wait in line)

* 006 - Road Trip

- the car is packed
- munchies (snacks)
- fill up the tank
- pit stop (quick stop for food or gas)
- got all the bases covered (have everything ready)
- all set (ready)
- let's get going
  - let's get down to business
  - let's get out of here
  - let's get cooking
- trunk (the luggage area of a car)

* 007 - The Office Virus

- computer froze (stop working)
- i'll be right up (go upstairs soon)
  - i'll be right there
  - i'll be right down
  - i'll be right out
- it turns out that
- act up (not working properly)
  - it's acting up again!

* 008 - What's your name again?

- how is it going (how are you)
- slip my mind (been forgotten)
- around here
  - do you live around here
  - there is a good restaurant just around the corner
  - Los Angles is a great place, i used to live around there
- terrible with (bad at)
  - you are terrible with numbers
  - i am terrible with directions
  - i am terrible with faces
- can you remind me
- acquaintance (someone you know, but who is not a close friend)

* 009 - Silence please!

- keep it down (be quiet)
- not such a big deal
- can't hear a thing

* 010 - Driving Sales

- drive sales (increase sales)
- match the competitors
- will never fly (will not work)
  - this plan will never fly

* 011 - New Guy in Town

- house warming gift
- fill me in (tell me)
- kick me out (force someone leave when they don't want to)
  - kick out of bed
  - kick out of house
  - kick out of class
- creep me out (scare)
  - crept out by clows
- scare the heck out of me
- juicy gossip/story

* 012 - Cleaning the House

- in the middle of something (doing something at the moment)
- i will be there in a second
- immaculate (perfectly clean, having no dirt at all)
- dish detergent
- hoover (vacuum)

* 013 - Out Of Control Spending

- profit and lose statement
- through the roof (suddenly very high)
- off the chart (very high)
- expenditures (amount of money spent on something)
- the bottom line (the net profit; the amount of money a business makes after expenses)

* 014 - I'm in Debt

- recession
- take out/get a loan (borrow money)
- hit me pretty hard
- on top of all that (besides that)

* 015 - I'm sorry, I love you

- watch out
- knock over (make something fall over)
  - knock over the vase
  - i didn't mean to knock you overd

* 016 - Turn left here!

- step on it (drive faster)
- have a fit (get angry)
- cut through (quickly go past or though something that blocks you)
  - let's cut through a park, it is a shortcut
- run a red light
- make a left/right/u-turn
- road rage
- back street (small street that is away from the main streets)
- take a side street

* 017 - Here Comes the Bride

- bride and groom walk down the aisle
- bridesmaid and groomsman
- maid of honor (female fiend or relative who acts as a witness at the wedding)
- best man (male friend or relative who acts as a witness at the wedding)
- flower girl (a girl at a wedding that throws flower petals down the aisle)
- ring bear (a boy at a wedding that holds the wedding rings)
- it's about time (finally, waiting a long time)
  - A: dinner is ready. B: it's about time, i am starving!
  - A: i got a job. B: it's about time, you've been unemployed for 2 years!
  - A: we almost get there. B: it's about time, we've been driving for 2 hours!
- reception (party held to celebrate something or to welcome people)
  - food's good at the reception

* 018 - Protest

- bailout (the act of saving a company form money problems)
- placard

#+BEGIN_EXAMPLE
  A: This is Action 5 News reporter Sarah O'Connell reporting live from Washington, D. C.
     where a protest has broken out.
     Thousands of angry citizens are protesting against the proposed bailout
     of the auto manufacturing industry!
     Sir, sir, Sarah O'Connell, Action 5 news. Can you tell us what's happening?

  B: Yeah, yeah, we're here because we feel this is an injustice!
     The financial irresponsibility of big business has to stop!
     We're there to show the government that we don't like the way that
     they're spending our tax dollars!

  A: Sir but what exactly is making everyone so angry?

  B: It's an absolute outrage, Sarah, the US government wants to give 25 billion
     dollars of taxpayers' money to the auto industry.
     These are companies that have been mismanaged and are now nearly bankrupt.

  A: I see. But, many supporters of the bailout argue that
     it could help save the jobs of millions of hard-working Americans.

  B: That maybe true, and I for one don't want to see anyone lose their job,
     but how can these CEOs ask for a bailout when they're making millions of dollars?
     And then, they have the nerve to fly to Washington in private jets!
     This costs hundreds of thousands of dollars!
     And they're asking for money! That is just not right!

  A: Good point.
     This is Sarah O'Connell reporting live from Washington D. C., back to you, Tom.
#+END_EXAMPLE

* 019 - Christmas Chronicles I

- eggnog (traditional Christmas drink containing eggs, cream, sugar and rum)
- get a load of (look at)
- pout
- don't take that tone with me
- Rudolph, Prancer and Dancer
- we've got ourselves a situation (we have a problem)

#+BEGIN_EXAMPLE
  You are under arrest, sir.
  You have the right to remain silent.
  You better not pout, you better not cry.
  Anything you say can and will be used against you.
  You have the right to an attorney.
  If you can not afford one, the state will appoint one for you.
  Do you understand all these rights that were just read to you?
#+END_EXAMPLE

* 020 - I Can See Clearly Now

- 20/20 vision (perfect eyesight)
- as blind as a bat (have really poor vision)
- check-up (regular examination by a doctor to make sure a person is healthy)
- make out (see clearly)
- head on
  - head on in to the room
  - head on out to the park
  - head on up to my room
  - head on over to the room

* 021 - What Do You Do

- go on about (talk about something a lot)
  - my mom is always going on about how I should get married
- how is it going (how are you)
- what do you do for a living

#+BEGIN_EXAMPLE
  A V.P. position is not easy, you know!
  I implement policies and procedures nationwide, of various departments,
  as well as train junior managers in FDA and EPA regulations.
  I also have to oversee daily operation of our quality control for the entire east coast.
  That alone means I hava 15 hundred employees under me.
#+END_EXAMPLE

* 022 - Christmas Chronicles II

- candy cane
- book (slang: arrest)
- speeding (driving too fast)
- impounded (held by the police)
- under heavy (being attacked or hurt)
  - we're under heavy attack
  - we're under heavy fire
  - the President is under heavy security
- stocking stuffer (small gifts that are put in the Christmas stocking)
- Christmas ornament (decoration that is used to make the Christmas tree beautiful)
- tooth fairy

* 023 - Making an Appointment

- booked solid
  - I can't get a hotel room, theyrre booked solid until after the New Year.
  - I'm sorry, there are no seats available on this flight, werre booked solid over the Christmas holidays.
  - Sorry, I can't meet with you today, I'm booked solid.
- fit you in (find time to see some- one in a busy schedule)

* 024 - Where should we eat

- bistro (small, trendy restaurant or bar)
- in the mood for
- de'cor (decoration)
- light (not heavy on stomach, easy to digest)
- a hole in the wall (a very small, usually cheap restaurant or bar)

* 025 - Planning For The Worst

- contingency plan (a plan that prepares for a situation where things can go wrong)
- backup plan
- pandemic (a situation where a disease is spread out very quickly, and affects many people in many countries)
- epidemic (event where a disease spreads really quickly and affects a large number of people)
- let's move to our next order of business (let's move on)
- head up the project (lead the project)

#+BEGIN_EXAMPLE
  I guess you'll need me to forecast employee absences as well, right?
  And I'll think about the impact this will have on our clients.
  Hey, what about vaccines? Should we be thinking about getting vaccines for our employees?
#+END_EXAMPLE

* 026 - New Year Resolution

- work out (exercise at a gym)
- stuffed
  - i can't eat more, i'm stuffed
  - I ate way too much! i'm stuffed!
- cut out (remove)
  - You have to cut out the salt from your diet. No more chips, no more French fries, no more popcorn.
  - It's time for me to focus on my work. I'm going to cut out everything else from my life!

* 027 - Asking for Time Off

- take some time off (stop working for a short time)
- bank holiday (public holiday recognized by law)
- used up all my vacation days

* 028 - I'm Sorry, I Love You II

- make it up to you (do something good as a balance to a bad or hurtful action)
- a twist of fate (unplanned events that has a big impact on the future)
  - a twist of fate brought us together
- turn down an invitation
- see someone (be in a relationship with someone)

#+BEGIN_EXAMPLE
  I woke up today thinking this would be just like any other ordinary day,but I was wrong.
  A twist of fate brought us together. I crashed into your life and you into mine,
  and this may sound crazy, but I'm falling in love with you.
#+END_EXAMPLE

* 029 - Investing in Emerging Markets

- turmoil (a state of confusion, disorder, disturbance)
  - with the civil war, a famine and the inflation, the country has been in turmoil for 10 years
  - there's been a lot of turmoil in my life recently, i've moved to new city, changed my job, broke up with my girlfiend
  - the devaluation of dollar caused a great deal of turmoil in the market
- nest egg (money that is saved to pay for something in the future, usually a house, or retirement)
- stimulus package (amount of money the government uses to improve the economy)
- hit up (ask for money)
  - I'm gonna hit up the boss for a raise.
  - Are you trying to hit me up for money?
  - I don't have any cash. Have you tried hitting up Sophie? She's rich.
- depreciation (an decrease in the value of something)
- appreciation (an increase in the value of something)
- aggregate demand (growing consuming demand)
- inevitable
  - Jason knew he was going to get laid off, but he was trying to delay the inevitable.

#+BEGIN_EXAMPLE
  A: Dad, I'd like to borrow some money.

  B: Sure, Johnny, how much do you need? five bucks?

  A: Come on, Dad, I need thirty thousand. I wanna get into the market.
     You know, I'm tired of hearing all this news about the economic downturn,
     the inevitable recession, people stuffing their money in their mattresses.
     I look at this as an opportunity. This is a chance for me to get a jump start
     on building my nest egg.

  B: I don't know about that; with all the uncertainty in the markets right now,
     it would be a very unwise decision to invest. I don't know if you're aware son,
     but there has been a lot of turmoil in the markets recently.
     There have already been half a million layoffs in the last few months,
     and we have no idea how the proposed stimulus package will impact the economy.
     There's just too much instability. I wouldn't feel comfortable investing in this climate.

  A: But look at it this way, every challenge is an oppor tunity.
     And anyway, I'm not talking about investing in the domestic market.
     There are emerging markets that promise great returns. Look at China, for example;
     they have 1.4 billion people, half a billion of whom have recently entered the middle class.
     Here alone, the aggregate demand for consumer goods represents
     an amazing wealth generating opportunity.

  B: Come on, son, you're looking at this too naively, the Chinese market
     has exhibited a great deal of instability,
     and their currency has been devalued by almost a whole percentage point.

  A: Fine, then! If that's the way you feel, so be it.
     But you're losing out on a great opportunity here.
     I'm going to go hit up Mum for the cash.
#+END_EXAMPLE
