* [[https://wordsinasentence.com/oaf-in-a-sentence/][Oaf]]

  =someone known for being dumb=

  - Since the oaf never performed very well in school, he became lazy by living for years in his parent’s basement never being able to gain employment.
  - With the oaf’s foolish answer in class, everyone rolled their eyes and ignored any future answers he would say.
  - As the oaf quickly drove over five lanes of traffic without looking to see if any cars were in the lanes, many drivers blared their horns at him.
  - While attempting to rob the bank, the oaf accidentally wrote his name on the slip he gave the bank teller demanding money.


* [[https://wordsinasentence.com/oars-in-a-sentence/][Oars]]

  =flat blades that are used to row a boat=

  - Pulling on both oars, the levers propelled the boat through the water.
  - The boat was guided by steering oars so large that it took a dozen men to maneuver them.
  - Before setting sail, the ship’s sails and oars were checked for damage.
  - The boat’s oars proved useless when trying to sail on the rocky water.


* [[https://wordsinasentence.com/oasis-in-a-sentence/][Oasis]]

  =a haven from something unpleasant or tiring=

  - After spending twelve hours in the car, we felt as though our hotel was our oasis. 
  - Jane found the tourist desk to be an oasis of information during her visit to the city.
  - As soon as I walked into the spa, I felt like I had entered an oasis of calmness. 
  - For adults, the serenity pool area is an oasis of quietness.


* [[https://wordsinasentence.com/oath-in-a-sentence/][Oath]]

  =a solemn promise=

  - Jurors convicted the man of lying during trial while under oath.
  - A huge crowd surrounded the court house while the newly elected officials took the oath of office.
  - Giving an oath to love her forever, the groom was instructed to kiss the bride.
  - Crossing his fingers while he gave an oath to protect and serve, the scoundrel smiled at his unsuspecting victims.


* [[https://wordsinasentence.com/obdurate-in-a-sentence/][Obdurate]]

  =unmoved by persuasion, pity, or tender feelings; stubborn=

  - With his obdurate personality and intense dislike for people, Jonathan had all the makings of a professional killer.
  - Sometimes, you are too obdurate for your own good!
  - Despite the defendant’s apology, the judge was obdurate and gave him a thirty-year sentence.
  - Because Janice was obdurate, she did not shed a single tear while hearing the tragic story.
  - Even though his fellow teammates urged him to accept the new coach, the star basketball player remained obdurate and refused to follow the coach’s directions.
  - The protestors were obdurate and did not move even when the police arrived.
  - Will you stop being so obdurate and at least listen to my point of view?


* [[https://wordsinasentence.com/obedience-in-a-sentence/][Obedience]]

  =behavior that is meets the demands of others=

  - Even the city’s best obedience trainer could not gain control of the unruly pup.
  - In total obedience to his father, the prince begrudgingly went into exile.
  - The nun committed herself to the cause and a life of obedience to Christ.
  - During the obedience competition, the winning schnauzer was the only canine to sit perfectly still.


* [[https://wordsinasentence.com/obedient-in-a-sentence/][Obedient]]

  =conforming or submitting to someone’s wishes or demands=

  - Only obedient children were permitted to participate in the field trip since the teachers could trust their behavior to be appropriate at the museum.
  - When the obedient trainer commanded Max to sit, stay and roll over, the beagle complied with every request.
  - Since Ms. Withers was a strict woman, her household servants were very obedient because they wanted to keep the job due to its high salary.
  - Citizens during ancient history were required to be obedient to all church officials by paying for indulgences and worship the way they were told to do.


* [[https://wordsinasentence.com/obeisance-in-a-sentence/][Obeisance]]

  =a respectful obedient attitude=

  - In my family, we say a prayer before each meal to show obeisance and thanks.
  - Obeisance is not one of the rude secretary’s personality traits.
  - Because the teenage troublemaker showed a sign of obeisance, the judge let him off with a warning.
  - The young girl showed obeisance when she bowed before the queen.
  - The villagers displayed their obeisance to their god by kneeling at his altar.
  - With obeisance, Ray apologized to his parents for missing his curfew.
  - I often open doors for senior citizens as a sign of obeisance.


* [[https://wordsinasentence.com/obelisk-in-a-sentence/][Obelisk]]

  =a 4-sided rectangular shaped column that comes to a triangular point at the top=

  - While touring Washington D.C. for the first time in my life, I identified the tall obelisk as the Washington Monument.
  - One of the twin boys crafted a 3-D sword resembling an obelisk whereas the other twin’s sword was curved and less pointy at the top.
  - Many memorials are shaped as an obelisk because their tall structure appears sturdy and powerful.
  - Following the architect’s plans for the memorial, the foreman yelled up to his crew to construct the pyramid of the obelisk.


* [[https://wordsinasentence.com/obesity-in-a-sentence/][Obesity]]

  =the state of being excessively overweight=

  - Doctors were concerned about his patient who had always been a large boy, but now he had reached the level of obesity by medical standards due to his size.
  - Due to the increase in the family’s obesity, Jane worried about the health of her family including heart attacks and diabetes.
  - A significant problem that plagues the country is obesity due to its citizens’ poor eating habits and lack of exercise.
  - Accused of being the reason for obesity in the United States, fast food restaurants are now starting to serve healthier options like salads and yogurt.


* [[https://wordsinasentence.com/obey-in-a-sentence/][Obey]]

  =to act in accordance with the rules or someone’s wishes=

  - Billy was a model student to his teachers because he would actively participate in class and obey all the rules.
  - Since the twins had trouble with respecting authority, they would seldom obey the laws which resulted in multiple arrests.
  - Wanting to obey the strict leader’s commands, the citizens would do anything he asked no matter how dangerous the tasks were.
  - Kindergartners quickly became aware that if they obey their teachers, they get to participate in recess.


* [[https://wordsinasentence.com/obfuscate-in-a-sentence/][Obfuscate]]

  =to deliberately make something confusing or difficult to understand=

  - The loan contract was filled with legal words meant to obfuscate trusting borrowers.
  - Because I am a sympathetic teacher, I avoid using language which will obfuscate my students.
  - Surprisingly, the efforts of the translator only served to obfuscate an already confusing conversation.
  - The last thing I want to do is obfuscate the concept by trying to explain it too rapidly. 
  - If you will obfuscate the store clerk with some crazy questions, I will steal the candy.
  - The con man hoped to obfuscate the elderly woman by using large words to describe his investment plan.  
  - Because I am honest, I never try to obfuscate my true intentions!  


* [[https://wordsinasentence.com/obituary-in-a-sentence/][Obituary]]

  =a notice of death that provides background information about the deceased=

  - The lone obituary was mistakenly listed in the paper under job postings instead of death notices.
  - As death drew near, the cancer patient insisted that she wanted to write the obituary that would be posted after her passing.
  - It wasn’t until writing her husband’s obituary that the new widow really accepted his passing.
  - Writing her father’s obituary notice was a way for the grieving daughter to get closure and celebrate his life.


* [[https://wordsinasentence.com/objectify-in-a-sentence/][Objectify]]

  =to reduce a person’s status and treat them negatively=

  - The boy’s mother refuses to let him listen to rap songs that objectify women or portray them in a negative way.
  - Narcissistic and selfish, the man tends to objectify and diminish the importance of every person in his life.
  - Trying to objectify his wife, the husband refused to treat her with dignity or respect.
  - Even though he was told not to objectify his classmates, the bully tried to diminish their self-worth any chance he got.


* [[https://wordsinasentence.com/objection-in-a-sentence/][Objection]]

  =a purpose for opposing or protesting a statement or action=

  - Everyone frowned when the father of the bride unjustly stated his objection to the marriage for the lovely young couple.
  - Before suing his neighbor, Mr. Bills discussed his objection with the neighbor’s fence being installed on his property.
  - The strictly religious woman argued her objection to her son’s school because the school’s celebration of Halloween violated her son’s religious rights.
  - During the Vietnam War, the United States felt a division of loyalty when common citizens would voice an objection to the war.


* [[https://wordsinasentence.com/objectionable-in-a-sentence/][Objectionable]]

  =insulting or upsetting actions or behaviors=

  - Since there was objectionable content in the movie, the teenager’s mother refused to let her daughter see the movie with her friends.
  - Any time the hypochondriac claimed to be sick, we felt certain his objectionable disease was merely a desire for attention.
  - Even though Billy was diagnosed with an objectionable disorder, it was believed he may just be a regular spritely 7-year old.
  - Objectionable methods used to extract terrorists’ information like water torture were frowned upon by some citizens but approved by military officials.


* [[https://wordsinasentence.com/objective-in-a-sentence/][Objective]]

  =that which is sought; a particular task or goal=

  - The objective of my resume is to obtain a position in the company’s quality assurance department.
  - Obviously the objective of the maximum-security prison is to keep all inmates imprisoned.
  - The objective of the video game is to eliminate the witch’s henchmen and rescue the princess.
  - If Matt passes five out of six classes, he will have met the objective for promotion to the seventh grade. 


* [[https://wordsinasentence.com/objectivity-in-a-sentence/][Objectivity]]

  =the condition of having an unbiased opinion=

  - The judge was removed from the bench because he lacked objectivity when listening to cases associated with minority defendants. 
  - Because the blog is known for its fairness and objectivity, it’s a popular news source for people who appreciate impartial articles.
  - The lawyers do their best to dismiss jurors who lack objectivity on the trial issue.
  - When it comes to someone hurting one of their own, police officers tend to lose their sense of objectivity. 


* [[https://wordsinasentence.com/objurgate-in-a-sentence/][Objurgate]]

  =to admonish or yell firmly at someone or something=

  - After the toddler had a temper tantrum in the store, the angry mother would objurgate her son in his face for ten minutes.
  - The principal and the teacher objurgate the misbehaving student so loudly that the other students could hear them in the classroom.
  - With a red face, the judge would objurgate the criminals who would enter his courtroom until they would admit they were wrong.
  - After viewing the yellow stain on the new carpet, the dog owners objurgate the little puppy which caused him to tuck his tail and cower under the bed.


* [[https://wordsinasentence.com/obligate-in-a-sentence/][Obligate]]

  =to be required or forced=

  - All citizens of the United States must obligate to vote in every election as their civic duty.
  - Witnesses of the crime will obligate to stand before the court and state what they saw at the scene in order for the criminal to be found guilty.
  - After years of the same Christmas customs, my family members obligate to buy presents at least for all of the children in the family.
  - All banks obligate people to repay their loans or take the chance of their credit being ruined.


* [[https://wordsinasentence.com/obligation-in-a-sentence/][Obligation]]

  =something you must do because of a law, a promise, rule, etc.=

  - Even though attendees were invited to the candle party, they were under no obligation to purchase anything.
  - Bradley felt he had an obligation to accept the offer to attend his father’s alma mater.
  - An obligation of being an employee is following standard operational procedures.
  - Because she was a police officer, Betty felt an obligation to uphold the law at all times.


* [[https://wordsinasentence.com/obligatory-in-a-sentence/][Obligatory]]

  =required by law or a set of rules=

  - As part of my obligatory court sentence, I must complete sixty hours of community service.
  - New hires must attend the obligatory orientation session.
  - Because Ray is an awesome host, he never fails to perform the obligatory duties like greeting each guest and keeping glasses full.
  - Every cheesy spy movie has the obligatory fight scene that lasts at least fifteen minutes.


* [[https://wordsinasentence.com/oblige-in-a-sentence/][Oblige]]

  =perform a good deed for someone=

  - Since my neighbor cuts my grass for free, I am happy to oblige him with a ride to the store.  
  - If you would like to see certain things on your tour, please tell the guide so she can oblige your requests if time permits. 
  - Sheila was happy to oblige the soldier with bus fare home.
  - When Jack asked for a loan, his father could not oblige him because of his recent job loss.


* [[https://wordsinasentence.com/obliging-in-a-sentence/][Obliging]]

  =accommodating; willing to be of assistance=

  - The obliging clerk was pleased to answer my numerous questions about the store.
  - Because my waitress appeared happy to serve me, her obliging nature earned her a huge tip. 
  - Jack was very obliging at work because he wanted to earn a promotion.
  - Out of fear of being whipped or killed, the slaves were obliging to their masters.


* [[https://wordsinasentence.com/oblique-in-a-sentence/][Oblique]]

  =not in a straightforward manner=

  - The slight wink was Larry’s oblique way of flirting with me.
  - Because the commercial is oblique in its sexual references, it has not been pulled from the Christian network.
  - Putting a dead rat on a person’s doorstep is an oblique way in which the mob has been known to warn possible snitches.
  - To avoid worrying his wife, the man made an oblique statement about the seriousness of his medical condition. 


* [[https://wordsinasentence.com/obliterate-in-a-sentence/][Obliterate]]

  =to destroy=

  - The dictator’s army is going to obliterate the rebel’s small village in less than five minutes. 
  - Although I spent hours building my daughter’s dollhouse, I was shocked to watch her obliterate it simply by pulling out one of the support columns.
  - Hank’s cheating is sure to obliterate his twenty-year marriage to Helen.
  - If a plane lands on your home, it will obliterate your property.
  - The property developers are going to obliterate the rainforest if they keep cutting down trees and driving out wildlife.
  - According to scientists, the nuclear weapon has the capacity to obliterate the entire city.
  - The general’s plan is to obliterate the enemy’s military runways so their fighter planes cannot launch an aerial attack.


* [[https://wordsinasentence.com/oblivion-in-a-sentence/][Oblivion]]

  =the condition of being unaware or uninformed=

  - After I was given the sedative, I was in complete oblivion and unaware of my surroundings.
  - Jim was so miserable in his marriage he often drank himself into oblivion to escape his sorrow.
  - Since Charles let his accountant handle all of his business dealings, he was in oblivion when the Internal Revenue Service asked him about tax fraud.
  - The novel put me in such a state of oblivion I forgot to prepare dinner for my family.


* [[https://wordsinasentence.com/oblivious-in-a-sentence/][Oblivious]]

  =unaware of what is present or occurring=

  - The huge dog closed its eyes and appeared oblivious to the crawling baby.
  - How could the rich man be oblivious to the hungry man asking him for a dollar?
  - As Gene rapidly ate his dinner, he seemed oblivious to the taste of the burnt food. 
  - The absent-minded couple acted oblivious to the mess their child made in the restaurant.


* [[https://wordsinasentence.com/oblong-in-a-sentence/][Oblong]]

  =possessing an elongated figure, like an oval or rectangle=

  -  The skating rink was oblong shaped and resembled a large oval.
  - When I looked at the moon, I saw its figure was half-moon or oblong.
  - His squinted eyes formed oblong shapes.
  - Under the special microscope, it was easy to see the oblong form of the sickle shaped blood cells. 


* [[https://wordsinasentence.com/obloquy-in-a-sentence/][Obloquy]]

  =shame from public disapproval=

  - After being released from prison, Kurt lived in obloquy and rarely left his apartment. 
  - The senator’s admission of adultery brought much obloquy and ended his political career.
  - Even though Jose knew telling the truth would bring obloquy from his gang, he refused to let his brother’s killer go free.
  - The soccer team went home to obloquy after losing the finals because of stupid mistakes.
  - Because Kate experienced obloquy after reporting the star quarterback for sexual assault, she changed schools.
  - James always felt obloquy because of his father’s infamy as a serial killer.
  - Since being arrested for associating with prostitutes, the minister has been in hiding to escape the obloquy of his actions.


* [[https://wordsinasentence.com/obnoxious-in-a-sentence/][Obnoxious]]

  =disagreeable in a way that disgusts other people=

  - Nobody wanted to talk to the obnoxious man. 
  - As soon as I got on the plane and saw I’d be sitting next to an obnoxious child, I asked the flight attendant for another seat.
  - The man was asked to leave the restaurant because of his obnoxious behavior.
  - Did you notice the obnoxious person picking his nose at the dinner table? 


* [[https://wordsinasentence.com/obnubilate-in-a-sentence/][Obnubilate]]

  =to obscure or darken something=

  - If a cloud passes in front of the sun, it will obnubilate the ground beneath it, creating shade and making everything darker.
  - I find it difficult to sleep when there is too much light in my room, so I use dark curtains to obnubilate the rays of the sun.
  - Sunglasses are one of the most common tools used by people to obnubilate the blinding and sometimes damaging rays of light from the Sun.
  - Some people use tinted windows to obnubilate the interior of their vehicles, hiding them from prying eyes outside.


* [[https://wordsinasentence.com/obscene-in-a-sentence/][Obscene]]

  =vile; disgusting=

  - I wish adult websites would stop sending me obscene emails!
  - If you keep using obscene language, you're going to get in trouble at school.
  - Tammy gave her son a good scolding when she found a stash of obscene magazines under his bed. 
  - As I rode past the driver who cut me off, I made an obscene sign with my fingers. 


* [[https://wordsinasentence.com/obscure-in-a-sentence/][Obscure]]

  =relatively unknown=

  - The obscure writer was not known in the literary community.
  - Because the millionaire was a shy man, he enjoyed living an obscure life in the country.
  - Today’s sighting is the first time Dr. Samuels has ever seen the obscure family of insects.
  - Since my husband prefers an obscure lifestyle, he does not interact through social media at all.
  - In our poverty-stricken town, having extra money is an obscure habit for most people. 
  - Everyone was shocked when the city council used an obscure rule to vote on the proposal without a majority of voters present. 
  - Although the new cancer drug has received a lot of interest from medical professionals, its side effects are obscure so the drug is still classified in the testing phase. 


* [[https://wordsinasentence.com/obscurity-in-a-sentence/][Obscurity]]

  =the condition of being unknown=

  - The teen heartthrob came out of obscurity and became one of the most famous entertainers in the world.
  - If you do not promote your film, it will remain in obscurity and no one will ever see it.
  - The author’s books remained in obscurity until her publisher reprinted them after her death.
  - When questioned about his fame, the actor stated he missed the obscurity of being able to go shopping without being bothered.


* [[https://wordsinasentence.com/obsequies-in-a-sentence/][Obsequies]]

  =a funeral service=

  - Last week, obsequies for the deceased students were held at the cemetery. 
  - Mourners around the world watched the celebrity’s televised obsequies. 
  - While working as a mortician, Kevin knew the worst part of his job was preparing for a child’s obsequies.
  - My grandmother never fails to send flowers to a deceased friend’s obsequies.


* [[https://wordsinasentence.com/obsequious-in-a-sentence/][Obsequious]]

  =Excessively submissive; overly obedient=

  - The princess had obsequious servants who showered her with attention.
  - At work, the obsequious assistant complimented her manager so much that she quickly advanced up the corporate ladder.
  - When he receives obsequious service, Lawrence always leaves a huge tip.
  - Extremely obsequious, most puppies want nothing more than to please their masters. 
  - From his obsequious behavior, it was obvious Jackson was smitten with his wife.  
  - It infuriates me that your obsequious personality makes you agree with every word I say!
  - Jane is the teacher’s favorite because she is so obsequious in class. 


* [[https://wordsinasentence.com/observance-in-a-sentence/][Observance]]

  =the act of conforming to situations and following rules=

  - Good students are in observance of the classroom rules by raising their hand to answer a question, speaking politely to others and keeping their hands and feet to themselves.
  - Their observance of silence resulted in the hush of the surrounding people until everyone was quiet in remembrance of the deceased man.
  - When the visitors entered the foreign country, they followed every traffic rule and ordinance due to their observance of the laws.
  - Once the exchange students become acclimated to the country’s culture, their observance of the traditions and customs will take place.


* [[https://wordsinasentence.com/observant-in-a-sentence/][Observant]]

  =to notice or detect things quickly=

  - Dr. Mills’ observant personality enabled her to be a great detective since she could determine if a suspect was lying.
  - The parents knew they would have to be observant around their son when they suspected him of using drugs.
  - Due to his observant tendencies, the nosy neighbor was able to give the police details of the robber next door.
  - Observant hikers will pay attention to the ground, so they don’t trip over small stumps and twigs.


* [[https://wordsinasentence.com/observation-in-a-sentence/][Observation]]

  =that which is noticed by observing or listening=

  - During our observation, we watched the solution change colors.
  - The detective made an important observation when he noticed the broken glass was outside the window.
  - While the infant is in the hospital, she will be under constant observation.
  - The astronomer discovered a new star during a recent observation.


* [[https://wordsinasentence.com/observe-in-a-sentence/][Observe]]

  =to watch cautiously and seriously=

  - “If you observe anything suspicious,” said the school’s security officer, “you must report it to the office immediately for the safety of the school.
  - After viewing about 8 hours of footage of the crime scene, Detective Mullins was able to observe the suspect talking to the victim.
  - The store owner made it a point to observe the type of customers who came into the store in order to place advertisements that catered to those type of people.
  - Ornithologists observe every aspect of a bird including their behaviors, appearance and social interaction with other birds.


* [[https://wordsinasentence.com/obsession-in-a-sentence/][Obsession]]

  =the control of one’s thoughts about something or someone=

  - Billy’s ex-girlfriend was deemed a stalker due to her obsession with him by always watching, calling and thinking about him.
  - The 40-year old’s obsession with youth and beauty was obvious with her two dozen plastic surgeries done just on her face.
  - Celebrities live a life of wealth and fame which seems to create an obsession by some of their fans who want to have lives just like them.
  - Her obsession with shopping caused Sally to spend her life savings in a matter of a few months leading to excessive debt and then bankruptcy.


* [[https://wordsinasentence.com/obsessive/][Obsessive]]

  =totally fixated on something or someone in a way that is unhealthy=

  - Because of his obsessive disorder, the patient focuses on washing his hands most of the day.
  - The obsessive husband is so fixated on how his wife spends her day, he is often late for work.
  - Milton’s obsessive desire to become a celebrity has led him to make some very poor decisions.
  - Because of her obsessive nature, the neurotic housewife fixates on keeping things spic and span.


* [[https://wordsinasentence.com/obsidian-in-a-sentence/][Obsidian]]

  =a dark black rock created from cooled lava with relatively no crystals in it=

  - Since the obsidian was easy to break, pieces of it were carved to make knives used in surgical procedures.
  - As a souvenir from the eruption of Mount St. Helens, I kept a chunk of the obsidian that was left from the historical flow.
  - With a solid black color, the obsidian could be easily spotted in the earth by its simple monochromatic color.
  - Geologists unearthed a pile of shards of obsidian as they dug at the site of a famous ancient volcanic eruption.


* [[https://wordsinasentence.com/obsolescence-in-a-sentence/][Obsolescence]]

  =becoming outdated=

  - Since the granite countertops were such an obsolescence in the neighborhood homes, the builder knew he would need to upgrade to higher quality materials like marble.
  - Due to the obsolescence of the car’s transmission, the mechanic knew he couldn’t purchase the needed transmission from any manufacturer in the world.
  - Once cell phones became equipped with visual tools, regular cameras became an obsolescence in the technological industry.
  - As I was cleaning out the office supply closet at work, I knew the shelf containing items of obsolescence like typewriter ribbon could be tossed out.


* [[https://wordsinasentence.com/obsolete-in-a-sentence/][Obsolete]]

  =no longer of use=

  - Many people believe the Internet has made the postal service obsolete.
  - If you look inside of most classrooms, you will not see chalkboards because they are nearly obsolete in education today.
  - Once Frank spent all of his lottery winnings, he became obsolete to his family members.
  - Despite what people say, I still use my VCR because it is not obsolete to me!


* [[https://wordsinasentence.com/obstacle-in-a-sentence/][Obstacle]]

  =anything that impedes or stops something from advancing or developing=

  - Having a bankruptcy in my background would be a difficult obstacle to overcome in financing a new house.
  - The new mother faced an obstacle of providing time for her newborn baby while working a demanding and time-consuming job.
  - As a refugee in a new country, one obstacle Frank was able to conquer was the language barrier by taking English classes at night.
  - Fierce winds and deadly waves were only one obstacle many explorers like Christopher Columbus confronted when sailing to unknown lands.


* [[https://wordsinasentence.com/obstinacy-in-a-sentence/][Obstinacy]]

  =the quality of refusing to be reasonable and change your behavior, plans, or ideas; stubborness=

  - Although the detectives grilled the witness for hours, his obstinacy in sticking to his story finally convinced them that he was telling the truth.
  - The obstinacy of both children in insisting on their own choice of movie resulted in an evening with no movie at all.
  - Lindsey just would not let go of her obstinacy over a vacation that didn’t involve tents and latrines, so Benjamin finally put his camping gear away and agreed to talk to a travel agent.
  - If it hadn’t been for Mason’s obstinacy and his mother’s anxiety, he probably would have been potty-trained months sooner.
  - No matter what logic or rationale I used, nothing I came up with could break through her obstinacy.
  - Because his obstinacy is greater than his judgment, Miles will never back down in a dispute.
  - Nora went suicide during Rush because she had her heart set on getting into just one sorority, but her obstinacy left her out in the cold when the bids went out.


* [[https://wordsinasentence.com/obstinate-in-a-sentence/][Obstinate]]

  =stubbornly refusing to change one's opinion or action; very difficult to change or persuade; refusing to obey=

  - Everyone described my grandfather as the most obstinate man alive!
  - Although the little boy knew he was wrong, he was too obstinate to apologize to his parents.
  - Obstinate and unyielding, the judge refused to give the defendant credit for time served.
  - The obstinate protestors refused to leave the office complex.
  - Because she is so obstinate, my niece often ends up eating dinner alone in her room.
  - Even though Henry’s friends wanted him to join them at the arcade, he remained obstinate and went to the library to study.
  - Cheryl was obstinate and refused to admit her marriage was over. 


* [[https://wordsinasentence.com/obstreperous-in-a-sentence/][Obstreperous]]

  =noisy and difficult to control=

  - Because my nephew is obstreperous, he often gets in trouble at school. 
  - The teenagers became obstreperous when their school team lost the football game.
  - When my husband drinks too many beers, he becomes obstreperous.
  - The football fans were obstreperous throughout the championship game.
  - After winning the battle, the obstreperous troops had to be calmed down by their commanding officer.
  - If you see me at a dance club with my friends, you might think I am obstreperous because I like having a fun time. 
  - When you are inside of a library, you should be quiet not obstreperous.


* [[https://wordsinasentence.com/obstruct-in-a-sentence/][Obstruct]]

  =to block or fill with obstacles=

  - I have a hard time driving through the downtown because of all the bikers who continually obstruct traffic.
  - We hope to prevent the municipality from planting trees near the crossway for fear that it may obstruct a driver’s view from oncoming traffic.
  - The protesters deliberately obstruct traffic by shutting off their engines during rush hour.
  - Because extra throat tissue can obstruct proper breathing while one sleeps, Frank’s doctor advised him to go on a diet.


* [[https://wordsinasentence.com/obstruction-in-a-sentence/][Obstruction]]

  =that which prevents progress; an impediment=

  - In addition to causing Gary great pain, the bowel obstruction is also preventing him from releasing waste. 
  - The police are filing obstruction charges against the woman who hid her husband’s bloody clothing.
  - Once the obstruction is removed, water will continue to flow through the pipe.
  - Your lying is an obstruction of justice that could allow a killer to flee the country.


* [[https://wordsinasentence.com/obtain-in-a-sentence/][Obtain]]

  =to secure or acquire something=

  - My daughter must obtain a copy of her immunization records before she can start school.
  - Who do I need to speak with in order to obtain an interview with the star quarterback? 
  - The crook will need to obtain a fake driver’s license in order to cash the old man’s check.
  - If you try to obtain medicine with a phony prescription, you could be arrested.


* [[https://wordsinasentence.com/obtainable-in-a-sentence/][Obtainable]]

  =something that is capable of being acquired=

  - Her only obtainable goal was to make straight A’s since she was too short for the basketball team and too clumsy for cheerleading.
  - Due to Betty’s test scores and IQ, her highest obtainable grade in English seemed to be a C+ according to her teachers.
  - Buff Fitness Center assured obtainable results for every client simply by sticking to a daily 45-minute exercise routine.
  - Making a decent living was only obtainable with at least a bachelor’s degree and a strong work ethic.


* [[https://wordsinasentence.com/obtest-in-a-sentence/][Obtest]]

  =to beseech or beg, usually a deity=

  - Although I obtest the Lord every night, my prayer has yet to be answered.
  - I obtest you, oh Heavenly Father, to grant me this one wish.
  - Waiting outside the temple, the believer could not wait to obtest his deity for financial favor.
  - The farmer placed his sacrifice upon the altar and began to obtest the god of harvest for another plentiful yield.


* [[https://wordsinasentence.com/obtrude-in-a-sentence/][Obtrude]]

  =to interrupt in an unpleasant manner=

  - Please silence your phones so they do not obtrude upon our meeting.
  - On our honeymoon, we put the do not disturb sign on our door so the maid would not obtrude on our privacy.
  - Just as I was about to have my first kiss, my mother chose to obtrude upon the special moment  by walking into my room.
  - How dare you obtrude upon my vacation by calling me with a work related issue!


* [[https://wordsinasentence.com/obtrusive-in-a-sentence/][Obtrusive]]

  =obvious in an unlikable way=

  - The vinegar in the sauce was obtrusive and ruined the taste of the steak. 
  - During the test, the clock on the wall was obtrusive as it ticked unusually loud. 
  - The obtrusive coat is so big and puffy that it cannot be worn comfortably in a crowded room. 
  - After the wedding, the obtrusive media followed the celebrity couple on their honeymoon.
  - Heather was obtrusive as she went out of her way to show everyone her pricey engagement ring.
  - When I glanced at the new mobile phone, I realized it was so big it would be obtrusive in my hand.
  - The woman’s obtrusive hat blocked my view of the concert stage.


* [[https://wordsinasentence.com/obtuse-in-a-sentence/][Obtuse]]

  =not able to think clearly or to understand what is obvious or simple=

  - Are you so obtuse that you will give away all your money to a fake charity?
  - The obtuse young man had a hard time understanding the simple instructions.
  - If you do not pay attention in math class, you may feel obtuse during the final exam.  
  - Sometimes my youngest brother seems too obtuse to understand anything I say.
  - After taking the strong medication, Jenny was so obtuse she could not read the newspaper.
  - The obtuse student was not able to answer a single test question.
  - Because the man was obtuse after a night of partying, he was unable to pass his driver’s test.


* [[https://wordsinasentence.com/obtuseness-in-a-sentence/][Obtuseness]]

  =a condition of lacking intelligence; stupidity=

  - In an attempt to hide his obtuseness on the subject, the student remained quiet during the discussion.
  - Larry’s obtuseness prevented him from being able to understand the simple instructions.
  - Because of Kim’s obtuseness, she has been in the same grade for two years.
  - Your dumb decisions are proof of your obtuseness.


* [[https://wordsinasentence.com/obverse-in-a-sentence/][Obverse]]

  =the reverse or foil of a certainty or fact=

  - While I thought my parents would be happy I got a job, the obverse was true when they learned I’d be working in a strip club.
  - Sadness is the obverse or opposite of happiness.
  - As a child, I quickly learned “no” was the disappointing obverse of “yes.”
  - To win the debate, you will need to prove the obverse of your opponent’s argument. 


* [[https://wordsinasentence.com/obviate-in-a-sentence/][Obviate]]

  =to prevent or eliminate=

  - We replaced the old mechanisms because we wanted to obviate any nervousness about potential breakdown.
  - I tried to obviate my mother’s awkwardness with the cell phone by telling her it wasn’t necessary to hold it up to her mouth when she speaks into it.
  - Because he wanted to obviate the strain of climbing the stairs, Dr. Johnson ordered the patient to have his bedroom furniture moved to the room on the bottom floor.
  - Even though the government has employed many safeguards to obviate abuse of the welfare system, there are still too many people robbing the taxpayers through fraudulent claims.
  - After his mother had fallen in the bathtub, Farley installed safety rails in order to obviate any recurrence of such a mishap.
  - Because our mother was always inclined to obviate conflict under any circumstances, we all got our own gifts on our siblings’ birthdays.
  - If you want to obviate the risk of skin cancer throughout your life, it’s important that you are protected from sun exposure from the time you are an infant.


* [[https://wordsinasentence.com/obvious-in-a-sentence/][Obvious]]

  =noticeable and likely to be determined=

  - When the child touched the hot stove with his hand, his obvious reaction would be to never touch the stove again.
  - To see if his students were listening, Dr. Toldwell posed a simple question with an obvious answer.
  - When the child received a bullhorn for a gift, every family member knew the obvious noise came from the obnoxious present.
  - As the woman in the wedding dress ran towards the Appleton Catholic Church, it was obvious that she was late for her wedding.


* [[https://wordsinasentence.com/obviously-in-a-sentence/][Obviously]]

  =clearly; in a way that is easy to see and understand=

  - Obviously wanting the boy to ask her to dance, the girl tapped her foot impatiently.
  - The defending champ was obviously the winner, but the crowd continued to cheer for the underdog.
  - The obviously underage group was quickly escorted out of the club by bouncers.
  - Folding the hand was obviously the smart choice; however, the risky poker player decided to go all-in.


* [[https://wordsinasentence.com/occasion-in-a-sentence/][Occasion]]

  =a particular and significant event or incident=

  - “This isn’t just any anniversary,” said the grandson, “it is a special occasion for Grandma and Grandpa to celebrate their 50th wedding anniversary.
  - Sarah understood the importance of the occasion when lots of money and time were spent getting the venue, food and music ready.
  - The 2010 Trayville Marathon marked the occasion when Sally was able to complete a full marathon without stopping.
  - Birth of their children was the most important occasion in the lives of Cassie and Fred which they would never forget.


* [[https://wordsinasentence.com/occasionally-in-a-sentence/][Occasionally]]

  =from time to time=

  - Before our relationship turned serious, we began meeting occasionally at a coffee shop that both of us enjoyed.
  - Occasionally I like to head out in my boat, to get away from my work environment that threatens to engulf me.
  - Although we like to go out for dinner occasionally, in the main we eat our meals at home.
  - Barbara followed instructions to stir the pot occasionally as the stew cooked slowly on the burner.


* [[https://wordsinasentence.com/occidental-in-a-sentence/][Occidental]]

  =pertaining to the countries in the western hemisphere=

  - Visitors from Thailand state that the occidental food at the restaurant tasted unusual since they were not familiar with this country’s food.
  - While tutoring Chinese children online, I teach English to the students as well as some of the occidental customs of America.
  - People from the eastern hemisphere were unaware of some of the occidental places located on the opposite side of the world.
  - Even though Zu knew many Asian languages, she struggled with understanding what was said by those who spoke an occidental language.


* [[https://wordsinasentence.com/occlude-in-a-sentence/][Occlude]]

  =to close up or block off=

  - The police officers have blocked off the road to occlude the bomb from the public.
  - Although I do not want you inside of my office, I will not occlude your entry by locking the door while I am away.
  - It is quite dangerous when blood clots occlude the flow of oxygen in the human body.
  - Since I do not like people looking inside of my home, I use blinds to occlude my windows.
  - It looks like the clouds are going to occlude the sun and ruin my picnic!
  - Because my parents did not trust strangers, they did everything they could to occlude me from the outside world.  
  - During the surgery, the doctor will do everything possible to not occlude the flow of blood to the patient’s heart.


* [[https://wordsinasentence.com/occult-in-a-sentence/][Occult]]

  =relating to magical or supernatural abilities=

  - The occult show about a group of teenage witches living together is one of the highest rated shows on television.
  - Although the pretend psychic has no occult powers, she leads people to believe she does.
  - It is said that on Halloween night all the occult creatures walk the Earth. 
  - Can you believe Sarah is going to take the occult arts class so she can learn how to torture her ex-husband from a distance?
  - Surprisingly, the nonfiction author is writing a novel that centers on an old man who engages in occult science to bring his wife back from the dead.
  - As soon as I learned the occult ritual involved killing a rabbit, I knew I wanted no part of the family’s annual tradition.
  - Mary’s occult shop contains a variety of spell books, herbs, and magical cards and crystals.


* [[https://wordsinasentence.com/occupancy-in-a-sentence/][Occupancy]]

  =living in or currently staying in a house or structure=

  - Building codes required a maximum occupancy of 125 people in the restaurant which was based on the number of exits.
  - Occupancy in the Grand Hotel was unusually only half filled due to the approaching hurricane in the area.
  - Landlords would prefer a full occupancy in their apartment buildings, so they could collect more rent from the people who live there.
  - On Christmas Eve, irony occurred when the homeless shelter had to turn away a pregnant woman because the shelter reached its maximum occupancy.


* [[https://wordsinasentence.com/occupant-in-a-sentence/][Occupant]]

  =someone who lives or is currently in a house or other structure=

  - Once the occupant realized the apartment building was on fire, she knew it was imperative to leave her possessions behind and exit the building immediately.
  - After the robbery, the police officers knocked on the door asking the occupant about whether he saw anything suspicious on the night of the crime.
  - State troopers may ask any occupant in the car for identification if there is unusual behavior from anyone in the car.
  - The occupant tried to explain to the home loan company that she was merely a tenant and did not own the house.


* [[https://wordsinasentence.com/occupation-in-a-sentence/][Occupation]]

  =an industry or service for which someone makes a living=

  - In the accounting occupation, the young man was hired specifically to be the accounts receivable clerk since he had prior experience doing that type of work.
  - Switching to a different occupation required the woman to take a few more classes so that employers in that field would consider her capable of doing that work.
  - When the man walked into the restaurant wearing scrubs, everyone knew that his occupation must be in the medical field.
  - After spending twenty years in the occupation of the restaurant sector, the manager decided to pursue another management position elsewhere.


* [[https://wordsinasentence.com/occupy-in-a-sentence/][Occupy]]

  =to live in or inhabit a place=

  - Landlords may expect damage to their houses if college students are expected to occupy their apartments or houses.
  - Farmer John realizes that rodents and raccoons seemed to occupy his old barn because of the scratch marks, fur and animal droppings left along the barn floor.
  - Ghost hunters speculated that no one seemed to occupy the abandoned hospital since the structure was in disarray and no remnants of human life were found.
  - The motel manager agrees to allow the couple to occupy the room for 3 weeks, but after that they would need to find a long-term rental place.


* [[https://wordsinasentence.com/occur-in-a-sentence/][Occur]]

  =to take place; happen=

  - There was no way to predict when the earthquake would occur, but scientists were certain it would happen.
  - More car accidents occur in Washington D.C. than any other city in the U.S.
  - Although diabetes and depression are different diseases, they can occur at the same time.
  - It seemed strange that pain did not occur immediately after the burn.


* [[https://wordsinasentence.com/occurrence-in-a-sentence/][Occurrence]]

  =an instance or happening=

  - Haley’s Comet is an occurrence that takes place approximately every seventy-six years.
  - After hearing about the ghostly occurrence at the hotel, I decided to seek lodging elsewhere. 
  - The changing of the seasons is a natural occurrence that happens four times a year.
  - As soon as the paroled felon started to work at the grocery store, drawer shortages became a frequent occurrence.


* [[https://wordsinasentence.com/octagon-in-a-sentence/][Octagon]]

  =an 8 equally sided shape=

  - Rainbow colors reflected onto the wall through an octagon as the light shines through the many surfaces of the prism.
  - Unfortunately, I did not see the red octagon on the side of the road when the police officer pulled me over for running a stop sign.
  - Each member in our family of eight had plenty of space at the large picnic table since it was in the shape of an octagon.
  - Since each small tile to be used on the floor was cut as an octagon, the installation of the floor was very tedious due to its many pieces.


* [[https://wordsinasentence.com/octogenarian-in-a-sentence/][Octogenarian]]

  =one who is between the age of 80 and 89=

  - My neighbor was an octogenarian and needed assistance addressing his 88th birthday invitations.
  - The octogenarian was losing his eyesight and was no longer able to drive.
  - My sick grandpa was very excited to be reaching octogenarian status.
  - For my report on ancestry, I needed to interview an octogenarian family member.


* [[https://wordsinasentence.com/ocular-in-a-sentence/][Ocular]]

  =associated with vision or eyesight=

  - Ocular pain forced me to call my eye doctor.
  - When my teenaged daughter learned she needed an ocular device to improve her vision, she immediately requested contact lenses.
  - Scientists wear goggles in the lab to prevent ocular injury.
  - If the ocular disease remains untreated, it could cause blindness.


* [[https://wordsinasentence.com/oculist-in-a-sentence/][Oculist]]

  =an out-of-date term which refers to either an ophthalmologist or optometrist=

  - The oculist gave me a prescription for new eyeglasses.
  - During my visit to the oculist, I took an eye exam.
  - My mother took me to see an oculist about my eye infection.
  - According to the oculist, contact lenses can improve my vision.


* [[https://wordsinasentence.com/oddity-in-a-sentence/][Oddity]]

  =an unusually strange person, thing, or event=

  - The lanky man and his petite wife are always looked at like an oddity in public.
  - The disorganized office was quite an oddity in the otherwise immaculate home.
  - It seemed such an oddity, the number one team in the nation lost to a team with a horrible record.
  - Real estate agents in the area thought it to be an oddity that booking appointments were dropping as the economy stabilized.


* [[https://wordsinasentence.com/ode-in-a-sentence/][Ode]]

  =a poem that praises or celebrates something=

  - Phil created lyrics for the choir that were an ode to his alma mater.
  - Mel recited a beautiful ode under his sister’s wedding canopy while softly strumming on his guitar.
  - The poet spent years writing an ode that takes many hours to recite.
  - I wrote an ode to the United States and asked Jeff to recite it at the parade.


* [[https://wordsinasentence.com/odious-in-a-sentence/][Odious]]

  =unpleasant; repulsive=

  - Because Mark had an odious personality, he had very few friends.
  - The athlete got arrested for participating in the odious sport of dog fighting.
  - Although I normally notice unpleasant smells right away, I cannot detect the odious scent you noticed in the house.
  - Cleaning the toilet is such an odious task.
  - To me, all spiders are odious creatures.
  - The milk must be old because it has an odious taste to it.
  - Although Clara has showered five times, she still carries the odious scent of the skunk which sprayed her.


* [[https://wordsinasentence.com/odium-in-a-sentence/][Odium]]

  =loathing for a thing or person deemed to be despicable=

  - The public’s odium towards the congressman is an advantage for the candidate opposing him in the election. 
  - After getting out of prison, the child molester still had to deal with odium from his neighbors.
  - The new abortion bill is sure to trigger odium from church leaders.
  - Because of my odium for the politician’s views, I have no plans to vote for him.


* [[https://wordsinasentence.com/odometer-in-a-sentence/][Odometer]]

  =an instrument used to measure how far a vehicle has travelled=

  - Odometer fraud is illegal, but that doesn’t stop scammers from rolling back the miles on used vehicles.
  - According to the odometer, the used vehicle had well over 200,000 miles.
  - Setting back the odometer allowed the crooked car salesman to trick potential buyers into thinking the vehicle was barely driven.
  - With a low price and only a few miles on the odometer, the like-new SUV was a steal.


* [[https://wordsinasentence.com/odor-in-a-sentence/][Odor]]

  =a distinctive smell=

  - A strong stench filled the room, causing the guests to gag at the odor.
  - The pine odor of the forest reminded the hiker of his childhood during Christmastime.
  - Pinching her nose to avoid the odor, the maid was horrified by the refrigerator’s rotting contents.
  - Although he couldn’t stand the odor, the man burned the vanilla candle to appease his wife.


* [[https://wordsinasentence.com/odoriferous-in-a-sentence/][Odoriferous]]

  =producing an unpleasant scent=

  - After eating six burritos, my brother turned the bathroom into an odoriferous chamber. 
  - The rotting corpse transformed the tiny house into an odoriferous dwelling.
  - The pregnant woman became nauseated when she smelled the scent from the odoriferous fish market.
  - The dog’s odoriferous gassiness made everyone leave the room.


* [[https://wordsinasentence.com/odorous-in-a-sentence/][Odorous]]

  =giving off a strong scent=

  - The odorous smell of tobacco filled the crowded room.
  - Asking the clerk for light perfume recommendations, the woman stressed that she didn’t want something too odorous.
  - Odorous flowers filled the garden, attracting both honeybees and hummingbirds.
  - On their first date, the couple made sure to avoid odorous foods like garlic and onions.


* [[https://wordsinasentence.com/odyssey-in-a-sentence/][Odyssey]]

  =a lengthy journey during which many events occur=

  - My twenty-year odyssey in the army allowed me to visit eighteen countries.
  - After enduring a messy divorce, Jill left the country and embarked on an emotional odyssey to rediscover herself.
  - Meditation allowed Mohammed to experience a spiritual odyssey.
  - During the odyssey across the country, the settlers were challenged by a number of trials.


* [[https://wordsinasentence.com/oenophile-in-a-sentence/][Oenophile]]

  =a connoisseur or person who loves wine=

  - Swishing the Pinot Nior around in her mouth, the oenophile savored the taste of the red wine. 
  - Although it was a popular wine, the oenophile was not a fan of Merlot. 
  - With a wine cellar in her home and a wide range of knowledge about various types, her friends considered her an oenophile. 
  - Over the years, the oenophile had gathered quite a collection of wine bottles.


* [[https://wordsinasentence.com/oeuvre-in-a-sentence/][Oeuvre]]

  =the entire collection of work belonging to an artist, writer, or musical composer=

  - The painter’s oeuvre includes over forty paintings and is characterized by the artist’s vivid depiction of nature.
  - Since the memorial concert will feature numerous hits from the singer’s oeuvre, it is going to last for several hours. 
  - The writer’s oeuvre will not be tainted by the inclusion of one poorly written novel.
  - One more sculpture and the museum will house the sculptor’s complete oeuvre. 


* [[https://wordsinasentence.com/off-putting-in-a-sentence/][Off-putting]]

  =unsettlingly unpleasant and repellent=

  - The hateful man’s off-putting attitude left him alone and without anyone to care for him.
  - Finding the attorney’s arrogance off-putting, the potential clients decided on a different firm.
  - Although most of the writer’s points were valid, his unusual style of writing was off-putting.
  - The pushy salesman ran off most of the company’s customers with his off-putting cold calls.


* [[https://wordsinasentence.com/offal-in-a-sentence/][Offal]]

  =the discarded elements of a procedure; in particularly, the leftover animal parts from processed meat=

  - The dog food is made from the offal that remains after the chicken is cut and processed.
  - While there are some people who prefer to eat the choice cuts of meat, I am content with the offal many individuals consider inferior.
  - The chef uses the calf’s internal organs and other parts of offal to make his stew.
  - Gourmet dishes such as sweetbread and foie gras are created from discarded meat parts referred to as offal.


* [[https://wordsinasentence.com/offend-in-a-sentence/][Offend]]

  =to cause another to feel upset or angry=

  - My grandfather never fails to offend someone when bringing up sensitive subjects over dinner.
  - Fearing that she might offend the newly widowed woman, the insurance agent was cautious when discussing her husband’s death.
  - The attorney’s strategy was to mock and offend those he cross-examined so that they would crack under pressure.
  - The comedian’s jokes did not offend all of the audience members, but several stormed out of the show.


* [[https://wordsinasentence.com/offense-in-a-sentence/][Offense]]

  =a violation of a law or rule=

  - Though it was only his first offense, the judge decided to sentence the criminal to a lengthy prison stay.
  - Entering the country without a visa was a federal offense.
  - Although petty theft is not a felony offense, it carries a hefty fine.
  - The man’s third DUI offense landed him in jail for at least a year.


* [[https://wordsinasentence.com/offensive-in-a-sentence/][Offensive]]

  =hateful or hurtful=

  - The offensive letter was given to the principal so he could try to find the writer of the hateful note.
  - Though my sister’s putdowns are offensive, I have figured out how to annoy her hurtful remarks and move on.
  - Even though parts of the President’s speech were offensive, the crowd pretended not to notice the hateful remarks.
  - Hateful and offensive language will not be tolerated in the court room and anyone making these types of statements will be asked to leave.


* [[https://wordsinasentence.com/offhand-in-a-sentence/][Offhand]]

  =impromptu and without previous thought or consideration=

  - He couldn’t recall the specific amount offhand, but the accountant was sure that an unusually large deposit had appeared earlier that day.
  - The trivia queen was able to spout off ridiculous facts offhand.
  - Embarrassed by her sisters’ offhand comments, the woman wished that her siblings weren’t so careless with words.
  - Even seemingly offhand camera shots of the ceremony were more focused than the planned shots.


* [[https://wordsinasentence.com/official-in-a-sentence/][Official]]

  =certified by an authoritative person=

  - With the official document in hand, Patricia would be able to enter the United States since it had been signed by the proper authorities.
  - Even though the young couple got married in a wedding chapel in Las Vegas, they wanted an official ceremony conducted by a minister who graduated from a seminary school.
  - An official call from the school board made it definite that I had a job as a teacher at Breaktown Middle School.
  - Only the official administrator of the city could declare a state of emergency since his job was given the duty to make that decision.


* [[https://wordsinasentence.com/officiate-in-a-sentence/][Officiate]]

  =to be in charge of leading an event or ceremony=

  - The bride’s father was flattered when asked to officiate his daughter’s wedding.
  - Signing up to officiate high school basketball games is a way to earn extra money.
  - Although the pastor never expected payment when he agrees to officiate a wedding, a nice meal is always appreciated.
  - To keep things fair, referees were selected to officiate the pro-bowl based on a lottery system.


* [[https://wordsinasentence.com/officious-in-a-sentence/][Officious]]

  =offensively intrusive or interfering=

  - Because Cory is the boss’s son, he thinks he can stick his officious nose into everybody’s business without fear of consequences.
  - I usually give law officers their due respect, but I just didn’t appreciate that policeman’s officious attitude when he was questioning me.
  - Mary doesn’t like it when officious strangers try to start a conversation in the checkout line.
  - While the officious sales clerk may have believed he was giving me some helpful advice, he was just wasting my time by telling me things I already knew.
  - I stopped enrolling in the continuing education courses because it never failed that someone in the class would monopolize the discussion with officious comments that made me yawn.
  - After several parishioners complained that the pastor’s officious secretary was distributing their confidential prayer requests to others, he told her that she had been breaking a sacred trust.
  - The librarian is an officious old bat who is always trying to tell me what I should or shouldn’t be reading.


* [[https://wordsinasentence.com/offset-in-a-sentence/][Offset]]

  =the distance or amount by which something is out of line=

  - Eying the painting on the wall, the gallery owner pondered whether the crooked frame was offset by a few centimeters.
  - With no way to correct the railing, the homeowner looked for a tape to measure the offset.
  - The man’s account was offset by nearly two million dollars.
  - While attempting to reassemble his project, the amateur builder realized that the wheels were offset by five inches.


* [[https://wordsinasentence.com/offshore-in-a-sentence/][Offshore]]

  =located some distance from the shore=

  - A roaring sound coming from offshore was the first signal of the devastating typhoon.
  - Offshore fishing opportunities offered more variety than simply casting from the bank.
  - Offshore drilling is a prosperous venture, but can have devastating economic effects on the ocean.
  - Ten foot waves and offshore winds combined with warm ocean weather created fabulous surfing conditions.


* [[https://wordsinasentence.com/offspring-in-a-sentence/][Offspring]]

  =the young ones produced by a plant or animal=

  - Scientists are using Punnett squares to predict the physical characteristics of the offspring of two plants. 
  - Because John dearly wanted a son, he was disappointed when his only offspring turned out to be a girl.
  - Most parents hope their offspring will be more successful in life than they are.
  - On average, this breed of dog will give birth to three or four offspring at a time. 


* [[https://wordsinasentence.com/oft-in-a-sentence/][Oft]]

  =occurring often=

  - The oft-quoted poet is famous now but unknown during his lifetime.
  - Oft-times, the couple would opt to stay indoors and play board games rather than enjoy a night on the town.
  - Trading the oft-injured player was the best decision for the struggling team.
  - Although the study is oft-repeated by scientists, no one has been able to definitively link immunizations and autism.


* [[https://wordsinasentence.com/ogle-in-a-sentence/][Ogle]]

  =to look at in a suggestive manner=

  - Because the women feel the construction workers ogle them, they hate to walk by the unfinished building.
  - The football players ogle the cheerleaders when they should be listening to their coach.
  - While the nerdy guys ogle the pretty girls at the party, they are too shy to invite them to dance. 
  - The boys sneaked into their father’s room to ogle his adult magazines.  


* [[https://wordsinasentence.com/ogre-in-a-sentence/][Ogre]]

  =a man-eating giant found in fairytales and legends=

  - The ogre tossed the sailors into the river, devouring the ones he thought would be most tasty.
  - Although most ogres loved to eat humans, Shrek was an oddity as he preferred rats.
  - Hiding in the forest, the giant ogre tried to curb his appetite for human flesh.
  - Long ago, a vicious ogre roamed the Kingdom and devoured the peasants one by one.


* [[https://wordsinasentence.com/ointment-in-a-sentence/][Ointment]]

  =a cream rubbed on the skin for medicinal purposes=

  - Antibiotic ointment was applied to the wound to keep bacteria at bay.
  - The homeopathic physician assured the depressed woman that spreading the ointment allover her body would cure her.
  - The oily ointment was great for the player’s sore knee but ruined his clothing.
  - Squeezing the ointment out of the tube, the boy rubbed the gooey contents onto his scraped knee.


* [[https://wordsinasentence.com/oleaginous-in-a-sentence/][Oleaginous]]

  =oily, greasy=

  - From the excess shine and acne on her face, you can tell Olivia has an oleaginous skin problem.
  - Even when you mix an oleaginous substance and water together they still separate.
  - I had to dab my pizza with a napkin because it is so oleaginous.
  - As an oleaginous land, lots of money was coming in from oil sales.


* [[https://wordsinasentence.com/olfactory-in-a-sentence/][Olfactory]]

  =pertaining to the smell sense=

  - Because my brother has straws in his nose, his olfactory sense is not picking up the odors coming from the kitchen.
  - The hound dog used his olfactory sense to locate the missing girl.
  - Even though Jason is blind, he can easily find the kitchen using his strong olfactory receptors.
  - My cold is interfering with my main olfactory nerve so I cannot smell anything.
  - When most people think of the olfactory organ in humans, they typically think of the nose.
  - The olfactory receptors translate information to the brain so it can recognize the source of the odor. 
  - Because my olfactory stimuli are easily irritated by pollen, I usually sneeze a lot in the spring.


* [[https://wordsinasentence.com/oligarchy-in-a-sentence/][Oligarchy]]

  =a territory or group that is controlled by only a few individuals=

  - In our small religious community, the major decisions of the town are made by the oligarchy, which is composed of six wise men.
  - The food service in the stadium is controlled by an oligarchy of four service providers.
  - While the system of democracy allows everyone to vote, oligarchy gives the power to only a few individuals.
  - The company’s oligarchy, consisting of the president, the vice-president, and the treasurer, makes all the key decisions.
  - After the election, the power once held by the three members of the oligarchy will be given to all citizens in the form of voting rights. 
  - My daughter insists our family is an oligarchy since my husband and I are the only ones who make the important decisions.
  - In the movie, the country was ruled by an oligarchy that was composed of five leaders, one from each of the nation's five factions.  


* [[https://wordsinasentence.com/ombudsman-in-a-sentence/][Ombudsman]]

  =a person who investigates complaints and mediates fair settlements especially between citizens and government officials=

  - Without an ombudsman to help mediate, the mayor’s office and the angered couple were forced to work things out themselves.
  - Once the ombudsman ruled against the government official, the citizens were happy and felt as if justice had been served.
  - The ombudsman recently settled several cases in which he found in favor of the consumer.
  - A long-term care advocate acted as an ombudsman between the patients’ families who claimed the hospital had violated their rights.


* [[https://wordsinasentence.com/omen-in-a-sentence/][Omen]]

  =a sign something is going to occur=

  - Many people view the sighting of a black cat as a bad omen.
  - According to my mother, the itching of your right hand is an omen that predicts a cash windfall. 
  - The fortuneteller told Ellen she saw a dark omen in her future and warned her to be mindful of strangers.
  - When the church burned the night before my wedding, I took it as an omen I needed to delay the ceremony.


* [[https://wordsinasentence.com/ominous-in-a-sentence/][Ominous]]

  =suggesting that something bad is going to happen in the future=

  - Because of the ominous music, we knew something bad was about to happen in the movie.
  - The warning sounds of an ominous storm made us run for cover. 
  - When I heard the front door slam, I took it as an ominous warning that my father was in a bad mood.
  - The broken window was an ominous sign someone had broken into our home.
  - My mother’s ominous tone let me know I was in trouble.
  - In the horror movie, the stupid teenagers ignore the ominous warnings and go inside the mysterious house on the hill. 
  - The dark clouds gave the sky an ominous appearance.


* [[https://wordsinasentence.com/omission-in-a-sentence/][Omission]]

  =something that was not included or present=

  - The omission of my name from the Honor Roll List made me regret the fact I had  played around all semester.
  - Because of the omission of John’s name from the list at the door, he was not allowed inside the club for the  movie’s after party.
  - The manager apologized for any omission he might have made while praising his office staff.
  - Since Jose was such a great soccer player, his omission from the team roster left everyone speechless.


* [[https://wordsinasentence.com/omit-in-a-sentence/][Omit]]

  =to leave out or exclude=

  - Janice was angry because she thought I chose to purposely omit her name from my party list.
  - Since Jill is allergic to tomatoes, she always asks the pizza company to omit the sauce from her pizzas.
  - The low calorie version of the dish requires you to omit the whole milk and use two percent milk instead.
  - Because Kim has a bad reputation, I elected to omit her from my daughter’s sleepover.


* [[https://wordsinasentence.com/omnibus-in-a-sentence/][Omnibus]]

  =a mode of transportation produced to carry a large number of passengers; often referred to as a bus=

  - In our neighborhood, most of the children ride an omnibus to school each day.
  - The omnibus was able to easily transport our large tour group. 
  - When the omnibus broke down on the highway, the passengers spent nearly two hours waiting for another bus. 
  - Each omnibus will carry sixty army recruits to the airport. 


* [[https://wordsinasentence.com/omnifarious-in-a-sentence/][Omnifarious]]

  =assorted; of many varieties and kinds=

  - The busy high schooler has ominfarious interests and does everything from snowboard to mountain climb.
  - Ominfarious fish fill the ocean, with some as big as sharks and others as small as minnows.
  - The witch filled her bowl with ominfarious treats and hoped the assorted candy would attract lots of children.
  - Filled with shelves of omnifarious reading material, the library has every genre of books one could imagine.


* [[https://wordsinasentence.com/omnific-in-a-sentence/][Omnific]]

  =possessing unlimited power to create anything=

  - The sculptor seemed omnific, molding any material into a wonderful masterpiece.
  - Filling the home with his omnific presence, the ghost was able to conjure up any image that could frighten the occupants.
  - Looking out at the glorious fields, the farmer awed at all of the wonders our omnific God was able to create.
  - Cooking dish after dish from scratch, the omnific chef’s apprentice wondered if there was any cuisine he couldn’t create.


* [[https://wordsinasentence.com/omnipotent-in-a-sentence/][Omnipotent]]

  =having virtually unlimited power or influence=

  - My teenager daughter likes to believe she is omnipotent in our household.
  - In some cultures, gods are considered to be omnipotent and all-powerful.
  - The cult leader led his followers to believe he was omnipotent.
  - In the play, the omnipotent narrator knows all of the characters’ thoughts and actions.
  - In our small town, the man who owns the only plant is seen as an omnipotent force in the community.
  - The arrogant doctor believed he was omnipotent and refused to listen to his peers.
  - Because the dictator was omnipotent, he did whatever he wanted without any negative consequences.


* [[https://wordsinasentence.com/omnipresent-in-a-sentence/][Omnipresent]]

  =able to be everywhere at one time=

  - The soccer coach described his star player as being omnipresent, all over the field at once.
  - Because my mother loves carrots, she adds them as an omnipresent ingredient in every dish she makes. 
  - Our omnipresent mayor never misses a chance to get in front of a camera.
  - When I went to college and left my omnipresent parents behind, I really began to enjoy my freedom.


* [[https://wordsinasentence.com/omniscient-in-a-sentence/][Omniscient]]

  =having total knowledge; all-knowing=

  - Melanie felt that it was important to know what every character was thinking, so she wrote her novel from an omniscient point of view.
  - He thinks he knows what is best for everybody, but as far I know he is not omniscient.
  - Without an omniscient narrator, the reader is intentionally left in the dark about the motivation of the antagonist until the very end of the story.
  - If the house had a brain, it would be omniscient because of all the cameras and communication devices in all the rooms.
  - Unless you are omniscient, you can’t possibly predict what type of technology we’ll be relying on in twenty years.
  - She claims to have psychic abilities, but she never said she was omniscient.
  - If world leaders had the capability to be omniscient, there would probably be an end to all war.


* [[https://wordsinasentence.com/omnivorous-in-a-sentence/][Omnivorous]]

  =eating both plants and animals=

  - Because my rabbit only eats plants, it is not omnivorous.
  - Sheila is a strict vegetarian who would never become omnivorous by adding meat to her diet.
  - Although Rick is omnivorous, he does not eat a lot of vegetables.
  - The small animal is omnivorous and feasts upon both nuts and bugs.


* [[https://wordsinasentence.com/omphaloskepsis-in-a-sentence/][Omphaloskepsis]]

  =a reflection process involved in looking at or becoming fascinated with your belly button=

  - As the quiet group of eccentric people stood bent over at the waist, their location for their omphaloskepsis at the public park made passersby stare at them.
  - During the time of my omphaloskepsis, I realized that my navel may have an infection due to its red coloring.
  - Since she consistently practiced omphaloskepsis, the girl’s navel was surrounded with tattoos and a belly ring in order to show her dedication.
  - Due to the man’s love of his midsection, he began to follow omphaloskepsis while praying and meditating.


* [[https://wordsinasentence.com/oncology-in-a-sentence/][Oncology]]

  =the examination and analysis of cancer=

  - After detecting a tumor in the man’s brain, his family physician knew to refer him to a specialist of oncology.
  - Having a certification in oncology allowed the nurse to be able to comment and provide her expertise to cancer patients.
  - When Tiffany’s grandmother died of a malignant tumor, she became inspired to focus her learning on oncology.
  - Sarah’s focus on oncology was caused by the recent diagnosis of leukemia with her young daughter.


* [[https://wordsinasentence.com/onerous-in-a-sentence/][Onerous]]

  =involving great effort and difficulty=

  - Taking care of the puppy is an onerous task.
  - When Jack agreed to help his father cut the grass, he did not realize the chore would be so onerous.
  - The flight attendant was not prepared to deal with the onerous passenger.
  - While the assignment seems simple, in reality, it is quite onerous.
  - Even though the computer will speed up our research efforts, the project will still be onerous. 
  - Despite his rigid training, the athlete was unprepared to handle the onerous terrain.
  - Because of overcrowding, it has become too onerous for the prison guards to keep track of all the convicts.


* [[https://wordsinasentence.com/ongoing-in-a-sentence/][Ongoing]]

  =to continue to happen=

  - Her ongoing nausea started last week and had not stopped, so the woman decided to visit her family doctor.
  - The freelance writer was delighted to hear that her current project would be an ongoing job for the next few months.
  - To sail around the world requires a lot of time and money in order to experience this ongoing trip.
  - Since the copier kept breaking over and over again, this created an ongoing problem for the employees.


* [[https://wordsinasentence.com/onomatopoeia-in-a-sentence/][Onomatopoeia]]

  =a word that has the same sound as its pronunciation=

  - One example of onomatopoeia is the word “buzz”.
  - When asked to point out the onomatopoeia in the sentence describing a bird, I pointed to “chirp”.
  - My class assignment involves writing a poem that contains onomatopoeia, a word that sounds exactly like its pronunciation.
  - Because Catie wanted to draw a picture depicting onomatopoeia, she sketched a picture of a lion roaring.
  - If you include onomatopoeia such as “tweet” in a poem about birds, it will create a distinct impression because it will allow the reader to hear the sound the bird makes.
  - The use of onomatopoeia in a passage will give the section a rhythmic feel because of the tone that is heard when the word is spoken.
  - Since we were supposed to raise our hands when we perceived onomatopoeia, I raised my hand when the cat said “meow” on the audiotape.


* [[https://wordsinasentence.com/onset-in-a-sentence/][Onset]]

  =at the start of something=

  - Arguments plagued the adult children about what to do with the matriarch of the family due to her onset of dementia.
  - When Tyler’s voice cracked for the first time, his mother knew that this was the onset of puberty for her son.
  - Being overweight and continuing to eat fatty foods resulted in Martha’s doctor preparing her for the onset of diabetes.
  - Feeling strong contractions revealed to the pregnant woman that she was in the onset of labor.


* [[https://wordsinasentence.com/onslaught-in-a-sentence/][Onslaught]]

  =a fierce attack=

  - After the apartment fire, there was an onslaught of frustrated people displaced from their homes.
  - After they were told the school was closing, there was an onslaught of angry parents demanding answers.
  - An onslaught of paintball opponents ushered towards me.
  - The adulterer was prepared for an onslaught of negative attention.


* [[https://wordsinasentence.com/ontology-in-a-sentence/][Ontology]]

  =the area of metaphysics that focuses on the characteristics of life=

  - Since Jim has a strong fascination with human existence, he has decided to major in ontology.
  - In ontology class, we are debating the role God plays in the existence of beings. 
  - In our discussion of ontology, we reviewed some of the traits that are indicative of life.
  - Students of ontology sometimes examine items in order to determine if they meet the theories associated with realness.


* [[https://wordsinasentence.com/onus-in-a-sentence/][Onus]]

  =the responsibility for something=

  - It is the onus of the applicant to completely fill out the application materials. 
  - As your mother, it is my onus to prepare you for a successful future. 
  - The onus is on the pharmacist to make sure the medications are properly dispensed. 
  - As a good teacher, I accept the onus for making sure my students learn something each day.
  - The ability to purchase movie tickets online has eliminated the onus of having to stand at the box office window.
  - Before the men became police officers, they had to swear to accept the onus for everyone in their communities.
  - It is the prosecuting attorney’s onus to prove the guilt of the defendant.


* [[https://wordsinasentence.com/onward-in-a-sentence/][Onward]]

  =progressing ahead=

  - “Onward, men we go!” shouted the army sergeant to his troops noticing the enemy in the near distance.
  - After twisting her ankle during the marathon, the runner failed to give up and decided to continue onward toward the finish line.
  - Once the flat tire was fixed on the side of the road, the couple traveled onward toward Disneyworld because nothing would stop them from taking this trip.
  - As the woman proceeded onward to accomplishing her goal of winning a gold medal, this Olympic hopeful practiced day and night.


  - You need to put some oomph into your acting.
  - Use a mild cleanser, but pick something with enough oomph to do the job.
  - Slowly stir a cup of regular yogurt into a soup that lacks oomph—tomato soup especially benefits from this.
  - It's not a bad song, but it needs more oomph.


* [[https://wordsinasentence.com/ooze-in-a-sentence/][Ooze]]

  =to trickle or seep out slowly=

  - Ink seemed to ooze from the pen creating a small blue stain on my brand new pants.
  - If the man stabs the victim, blood will most likely ooze from the wound and down the victim’s body.
  - Slimy substances ooze from the sewer pipe into the yard confirming a leak.
  - The chocolate pudding mixture would ooze from inside of the cupcake when someone would bite into it.


* [[https://wordsinasentence.com/opacity-in-a-sentence/][Opacity]]

  =a blurriness or cloudiness look to something=

  - Due to the opacity of the lenses in my glasses, I could not read the print on the pages of my book.
  - When I was looking down into my dog’s face, I noticed the opacity in my dog’s eyes due to his cataracts.
  - After using the wrong glass cleaner on the window, the opacity on the pane made it look dirty.
  - During the rainstorm, condensation created the opacity on the front windshield making it impossible to drive safely.


* [[https://wordsinasentence.com/opalescent-in-a-sentence/][Opalescent]]

  =multi-colored; rainbowlike=

  - The opalescent star sparkled with all the amazing colors of the rainbow.
  - Peering at the opalescent ring in the case, the young woman liked it because of its multi-colored stones.
  - Topped with an opalescent glass covering, the table sparked with multi-colored shine.
  - The opalescent opal shimmered with a rainbowlike glow that reflected all colors of liht.


* [[https://wordsinasentence.com/opaque-in-a-sentence/][Opaque]]

  =not able to be seen through=

  - Because my privacy is important to me, I have opaque blinds on all my windows. 
  - I cannot see through the glass because it is opaque.
  - As Larry is an experienced liar, his stories are always quite opaque.
  - Continue adding flour to the sauce until it becomes opaque.
  - While the president claims to have an open door policy, his actions are always hid behind an opaque curtain.
  - Jack’s tinted car windows appear opaque to everyone outside the car.
  - I do not like my daughter’s friends because most of them wear pants which are not opaque and are far too revealing.  


* [[https://wordsinasentence.com/open-primary-in-a-sentence/][Open primary]]

  =an election that does not require voters to be a member of a particular political party to take part=

  - Because she is a registered voter, Anna will be able to take part of the open primary next month.
  - Mike is a Republican, his wife is a Democrat, but both are able to vote in the state’s open primary.
  - The politician is campaigning for voters on both left and right to cast a ballot for him in the open primary.
  - Both Missouri and Michigan have an open primary system where voters don’t need to be a member of a certain party to vote.


* [[https://wordsinasentence.com/open-minded-in-a-sentence/][Open-minded]]

  =being willing to accept others’ thoughts and beliefs=

  - Several open-minded people agreed with the farfetched idea that the world is round.
  - In order for the new business venture to work, the couple had to be open-minded since no one believed in their idea.
  - “I will travel around the world,” said the open-minded young woman, “and find work wherever I can.”
  - Using unconventional methods, the teacher needed to have open-minded parents so that her lessons would make her students successful.


* [[https://wordsinasentence.com/openness-in-a-sentence/][Openness]]

  =the act of being exposed=

  - Most people today want an openness in the house so that the living room, dining room and kitchen are unrestricted from each other.
  - While swimming close to the openness in the sea cave, I was worried that the current might suck me in.
  - After installing the skylights, the couple enjoyed the openness of the house to the sky.
  - When I climbed up the tallest tree, I could see the openness of the land below for miles.


* [[https://wordsinasentence.com/opera-in-a-sentence/][Opera]]

  =a theatrical production including loud vocals=

  - When the conductor led the opera, the singers and musicians performed their very best for the audience.
  - In order for the opera to be successful, each singer was donned in elaborate costumes prior to going on stage.
  - The singing from the opera could be heard outside the theater and even down the street.
  - Even though Italians are known for the opera, it was actually a Greek man named Jacopo Peri who is considered to have created the first opera.


* [[https://wordsinasentence.com/operative-in-a-sentence/][Operative]]

  =to become fully functional=

  - You must set up a network name, router, and password for the WiFi to become fully operative.
  - The restaurant was not operative until they passed inspection.
  - The car was not operative until the engine was fixed.
  - A restaurant is only fully operative with a kitchen, cook, and waiters.


* [[https://wordsinasentence.com/operose-in-a-sentence/][Operose]]

  =to be done strenuously and laboriously=

  - Once the spoiled teenager was sent to work in the fields, she learned the responsibility and diligence after the first day of operose work.
  - In order to provide enough food for the family, the poor child had the operose task of cleaning every square inch of a building by herself.
  - The operose climb up the mountain involved hours of drills and strength training prior to the expedition.
  - Even the easiest child birth is an operose medical situation because it is always requires preparation from the mother.


* [[https://wordsinasentence.com/opiate-in-a-sentence/][Opiate]]

  =an opium based medication prescribed as a sleep aid or pain reliever=

  - After Richard was injured in a car accident, he was given an opiate for pain management.
  - Last year, I became addicted to an opiate I used for pain relief. 
  - Janice cannot go to sleep each night without taking an opiate.
  - Rick’s history of drug addiction makes him hesitant to use an opiate for pain relief. 


* [[https://wordsinasentence.com/opine-in-a-sentence/][Opine]]

  =to give an opinion=

  - Rather than disagree with my husband in public, I waited until we got home to opine my thoughts on the subject.
  - Dentists opine flossing is essential for maintaining good dental health.
  - While one referee felt the kick was good, the other referee chose to opine a different outlook on the play.
  - Many religious groups opine cloning is an act that attempts to mimic God’s power.


* [[https://wordsinasentence.com/opinion-in-a-sentence/][Opinion]]

  =a belief or outlook that is often based on feeling and not fact=

  - The preacher stood firm in his opinion and wouldn’t believe anything the scientist said about dinosaurs.
  - In my opinion, children under the age of two should not be allowed to watch television.
  - The husband had no opinion on paint color and preferred his wife take charge of the decisions.
  - Because she was so open-minded, the tolerant woman valued her classmate’s opinion on the matter.


* [[https://wordsinasentence.com/opinionated-in-a-sentence/][Opinionated]]

  =very certain of one’s views or opinions=

  - Because Tessa is so opinionated, she disregards the opinions of other people in favor of her own views.
  - The opinionated man thought he knew more than the doctor and refused to accept the diagnosis.
  - If a team leader is too opinionated, he may alienate his team members by ignoring their viewpoints.
  - The reporter’s opinionated version of the story was completely one-sided.


* [[https://wordsinasentence.com/opponent-in-a-sentence/][Opponent]]

  =a rival or challenger=

  - Bill wondered who his opponent would be in the first round of the karate tournament.
  - With his first punch, Ali knocked out his opponent. 
  - Ted is a skilled chess player so he will be a tough opponent.
  - Because my upcoming opponent has won several championships, I need to make sure I’m ready for tomorrow’s match.


* [[https://wordsinasentence.com/opportune-in-a-sentence/][Opportune]]

  =at a useful or convenient moment=

  - With all of the mobile applications being sold for millions of dollars, now is an opportune time to become a mobile developer.
  - Jessie got a job at the restaurant simply by being there at the opportune moment when the manager fired another server.
  - If someone rings my doorbell at an opportune moment, I can end this bothersome phone call with my mother-in-law. 
  - The teenager knew there would never be an opportune time to tell her parents she was pregnant.


* [[https://wordsinasentence.com/opportunist-in-a-sentence/][Opportunist]]

  =an individual who will take advantage of a circumstance to better his or her situation=

  - The sleazy hotel owner was an opportunist who took advantage of the hurricane to raise his room  rates.
  - Because Henry was an opportunist, he often pretended to be poor to receive free groceries from the county.
  - Any person who steals from the elderly is an opportunist of the worst kind.
  - When the opportunist looked at the houses damaged by the tornado, he saw a quick way to make money by overcharging for building supplies.


* [[https://wordsinasentence.com/opportunistic-in-a-sentence/][Opportunistic]]

  =used to describe someone who take’s advantage of an opportunity or situation for self-gain=

  - The opportunistic couple tried to take advantage of the elderly man, convincing him to sign over his home.
  - Opportunistic catfishes prey on older women who want to be loved.
  - Many of the opportunistic companies preyed on the vulnerabilities of others to sell their products.
  - Divorcing her husband after only a year, the wealthy lady explained that she felt he was opportunistic.


* [[https://wordsinasentence.com/opportunity-cost-in-a-sentence/][Opportunity cost]]

  =a benefit or profit that must be given up in order to gain something else=

  - My mother explained she could not buy two snacks and that popcorn would be our opportunity cost if we chose to get candy.
  - Samantha looks at the money should would save living in a cheaper place as the opportunity cost of owning a nice home.
  - Being able to spend their own earned money is an opportunity cost given up by some housewives.
  - Because the city decided to build a new hospital instead of a park, the planned playground will end up an opportunity cost.


* [[https://wordsinasentence.com/opportunity-in-a-sentence/][Opportunity]]

  =a strong likelihood for development or improvement=

  - Every opportunity was created for the students to succeed by providing tutoring services, peer assistance and parental involvement.
  - Once Kelly graduated from college, she had a better opportunity to secure a high-paying job.
  - When the large paper factory was built in my small town, I knew it would provide me with a job opportunity.
  - Attending the smaller college would provide the athlete with an opportunity to play football during his freshman year.


* [[https://wordsinasentence.com/oppose-in-a-sentence/][Oppose]]

  =to go against something=

  - Due to Sheila’s religious belief that life is precious, she would oppose the death penalty for any crime.
  - Wanting a more serene and natural setting, many neighbors in the area oppose the idea of condominium developments being built on the land.
  - Once the community voiced their anger towards drug dealing in the neighborhoods, they would oppose any suspicious activity by calling the police.
  - In the early 1900s, many women would oppose officials by protesting in the streets for women’s right to vote.


* [[https://wordsinasentence.com/opposite-in-a-sentence/][Opposite]]

  =something that is contrary to something else=

  - When I realized that traveling north on the interstate was wrong, I quickly went in the opposite direction and headed south.
  - It was ironic that I expected my friend to help me in a time of need, but the opposite happened when my enemy showed compassion towards me.
  - Typically, people are attracted to other people who have opposite personalities than their own because they complement each other.
  - Due to her family history, Karen’s counselors advised her to run the opposite way when she is offered drugs or alcohol.


* [[https://wordsinasentence.com/opposition-in-a-sentence/][Opposition]]

  =a challenger or an opposing opinion=

  - The politician’s opposition claims he has a history of sexually harassing women.
  - Because the president wanted his healthcare policy implemented, he ignored the public’s opposition and executed the plan anyway.
  - I expect to hear a great deal of opposition from my father when I tell him about my older boyfriend. 
  - Since the opposition plans to vote down the representative’s budget proposal, it will be a while before the schools receive necessary funding.


* [[https://wordsinasentence.com/oppress-in-a-sentence/][Oppress]]

  =to hold down through use of force or fear=

  - The dictator uses fear to oppress his people.
  - Throughout history, racist groups have tried to oppress minorities by way of force and fear.
  - The bully was able to oppress his victims by threatening them with violence.
  - For centuries, men tried to oppress women by forbidding them to work outside of the home. 


* [[https://wordsinasentence.com/oppressive-in-a-sentence/][Oppressive]]

  =overwhelming; restricting=

  - Because I am very sensitive to the oppressive heat, I tend to spend most of the summer indoors.
  - Many people come to this country because the oppressive leaders in their native lands took away their freedoms.
  - While John views himself as a spiritual individual, he believes the rules of any organized religion are too oppressive for his relaxed nature.
  - Plans have been made to overthrow the oppressive government.
  - When the oppressive dictator died, millions of people celebrated his death. 
  - The citizens unanimously voted to overturn the oppressive laws that had once controlled their lives. 
  - Last summer, thousands of people died from strokes relating to the oppressive temperature.


* [[https://wordsinasentence.com/oppressor-in-a-sentence/][Oppressor]]

  =one who dominates someone by hard work or slavery=

  - Under the communist government, many citizens felt the suffering and persecution at the hands of the oppressor.
  - In the early 20th century, many young children worked dangerous jobs usually supervised by an oppressor who only cared about making money.
  - My mother became a ruthless oppressor when she forced us to work all day cleaning the house, barn, and fields only to have to start the process over again tomorrow.
  - Many slaves were owned by an oppressor who abused them and made them tend the fields day and night.


* [[https://wordsinasentence.com/opprobrious-in-a-sentence/][Opprobrious]]

  =conveying shame or contempt=

  - Elaine was offended by her friends’ opprobrious remarks about her drunken behavior.
  - At the party, a suspicious Kim was convinced her friends were making opprobrious comments about her appearance.
  - The boy is sure to be kicked out of school for directing opprobrious remarks to his principal.
  - Did you see the teacher’s shocked expression when the student called her an opprobrious word?


* [[https://wordsinasentence.com/opprobrium-in-a-sentence/][Opprobrium]]

  =the disgrace incurred by conduct considered outrageously shameful=

  - Ben’s criminal opprobrium nearly cost him the election.
  - While my actions were inappropriate, I do not consider them an opprobrium which will ruin my reputation. 
  - The celebrity chef earned opprobrium when she made a racial slur in front of the media.
  - For the rest of his life, the president will be remembered for his opprobrium brought on by entering our country into an international war.
  - Because the athlete used steroids to increase his performance, he had to face the opprobrium of the sports committee.
  - The government is willing to ignore public opprobrium and build the highway through the city park.
  - After the singer was arrested, he went into seclusion and hoped the opprobrium would soon be forgotten.


* [[https://wordsinasentence.com/oppugn-in-a-sentence/][Oppugn]]

  =to doubt the authenticity of something=

  - During a presidential election, many politicians oppugn the ideas of the opposing party by providing proof of their wrongdoings.
  - Historians often present evidence of the existence of the Holocaust where many skeptics oppugn the likelihood of this historical event.
  - After scientists oppugn the conclusions of the study on birds, the chief researcher showed these doubters his footage from the study.
  - At the garage sale I would oppugn the designer purses as knock-offs since they were being sold so cheaply.


* [[https://wordsinasentence.com/opt-in-a-sentence/][Opt]]

  =to make a selection=

  - After receiving many worthless advertisements in her email, Cynthia decided to opt out of receiving any emails from unknown senders.
  - When the robbery occurred, the homeowners realized they would opt to reestablish connection with their expired home security system.
  - Between taking a vacation or getting braces for our younger daughter, we opt for the braces because that seems to take priority over the vacation.
  - The house seemed to have more room, but I would opt for the apartment due to the abundance of amenities it offers.


* [[https://wordsinasentence.com/optic-in-a-sentence/][Optic]]

  =pertaining to the eye=

  - Incessant exposure to bright light created optic damage to the patient resulting in being visually impaired.
  - Once the optic nerve was severed during the surgery, the surgeon knew the patient would receive the vision without allowing an impulse to the brain.
  - Dr. Kane was pelted with a barrage of optic questions after the students watched a documentary about visual diseases.
  - Sunglasses allowed people to protect their optic senses by limiting the force of the brightness into their pupil.


* [[https://wordsinasentence.com/optimism-in-a-sentence/][Optimism]]

  =hopefulness about things to come=

  - Gail’s optimism allows her to believe anything is possible.
  - Although I hate my coworkers, I try to get along with them because my optimism reminds me my job is only temporary. 
  - Jake’s optimism decreased when his boss told him his services were no longer needed.
  - If a person does not have optimism, he or she will not look forward to the future.


* [[https://wordsinasentence.com/optimist-in-a-sentence/][Optimist]]

  =one who always has a positive outlook=

  - As an optimist, I always believe tomorrow will be better than today.
  - My sister is not an optimist because she always expects the worst case scenario.
  - Because Jane is an optimist, she is certain all people are good at heart. 
  - While my son is a pessimist who condemns everything, my daughter is an optimist who sees a rainbow after every storm.


* [[https://wordsinasentence.com/optimistic-in-a-sentence/][Optimistic]]

  =hopeful about the future or a specific outcome=

  - Though we haven’t won a game all year, our team is still optimistic that today we will win.
  - Jenny is optimistic and hopes for the best even when things look bleak.
  - Optimistic and hopeful, the couple set out on a hunt to find their dream home.
  - Aaron’s optimistic attitude helps him stay positive when he’s having a tough time at school.


* [[https://wordsinasentence.com/optimum-in-a-sentence/][Optimum]]

  =the best condition=

  - For my financial circumstances, the optimum loan would need to have an interest rate below  four percent.
  - My doctor says the optimum weight for a woman of my height is one hundred and fifty-five pounds.
  - During the hot summer months, the optimum temperature inside our home is around seventy-five degrees.
  - It takes Jared an hour to drive to work even in optimum traffic conditions.


* [[https://wordsinasentence.com/optometrist-in-a-sentence/][Optometrist]]

  =a doctor whose medical practice revolves around detecting and correcting vision problems=

  - Visiting the optometrist to have his eyes checked was quite an achievement for the overly nervous patient.
  - Although initially the optometrist found nothing wrong with the woman’s vision, he now saw an astigmatism.
  - Concerned about the diagnosis she received from the optometrist, the cautious patient decided to get a follow-up eye exam.
  - The man’s children urged him to see an optometrist since he could barely see a few feet in front of him.


* [[https://wordsinasentence.com/opulent-in-a-sentence/][Opulent]]

  =extravagant and rich=

  - Because the movie star made over ten million dollars a film, she was able to maintain an opulent lifestyle.
  - We were afraid to sit in the chairs because they looked so opulent.
  - Although the hotel was filled with opulent designer furnishings, its room rates were surprisingly affordable.
  - The couple spent over eighty thousand dollars on opulent kitchen appliances.
  - Even though the evil king knew many of his people were dying of starvation, he continued to spend money decorating his opulent castle. 
  - The hotel’s opulent facilities include four gourmet restaurants, a movie theater, and an indoor tennis court.
  - If Jackie does not get a large divorce settlement, she will not be able to maintain her opulent style of living.


* [[https://wordsinasentence.com/opus-in-a-sentence/][Opus]]

  =a significant work from an artist, writer, or other creative individual=

  - The songwriter worked day and night on the opus he prayed would make him famous. 
  - When the author released his last novel, reviewers described it as his opus and labeled it his best work.
  - Henry was emotionally destroyed when the play he felt was his opus was ripped to shreds by critics. 
  - Although the singer died over thirty years ago, his opus remains near the top of the music charts. 


* [[https://wordsinasentence.com/opuscule-in-a-sentence/][Opuscule]]

  =an insignificant literary, art, or musical work=

  - Although Shakespeare had many famous plays, the opuscule one performed by the cast was a little-known.
  - The opuscule was a work of art is traditionally considered insignificant by critics.
  - Performing the opuscule in front of a large crowd, the successful pianist hoped to gain more recognition for her unknown compositions.
  - Hoping that it would be his literary masterpiece, the author was disappointed that critics referred to the novel as an opuscule.


* [[https://wordsinasentence.com/oracle-in-a-sentence/][Oracle]]

  =an individual with great intelligence or a person who speaks for a deity=

  - The computer genius is viewed as the oracle of technology who changed the world.
  - In ancient times, one would give the oracle a gift in exchange for her predictions.
  - The highly-regarded professor is an oracle who enlightens students on the subject of philosophy.
  - When the oracle touched my hand, she gasped and told me I didn't want to know my future. 


* [[https://wordsinasentence.com/oracular-in-a-sentence/][Oracular]]

  =prophetic; predictive=

  - Oracular predictions proved to be true as the medium knew that Donald Trump would be elected president.
  - Gazing into her crystal ball, the clairvoyant uttered an oracular tale of what the woman’s life would be like.
  - The soothsayer’s oracular responses were trusted by the tribe since most of his prophecies had at least a hint of truth.
  - Pretending to offer oracular readings, the sham psychic lined her pockets with money from the gullible.


* [[https://wordsinasentence.com/oration-in-a-sentence/][Oration]]

  =a ceremonial speech that is formal=

  - Although the pope’s oration lasted for only fifteen minutes, it left many in the audience in tears.  
  - The bishop gave an oration about responsibilities before crowning the prince.
  - After the president takes his oath of office, he gives an oration outlining his hopes for the country.
  - The serial killer said he did not want to receive an oration from a priest before his execution.


* [[https://wordsinasentence.com/orator-in-a-sentence/][Orator]]

  =one who excels at speaking to an audience=

  - Thad is a much-liked orator who keeps people fully engaged while he is speaking.
  - If you want to be a successful politician, you should strive to become a great orator so you can win votes with your words.
  - I left the room as soon as the racist orator started to spread his message of hate.
  - Because Heather is a gifted orator, she is often called upon to host events.
  - Katie was looking forward to hearing the guest orator speak in her economics class.
  - Because Rick is an excellent orator who can sway people with his speech, he is an amazing lawyer. 
  - I realized Angie was a wonderful orator when I heard her deliver an amazing spoken word poem. 


* [[https://wordsinasentence.com/orchard-in-a-sentence/][Orchard]]

  =acreage where fruit trees are produced=

  - Apparently, the Apple Tree Restaurant acquired its apples for its dishes from the orchard that lined the road next to the restaurant.
  - The fruit stand located on the side of the road sold only produce picked from a local farmer’s orchard.
  - While driving to the apple juice factory, we passed by a large orchard with lines of trees growing in row after row.
  - Many migrant workers were hired for the spring season to pick the apricots in the orchard.


* [[https://wordsinasentence.com/orchestra-in-a-sentence/][Orchestra]]

  =a group of people who play musical instruments together=

  - The trumpet could be heard over all of the other instruments in the orchestra.  
  - Classical tunes played by the orchestra echoed throughout the auditorium.
  - Before they began playing music, the different instruments of the orchestra had to be arranged in sections.
  - Playing in a small band was a start, but the musician hoped to one day play with a great orchestra.


* [[https://wordsinasentence.com/orchestrate-in-a-sentence/][Orchestrate]]

  =to organize or plan all of the details of an event=

  - Cautious FBI agents were able to orchestrate the sting without setting off any red flags.
  - It seemed unlikely that the terrorist was able to orchestrate such a large-scale crime alone.
  - To take responsibility away from the bride and groom, an event planner was hired to orchestrate the wedding.
  - Being able to orchestrate such a wide scale production took a great deal of planning and a large support staff.


* [[https://wordsinasentence.com/ordain-in-a-sentence/][Ordain]]

  =to deliver a decree or confirm a person into a religious ministry=

  - If the church decides to ordain the convicted rapist as a deacon, many people will leave the congregation.
  - John knows the ministry will never ordain him as a priest because of his checkered past.
  - What made the fashion gods ordain floral prints as the must-have style of the year?
  - For the first time, our conservative church elders will ordain a woman as a minister.


* [[https://wordsinasentence.com/ordeal-in-a-sentence/][Ordeal]]

  =a tough experience=

  - The eighteen-hour plane trip was an ordeal for my hyperactive toddler.
  - Even the experienced wedding planner found it quite an ordeal to plan and execute a ceremony in twenty-four hours.
  - The hostage endured a horrible ordeal under the hands of his abusive kidnappers. 
  - For my teenage daughter going without her mobile phone for a day is a real ordeal.


* [[https://wordsinasentence.com/orderly-in-a-sentence/][Orderly]]

  =having a neat and organized system=

  - Orderly gardens surrounded by fences were lined in meticulous rows.
  - Santa’s tidy elves arranged mounds of gift in an orderly manner.
  - His usually orderly workspace was now disheveled stacks of papers.
  - Due to the systematic and orderly investigation, DNA evidence was able to be preserved at the crime scene.


* [[https://wordsinasentence.com/ordinance-in-a-sentence/][Ordinance]]

  =legislation or a decree=

  - The county ordinance prohibits smoking inside public establishments.
  - When the ordinance is passed, people will be fined for not keeping their front lawns neatly cut.
  - The ordinance abolished slavery in all villages ruled by the king.
  - When our city council passed an ordinance prohibiting Sunday alcohol sales, many citizens were upset about the restriction.


* [[https://wordsinasentence.com/ordinarily-in-a-sentence/][Ordinarily]]

  =usually, normally, or routinely=

  - Ordinarily I wouldn’t bother going outside before noon, but it’s snowing and I would like to play in it before it all melts.
  - Ordinarily my brother and I get on each other’s nerves, but since today is our mom’s birthday, we worked together to make it special for her.
  - Even though I would ordinarily wake up at eight, I was feeling sick and I stayed in bed for another two hours.
  - I ordinarily only work on weekdays, but my boss needed me to fill in for someone on Saturday this week, so I had to beak the norm.


* [[https://wordsinasentence.com/ordinary-in-a-sentence/][Ordinary]]

  =normal; average=

  - Although it seemed extreme to others, working a 16 hour shift was part of the officer’s ordinary day.
  - Even ordinary workers were expected to come to work dressed in formal business attire.
  - In her latest novel, the author’s main focus was instances when ordinary citizens did heroic things.
  - Painting the ordinary wall a brighter color helped to brighten up the office space.


* [[https://wordsinasentence.com/ore-in-a-sentence/][Ore]]

  =element that naturally yields a metal=

  - After stumbling upon an abandoned mine, the experienced miner realized that ore could still be extracted here to produce iron.
  - Copper ore was frequently mined in this country due to its excessive exports of copper.
  - Using many tools, the miners traveled to the mine to unearth the minerals from the ore.
  - As the child looked at the copper in the quarry shop, the parent explained how the copper was separated from the ore in the mine.


* [[https://wordsinasentence.com/organelle-in-a-sentence/][Organelle]]

  =a specialized part of a cell=

  - An organelle is a structure inside of a living cell that has a specific role.  
  - Because the mitochondrion is the organelle that supplies energy to the cell, it’s often referred to as a power house.
  - Photosynthesis takes place inside of the chloroplast, an organelle that is only found in plant cells.
  - When foreign particles enter cells, an organelle called a lysosome uses digestive enzymes to eliminate the unwanted materials.


* [[https://wordsinasentence.com/organic-in-a-sentence/][Organic]]

  =originating from living material=

  - The bakery features Italian baked goods made from purely organic, sustainable ingredients.
  - The farm’s organic eggs were produced by cage-free poultry that were fed without unnatural ingredients.
  - Currents picked up many types of organic material as it flowed through the riverbed.
  - Passing out samples, marketers tried to convince customers that their organic fruit was much healthier than processed produce.


* [[https://wordsinasentence.com/organism-in-a-sentence/][Organism]]

  =a distinct living creature=

  - The fish is an organism that must remain in water in order to live.
  - Because the lion is a dangerous organism, it should be avoided at all times. 
  - The bat is a nocturnal organism that sleeps during the daylight hours.
  - In the food chain of life, each organism is linked to another organism.


* [[https://wordsinasentence.com/organization-in-a-sentence/][Organization]]

  =a group of individuals who come formally come together for a specific cause or purpose=

  - An emergency aid organization stepped in to provide medical care, shelter, and food supplies to Japan after a tsunami devastated the coast. 
  - The charity organization was composed of over a hundred church-going ladies who knit hats for cancer patients.
  - The military aid organization sent care packages to soldiers overseas that were filled with personalized snacks and letters from loved ones.
  - The crime organization was built by a local group of gang leaders who used weekly meetings to discuss which gangs would sell drugs, weapons, and stolen merchandise.


* [[https://wordsinasentence.com/orgastic-in-a-sentence/][Orgastic]]

  =having a great pleasure of emotion=

  - With orgastic shock, I realized that I had just won the lottery and started to jump up and down for joy.
  - Based on her orgastic feelings, the young girl told everyone that she was dating the most popular boy at school.
  - The orgastic man was jumping up and down when he received his prized possession back from the robbers who stole it.
  - Due to the orgastic sound of joy coming from the woman, everyone in the family realized that the happy woman just found out that she is pregnant.


* [[https://wordsinasentence.com/orgulous-in-a-sentence/][Orgulous]]

  =proud and arrogant=

  - At the company party, the snobbish analyst and her orgulous husband constantly bragged about their wealth. 
  - Obsessed with his luxury cars and expensive watches, the orgulous man was arrogant when it came to his possessions.
  - The orgulous athlete came across as self-centered in most of his interviews.
  - The scientist, being proud and orgulous, wouldn’t dare admit that he might have made a mistake during research.


* [[https://wordsinasentence.com/orient-in-a-sentence/][Orient]]

  =to push in the direction of a goal=

  - During the staff meeting supervisors will orient team members to their monthly objectives.
  - The merger will not be successful if the two firms can’t orient to the goals of one company.
  - Since the elderly doctor refuses to embrace technology, it is impossible to orient him to new surgical procedures.
  - The counselor will help you orient so you can fulfill the necessary graduation requirements.


* [[https://wordsinasentence.com/orientation-in-a-sentence/][Orientation]]

  =the process of becoming familiar or acquainted with people or things=

  - In order for the new employees to understand the functions and interactions of the different departments at the company is by conducting a job orientation at the beginning of their employment.
  - College orientation is a requirement for freshmen students to attend to get acclimated to the college life and education.
  - With the orientation to a new city, I was then able to eventually find my way around the city without using my GPS.
  - “The orientation of a new language can only lead to fluency,” said the foreign exchange student, “by fully interacting with people on a daily basis who speak this language.”


* [[https://wordsinasentence.com/orifice-in-a-sentence/][Orifice]]

  =an opening or cavity through which things move=

  - Your mouth is an orifice through which food and beverages travel into your body. 
  - Because my son is an infant, his temperature is taken through his anal orifice. 
  - The odor coming from my brother’s rear orifice smells like rotten eggs.
  - During intercourse, a man inserts his penis inside of the woman’s vaginal orifice.


* [[https://wordsinasentence.com/origin-in-a-sentence/][Origin]]

  =the place or situation from which a person or thing came forth=

  - My last name is Scottish in origin because both of my parents are of Scottish descent.
  - Since Jill’s mother is French and her father is Swiss, her ethnic origin is a mix of both backgrounds.
  - You can define the word by tracing its origin back to the Greek language.
  - Because the doctor believed the patient’s issues were mostly psychological in origin, he referred her to a psychiatrist.


* [[https://wordsinasentence.com/original-in-a-sentence/][Original]]

  =the first or earliest example of something=

  - The original Van Gogh fainting sold for several million dollars while a copy costs on a few bucks.
  - My grandmother’s original apple pie recipe is the one that all of my baking is based on.
  - Without the original contract, there is no way to prove how much money was promised in the beginning.
  - The original version of the watch sold for a lot less than the newer type of wristwear.


* [[https://wordsinasentence.com/originality-in-a-sentence/][Originality]]

  =the uniqueness or being first for something=

  - Due to the originality of the chef’s creations, the judges had never tasted anything like this dish before.
  - When the scientist decided to research about the new problem, the originality of the topic meant that there was no other research about it.
  - People gawked and laughed at Alexander Graham Bell’s telephone because the originality of this invention seemed so far-fetched.
  - Ms. Thomas would grade our essays on originality so she didn’t want us to write something that she had seen before.


* [[https://wordsinasentence.com/originate-in-a-sentence/][Originate]]

  =to occur or begin=

  - Did Gina originate the rumor after Kate kissed her boyfriend?
  - The sounds appear to originate from my noisy neighbor’s house.
  - According to the author, his stories originate from his childhood memories.
  - The outgoing celebrity is always the first to originate a fashion trend.


* [[https://wordsinasentence.com/orison-in-a-sentence/][Orison]]

  =a devotion or request to a god=

  - When the devastating earthquake took place, the first responder on the scene whispered a quick orison in hopes of finding people alive.
  - Every night Carol’s daughter would recite an orison to make her very sick mother well.
  - Clasping his hands together with his eyes closed, the man would bow his head and utter an orison to his god.
  - In ancient times during war, devout followers would recite an orison throughout the day in order for their god to allow them to claim victory against their enemy.


* [[https://wordsinasentence.com/ornament-in-a-sentence/][Ornament]]

  =a decoration added onto something else to make it more beautiful=

  - The 3-year-old child hung the blue sparkling globe on the Christmas tree because it was his favorite ornament.
  - Sarah wanted to create a more seasonal look to her house, so she hung an ornament in every space of her house commemorating the holiday.
  - Once the ornament was added to the center of the table, everyone began commenting on her original and colorful centerpiece.
  - The child spent hours decorating his ornament with glitter, stickers, and paint to put on the top of the tree.


* [[https://wordsinasentence.com/ornate-in-a-sentence/][Ornate]]

  =extravagantly adorned or worded=

  - The uneducated man could not understand the ornate speech made by the Ivy League professor. 
  - Because the wedding dress is ornate with pearls and diamonds, it is valued at nearly half a million dollars.
  - Every bedroom in the billionaire’s mansion is ornate with luxurious furnishings and classical works of art.
  - Since the engagement party is supposed to be a simple outdoor barbecue, we ask people to avoid dressing in an ornate manner. 


* [[https://wordsinasentence.com/ornery-in-a-sentence/][Ornery]]

  =crotchety, rude, or mean=

  - The ornery old man is always treating everyone around him very rudely, which is probably why nobody likes him.
  - I can be very ornery if I don’t get my coffee in the morning, being mean to everyone that tries to bother me.
  - If there is one thing that will make my mother very ornery, it is my father leaving the toilet seat up, which makes her yell a lot.
  - An ornery person usually treats everyone around them poorly, either being mean or just cold in general.


* [[https://wordsinasentence.com/orotund-in-a-sentence/][Orotund]]

  =haughty in tone or style=

  - The millionaire’s orotund manner made him come across as arrogant. 
  - When the president visits with the automotive workers, he tries to be one of the guys by avoiding the use of orotund dialogue. 
  - The blogger does not write in an orotund style because he wants his articles to appeal to the general public.
  - Because the politician made an orotund speech about his wealthy upbringing, he lost favor with the middle class voters. 


* [[https://wordsinasentence.com/orphanage-in-a-sentence/][Orphanage]]

  =a public institution for the care and protection of orphans=

  - Since their parents died in a plane crash, Paul and Kevin would go to an orphanage since no relatives would let them live in their houses.
  - Ms. Peterson was aware that her student lived in a group home instead of an orphanage because his parents still had limited supervision to see him.
  - After shutting down the abusive orphanage, many of the kids went to live in foster care dispersed throughout the state.
  - Missouri’s state orphanage was already busting at the seams with over 200 children in their small facility when 50 more children would be placed there.


* [[https://wordsinasentence.com/orthodontist-in-a-sentence/][Orthodontist]]

  =a doctor specializing in dental work for avoiding or improving uneven teeth=

  - An orthodontist required my daughter to get braces for two years since her front teeth were not in alignment with the other teeth.
  - My dentist required me to consult an orthodontist when one of my adult teeth was coming in crooked.
  - “I have never seen an orthodontist in my life,” bragged the teenager, “because all of my teeth are perfect and straight.”
  - The middle-aged woman got a second opinion from another orthodontist when her treatment required a full set of braces.


* [[https://wordsinasentence.com/orthodox-in-a-sentence/][Orthodox]]

  =common; familiar=

  - The minister called me an upstart when I dared to question his orthodox views. 
  - During the orthodox sex education class, the teacher repeated the same lecture she had been repeating for ten years.
  - The tenured economic professors who had taught their orthodox ideas for years did not appreciate questions from the newly hired professor. 
  - While my brother is quite adventurous and likes to try new things, I hate change and prefer to maintain an orthodox lifestyle. 


* [[https://wordsinasentence.com/orthography-in-a-sentence/][Orthography]]

  =the aspect of language that is associated with spelling=

  - While the punctuation in the paper was fine, the writing contained many misspellings that revealed a weakness in orthography.
  - We hired a tutor to work with Ben on his spelling so he would not earn a poor grade in orthography.
  - Because the principal is a whiz in orthography, she is the ideal person to manage the spelling competition.
  - English orthography makes use of twenty-six letters to spell vocabulary.


* [[https://wordsinasentence.com/orthopedic-in-a-sentence/][Orthopedic]]

  =abnormalities relating to the bones or skeleton of a human=

  - Following the car crash, his orthopedic injury would require setting the broken bone of his leg back into place.
  - The orthopedic surgeon opted to x-ray the man’s lower back to determine if he had a herniated disc in his spine.
  - To correct the pain in your feet, wearing orthopedic shoes will align the bones in your feet and legs.
  - Consulting an orthopedic doctor proved necessary when sharp pains in my spine consistently got worse.


* [[https://wordsinasentence.com/oscillate-in-a-sentence/][Oscillate]]

  =to swing back and forth=

  - Though you cannot see it, sound waves constantly oscillate as they travel through the air.
  - The pendulum oscillated side to side, making it difficult for the man to focus on anything but the clock.
  - To aide with his hypnosis, the hypnotists oscillated a pocket watch in front of his patient.
  - As a demonstration, the science teacher placed a string on top of a speaker so his students could watch it oscillate.
  - As a politician, it is expected that he will sometimes oscillate on his policy, changing his stance as new evidence is presented.
  - Watching the readings from the earthquake, the scientist could easily see the intensity oscillate.
  - The musician watched the metronome oscillate back and forth, using it to keep himself from playing too quickly.


* [[https://wordsinasentence.com/osculate-in-a-sentence/][Osculate]]

  =to caress with one's lips or kiss=

  - As a teen, I don’t enjoy seeing my parents osculate each other because their smooching is gross.
  - Mara hopes working in the kissing booth will afford her the chance to osculate her dream guy.
  - While dogs don’t osculate people with their lips, they do lick to show affection.
  - My grandmother can’t osculate me without leaving a bunch of spit on my cheek.


* [[https://wordsinasentence.com/osmosis-in-a-sentence/][Osmosis]]

  =the capability to comprehend things without exertion=

  - Because Gail never studies but always does well on exams, she must learn through osmosis.
  - It seems as though Helen absorbs information through osmosis because she understands everything after hearing it only once. 
  - Since Matt has never taken piano lessons but plays like a professional pianist, everyone assumes he acquired the skill through osmosis. 
  - Ann must have gained her knowledge by way of osmosis because she skipped school almost every day.


* [[https://wordsinasentence.com/ossify-in-a-sentence/][Ossify]]

  =to become firm in a certain way=

  - My father’s opinion has started to ossify so I know he won’t change his mind.
  - Because Elaine has an impulsive nature, she’ll never allow her behaviors to ossify. 
  - This type of arthritis causes the joints to ossify to the point they become immobile. 
  - After Tim joined the church, his beliefs about the afterlife started to ossify.


* [[https://wordsinasentence.com/ostensible-in-a-sentence/][Ostensible]]

  =appearing as such but not necessarily so=

  - Your ostensible prank has done a lot of damage, and now you must face the consequences of your actions.
  - While Jerry is the ostensible author of this amendment, there is some question of who actually deserves credit for the idea.
  - While the ostensible destination of our trip sounded appealing, I was dreading the long drive it would take to get there.
  - In this neighborhood, George is the ostensible authority on native plants for landscaping.
  - The ostensible cause of the breakdown seems to be that someone has tampered with the gas tank.
  - As the ostensible Alpha male, Sandulf led the pack through the mountains in search of food and water.
  - Gary’s ostensible purpose for calling his mother was to see how she was doing, but she soon figured out that he needed money again.


* [[https://wordsinasentence.com/ostensibly-in-a-sentence/][Ostensibly]]

  =to all outward appearances=

  - Although Clyde had plans to spend the day with his mistress, ostensibly he appeared to be getting ready for work by packing his brief case. 
  - Ostensibly, the celebrity seemed to be hiding from photographers by wearing a disguise.
  - Other nations were suspicious when our government sent troops into the war-torn country, ostensibly to help restore peace. 
  - Ostensibly, the surveillance cameras have been installed for our protection, but we believe management uses them to monitor our daily activities.
  - Dressed as a homeless man, the billionaire, ostensibly, appeared to be a beggar in need. 
  - Ostensibly, the free meal coupon seems like a great deal, but when the service charges are added, the meal is no longer free.
  - Although Janice went to church ostensibly to worship, she actually attended service each week to search for a husband.  


* [[https://wordsinasentence.com/ostentatious-in-a-sentence/][Ostentatious]]

  =intended to attract notice and impress others in an extreme and unnecessary way=

  - I tried to tell Mary her fur coat was a bit too ostentatious to be worn at a funeral!  
  - Even though Larry has a gigantic art collection, he does not present it in an ostentatious manner to everyone who enters his home.
  - My wealthy aunt who enjoys flaunting her wealth always wears an ostentatious diamond necklace.
  - Although Henry was a millionaire, no one ever considered him ostentatious because of the laid-back way in which he carried himself.
  - Everyone could tell the singer was a diva simply by looking at her brightly-colored ostentatious outfit.
  - Because Sarah puts up at least two thousand Christmas lights each year, she always has the most ostentatious decorations in our neighborhood.
  - The little girl’s birthday party was an ostentatious affair with live ponies, a chocolate fountain, and a six-tier cake.


* [[https://wordsinasentence.com/osteoporosis-in-a-sentence/][Osteoporosis]]

  =bone disease=

  - Bob was diagnosed with osteoporosis because his leg bones were brittle and weak.
  - Many people don’t realize men get osteoporosis also, but it's usually called “low bone density” for them.
  - Increasing your calcium consumption will keep your teeth and bones strong and decrease your risk for developing osteoporosis.
  - A good way to ward off osteoporosis is to teach young women to work plenty of dairy products into their diet.


* [[https://wordsinasentence.com/ostracize-in-a-sentence/][Ostracize]]

  =exclude someone=

  - As a teacher, your job is not to ostracize your students but to show them support so they can become contributing members of society.
  - Sadly, the rich children ostracize the other girl because she comes from a poor family.  
  - Although Margie was not responsible for the court’s decision in her favor, she knows the people on the other side of the courtroom will still ostracize her. 
  - Can you believe that country still has laws, which allow it to ostracize people of the Christian faith and treat them like second-class citizens?
  - In some countries, having different beliefs may cause people to ostracize you and deny you access to certain places. 
  - Bill knew his community would ostracize him after his release from prison so he moved to another town. 
  - Unfortunately, teenagers will ostracize their peers and make them feel unwanted for the simplest reasons. 


* [[https://wordsinasentence.com/otiose-in-a-sentence/][Otiose]]

  =not useful=

  - Attempting to get Beth to change her mind is otiose because she is totally inflexible.
  - It’s otiose to spend so much on catering when few people have responded to the invitation.
  - While reading Hank’s column, the editor deleted the second paragraph because he found it otiose and unnecessary.
  - It is otiose to put a tiny bandage on a wide open wound.


* [[https://wordsinasentence.com/ouch-in-a-sentence/][Ouch]]

  =an exclamation of hurt or pain=

  - She yelled, “Ouch!” as she tumbled down the stairs breaking her arm.
  - Ouch,” the toddler cried when she skinned her knees falling down on the concrete driveway.
  - The pain in the woman’s side worsened so she yelped, “Ouch,” as she clasped her stomach.
  - While putting on mascara, the brush accidentally fell into my eye causing me to yell, “Ouch!”


* [[https://wordsinasentence.com/ought-in-a-sentence/][Ought]]

  =must or should=

  - After being insulted for the tenth time that day, the store clerk thought there ought to be a law against rudeness.
  - After studying the terms for biology class every day, the class ought to make a good grade on the quiz.
  - When I read the training manual cover to cover with the material I had already experienced, I ought to know how to do the job.
  - Since the woman sang the national anthem many times, she ought to know the lyrics by heart.


* [[https://wordsinasentence.com/ourselves-in-a-sentence/][Ourselves]]

  =myself and at least one other person together=

  - We would walk to school by ourselves because our parents had to go to work early that morning.
  - If Sarah gets sick one more time, Pete and I will have to pay the doctor bill ourselves since my aunt has stopped paying our bills.
  - Since we are a stingy couple, the only people who will benefit from the lottery we won is ourselves.
  - As the CEO of the company, I was only thinking of ourselves when our factory polluted the local rivers.


* [[https://wordsinasentence.com/oust-in-a-sentence/][Oust]]

  =to banish or kick out=

  - Environmental specialists would prefer to oust herbicides because they can cause health problems and diseases to many people.
  - Many citizens of Germany wanted to oust Adolf Hitler but were too scared to do anything about it.
  - Board members realized that they would have to have at least a 2/3 vote to oust the horrible president.
  - Since the CEO was the top man at the company, it would be almost impossible for anyone to oust him.


* [[https://wordsinasentence.com/out-of-the-blue-in-a-sentence/][Out of the Blue]]

  =without warning=

  - I was driving along the road at night when a deer jumped out at me out of the blue, wrecking the front of my car.
  - My girlfriend and I were having a nice date, but I must have said something to make her mad because she was soon yelling at me out of the blue.
  - It looked like it was going to be sunny all day, yet the moment I stepped outside it started raining out of the blue.
  - Hiccups are notorious for their ability to come completely out of the blue yet disappearing just as suddenly.


* [[https://wordsinasentence.com/outbreak-in-a-sentence/][Outbreak]]

  =a quick increase in an action or number of something=

  - After having chicken pox as a child, I am susceptible to getting an outbreak of shingles since the virus is already in my system.
  - Even though the school did not want to scare any parents, they did warn them that an outbreak of lice has occurred at the school.
  - Once a few cases of Ebola were detected, the news media warned its viewers of the outbreak of this highly dangerous disease.
  - Since the country bombed their enemy in a surprising fashion, this caused an outbreak of war lasting a few years.


* [[https://wordsinasentence.com/outburst-in-a-sentence/][Outburst]]

  =a quick discharge of someone’s feelings=

  - The man’s outburst of profanity startled everyone as they noticed his reddened face.
  - When Sally revealed her pregnancy to her family, an outburst of joy could be heard by the neighbors next door.
  - Ms. French punished her class when there was an angry outburst from her four-page essay assignment.
  - After insulting the young man’s mother, his outburst swiftly turned from verbal to physical violence.


* [[https://wordsinasentence.com/outcast-in-a-sentence/][Outcast]]

  =someone who is excluded from a group=

  - After calling the police at a party, the teenager became an outcast among her friends and classmates.
  - Due to her unusual witchery, the outcast and her children remained in their home most of the time.
  - Since Terry was overweight and had limited athletic ability, many of her sporty friends treated her as an outcast during gym class.
  - Rarely speaking to people at school, the outcast walked home alone with his hoodie draped over his head.


* [[https://wordsinasentence.com/outcome-in-a-sentence/][Outcome]]

  =an action that takes place after a triggering event=

  - When the jury filed back into the courtroom, the outcome of the trial was delivered to the packed courtroom.
  - Even though the outcome of the election had not been revealed, the candidate was prematurely celebrating.
  - Germany’s citizens suffered many financial difficulties due to the outcome of World War I.
  - Franklin Roosevelt created the Tennessee Valley Authority as an outcome of the Great Depression.


* [[https://wordsinasentence.com/outcry-in-a-sentence/][Outcry]]

  =a loud utterance or yell=

  - An outcry from the peasants for the poor working conditions forced the landowner to make changes due to their complaints.
  - When the parents heard their child was being punished, their outcry to the principal was silenced when they viewed the video of their child stealing the cell phone.
  - After the child was killed despite multiple visits from the child welfare department, an outcry from the public demanded a change in the system.
  - Bringing out the corvette for his wife’s birthday caused an outcry of joy from his wife and children regarding the expensive sports car.


* [[https://wordsinasentence.com/outfit-in-a-sentence/][Outfit]]

  =to provide with attire or equipment=

  - We will need to outfit our soldiers with the proper protection if we want them to survive the rigors of combat.
  - It is the dresser’s job to outfit the superstar with clothes that will really make them stand out during their performance.
  - Actors must rely on the people that run their wardrobe to outfit them appropriately for their cinematic role.
  - I am going to outfit my son with everything he needs for the first day of school, included a folder full of paper and three sharpened pencils.


* [[https://wordsinasentence.com/outfox-in-a-sentence/][Outfox]]

  =to con or trick someone using keen and smart ways=

  - Using his wit and finesse, the veteran defense attorney was able to outfox any lead witness into saying incriminating information about themselves.
  - Usually politicians spend their careers trying to outfox their opponents with colorful stories, false promises and believable lies to get the people to vote for them.
  - Timothy began to outfox his parents by coming home right before curfew and then escaping back out his window to rejoin his friends.
  - Scammers will intentionally target the elderly in order to outfox them by having them send money to a fictional charity.


* [[https://wordsinasentence.com/outgoing-in-a-sentence/][Outgoing]]

  =sociable and friendly=

  - Due to her outgoing personality, Kim made friends who always wanted to be around her.
  - Since opposites attract, the outgoing wife always got along with her introverted husband.
  - The saleswoman made her customers feel very welcome and comfortable since she was such an outgoing person.
  - When no one spoke up after the teacher asked a question, the outgoing boy was willing to share his answers with the rest of the class.


* [[https://wordsinasentence.com/outlandish-in-a-sentence/][Outlandish]]

  =very unusual=

  - Jim’s outlandish plan to get money involves robbing a bank with water guns.
  - Can you believe the outlandish rapper wants to run for president?
  - When the boy was asked about his report, he created an outlandish story about aliens stealing his work.
  - The male clown looked outlandish in the party dress. 


* [[https://wordsinasentence.com/outlaw-in-a-sentence/][Outlaw]]

  =a criminal who has disobeyed the law but has not been captured yet=

  - Everyone who passed by the wanted poster of the dangerous outlaw wanted to find him so they could get the reward money.
  - After the man robbed the federal bank, he became an outlaw who was on the run from the local lawmen.
  - Jesse James became a legendary outlaw because he and his posse robbed more than twenty banks and trains during his short lifetime.
  - On television, the kids would watch the gun slinging outlaw shoot at the innocent man in a duel.


* [[https://wordsinasentence.com/outlet-in-a-sentence/][Outlet]]

  =a large tube or opening where water flows out=

  - All my neighbors realized that my carpenter’s drill hit the underground pipe because water spewed from the outlet flooding my yard.
  - When the hot water heater sprung a leak, the water found an outlet which damaged the carpet in the house.
  - Since water was not emerging from the outlet, it became apparent that it was completely plugged with debris.
  - After turning on the water, water did not pour out of the sprayer but it was leaking from an outlet in the middle of the water hose.


* [[https://wordsinasentence.com/outlier-in-a-sentence/][Outlier]]

  =an outsider=

  - The scholarship student was treated as an outlier by her wealthy peers.
  - Jenna was a known outlier because she was the only person in her southern town to openly proclaim being an atheist and listening to reggae.
  - During a criminal investigation, detectives typically question the outlier because they’re seen as reclusive, lonely, and likely hold a grudge.
  - In her family out Democrats, Jamie was an outlier because she chose to be conservative.


* [[https://wordsinasentence.com/outline-in-a-sentence/][Outline]]

  =outer edge of lines of a person, item or thing=

  - So that the text box would be noticeable on the poster, I decided to outline the box with a dark black marker.
  - Our geography teacher told us to outline each northern state in red and each southern state in blue.
  - Gardeners will typically outline the border of each of their flowerbeds with either small rocks, wooden beams or bricks.
  - The most painful part of getting a tattoo is when the tattoo artist will outline the figure in dark black so that it stands out.


* [[https://wordsinasentence.com/outlook-in-a-sentence/][Outlook]]

  =viewpoint on a topic=

  - Many men have a negative outlook on marriage because they are so scared of commitment.
  - After suffering depression for years, Sarah finally had a new outlook on life when her baby was born.
  - When Karen was demoted at her job, her outlook on the future seemed grim since she could barely afford her bills each month.
  - With many people quitting their jobs at her law firm, the outlook for the company seemed like it would close.


* [[https://wordsinasentence.com/outnumbered-in-a-sentence/][Outnumbered]]

  =to be more than some other number or amount=

  - Knowing that they were outnumbered by their opponent, the small army decided to retreat from the battle.
  - The number of people wanting pizza outnumbered those wanting seafood, so we headed to a pizza parlor.
  - Christians outnumbered Muslims in the city by at least 100 to 1.
  - Although the coach had a strong basketball team,


* [[https://wordsinasentence.com/output-in-a-sentence/][Output]]

  =an object that is manufactured or created=

  - With hopes of increasing the amount of output of their computers, the factory hired several more workers.
  - In order to meet the high demand of Talking Tiffany dolls, the doll plant established a quota for the number of output of dolls.
  - After the printer stopped, its output of paper was sent to the receiving tray at the top of the printer.
  - Many people are scared worldwide due to the escalation of the output of terrorists from terrorist groups.


* [[https://wordsinasentence.com/outrage-in-a-sentence/][Outrage]]

  =very mad with fury=

  - Outrage over the recent election resulted in many millions of people rioting in the streets in order for people to hear their point.
  - After the police shot an innocent man in the streets, outrage from the local citizens caused many of them to beg for reform.
  - When the 8th grader talked back to the teachers for the third time that day, the teachers’ outrage grew until they sent her to the principal’s office.
  - As the teenage driver cut me off on the interstate, I screamed at him due to my outrage of the incident.


* [[https://wordsinasentence.com/outraged-in-a-sentence/][Outraged]]

  =mad; upset=

  - Outraged by the politician’s phony promises and unethical policies, the masses revolted.
  - Parents as well as teachers felt outraged at the budget school’s drastic slashing of the budget.
  - Outraged by the owner’s lack of compassion, the advocate petitioned the judge to have the animals removed from the home.
  - The detective understood the family’s concern as they were outraged that their brother was the latest shooting victim.


* [[https://wordsinasentence.com/outrageous-in-a-sentence/][Outrageous]]

  =shockingly distasteful or terrible=

  - My stern mother does not tolerate outrageous behavior at the dinner table.
  - Before we left for church, our father warned us of the consequences if we behaved in an outrageous manner during the service.
  - The outrageous cartoon made fun of the boy who was dying from cancer.
  - While the man thought he was charming the ladies at the bar, he was actually offending them with his outrageous comments. 


* [[https://wordsinasentence.com/outre-in-a-sentence/][Outre]]

  =weird and shocking=

  - During the Victorian era men wearing wigs were considered normal, but today it is thought to be outre.
  - People stared at the outre news story depicting a dog running for president of its country.
  - Many circuses and carnivals gained popularity due to the outre people in the sideshow attractions like the sword swallower and the fire breather.
  - Since there are so many syllables in this outre word, it was very difficult to pronounce and figure out the meaning.


* [[https://wordsinasentence.com/outreach-in-a-sentence/][Outreach]]

  =to offer or give aid or service=

  - When the police officer gave his new shoes to a homeless man, this outreach of sympathy was appreciated by the man.
  - An employment outreach was needed in the poor town since so many people had a difficult time finding a job.
  - Handing the teacher a gift card for $500 was the parents’ outreach of gratitude for helping their child learn how to read.
  - The outreach of love was extended to each and every person who came through the homeless shelter.


* [[https://wordsinasentence.com/outright-in-a-sentence/][Outright]]

  =to do something completely or instantly=

  - Kathy responded outright to the question that the teacher was asking even though the teacher asked the students to quietly write down their answers.
  - Arguing with the referee was outright wrong for the parent to do in front of his child since it set a bad example.
  - When the amateur chef poured a cup of salt into the recipe, his customers believed his bread was outright too salty.
  - After the video showed the boy stealing the money from the cash register, he was outright guilty of theft so there was no way he could get out of this mess.


* [[https://wordsinasentence.com/outset-in-a-sentence/][Outset]]

  =at the start of something=

  - Every character at the outset of the book was fully developed so that the reader knew everything about the characters prior to the plot.
  - At the outset of the training process, the safety rules were explicitly stated so that no one would get hurt.
  - Since the doctor discovered the cancer during the outset of its stage, the person would fully recover.
  - Tasks were distributed during the outset of the project so that everyone knew exactly what they had to do.


* [[https://wordsinasentence.com/outside-in-a-sentence/][Outside]]

  =the external or exterior area of a place=

  - “Do not color outside the lines,” the kindergarten teacher told her students, “because that would be messy.”
  - Children should only scream and run outside of the house because otherwise they would cause a disturbance.
  - The father was arrested because he traveled outside the state, and his probation stated he must remain in Oklahoma.
  - Rain was pouring down outside which helped the plants grow since they needed the moisture.


* [[https://wordsinasentence.com/outskirts-in-a-sentence/][Outskirts]]

  =the outer edge of an area or town=

  - When Arthur died, he went to the outskirts of heaven before entering the pearly gates.
  - Travelers had to drive completely through the city because the interstate ran along the outskirts of the town.
  - The wife complained about hating to drive a long distance since she and her husband bought a house on the outskirts of town.
  - Even though the dangerous criminals were seen on the outskirts of town, the townspeople were still scared.


* [[https://wordsinasentence.com/outsource-in-a-sentence/][Outsource]]

  =to contract a job out to another person or place=

  - Many businesses outsource their projects to workers in the Philippines who will work for a much lower wage.
  - With so many writing projects to work on, the editor decided to outsource some of the easier tasks to other freelancers.
  - After looking at the numbers, the company has decided to outsource production to China and save money.
  - The company began to outsource payroll responsibilities to a third party to make it easier on office staff.


* [[https://wordsinasentence.com/outspoken-in-a-sentence/][Outspoken]]

  =opinionated and frank=

  - Several of the outspoken candidates resorted to name calling during the presidential debate.
  - I cringed when my outspoken daughter told the woman that she was overweight and needed to diet.
  - After learning that she would lose her job to someone less qualified, the woman became outspoken in her demands for a pension.
  - As people get older, they become more senile and outspoken since they can’t control their words.


* [[https://wordsinasentence.com/outstanding-in-a-sentence/][Outstanding]]

  =terrific and wonderful=

  - Samuel made an outstanding catch during his baseball game by reaching over the back wall to catch the ball.
  - Her outstanding personality made everyone want to be around her since they liked her so much.
  - At the art museum, everyone bragged about the outstanding work of art showcased in the center of the gallery.
  - Since Jonas was an outstanding employee, he won the award for the “Employee of the Month.”


* [[https://wordsinasentence.com/outstretched-in-a-sentence/][Outstretched]]

  =to extend or stretch out=

  - Katie smiled and nodded as the senator shook her outstretched hand.
  - With her neck outstretched and nose in the air, the dog smelled the meat cooking on the grill.
  - The doctor examined the patient’s knee when her leg was outstretched on the table.
  - Her happy dance consisted of swaying hips, a big smile, and outstretched hands.


* [[https://wordsinasentence.com/outstrip-in-a-sentence/][Outstrip]]

  =to move further=

  - Being trained for the Kentucky Derby, these horses outstrip any of the other horses running down the track.
  - “If you want to outstrip the competition, then you need to work out at the gym,” the coach told his athletes.
  - In a race of the transportation, a train would outstrip a horse because a train has an engine.
  - Even though the marathon runner was a senior citizen, he could outstrip the young 20-year old due to his experience in running.


* [[https://wordsinasentence.com/outweigh-in-a-sentence/][Outweigh]]

  =for something to be more important or further along than something else=

  - Since the job paid much less and was more difficult, its disadvantages definitely outweigh the benefits.
  - Sending her daughter to an untrustworthy daycare did not outweigh the mother making money from a full time job.
  - Since Hulu is cheaper than Netflix, then Hulu definitely outweighs Netflix simply due to price.
  - If you want more choices with your exercising, treadmills outweigh ellipticals in that regard.


* [[https://wordsinasentence.com/outwit-in-a-sentence/][Outwit]]

  =to be more cunning or brilliant over someone else=

  - In the song, “Devil Went Down to Georgia,” the boy was able to outwit the devil by playing his fiddle better.
  - To actually win a sport, you really need to be stronger and able to outwit your opponent with a great strategy.
  - Due to a neighborly feud, the Cranstons could outwit the Liliths because they could play better tricks on them.
  - All the other dogs could outwit Sparky since he was the runt of the litter when he was born.


* [[https://wordsinasentence.com/ovation-in-a-sentence/][Ovation]]

  =an excited cheer and clapping after a performance from the spectators=

  - After the blind man played a perfect sonata on the piano, the crowd gave him a standing ovation.
  - The scared girl gave the best presentation in the classroom which resulted in an ovation from her classmates.
  - Before the fans left the bleachers, they gave an ovation to the team for winning their only game of the season.
  - The talent show ended with such a loud ovation that people in the next building could hear it.


* [[https://wordsinasentence.com/overall-in-a-sentence/][Overall]]

  =all parts, referring to the whole of something=

  - While the overall effectiveness of a squad is the most important thing in the military, it’s the skill of the individual soldiers that make the squad effective.
  - The overall performance of a sports team is not reliant on any one player, but rather all of the players working together.
  - The cost of each item I’m buying is ten dollars, but since I am buying three the overall cost of my grocery trip will be thirty dollars.
  - Overall, my group of friends is silly and fun-loving, but individually we can still be serious when we need to be.


* [[https://wordsinasentence.com/overarching-in-a-sentence/][Overarching]]

  =primary or predominantly=

  - The boss set some overarching goals for his employees that they must work on immediately plus a few minor goals to do in their spare time.
  - With the detective, the overarching question that he wanted answered was who killed the dead guy because everything else seemed trivial.
  - Since the book’s overarching theme was good versus evil, the book club leader knew she needed to guide her members to discuss this since it was important.
  - After looking through all of the prom dresses, the young girl selected the overarching choice that she knew would look the best on her.


* [[https://wordsinasentence.com/overbearing-in-a-sentence/][Overbearing]]

  =overly bossy, domineering, or arrogant=

  - Debra has a tendency to act in an overbearing and domineering way which tends to turn Ted off.
  - Sally felt that the cop acted in a very overbearing way when he yelled at her to pull off of the road.
  - After years of living with a bossy and overbearing wife, Max decided to divorce her.
  - Veronica prefers to avoid scents that are overbearing, opting for perfumes that are airy and light.


* [[https://wordsinasentence.com/overboard-in-a-sentence/][Overboard]]

  =to do something to the extreme=

  - My mother always goes overboard with Christmas decorations, hanging lights and garland on every inch of the house.
  - Lucy looks pretty with a touch of makeup but looks like a clown when she goes overboard.
  - Security at the gate seemed to go overboard by locking up all of the rowdy concert goers.
  - The football fan tried not to go overboard with celebrating, but he couldn’t control himself when his team scored.


* [[https://wordsinasentence.com/overcast-in-a-sentence/][Overcast]]

  =cloudy; gloomy=

  - The children wanted to go swimming, but the overcast day made it a little too cool to get into the pool.
  - Overcast skies and no humidity made it the perfect day to go fishing.
  - The dark and overcast day set a gloomy atmosphere even before the rain started.
  - Predicting overcast skies and an overall cloudy week, the weather man suggested getting any gardening done while it is cool.


* [[https://wordsinasentence.com/overcome-in-a-sentence/][Overcome]]

  =to succeed in dealing with a problem or difficulty=

  - Ted knows that he would have no problem speaking in public if he would only overcome his fears instead of running away from them.
  - Dad instilled in us the belief that if we tried hard enough, there is nothing in the world that we could not overcome.
  - Pat grew more despondent with each passing day as he realized that there was no way he would ever overcome his cancer.
  - Winning the presidency seemed to be a hurdle that was too difficult to overcome, which is why Donald dropped out of the race.


* [[https://wordsinasentence.com/overcompensate-in-a-sentence/][Overcompensate]]

  =to take extreme measures to correct a perceived weakness, error, or problem=

  - The young mother tried to overcompensate for her lack of experience through buying her child lots of expensive gifts.
  - Since he was a weak math student, the student tended to overcompensate by doing exceptionally well in other subjects.
  - The macho man was known for his tendency to overcompensate for his lack in height trough his toughness.
  - Because she felt so worthless inside, the insecure girl tried to overcompensate through an “I don’t care’ attitude.


* [[https://wordsinasentence.com/overdo-in-a-sentence/][Overdo]]

  =to do too much of something=

  - If you overdo it in the gym, your muscles will be extremely sore in the morning.
  - My coach insists that if I overdo my vocal workouts I will end up with a sore throat.
  - The man’s mother cautioned him not to overdo it, but he still worked way too much.
  - I always overdo it when I eat out, eating both too much steak and dessert.


* [[https://wordsinasentence.com/overdue-in-a-sentence/][Overdue]]

  =late; past due=

  - The overdue mother’s due date had passed a week ago and she couldn’t wait to have her baby.
  - Placing a note on the couple’s door, the landlord insisted that they pay their overdue rent.
  - I have several overdue books that need to be turned to the library so that I don’t owe a lot of fees.
  - The overdue Redbox money should have been returned last night, but I wanted to watch it again.


* [[https://wordsinasentence.com/overhaul-in-a-sentence/][Overhaul]]

  =to assess and replace with something better or newer=

  - After the Bolsheviks assassinated the Romanovs, they began an overhaul of the Russian government and completely rewrote the laws.
  - The baker spent several thousand dollars on the complete overhaul of all of his outdated kitchen appliances and replaced them with the latest models.
  - When Dalia broke up with her boyfriend, she did a massive overhaul of their entire apartment and threw away everything that reminded her of her ex.
  - After more than half of her class failed their exam, the teacher reevaluated her teaching methods and started a complete overhaul of every worksheet and assignment.


* [[https://wordsinasentence.com/overjoyed-in-a-sentence/][Overjoyed]]

  =exceedingly happy=

  - The couple was overjoyed when they found out they were pregnant after being unable to conceive for years.
  - She was overjoyed when her boyfriend of three years asked her to marry him.
  - Bryan was so overjoyed when his crush accepted his invitation to go out on a date that he literally jumped in the air.
  - The charity was overjoyed when they raised enough to provide the whole homeless community with Christmas dinner.


  - 24 hours of TV coverage of the US election verged on overkill.
  - The outfit was cute, but the accessories were overkill.
  - A long, flashy smile with all your teeth showing is overkill, especially at work.
  - So it’s not overkill to warn shoppers once again to be a little paranoid when they spot a too-good-to-be-true deal online.


* [[https://wordsinasentence.com/overlook-in-a-sentence/][Overlook]]

  =to supervise and direct=

  - When the young man got hired at the restaurant, the manager would overlook the new employee’s work to make sure he was doing his job correctly.
  - At the garage sale, the young girl was told to overlook the money box so that no one could take it if her mother was helping other customers.
  - As the head server, she had to wait tables as well as overlook the responsibilities of her staff since she was accountable for the rookie servers.
  - Ben had to overlook the complaint department at the customer service counter which meant he had to solve all of the problems by the customers.


* [[https://wordsinasentence.com/override-in-a-sentence/][Override]]

  =To use one’s authority to cancel or overrule the action or decision of another=

  - A manager is needed to override the transaction if the clerk makes a mistake.
  - The president has decided to override his advisors’ decision and put his own plan in place.
  - In order to delete the purchase, an override must occur and a code must be entered.
  - Without a way to override his boss’s decision, Paul had to make the best of the situation.


* [[https://wordsinasentence.com/oversight-in-a-sentence/][Oversight]]

  =something that someone does by mistake, without seeing that they are doing it=

  - Rob apologized for the oversight, insisting that it was a mistake that would never happen again.
  - The politician figured that he could always apologize for the budgeting error, claiming that it was merely an oversight.
  - Judge Judy said that she was convinced that Joe had willfully withheld wages from his employee and that it was anything but an oversight.
  - Harry apologized for not inviting me to his wedding, insisting that it was an unintentional oversight.


* [[https://wordsinasentence.com/overt-in-a-sentence/][Overt]]

  =open and not secret=

  - In some countries, racial prejudice is overt and not disguised in the least. 
  - The film’s R rating is based on its content’s overt violence and sexual acts.
  - Because of Frank’s religious beliefs, he was able to forgive his attackers for their overt hatred.
  - It was an obvious case of overt discrimination when the newly hired Caucasian man was promoted instead of the African American worker who had been with the firm for ten years.
  - As soon as Beverly saw the dog’s overt aggression, she stood in front of her daughter to protect her.
  - The security guard easily noticed the shoplifter’s overt actions. 
  - Since the detective is an observant fellow, he can easily notice facts that are not overt.


* [[https://wordsinasentence.com/overthrow-in-a-sentence/][Overthrow]]

  =a removal of a figure or establishment from power=

  - In order to overthrow someone in a position of authority, you will need enough power or support to remove them from power.
  - An overthrow of government can only be carried out by rebels with enough military strength to defeat the government army.
  - Jealous of her popularity, Laura wanted to overthrow Sarah as the most popular girl in school and take her place for herself.
  - The overthrow of the Czars and the rise of the Soviet Union in Russia was caused by the disgruntled and starving people of the nation.


* [[https://wordsinasentence.com/overtly-in-a-sentence/][Overtly]]

  =publicly, openly=

  - It is important to read through contracts before you sign them because some things are not overtly stated.
  - Larry was surprised when the job interviewer asked him overtly religious questions.
  - Although Nancy’s boss is not overtly racist, he does make some questionable remarks when annoyed.
  - Sandra was lulled into switching careers because the interviewer avoided overtly stating the terms of the job.


* [[https://wordsinasentence.com/overture-in-a-sentence/][Overture]]

  =a piece of music played at the beginning of an opera or musical play=

  - When he heard the overture begin to play, the actor immediately became nervous.
  - The conductor led the band through the overture of The Wizard of Oz.
  - The music class was given the honor of creating an overture for the commencement ceremony.
  - Wanting to add a new song to their repertoire, the violinist studied an overture.


* [[https://wordsinasentence.com/overview-in-a-sentence/][Overview]]

  =a general review or summation of something=

  - Because we needed to get the plan down quickly, our leader gave us a quick overview instead of a detailed plan.
  - Having just arrived on the scene, the commander asked for an overview of the situation so he could understand the gist of what was going on.
  - If you need to get a rough idea of something rather than a detailed understanding, you should ask for an overview of it.
  - Because the test was tomorrow, our teacher gave us an overview of everything that was going to be on it so we could have a rough understanding of what would be on it.


* [[https://wordsinasentence.com/overweening-in-a-sentence/][Overweening]]

  =arrogant; conceited=

  - Ever since Jim won the contest, he has been overweening and acting as though he is the smartest kid on the planet.
  - The overweening professor laughed at his students when they asked what he felt were stupid questions.
  - Because Al was overweening about his intelligence, he thought he could pass the test without studying.
  - Bragging about your numerous victories makes you seem a bit overweening.


* [[https://wordsinasentence.com/overwhelm-in-a-sentence/][Overwhelm]]

  =to overpower in thought or emotion=

  - A major test, a research project, and three assignments due tomorrow would overwhelm all the students with the amount of time and energy it would take to prepare for all of those tasks.
  - Five children under the age of 5 years old would overwhelm any mother with many diaper changes, yelling, screaming, and fighting among the children.
  - The news of their mother’s lymphoma and their father’s car accident seemed to overwhelm Karen and her sister which resulted in their hysterical crying.
  - “Do not overwhelm me with all of the reasons why you can’t get the work done by tomorrow’s deadline,” the strict boss said to his employer.


* [[https://wordsinasentence.com/overwrought-in-a-sentence/][Overwrought]]

  =in a state of excessive nervousness, excitement, or anger=

  - The bride was overwrought when the florist delivered the wrong flower order.
  - An overwrought mom frantically searched the park for her missing son.
  - The man’s wife was completely overwrought at his funeral.
  - When she was not awarded a scholarship, the student became overwrought.


* [[https://wordsinasentence.com/overzealous-in-a-sentence/][Overzealous]]

  =too enthusiastic, determined=

  - The defense worried that the judge would be influenced by the overzealous prosecutor.
  - I hate overzealous cops who relish in handing out speeding tickets.
  - Jason is an overzealous cyclist who is constantly riding his bike.
  - Maria’s overzealous hug made me suspicious of her motives.


* [[https://wordsinasentence.com/oxen-in-a-sentence/][Oxen]]

  =typically male bovine trained as draft animals and beasts of burden=

  - A pair of oxen are used to pull the farm cart that we own, since it is far too heavy to be carried with less powerful beasts.
  - Most bovines that are going to be used as oxen are castrated first, because they are easier to control with all of that testosterone.
  - While any bovine could be used to pull a cart, most oxen are male since they tend to have more physical strength.
  - Most oxen are simply male cows, but they can be bulls as well, since the most important thing is how strong they are.


* [[https://wordsinasentence.com/oxidation-in-a-sentence/][Oxidation]]

  =the result of a substance coming into contact with oxygen, generating a deficit of electrons=

  - During oxidation, the oxygen caused the paint to peel off the metal rod.
  - The process of oxidation describes an oxygen reaction that produces a loss of electrons.
  - As a result of oxidation, the material started to rust after being exposed to oxygen.
  - When an enzyme in your apple slices interacts with oxygen, the resulting oxidation causes the fruit to turn brown. 


* [[https://wordsinasentence.com/oxidize-in-a-sentence/][Oxidize]]

  =to merge with oxygen such as in the process of rusting or burning=

  - If you leave your bike in the rain, it will oxidize and begin to rust.
  - Even if the silver tray starts to oxidize, you can use polish to cover up the blemish.  
  - Untainted potassium will oxidize rapidly when it is exposed to air.
  - The metal roof will oxidize after a few years and turn an unpleasant shade of green.


* [[https://wordsinasentence.com/oxymoron-in-a-sentence/][Oxymoron]]

  =an expression that contains words with opposite meanings=

  - Normally, an oxymoron consists of a noun and an adjective which clashes in opposition with that noun.
  - The oxymoron “pretty ugly” implies that a person can be both attractive and unattractive at the same time.
  - Putting two contrasting terms together is the easiest way to make an oxymoron.
  - Since shrimp are never actually large, the oxymoron “jumbo shrimp” is pretty obvious.
  - Everyone knows the concept of a “civil war” is an oxymoron because wars are never civil.
  - If you want to make an obvious contradiction with words, then you should use an oxymoron.
  - As an oxymoron is a term or phrase which is generally composed of opposing words, an oxymoron is a clear contradiction.


* [[https://wordsinasentence.com/oy-vey-in-a-sentence/][Oy Vey]]

  =a Yiddish phrase expressing dismay or exasperation=

  - I'm an hour late for work and I still cannot find my car keys. Oy Vey.


* [[https://wordsinasentence.com/ozone-in-a-sentence/][Ozone]]

  =the type of oxygen located in a high tier of the Earth’s atmosphere=

  - Without the ozone layer, life will cease to exist on Earth. 
  - The ozone in the air reduces the amount of radiation that comes from the sun.
  - Because of the high amount of pollution in the area, the ozone layer is being depleted.
  - Ozone is a kind of oxygen that makes up one of the layers of the Earth’s atmosphere. 


