* [[https://wordsinasentence.com/qua-in-a-sentence/][Qua]]

  =used to say “as” or “as a”=

  - At the gallery, the work of art qua art is being displayed in a special showroom.
  - Many people underestimate the power of rap music qua music.
  - The mediocre movie cannot, qua film, have the same effect as the novel did.
  - Qua physician, the doctor treats hundreds of patients each year.


* [[https://wordsinasentence.com/quadrangle-in-a-sentence/][Quadrangle]]

  =a rectangular or square shaped courtyard=

  - Overlooking the quadrangle, the children could not wait to leave their apartment and play in the square courtyard.
  - Surrounding the quadrangle were many elaborately built houses and luscious gardens that took away from the square.
  - A picturesque quadrangle was positioned in the middle of the 40-acre campus.
  - Taking his place in the quadrangle, the court jester pleased the crowd inside the piazza with his tricks.


* [[https://wordsinasentence.com/quadrant-in-a-sentence/][Quadrant]]

  =one section of something that is divided into four parts=

  - During the hurricane, the low-lying fourth quadrant of the city was hit much harder than the other three areas.
  - One quadrant of the classroom was set up with a computer lab while the other areas were filled with desks, a reading center, and the teacher’s personal space.
  - An injury to the right-front quadrant of his head caused migraines that affected the other three parts as well.
  - Dividing the cabin into four parts, the camp leader assigned a specific quadrant to each scout.


* [[https://wordsinasentence.com/quadrennial-in-a-sentence/][Quadrennial]]

  =lasting or occurring every four years=

  - The quadrennial election happens every four years.
  - In my family, we have a quadrennial reunion in which all family members come together every four years.
  - Since he was elected for a quadrennial term, the mayor will have the next four years to clean up the city.
  - It seemed that the wildflowers were quadrennial as they popped up in our garden about every four years.


* [[https://wordsinasentence.com/quadriceps-in-a-sentence/][Quadriceps]]

  =A large muscle in the thigh (front) that is used to extend the leg or bend the hip=

  - Stretching his quadriceps helped the runner prepare for the strain his leg would endure during the race.
  - A strain in his quadriceps caused the man to have trouble doing simple things like bending his leg.
  - Although his sartorius muscle is strong, his quadriceps is much weaker than a leg muscle should be.
  - His right quadriceps muscle had a tear that forced the trainer to take sever weeks off from work.


* [[https://wordsinasentence.com/quadrilateral-in-a-sentence/][Quadrilateral]]

  =Four-sided=

  - The quadrilateral shaped garden contained a different vegetable in each of the four quadrants.
  - A triangular cake was baked but the bride insisted on a quadrilateral dessert with an extra-side.
  - Decorative wrapping paper covered each of the four sides of the quadrilateral box.
  - Claiming a side of the quadrilateral room, each of the four siblings seemed happy with his or her sleeping quarters.


* [[https://wordsinasentence.com/quadruped-in-a-sentence/][Quadruped]]

  =an animal that has four feet=

  - My little girl likes to walk on her knees and hands like a quadruped.
  - When the furry quadruped had one of its legs amputated, it became a three-legged cat.
  - A pig moves on four legs so by definition it is a quadruped.
  - Although my dog is a quadruped who walks on four legs, it will walk as a biped in order to receive a treat.


* [[https://wordsinasentence.com/quadruple-in-a-sentence/][Quadruple]]

  =multiply by four=

  - When the star player took the basketball court, the home team’s score seemed to quadruple within a short period of time from 10 to 40.
  - Ever since football helmets became optional for the local ragtag football team, the hospital got ready because it knew their injuries would quadruple.
  - Harry received the promotion to the delight of his wife since he would receive use of the company car, an increase in vacation time, and his salary would quadruple in size.
  - As the single mother of two married a man with six children, the house would burst at the seams since it would quadruple in size.


* [[https://wordsinasentence.com/quadruplicate-in-a-sentence/][Quadruplicate]]

  =to multiply something by four=

  - Since there were four members in each group, we had to quadruplicate the craft supplies by four.
  - Using four specific sample sets, we tried to quadruplicate the original results.
  - Four different concert dates required the musicians to quadruplicate their performance over and over.
  - The photo processor was asked to quadruplicate the reunion pictures for the mom, dad, and their two children.


* [[https://wordsinasentence.com/quaff-in-a-sentence/][Quaff]]

  =to hastily consume a beverage=

  - The huge athlete was able to quaff down a gallon of water in less than two minutes.
  - On any college campus, you can find at least one frat boy who will quaff any beverage given to him.
  - My husband always has to quaff a pot of coffee before leaving for work.
  - When the thirsty sailors were on leave, they would quaff as much beer as they could hold. 
  - The intoxicated girl tried to quaff the entire keg.
  - When the man was rescued from the desert, he wanted to quaff the entire bottle of water.
  - After the last final exam, my friends and I went to the pub to quaff a few drinks.


* [[https://wordsinasentence.com/quagmire-in-a-sentence/][Quagmire]]

  =a situation from which it is hard to escape=

  - Many young people do not realize the quagmire to which occasional drug use can lead.
  - Since Jim lost all of his money gambling, he is stuck in a financial quagmire.
  - When Hank called me from jail, I knew he was in a quagmire.
  - When Marie’s car broke down, getting to work became a quagmire for her.


* [[https://wordsinasentence.com/quail-in-a-sentence/][Quail]]

  =a small, short-tailed, commonly hunted bird=

  - Known as a gourmet chef, Emeril Lagasse created a masterpiece of flavors by snipping off the wings and removing the feathers off the quail before roasting and serving it to the queen.
  - For the experienced hunters, hunting quail proved difficult due to its high flying abilities and its brown feathers allowing it to camouflage into nature.
  - When I visited the local park, a quail darted near the pond and pecked with its beak at the bread crumbs lying around.
  - The only artwork I was interested in at the art sale was a watercolor picture of a brown quail perched with its short tail dangling over the tree limb.


* [[https://wordsinasentence.com/quaint-in-a-sentence/][Quaint]]

  =appearing old-fashioned in an appealing way=

  - My grandmother’s quaint home is filled with knick-knacks from her childhood.
  - As I walked through the quaint shop, I felt as though I was transported back in time.
  - The quaint village does not appear to have changed since it was first settled in the early 1900s.
  - Before I left the old house, I had to sit in the quaint rocking chairs on the front porch.
  - The antebellum mansion looks very quaint under the moss-covered trees.
  - As soon as we entered the quaint home, we noticed it was filled with charming antiques.
  - Tabitha looked adorable in her quaint homemade dress.


* [[https://wordsinasentence.com/quaker-in-a-sentence/][Quaker]]

  =A nickname for a religious member of the Religious Society of Friends=

  - The Quaker believer spent his nights reading the doctrine of the Inner Light.
  - Rejecting formal ministry based assemblies, the Quaker set up a prayer meeting in his house.
  - Quaker friends believe that there is God in everyone and everyone has a direct line to God.
  - Many Quakers turn to Christian scriptures for insight and guidance but do not hold them as the final authority.


* [[https://wordsinasentence.com/qualification-in-a-sentence/][Qualification]]

  =a special skill or requirement that makes a person eligible for a position or activity=

  - Credit qualification was required before the lender would approved the mortgage loan.
  - The inexperienced clerk was not hired since she did not meet the three year work qualification requirement.
  - One qualification for employment is that the potential employee must meet a drug screen.
  - Passing the qualification round, the runner prepared for the next phase of the competition.


* [[https://wordsinasentence.com/qualify-in-a-sentence/][Qualify]]

  =to become eligible or suitable for something=

  - To qualify for a housing loan, the applicant had to raise his credit score by several points.
  - The runner must come in first or second place to qualify for the next round.
  - Tim tried to qualify for government assistance but wasn’t eligible because he made too much money.
  - To qualify for the position, a candidate must have 2-4 years’ experience working in a business office.


* [[https://wordsinasentence.com/qualitative-in-a-sentence/][Qualitative]]

  =associated with type or quality=

  - The qualitative study will reveal the elements present in the compound.
  - Before the judges rate the desserts, a qualitative assessment will be used to categorize the dishes.
  - The qualitative differences in last year’s smartphone and this year’s version are not sizeable enough for the price hike.
  - While a quantitative analysis produces an amount, a qualitative analysis reveals a quality or kind.


* [[https://wordsinasentence.com/qualities-in-a-sentence/][Qualities]]

  =attributes or characteristics of a person, place, or thing=

  - Although her date had many of the qualities she desired in a husband, the woman could not get over his tendency to chew with his mouth open.
  - Excellent written and oral communication skills are proven qualities of a strong leader.
  - Before his interview, the candidate pondered the best way to demonstrate his positive qualities to the panel.
  - Confidence and a positive attitude were the server’s most attractive qualities.


* [[https://wordsinasentence.com/qualm-in-a-sentence/][Qualm]]

  =a feeling of doubt or uncertainty about whether you are doing the right thing=

  - Under the influence of drugs, Matt had no qualm whatsoever about spending all of his money at the casino.
  - I have a serious qualm about my teenage daughter dating an older man.
  - Without any qualm, the killer shot the young woman in the face.
  - My qualm with this company is their lack of contributions to local charities.
  - The crooked businessman appeared to have no qualm about tearing down the nursing home to build a parking lot.
  - As Jenna walked down the aisle to meet her future husband, she experienced a qualm that almost made her change her mind about getting married.
  - When Margaret desperately needed money, she seemed to have no qualm about robbing others.


* [[https://wordsinasentence.com/quandary-in-a-sentence/][Quandary]]

  =a state of doubt about what to do in a certain situation; a difficult situation=

  - Mark is in a quandary about whether or not he should keep the money he found in the park.
  - When the lawyer told us our lawsuit options, we realized we were in a quandary about which legal path to take.
  - I find myself in a moral quandary about whether or not I should tell my wife the truth about my affair.
  - Because you are in a quandary and doubting your ability to make a decision, I suggest you talk to one of your friends about your problem.
  - Since I am always honest with my parents, I found myself in a quandary when my best friend asked me to lie to my father about my whereabouts.
  - The decline of the housing market has put many real estate agents into a financial quandary.
  - When my husband and I were debating our vacation plans, we were in a quandary between going on a cruise and flying to New York City. 


* [[https://wordsinasentence.com/quantifiable-in-a-sentence/][Quantifiable]]

  =able to be measured=

  - Scientists used a calculator to average the quantifiable data gathered during the experiment.
  - Although the teacher tried to determine which children were the best readers from the assessment, the results were not quantifiable.
  - After grading all of the quantifiable tests, the teacher wrote letter grades on each one.
  - Quantifiable surveys were conducted to gauge the number of employees who were unhappy with current insurance options.


* [[https://wordsinasentence.com/quantify-in-a-sentence/][Quantify]]

  =to assign a quantity to=

  - In my statistics class, we needed to quantify the probability of winning the lottery.
  - Since it is impossible to quantify the number of stars, the night sky fascinates me.
  - The census bureau attempts to quantify how many people reside in a household.
  - Our objective was to quantify the gallons of water in the local lake.


* [[https://wordsinasentence.com/quantitative-in-a-sentence/][Quantitative]]

  =pertaining to the measureable amount of something=

  - After writing down everyone’s height in his 4th period class, the student analyzed the quantitative data to determine he was the tallest student in the class.
  - Conducting a quantitative analysis of the company’s stock over time proved to be helpful when promoting the company’s product.
  - While deciding on my science project, I realized I wanted to do a quantitative study so that I could analyze the measurements as opposed to a more subjective approach.
  - During my quantitative survey, I asked students to write down the number of times they had traveled out of the country.


* [[https://wordsinasentence.com/quantity-in-a-sentence/][Quantity]]

  =the amount of something=

  - The store owner checked the quantity of tires and realized he needed to order more.
  - Because the quantity of televisions for sale was low, many customers left the store emptyhanded.
  - Hal counted the quantity of green apples to see if it was higher than the number of red ones.
  - Right before Halloween, the store will order triple the usual quantity of pumpkins.


* [[https://wordsinasentence.com/quantum-in-a-sentence/][Quantum]]

  =The smallest amount of something, specifically energy=

  - Measuring the quantum amount of the object essentially destroyed it.
  - Quantum complexities are just a small part of the make-up of the human brain.
  - Quantum mechanics was used to explain properties of several energy forms.
  - While quantum energy could not be measured fully, the scientist continued to work on the experiment.


* [[https://wordsinasentence.com/quarantine-in-a-sentence/][Quarantine]]

  =a place where individuals or animals who have contagious diseases are held=

  - Until it is determined whether or not the dog has rabies, it will be placed in quarantine.
  - The woman with Ebola has been placed in quarantine to ensure she does not spread the virus.
  - As long as John is in quarantine, he will not be able to contaminate anyone else.
  - The contagious patients will be placed in quarantine and then treated to stop the circulation of the disease.


* [[https://wordsinasentence.com/quarrel-in-a-sentence/][Quarrel]]

  =a verbal disagreement that is usually noisy=

  - The quarrel my husband and I had was so loud it woke our children.
  - After the quarrel Jack had with his boss, he doubted he would have a job much longer.
  - Phil’s walking away from Bill brought an end to the quarrel.
  - Since Tom and Ann had a public quarrel about Ann's infidelities, the two have lived in separate locations. 


* [[https://wordsinasentence.com/quarrelsome-in-a-sentence/][Quarrelsome]]

  =argumentative; confrontational=

  - The younger brother’s quarrelsome nature resulted in constant arguments and the splitting of the family business.
  - Although the attorney’s quarrelsome attitude caused her trouble at home, it helped her excel when arguing her clients’ cases.
  - The two quarrelsome neighbors caused many sleepless nights for those who lived around them.
  - Bringing out his father’s quarrelsome nature, the teenage boy enjoyed getting his dad riled up.


* [[https://wordsinasentence.com/quarry-in-a-sentence/][Quarry]]

  =an area from which materials like stone are removed=

  - At night, the moonlight caused the stones in the quarry to shine.
  - The men who work in the rock quarry wear masks to keep the stone particles out of their eyes. 
  - On Monday, the middle school students will visit the quarry to search for limestone.
  - People are asked to remain out of the abandoned quarry because of the danger of falling rocks.
  - In the old days, the prisoners had to work at the rock quarry.
  - The granite supply from the quarry is almost depleted.
  - While digging among the stones, the quarry workers found human remains. 


* [[https://wordsinasentence.com/quarter-in-a-sentence/][Quarter]]

  =one of four equal parts=

  - With five minutes left on the clock, the defense performed much better than they did in the previous quarter.
  - Only one quarter of the four auditorium sections were filled to capacity.
  - A quarter of the guests requested specialized meals while the other three-fourths ordered directly form the menu.
  - Although a quarter of the money is dedicated to the employee salaries, most of the budget is used to purchase new inventory.


* [[https://wordsinasentence.com/quartet-in-a-sentence/][Quartet]]

  =a musical group with four members=

  - The final performance had to be postponed since two of the four members were sick with the flu.
  - Blending their four voices methodically, the quartet sang in perfect harmony.
  - The quartet was originally an all-male group, but a female musician replaced the fourth member last year.
  - The soloist was nervous about joining the quartet as she wasn’t used to having to harmonize with three other voices.


* [[https://wordsinasentence.com/quasar-in-a-sentence/][Quasar]]

  =an incredibly distant celestial object made of a vivid mass of light and energy=

  - A quasar is a cosmic entity that is filled with energy. 
  - When the astronomer looked through his telescope, he was able to see a brightly lit object known as a quasar.
  - A black hole is the powerful energy source that fuels a quasar. 
  - Because a quasar is so bright, it overshadows the light given off by celestial objects in its vicinity.


* [[https://wordsinasentence.com/quash-in-a-sentence/][Quash]]

  =to put an end to something=

  - Refusing to give in to the toddler’s demands, the exasperated mother was hell-bent on coming up with a plan to quash the tantrums.
  - My defense team tried to quash the subpoena but it was served anyway.
  - Tired of squabbling, the exhausted husband agreed to quash the argument and go shopping with his wife.
  - Scientists were able to quickly quash the outbreak through a new immunization.


* [[https://wordsinasentence.com/quasi-in-a-sentence/][Quasi]]

  =having features that are similar to another thing=

  - Since my father was in the military for twenty-five years, he treats our home like it is a quasi-base camp.
  - My scout troop made my father a quasi leader because of all the support he gave us during the year. 
  - Although only a few people showed up at my party, it was still a quasi success because everyone who came to the event had fun.
  - The two children agreed to trade teddy bears by signing their names on a quasi contract written in crayon. 


* [[https://wordsinasentence.com/quaver-in-a-sentence/][Quaver]]

  =a tremor in an individual’s voice usually caused by nervousness or anxiety=

  - You could hear a quaver in the nervous girl’s tone.
  - Did you hear the quaver in Kim’s voice when she thanked everyone for attending her going away party?
  - When the teenager was pulled over by police, he was so scared he had a quaver in his voice.
  - Because of my social anxiety, I hear a quaver in my speech when I talk to strangers. 


* [[https://wordsinasentence.com/quay-in-a-sentence/][Quay]]

  =a concrete loading dock situated on the edge of a body of water=

  - After years of loading and unloading freight on top of it, sections of the old concrete quay began to crumble into the sea.
  - The quay was constructed out of material tough enough to stand water erosion and heavy loads.
  - Since boats seemed to flock to the main dock, another quay was built on the north end of the shore.
  - Porters moved large carts of freight from the vessel to the quay in the Maine harbor.


* [[https://wordsinasentence.com/queasy-in-a-sentence/][Queasy]]

  =feeling sick and nauseated=

  - As the boat began to pick up speed, a few of the ship’s passengers began to feel queasy from the motion.
  - Arguing with her mother always made the young girl queasy and nauseous.
  - After eating too much dessert, Macy felt an uneasily queasy feeling in her stomach.
  - Because she was prone to motion sickness, Valerie always feels queasy after a long car ride.


* [[https://wordsinasentence.com/queen-in-a-sentence/][Queen]]

  =a woman ruler of a kingdom or country=

  - Presenting a feast fit for a queen, the peasants tried to make sure everything was in place for her majesty.
  - Although the queen did not approve of her daughter-in-law, she was happy when a male heir to the thrown was born.
  - Staring in awe as the queen chewed with her mouth open, the serfs and kingdoms were in shock that a crowned monarch would act in such a way.
  - The empress’s ailing health caused a new queen to step fourth and prepare to take the throne.


* [[https://wordsinasentence.com/queer-in-a-sentence/][Queer]]

  =strange; odd=

  - Peering into the queer little house, Georgia couldn’t understand why all the unusually shaped furniture was painted pink and blue.
  - Because of his queer habits, the recluse was seen as strange by his fellow townspeople.
  - Lily found it queer that her sister had pet monkey’s but accepted her odd obsession all the same.
  - The queer little object looked like something out of a science fiction movie.


* [[https://wordsinasentence.com/quell-in-a-sentence/][Quell]]

  =to calm or reduce=

  - Before Sarah gives a speech, she always drinks a shot of whiskey to quell her nerves.
  - The old man drinks warm milk to quell his upset stomach.
  - During the riots, over five hundred policemen worked to quell the uproar.
  - The principal tapped the microphone to quell the noise in the auditorium.
  - In order to quell unemployment, the government is giving more business loans.
  - Troops are being deployed to quell the threat of violence from the terrorist nation.
  - Because Hiriam wants to quell his urge to smoke, he is now using nicotine patches.


* [[https://wordsinasentence.com/quench-in-a-sentence/][Quench]]

  =to satisfy an actual or figurative thirst, or to put out a fire=

  - Aiming to quench her thirst, the runner guzzled down the water at full speed.
  - When they were finally able to quench the flames of the fire, the firefighters breathed a sigh of relief. 
  - Although it failed to quench her thirst for a summer road trip, the mini-vacation at the lake was a distraction for the avid traveler. 
  - Unable to quench the flame on by blowing, the birthday girl laughed as she realized that her parents had bought a prank candle.


* [[https://wordsinasentence.com/querulous-in-a-sentence/][Querulous]]

  =full of complaints; complaining=

  - If there was an award for being querulous, my aunt would win because she is always complaining about something.
  - I don’t mean to be querulous, but I do believe I should get my money’s worth at all times.
  - Forgive me for sounding querulous, but there is a bug in my soup.
  - Whenever my father had too many drinks, he would become querulous and complain about everything.
  - During the plane trip, I had to sit next to a querulous lady who did nothing but criticize the flight attendants.
  - If my little boy does not take his nap on time, he becomes querulous and finds fault with everything.
  - I was a querulous kid who always argued with my mother when she put vegetables on my dinner plate.


* [[https://wordsinasentence.com/query-in-a-sentence/][Query]]

  =an inquiry for information=

  - State officials have launched a query into allegations of judicial misconduct by Judge Petros.
  - Because Lisa is such a curious child, she is always making one query after another.
  - The substitute teacher couldn’t respond to the student’s query because she was unfamiliar with the subject material.
  - Once the results of the autopsy are revealed, the police may open a query into the cause of death.


* [[https://wordsinasentence.com/quest-in-a-sentence/][Quest]]

  =a trip taken to find something or someone=

  - Jan’s quest for fame led her to do immoral things.
  - When Phil was on a quest for his soul mate, he went on hundreds of dates.
  - The knight travelled throughout the world while on his quest for the holy grail.
  - During my quest to be healthier, I will seek assistance from both a nutritionist and a personal trainer.


* [[https://wordsinasentence.com/questionable-in-a-sentence/][Questionable]]

  =not certain; doubtful=

  - Attending the game is questionable since it will probably be rescheduled due to rain.
  - Because of his questionable motives, many citizens felt the mayor might be stealing money from the city.
  - The injured player is listed as questionable on the roster since many do not think he will return this season.
  - Because of her questionable alibi, the police thought the murder suspect might be hiding something.


* [[https://wordsinasentence.com/questionnaire-in-a-sentence/][Questionnaire]]

  =a set of questions used to gain specific information from people responding to the survey=

  - Respondents to the second questionnaire provided follow up information about the types of cleaning products they use.
  - Although the questionnaire was aimed at married couples, many single parents responded to the poll as well.
  - Filing out the questionnaire was a daunting task since the inquiry form was so long.
  - Questionnaire makers used prizes as a way to rope shoppers into filling out their surveys.


* [[https://wordsinasentence.com/queue-in-a-sentence/][Queue]]

  =a waiting list or line in which people and/or problems are dealt with in order=

  - We stood in the queue for hours waiting to get tickets to the championship game.
  - Even though I arrived at the post office early, I still had to wait in the queue before I could see a clerk.
  - The queue to get onto the bus was so long I wondered if I would be able to find a seat.
  - Because the woman was inconsiderate, she ignored the people standing in the queue and went directly to the register.


* [[https://wordsinasentence.com/quibble-in-a-sentence/][Quibble]]

  =to quarrel about minor matters=

  - It is normal for married couples to quibble over small things like who controls the television remote.
  - Whenever the two historians meet, they quibble over historical facts before drinking a pitcher of beer.
  - We should not quibble over a small detail like borrowed money before your surgery.
  - When my ex-husband and I are together, all we do is quibble over the lack of support he gives me.
  - The billionaire did not quibble over the five-dollar service charge.
  - As usual the city council members chose to quibble over holiday party details rather than deal with the city’s issues.
  - How long do you think the politicians will quibble over the budget proposals before they finally select one?


* [[https://wordsinasentence.com/quick-in-a-sentence/][Quick]]

  =moving fast or doing something in a short timeframe=

  - The rabbit was much too quick for my large dog to catch him, darting away and into a small crevice.
  - A basketball player must be quick on his feet to move around the court and react to the actions of other players.
  - In a Wild West showdown, a quick cowboy that could draw his gun in the blink of an eye was a living one, and his not so quick enemy was often dead.
  - My friend is very quick when it comes to math, being able to solve most equations in just a few seconds.


* [[https://wordsinasentence.com/quickly-in-a-sentence/][Quickly]]

  =at a rapid speed; fastly=

  - Speeding quickly down the highway, the distracted driver missed a curve and careened off of the mountainside.
  - The runner moved quickly towards the finish line and ended up in 1st place.
  - Pulling the trigger quickly, the cowboy was able to win the duel by shooting his foe first.
  - Escaping quickly out of the back door, the fast-moving woman was able to get out of the burning building without being hurt.


* [[https://wordsinasentence.com/quid-pro-quo-in-a-sentence/][Quid pro quo]]

  =a Latin term that refers to a deal in which something is given but only in exchange for something else, often use in legal cases=

  - Continuing quid pro quo, the bread maker always gave the butcher loaves in exchange for beef.
  - Accused of quid pro quo sexual harassment, the CEO denied promising his assistant a job in exchange for a date.
  - The basis of the suit was a quid pro quo claim in which a woman claimed she was fired after refusing to have sex with her boss.
  - Signing the quid pro quo contract, the model agreed to wear the clothing on the runway in exchange for exposure.


* [[https://wordsinasentence.com/quiddity-in-a-sentence/][Quiddity]]

  =the qualities of something that makes it what it is, usually on purpose=

  - The quiddity of motherhood was reflected in Ms. Dowling because she was always baking cookies and tending to her child’s needs.
  - The actual quiddity of his leadership skills shined through when Timothy was able to easily convince a crowd of people about his viewpoint.
  - The stout and prestigious photograph of the prominent soldier showed the quiddity of his power.
  - When someone’s first baby is born, they experience the true quiddity of life because they know this was meant to be.


* [[https://wordsinasentence.com/quidnunc-in-a-sentence/][Quidnunc]]

  =a busybody who always wants to know other people’s business=

  - The town’s biggest quidnunc, Nancy loved to gossip about other people’s personal lives.
  - You should stop being a gossiping quidnunc and mind your own business!
  - My aunt is a nosy quidnunc who calls my mother each evening to hear the latest town gossip.
  - Rolling her eyes at Mrs. Murdock’s chattering, Ramona couldn’t believe she lived next to such a meddlesome quidnunc.


* [[https://wordsinasentence.com/quiescent-in-a-sentence/][Quiescent]]

  =not active; quiet=

  - For once, our hyperactive Great Dane is quiescent and resting on the rug.
  - Now that school has started back, my neighborhood is pretty quiescent during the day.
  - While the bees are quiescent early in the morning and in the evening, they are overactive in the middle of the day.
  - During the quiescent phase of the lab, we simply observe and note the growth of the cells.
  - After the mediation between the two warring countries, the region became quiescent.
  - You have no reason to be concerned about the quiescent volcano.
  - As long as the protest remains quiescent, the police will not be called.


* [[https://wordsinasentence.com/quiet-in-a-sentence/][Quiet]]

  =calm with little or no noise=

  - Moving into a quiet neighborhood, the couple was glad to be able to sleep peacefully at night.
  - On the quiet summer night, the only thing that could be heard was the croaking of the frogs in the pond.
  - The sleepy toddler was quiet and stopped whining as she drifted off to sleep.
  - It is important to be quiet in the library, especially when others are trying to read in peace.


* [[https://wordsinasentence.com/quietude-in-a-sentence/][Quietude]]

  =a state of quiet stillness and calmness=

  - In quietude and coolness, the couple enjoyed a picnic on a grassy knoll beside the calm stream.
  - An eerie quietude filled the house as the children napped on their mats.
  - Needing a great amount of quietude, the hermit secluded himself in his peaceful home.
  - Quietude occupied the library, making it the perfect place to study in silence.


* [[https://wordsinasentence.com/quietus-in-a-sentence/][Quietus]]

  =the termination of something, usually unpleasant in nature=

  - The police officer’s arrival brought a quietus to the argument between the two neighbors.
  - After weeks of suffering, the cancer-stricken cat received a quietus of the pain by taking her final nap. 
  - The quietus of the riots won't occur until more police officers are brought into the city.
  - The signing of the treaty produced a quietus of the war that had plagued the continent for a decade.


* [[https://wordsinasentence.com/quill-in-a-sentence/][Quill]]

  =a pen made from the feather of a bird=

  - Placing the pointed black quill on the paper, the president prepared to write a letter to the general.
  - A quill was crafted from a long bird feather and was used to write notes.
  - As far back as the 2nd century B.C., people could use a feather-crafted quill to pen out messages.
  - Dipping his quill into the dark ink, the writer began to jot down his latest poem.


* [[https://wordsinasentence.com/quilt-in-a-sentence/][Quilt]]

  =a blanket made by sewing fabric squares or pieces together usually in a pattern=

  - When I unfolded my grandmother’s hand-sewn quilt, I could see different shapes coming together in a specific design.
  - By laying the quilt on the bed, you could still see several shapes stitched together to create the part of a star.
  - Using the colorful quilt as a blanket, the young woman noticed the person who made it had been careful to hand-stitch each piece together.
  - A patchwork quilt may look like it was quickly sewn together without much thought put into it, but it is actually a well-thought out arrangement.


* [[https://wordsinasentence.com/quintessence-in-a-sentence/][Quintessence]]

  =most perfect example of its type=

  - Hillary has always been the quintessence of high fashion, so I was taken aback when I saw her wearing an old, saggy pair of jeans and a ragged T-shirt.
  - Babies are the quintessence of purity; if only we could preserve that sweetness for a lifetime.
  - These chocolate bars are the quintessence of delicious treats for the soul.
  - For many children and adolescents all over the world, the name Voldemort is the quintessence of evil.
  - When I was in elementary school, I believed that coming down with chicken pox during Christmas vacation was the quintessence of misery.
  - She told everyone she saw that her new kitten was the quintessence of cuteness.
  - The corruption scandal was reported as the quintessence of dirty politics.


* [[https://wordsinasentence.com/quintessential-in-a-sentence/][Quintessential]]

  =a model example of a specific quality=

  - The critics love the director’s latest film and consider it to be the quintessential horror movie.
  - Combined together, rosemary and pork are the quintessential ingredients for a meat dish.
  - Everyone knows watermelon is the quintessential fruit on a hot summer day.
  - Before the arrival of modern means of communication, carrier pigeons were the quintessential means of message delivery.


* [[https://wordsinasentence.com/quip-in-a-sentence/][Quip]]

  =a clever statement=

  - The president responded to the journalist’s question with a clever quip.
  - Because the teacher did not understand my quip, she asked me to stay after class to explain my comment.
  - I punched my brother when he made a quip about my hair.
  - Although the comic thought he made a funny quip, he actually offended the audience with his provoking statement.


* [[https://wordsinasentence.com/quirk-in-a-sentence/][Quirk]]

  =an odd behavior or different way of acting=

  - Janice has this irritating quirk of rolling her eyes whenever she speaks.
  - According to Ken, his habit of constantly wringing his hands is just an uncontrollable quirk.
  - Wearing only pink socks is Greg’s oddest quirk.
  - In the film, the killer’s quirk of styling his victims’ hair led the police to the salon where he worked.


* [[https://wordsinasentence.com/quisling-in-a-sentence/][Quisling]]

  =a traitor who helps an enemy that has taken control of his or her country=

  - The quisling was a traitor who helped the British when they came to try and take over his country.
  - A traitor to his country, Benedict Arnold, was written doing in history as a treacherous quisling.
  - Hanging his head in shame, the spineless quisling was exiled from his country for treason.
  - The quisling helped the Russians conquer his country and sold them many classified documents.


* [[https://wordsinasentence.com/quit-in-a-sentence/][Quit]]

  =to leave a place or stop doing a task=

  - The teacher wanted to quit her job, but she has to find another one first.
  - Michael is trying to quit smoking through the help of his doctor.
  - The boy’s mom will force him to quit the football team if he doesn’t do well in school.
  - We quit playing dolls and started drawing instead.


* [[https://wordsinasentence.com/quite-in-a-sentence/][Quite]]

  =significantly; fairly=

  - Seasoned wings were quite tasty, but not as delicious as the corn on the cob.
  - To be December, it was quite warmer than usual.
  - When it was my turn to sing on stage, I was quite nervous.
  - The pond was quite deep and contained many different types of fish and other aquatic animals.


* [[https://wordsinasentence.com/quiver-in-a-sentence/][Quiver]]

  =to shudder with a slight sound or motion, usually because of strong feelings=

  - I knew Jill was upset when her lips started to quiver. 
  - If you are really Ann’s friend, you will tell her she does not look cute when she makes her false eyelashes quiver. 
  -  Jack’s voice started to quiver when he talked about his dead wife.
  - Whenever I see my wonderful husband, my heart starts to quiver. 


* [[https://wordsinasentence.com/quivering-in-a-sentence/][Quivering]]

  =trembling and shaking=

  - Quivering when she came out of the chilly water, the swimmer decided that it was too cold to swim after all.
  - The quivering jelly shook back and forth on the serving platter as it was delivered to the table.
  - Lost and alone, the puppy spent the cold winter night shakily quivering in an abandoned barn.
  - The frostbitten hikers were found quivering in a shack during one of the winter’s worst snow storms.


* [[https://wordsinasentence.com/quixotic-in-a-sentence/][Quixotic]]

  =unrealistic and impractical=

  - Although Jack’s plan for killing the giant was quixotic, it was the village’s only hope.
  - Henry knew running for class president was a quixotic idea, but he was not going to let his enemy run unopposed.
  - It is quixotic to think you can get away with walking into the prison and breaking out your boyfriend. 
  - While the knight’s quest sounded noble, in reality it was a quixotic plot which could only end in the young man’s death.
  - Everyone told Jennifer her dream of being a Hollywood star was quixotic, but she proved them wrong when she became a ten million dollar actress.
  - Because reality does not always have a happy ending, most women prefer to watch quixotic romantic-comedies that normally end with the girl getting her guy.
  - Nobody believed the tiny boy would achieve his quixotic goal of making the football team.


* [[https://wordsinasentence.com/quizzical-in-a-sentence/][Quizzical]]

  =suggesting confusion or disbelief=

  - Because I am a male, the doctor gave me a quizzical look when I told him I was pregnant. 
  - The writer’s quizzical poem about love reveals his doubts about the existence of the emotion.
  - With a quizzical expression on his face, Jack raised his hand to ask his teacher a question.
  - It was obvious from the quizzical looks on the students’ faces they did not understand what their professor was saying.


* [[https://wordsinasentence.com/quondam-in-a-sentence/][Quondam]]

  =former; previous=

  - The quondam beauty queen was much more exotic than the one currently being crowned.
  - Before retiring, the quondam editor trained me to take over his position.
  - Readers were surprised that the quondam CEO was speaking out against the company that he helped build from the ground up.
  - The quondam lovers could barely look at each other after they ended their relationship.


* [[https://wordsinasentence.com/quorum-in-a-sentence/][Quorum]]

  =the needed number of people to be present at a meeting in order to conduct business=

  - When Congress met to discuss the issue at hand, they realized that they would postpone the session until a quorum was met.
  - Too many absences due to summer vacations caused the meeting to cancel since a quorum was not formed.
  - “There must be a quorum of 25 members,” explained the club president, “or we can’t elect our next vice president.”
  - The secretary of the Hillsdale Garden Society took attendance at the gathering to determine if a quorum was met.


* [[https://wordsinasentence.com/quota-in-a-sentence/][Quota]]

  =a goal or quantity that is assigned=

  - Each seamstress has a quota of fifty blankets that must be sewn each day.
  - In order to keep her sales job, Kate must meet a quota each month by selling at least fifteen thousand dollars’ worth of furniture.
  - Jane exceeded her duty fee quota when shopping overseas and had to pay a twenty-dollar fee when she returned to the U.S.
  - Because of the fuel shortage, gas stations have set a quota of ten gallons per vehicle until the supply of gasoline increases.


* [[https://wordsinasentence.com/quotidian-in-a-sentence/][Quotidian]]

  =everyday events that are normal and not that exciting=

  - As the days of celebration wore on, the formerly spectacular events began to seem more quotidian, and the king found himself yawning at the chariot races.
  - There is a precise schedule for taking care of quotidian tasks, but all your time is your own once you have completed them.
  - Every year Mrs. Anderson is faced with the task of taking quotidian assignments from the curriculum and trying to make them stimulating for her students.
  - Even though the life of rock stars may seem exciting and glamorous, the days they spend traveling while on tour are as quotidian as yours and mine.
  - Compared to the process of shopping for their time share, the couple found it difficult to sit through the quotidian necessity of ironing out the details in the contract.
  - Because Arthur has a simple quotidian talent for painting, he prefers to create art for his own enjoyment rather than exhibiting it to the public.
  - Emily has an admirable enthusiasm for life, and she attacks even the most quotidian of chores with energy and passion.


* [[https://wordsinasentence.com/quotient-in-a-sentence/][Quotient]]

  =the end of result of division=

  - The fun quotient reduced significantly when mom decided to tag along.
  - Writing the equations in both product and quotient form, the teacher instructed students to answer the division questions first.
  - Paid days off weighs heavily into the employees’ work-satisfaction quotient.
  - The borrower saw the biggest improvement of his credit score when he focused on paying the larger quotient of his debt.


