* [[https://wordsinasentence.com/ubiquitous-meaning-in-a-sentence/][Ubiquitous]]

  =existing or being everywhere at the same time=

  - When I was a kid, I thought my parents were ubiquitous because it seemed as if they knew everything I did.
  - Since my sister loves the color pink, she made sure the hue was ubiquitous during her wedding.
  - Because the police presence was ubiquitous at the parade, everyone felt very safe. 
  - As evidenced by the increased number of shootings in this country, gun violence has become a ubiquitous epidemic.
  - Constantly peering over our shoulders, our project manager was a bit too ubiquitous at work.
  - A ubiquitous symbol of love found everywhere on Valentine’s Day is the heart.
  - The phrase “going green” is one of the latest ubiquitous phrases being tossed around by corporations.


* [[https://wordsinasentence.com/ubiquity-in-a-sentence/][Ubiquity]]

  =the attribute of being commonplace=

  - The ubiquity of cars in first world countries makes them so common that it’s almost inconceivable for a family to not own a car in those countries.
  - As far as human facial features are concerned, the ubiquity of black and brown hair is especially notable in comparison to the rarity of red hair.
  - An idea that has a fair amount of ubiquity to it is the notion of working for money to pay for things you want.
  - Nothing screams ubiquity in today’s society than seeing teenagers on their phones, as you can literally find them almost anywhere.


* [[https://wordsinasentence.com/ulterior-in-a-sentence/][Ulterior]]

  =hidden or concealed=

  - Politicians often use religion as a tool to get people to believe them despite their ulterior motives.
  - The salesman claimed he wanted to help the couple get a great deal, but his ulterior motive was to get rid of the clunker sitting on his lot.
  - The accountant’s ulterior motives led her to stealing bank funds under the company radar.
  - Because he owns a contracting company, the governor has an ulterior motive when giving out deals.


* [[https://wordsinasentence.com/ultimate-in-a-sentence/][Ultimate]]

  =the best achievable=

  - The scholar’s ultimate goal was to get his research published in a medical journal.
  - The writer’s ultimate dream was to get a top agent and sell her book to a Big Five publisher.
  - Hitler’s ultimate goal was to eliminate minorities from Germany and have a pure, aryan state.
  - The revolutionary’s ultimate aim is to overthrow the oppressive system and replace it with something better for the masses.


* [[https://wordsinasentence.com/ultimately-in-a-sentence/][Ultimately]]

  =finally; in the end=

  - Ultimately, we decided to buy the smaller house that had a lower price tag.
  - The family looked into both school districts, but ultimately went with the safer choice.
  - After a six-week trial, the accused was ultimately convicted of murder.
  - Maria mulled over the menu but ultimately decided to order the lobster tail.


* [[https://wordsinasentence.com/ultimatum-in-a-sentence/][Ultimatum]]

  =terms that must be agreed upon or else there will be negative consequences=

  - After hearing my wife’s ultimatum about her or the truck, I packed up my belongings and drove the truck out of the driveway. 
  - Kurt received an ultimatum from work that gave him the option of showing up to work regularly or losing his job.
  - If I do not give my daughter an ultimatum of a negative consequence, she will not complete her chores.
  - Obviously our son was not concerned about the ultimatum we gave him because he sill came home two hours late.


* [[https://wordsinasentence.com/ultracrepidarian-in-a-sentence/][Ultracrepidarian]]

  =a person who acts like an expert but rarely knows any real information about the subject=

  - The ultracrepidarian talked about physics as if he were Stephen Hawking himself but had no real knowledge of the subject.
  - Every university class has an ultracrepidarian who speaks like he’s an expert on the subject but really has very little knowledge.
  - Bruce knew that the ultracrepidarian liked to use big words and pretend to know about complex ideas like quantum physics that she had never studied in her life.
  - Shane was the ultracrepidarian of the family who always had a comment about politics or current events without any facts or statistics to back it up.


* [[https://wordsinasentence.com/ululation-in-a-sentence/][Ululation]]

  =a howling or wailing sound produced to express an emotion, especially grief=

  - Letting out a loud, high-pitched ululation, the deceased woman’s daughter continued to wail over her casket.
  - The sound of the mother’s ululation cold be heard over the cries of all of the other grieving parents at the crash site.
  - The upset child let out a kind of ululation as she howled and wailed while clinging to her mother’s dress.
  - When finding out his father died, the grief stricken young man let out a blood curdling ululation.


* [[https://wordsinasentence.com/umbrage-in-a-sentence/][Umbrage]]

  =to take offense; to find offensive=

  - Don't take umbrage to my biblical views!
  - Taking umbrage to a blonde joke, Jenna stormed out of the room.
  - Please help students rather than giving them umbrage for not knowing the answer.
  - I take umbrage to insults.
  - Principal Buckwald resigned following a senior prank, clearly taking umbrage to the pranksters. 
  - You are racist for taking umbrage against people of color!
  - The coach gave umbrage to his team for not winning a single game.


* [[https://wordsinasentence.com/umbrageous-in-a-sentence/][Umbrageous]]

  =providing shade=

  - Sitting under the umbrageous tree, the overheated workers were thankful for the shade.
  - The canopy was umbrageous and provided shade for all the wedding guests who sat underneath.
  - Placing a floppy and umbrageous sunhat on her head, the beach goer laid in her chair and relaxed.
  - The gardener moved several of her plants to the umbrageous part of the yard so that they would have plenty of shade.


* [[https://wordsinasentence.com/umpire-in-a-sentence/][Umpire]]

  =a person who controls play and makes sure that players follow the rules in a sports event=

  - “Strrrrike!” yelled the umpire as the batter took a missed swing at the ball.
  - The umpire seems to favor the other team and calls our mistakes but not theirs.
  - The umpire was trained at a referee school where officials go to learn specific rules of the game.
  - Insulting the umpire, the angry parent continued to shout at the ref after he called an out on his son.


* [[https://wordsinasentence.com/umpteen-in-a-sentence/][Umpteen]]

  =an extremely large number=

  - I have taken the test umpteen times still haven’t made a passing score.
  - My mother complained that she had called my name umpteen times, but I never answered her.
  - You’ll find umpteen variations of the same toy on the internet, but they all do the same thing.
  - The patient went to the doctor umpteen times but was never able to find a cure for her disease.


* [[https://wordsinasentence.com/unabashed-in-a-sentence/][Unabashed]]

  =brazen; bold=

  - The woman’s unabashed admirer showed up to her house with a guitar and a song.
  - Even though the mission was dangerous, the bold and unabashed troop had no fear.
  - The unabashed message was brazen enough to get a response from the company.
  - Without their unabashed leader, there was no way for the cowardly group to pull of the heist.


* [[https://wordsinasentence.com/unabated-in-a-sentence/][Unabated]]

  =persistent; relentless and refusing to give up=

  - Even after he was turned down three times, the inventor, unabated, refused to give up on his design.
  - The parents continued to abuse their children, unabated by the threat of child services.
  - If global warming continues unabated future generations may not have a world to call home.
  - Although our government has threatened them, North Korea continues their missile launches unabated.


* [[https://wordsinasentence.com/unable-in-a-sentence/][Unable]]

  =incapable; not able=

  - The principal was unable to attend the meeting and sent two of her teachers instead.
  - Although I was unable to remember the man’s name, I knew his face as soon as I saw him.
  - The woman was unable to pay her rent this month and may lose her home.
  - Because I have been sick, I am unable to go on the beach trip with my sisters.


* [[https://wordsinasentence.com/unacceptable-in-a-sentence/][Unacceptable]]

  =not allowable or welcome=

  - Cursing inside the church is unacceptable and will not be tolerated by the priest.
  - Although it is unacceptable to wear a bathing suit in the building, several of the girls did it anyway.
  - The dean explained that smoking during breaks is unacceptable and isn’t allowed on campus.
  - An unacceptable number of students have been late to class, making the teacher angry.


* [[https://wordsinasentence.com/unaccountable-in-a-sentence/][Unaccountable]]

  =unexplainable; mysterious=

  - Thinking back over the strange and unaccountable event, the dinner guest wondered how the host made the glass float in midair.
  - By some unaccountable accident, I was placed in first class instead of my third class seat.
  - For some unaccountable reason, my sister decided to tell my mother about the time we broke her antique clock while wrestling.
  - With one look at the orphan, she felt an unaccountable love for the young boy and knew instantly that she would be his mother.


* [[https://wordsinasentence.com/unadulterated-in-a-sentence/][Unadulterated]]

  =pure; untainted=

  - The unadulterated taste of pepper was strong and pure.
  - Nothing could taint the woman’s unadulterated joy during the birth of her child.
  - With an unadulterated heart that is pure, Snow White was an easy target for the evil witch.
  - The unadulterated tomb is still complete and has not been taken over by scientists or tourists.


* [[https://wordsinasentence.com/unaffected-in-a-sentence/][Unaffected]]

  =not changed or altered=

  - My sister’s home was ruined by the latest flood but my residence was unaffected.
  - Some cities appear to be unaffected by the flu while others have had lots of people die from it.
  - While a few companies will be unaffected by the cuts, many businesses will have to shut their doors.
  - Drinking water helps some women lose pounds but my weight seems to be unaffected by it.


* [[https://wordsinasentence.com/unaided-in-a-sentence/][Unaided]]

  =without help or assistance=

  - The elderly gentleman can no longer walk unaided and depends on a walker to move.
  - Even though she makes a huge mess without her mother’s help, the toddler loves to eat her cereal unaided.
  - Placing a simple slip knot on the rope allowed the lone scout to raise the flag unaided.
  - Because he is completely dependent on his eye glasses, it is hard for the legally blind man to see with his unaided eyes.


* [[https://wordsinasentence.com/unalike-in-a-sentence/][Unalike]]

  =differing from each other or dissimilar=

  - Although they are twins, the sisters are opposites and couldn’t be more unalike.
  - The two cars are unalike and have nothing in common.
  - The beaches are very different and even though they are both in Mexico, they are very unalike.
  - I don’t know how my parents are still married since their attitudes are so unalike.


* [[https://wordsinasentence.com/unalloyed-in-a-sentence/][Unalloyed]]

  =completely genuine=

  - My best friend announced her unalloyed happiness for my engagement.
  - During the church service, the congregation gave God unalloyed praise.
  - Sarah did not greet Angela with unalloyed warmth because the two women disliked each other.
  - When my boyfriend proposed to me, I felt unalloyed joy.


* [[https://wordsinasentence.com/unalterable-in-a-sentence/][Unalterable]]

  =permanent; unchangeable=

  - Because of the handmade lace on the side, the dress is unalterable.
  - I feel that the old wallpaper is unalterable, but my mother thinks she can take it down with no problem.
  - The monuments were supposed to be permanent and unalterable, several changes are now being suggested.
  - An unalterable agreement was put in place and cannot be changed by any party.


* [[https://wordsinasentence.com/unambiguous-in-a-sentence/][Unambiguous]]

  =expressed in a clear and precise way=

  - Reading the unambiguous article, the editor was glad to have found an author that is clear and concise.
  - I tried to make my complaints unambiguous so that the Better Business Bureau would know exactly what the company had done wrong.
  - The federal government provides unambiguous guidelines that are explicit when listing the types of foods school cafeterias can serve.
  - Although some of the speakers rambled on, the key note orator’s speech was unambiguous and to the point.


* [[https://wordsinasentence.com/unanimous-in-a-sentence/][Unanimous]]

  =in total agreement or accord=

  - The unanimous consent of all the shareholders was required to approve the merger.
  - Because the jury could not reach a unanimous decision, the case will be retried.
  - My husband and I made a unanimous choice to relocate after a convicted child molester moved next door to us.
  - When the grand jury made a unanimous decision to not indict the crooked police officer, the angry city responded with a two-day riot.


* [[https://wordsinasentence.com/unassailable-in-a-sentence/][Unassailable]]

  =safe from being overtaken=

  - With a thirty-point lead and only two seconds left in the game, it is certain the home team has an unassailable lead over its rival.
  - No one imagined the unassailable beverage company would one day be purchased by a more successful entity.
  - Because the prosecutor felt he had an unassailable case, he was not willing to settle for a plea bargain.
  - DNA evidence is unassailable and cannot be disproven.


* [[https://wordsinasentence.com/unassuming-in-a-sentence/][Unassuming]]

  =not putting on airs; modest=

  - The unassuming actor personally responds to his fan mail.
  - When I walked into the unassuming restaurant, I was shocked to learn they had a world famous chef on staff. 
  - The supermodel turned down an arrogant football player to marry an unassuming auditor.
  - While everyone expected the rap star to buy a mansion, he shocked the world by purchasing an unassuming cottage.


* [[https://wordsinasentence.com/unattached-in-a-sentence/][Unattached]]

  =not having a committed romantic partner=

  - My mom has been unattached ever since my dad died a few years ago, as she has little desire to reenter a romantic relationship now.
  - I am currently unattached, with no one to call my significant other even though I would very much like to.
  - If you are looking to enter a romantic relationship with someone, you should seek the unattached, not those that are already taken.
  - Someone who is unattached does not have a significant other or anyone that they have a romantic relationship with.


* [[https://wordsinasentence.com/unattainable-in-a-sentence/][Unattainable]]

  =impossible to attain or reach=

  - Even though I wanted the nursing job at the local hospital, I knew my qualifications made the job unattainable for me.
  - Since the child was less than four feet tall, the present located on the top shelf was unattainable.
  - Because space travel is so expensive, flying to the moon is unattainable for the average, everyday person.
  - The squirrels realized that the acorns were unattainable in the forest because there were only pine trees there.


* [[https://wordsinasentence.com/unavailable-in-a-sentence/][Unavailable]]

  =not available to be accessed; out of stock=

  - My favorite brand of peanut butter is unavailable, so I had to go with the off brand.
  - Several bestsellers that are unavailable for purchase at this store can be found down at the bookstore down the street.
  - Tech support is unavailable after nine, but someone will be able to assist you first thing in the morning.
  - The parent teacher spot I wanted was unavailable, so I had to take the slot that was closest to lunch time.


* [[https://wordsinasentence.com/unavoidable-in-a-sentence/][Unavoidable]]

  =required; necessary=

  - Training for the run is unavoidable since my current runtime is thirty seconds over goal.
  - If you want to move up in the company, coming in early and working late is unavoidable.
  - Speaking to my mother about my plans to move was unavoidable, but I still didn’t look forward to hearing her cry.
  - Reducing staff pay is unavoidable if the struggling café is going to keep its doors open.


* [[https://wordsinasentence.com/unaware-in-a-sentence/][Unaware]]

  =having no knowledge of a situation or fact=

  - The neighbors claimed to have been unaware that the shooting victim was a part of a well-known gang.
  - The doctor was unaware of the problems his patient was having with depression and was glad she finally told him.
  - The citizens were unaware of the serial killer that was lurking in the neighborhood.
  - More than half of the very sick patients were unaware that they even had an infection.


* [[https://wordsinasentence.com/unbearable-in-a-sentence/][Unbearable]]

  =so unpleasant or painful as to be unendurable=

  - The heat was unbearable, so we went inside.
  - Since mom’s death, life has become unbearable for Shirley.
  - Sitting in court, the tension was simply unbearable.
  - Karen wouldn’t stop yelling, so I brought the unbearable meeting to an end.


* [[https://wordsinasentence.com/unbeaten-in-a-sentence/][Unbeaten]]

  =champion; undefeated=

  - Floyd Mayweather Jr. retired from boxing Unbeaten, with a 49 to 0 record.
  - The unbeaten contender came into the ring with confidence and left with another win.
  - In 1934 Chicago Bears went unbeaten with a 13-0 season.
  - Even though he was unbeaten, the wrestler was nervous about his up-and-coming match.


* [[https://wordsinasentence.com/unbecoming-in-a-sentence/][Unbecoming]]

  =not proper or appropriate=

  - My grandmother still insists that pants are unbecoming of a lady going to church.
  - Citizens though the political attack ads to be unbecoming, unsuitable for such an important campaign.
  - The bully’s unbecoming behavior spread throughout the school and even good kids began acting mean.
  - Lackluster movie choices are unbecoming of a theater that is held to such a high standard.


* [[https://wordsinasentence.com/unbefitting-in-a-sentence/][Unbefitting]]

  =not suitable or compatible=

  - The tacky looking dress was unbefitting for a royal duchess.
  - Spitting on the sidewalk is unbefitting a true gentleman with manners.
  - Although the woman though the couch would look good in her home, it was actually unbefitting.
  - The nurse’s nasty personality was unbefitting, since those working in a helping profession should be kind and compassionate.


* [[https://wordsinasentence.com/unbeknownst-in-a-sentence/][Unbeknownst]]

  =without an individual’s knowledge=

  - Unbeknownst to Natasha, Kurt saw his mistress three times a week.
  - Jane's gambling addiction was unbeknownst to her husband.
  - Unbeknownst to the cheering fans, the touchdown was immediately ruled invalid.
  - With Amy’s help and unbeknownst to my mother, I planned a surprise family reunion.


* [[https://wordsinasentence.com/unbelievable-in-a-sentence/][Unbelievable]]

  =incredible; not able to be imagined=

  - Staring at the winning ticket, the man felt it unbelievable that he could be a millionaire.
  - An unbelievable amount of people filled the stadium, so many attending that they had to close the gates.
  - The island resort is an unbelievable place that has all of the amenities that one could only dream of.
  - Reaching his hand out at the last moment, the player made one of the most unbelievable catches in history.


* [[https://wordsinasentence.com/unbiased-in-a-sentence/][Unbiased]]

  =fair; without bias or prejudice=

  - Workers at the voting place were trained to discuss the candidates’ beliefs in an unbiased way.
  - Unbiased statements are expected from all salesmen, but we know that will not happen.
  - It seemed difficult for the doting mother to give an unbiased opinion of her prize-winning daughter.
  - During the meeting, the human resources department discussed their preferences for the job vacancy with an unbiased view.


* [[https://wordsinasentence.com/unbridled-in-a-sentence/][Unbridled]]

  =not restrained; uncontrolled=

  - The unbridled stallion was allowed to gallop wherever he pleased.
  - Unbridled ambition led the man to success since there was no one to hold him back from his dreams.
  - Running about with unbridled energy, the wild toddler could not be calmed down for her nap.
  - The victim’s father could not be stopped from releasing his unbridled anger in court.


* [[https://wordsinasentence.com/uncanny-in-a-sentence/][Uncanny]]

  =strangely weird=

  - Jeff is an uncanny man who likes to eat raw meat.
  - When the psychic looked at the abandoned house, she had an uncanny sense that something bad had happened to the owner.
  - My best friend Angela has the uncanny ability to know my thoughts before I speak.
  - Because of the crook’s uncanny resemblance to my father, he was able to use the stolen identification and credit cards without anyone becoming suspicious. 
  - They say dogs have an uncanny way of sensing bad people.
  - As soon as the casino realized Jesse had an uncanny knack for winning at blackjack, they banned him from the casino.
  - Bill is an exceptional detective because of his uncanny aptitude for noticing small details.


* [[https://wordsinasentence.com/unceasing-in-a-sentence/][Unceasing]]

  =constant; continuous=

  - The stalker continued his unceasing phone calls until he was eventually arrested for his harassment.
  - With unceasing prayers, the daughter continued to cry out to the Lord at her father’s deathbed.
  - The unceasing begging from the peddlers on the street corner was annoying to those who worked in nearby buildings.
  - The storm seemed unceasing as it rocked the coast with constant rain and winds.


* [[https://wordsinasentence.com/unceasingly-in-a-sentence/][Unceasingly]]

  =unendingly or constantly=

  - I usually never get a word in during the conversation with Bill since he talks unceasingly about every topic he can think of.
  - After three hours of my headache hurting unceasingly, I decided that I would always have this headache unless I took some aspirin.
  - As the 90-year old husband and wife celebrated their 70th wedding anniversary, their love unceasingly ensued after years and years of being together.
  - Since we decided to eat at the Western Sizzlin’ Restaurant, we could eat unceasingly from each and every item on the bar since it was an all-you-can-eat buffet.


* [[https://wordsinasentence.com/uncertain-in-a-sentence/][Uncertain]]

  =not sure; doubtful=

  - Still uncertain about where they wanted to go for their honeymoon, the engaged couple decided to research several different islands.
  - The uncertain senior still couldn’t decide where he wanted to attend college.
  - The victim was uncertain about how tall the attacker was, but knew exactly what his face looked like.
  - When the woman was asked a difficult and confusing interview question, an uncertain look flashed across her face.


* [[https://wordsinasentence.com/uncertainty-in-a-sentence/][Uncertainty]]

  =doubt or hesitation=

  - With uncertainty, the young girl slowly opened the door since she was home alone and didn’t know who was knocking.
  - Since a ruler is not completely accurate, there may be some uncertainty with the measurement so don’t expect an exact amount.
  - After sales have been decreasing for the past 18 months for the Stanley Book Publishing Company, the uncertainty of the company’s future made the employees worry about their jobs.
  - Sylvia has some uncertainty with the seriousness of her relationship with Tony when she saw Tony kiss his ex-girlfriend.


* [[https://wordsinasentence.com/uncharacteristic-in-a-sentence/][Uncharacteristic]]

  =unusual; abnormal=

  - Disappearing was uncharacteristic for the elderly man, so the police sent out a search party.
  - Although wearing makeup was uncharacteristic of the tomboy, she looked beautiful with it on.
  - Making plays that are uncharacteristic of the offense is one way to trip up the other team.
  - The usually loving dog’s uncharacteristic displays of aggression surprised its owners.


* [[https://wordsinasentence.com/uncharted-in-a-sentence/][Uncharted]]

  =not surveyed, mapped, or investigated=

  - Ships should not sail in uncharted waters, because they might get lost.
  - Before the discovery of America, many explorers traveled through uncharted waters.
  - The island was uncharted, so nobody knew what to expect there.
  - Antarctica provides many uncharted regions because of its extreme temperatures.


* [[https://wordsinasentence.com/uncomfortable-in-a-sentence/][Uncomfortable]]

  =not at ease or relaxed=

  - An uncomfortable feeling crept over the woman as she walked alone in the dark alley.
  - Even though the boy was uncomfortable with his friend’s plan to rob the bank, he pretended to be okay with it.
  - Sitting in the stiff chair all day long was extremely uncomfortable.
  - Feeling uncomfortable with the terms of the contract, the homeowner decided to go with her gut and cancel the purchase.


* [[https://wordsinasentence.com/uncompromising-in-a-sentence/][Uncompromising]]

  =steady and unshakable; adamant=

  - The ethical nurse was awarded an excellence honor for her uncompromising commitment to her patients during tough times.
  - Many of the company’s rules were rigid and uncompromising, leaving the workers to look for new jobs.
  - Even after looking for Merlin’s sword for many years, King Arthur was uncompromising and refused to give up on his quest.
  - A steady, uncompromising faith in God gave David the strength he needed to march into battle.


* [[https://wordsinasentence.com/unconditional-in-a-sentence/][Unconditional]]

  =having no controls or limits=

  - The mother’s love for her son was unconditional and she loved him no matter what mistakes he made.
  - None of the Burger King coupons were unconditional, all came with limits and couldn’t be used on certain items.
  - If the vacation offer is unconditional, it can be used on any date and at any hotel.
  - The country has unconditional protection for refugees and will allow any who is being tormented in their own country to come there with no questions asked.


* [[https://wordsinasentence.com/unconducive-in-a-sentence/][Unconducive]]

  =not favorable or not encouraging=

  - Constant moving around can make a classroom unconducive for taking test.
  - After finding black mold in most of the walls, the inspector ruled the house was an unconducive environment to live in.
  - Loud noise of the trains passing by made the small library unconducive for reading.
  - Extreme heat and a lack of water made the desert area unconducive to most plant life.


* [[https://wordsinasentence.com/unconformity-in-a-sentence/][Unconformity]]

  =a geological occurrence in which there is erosion of rock and then new sedimentary rock is deposited on top=

  - The geologist explained that an unconformity shows the time during which no sediments were well-kept in an area.
  - A large gap in the rocks patterns means there was probably a great period of erosion during that time.
  - Erosion through wind and water created an unconformity on the land and washed away a thousand years’ worth of geological records.
  - The unconformity on the top of the rock represents a time when no sediment was deposited, but instead was washed away.


* [[https://wordsinasentence.com/uncongenial-in-a-sentence/][Uncongenial]]

  =not friendly or welcoming=

  - The woman’s uncongenial dining companions on the cruise ship were rude the entire dinner.
  - Originally the supervisor seemed uncongenial, but eventually his personality warmed up.
  - An uncongenial group of mean girls ruled the cafeteria with gossip and hatefulness..
  - My mother comes off as uncongenial, but once you get to know her you will see that she is friendly.


* [[https://wordsinasentence.com/unconscionable-in-a-sentence/][Unconscionable]]

  =not right or unreasonable=

  - Allowing blind people the right to drive is not only foolish, but it is unconscionable.
  - It is unconscionable that my school bus ride takes over an hour every morning, considering I live only 3 miles from school.
  - The judge deemed the torture and killings of innocent people to be unconscionable.
  - Spitting at the teacher is unconscionable conduct and such behavior is subject to expulsion.


* [[https://wordsinasentence.com/unconscious-in-a-sentence/][Unconscious]]

  =comatose and unaware of what is going on=

  - I was unconscious during the surgery and didn’t have any idea what had happened until I woke up.
  - When struck with a hard blow to the head, the boxer was rendered unconscious and fell to the ground.
  - The robber knocked the man unconscious and ran off with his briefcase.
  - A boulder fell from the edge of the steep cliff, knocking the mountain climber unconscious and leaving him clinging to life.


* [[https://wordsinasentence.com/unconstitutional-in-a-sentence/][Unconstitutional]]

  =illegal and unlawful according to America’s Constitution=

  - Stopping the media from publishing truthful articles is unconstitutional since Americans have the right to freedom of speech.
  - The thirteenth amendment of the constitution ruled it unconstitutional to have slaves or indentured servants.
  - The Supreme Court ruled that segregating black and white students is unconstitutional and outlawed this illegal practice.
  - Because the act is constitutional, it is against our country’s laws.


* [[https://wordsinasentence.com/unconstrained-in-a-sentence/][Unconstrained]]

  =free and not restricted or restrained=

  - Swimming in the pool under the stars, the relaxed woman felt free and unconstrained.
  - The unconstrained managers have free rein in the investments they choose.
  - Even though he can choose one or two of his classes, the student wished he was unconstrained to pick them all.
  - Unconstrained internet mean customers never have to worry about running out of data.


* [[https://wordsinasentence.com/unconventional-in-a-sentence/][Unconventional]]

  =unusual; eccentric=

  - The gay man and lesbian woman’s unconventional marriage seemed strange to those who didn’t know them personally.
  - The unconventional wedding ceremony on the cruise ship was different from traditional nuptials but still lots of fun.
  - Many of the governor’s ideas were seen as unusual or eccentric, but his unconventional practices have brought more jobs to the area.
  - Unconventional cake designs are the baker’s specialty since she likes to make quirky and odd-shaped desserts.


* [[https://wordsinasentence.com/uncouth-in-a-sentence/][Uncouth]]

  =having a lack of acceptable manners=

  - While George comes from a very wealthy family, he often behaves in an uncouth manner and acts as though he has no social skills at all. 
  - My mother banished my brother from the dinner table after he drank too much and started to act uncouth. 
  - The uncouth young man did not know which fork to use during the salad portion of the formal dinner. 
  - Because Sarah is well mannered and knows how to behave in social situations, she is the total opposite of her uncouth twin Lacey.
  - Maria showed exactly how uncouth she was by appearing at Ann’s birthday party without an invitation.
  - In my family, it is considered uncouth to question someone about the value of a gift they give you.
  - Although Elaine has taken many classes on social customs, she is still uncouth and does not know how to properly greet foreign dignitaries.  


* [[https://wordsinasentence.com/uncover-in-a-sentence/][Uncover]]

  =to disclose or unearth something that was once hidden=

  - The explorers set out to uncover the location of the Holy Grail, but never found the legendary object.
  - Police were able to uncover an underground drug ring that had worked under the radar for several years.
  - It took several spies to uncover the German secrets.
  - Kicking the brush out of the way, the hunters were surprised to uncover a hidden tunnel in the forest.


* [[https://wordsinasentence.com/unction-in-a-sentence/][Unction]]

  =an anointing for a ceremonial or religious purpose=

  - I hope you can attend my daughter’s baptismal unction.
  - When William became king, the highest bishop in the land performed the formal unction.
  - The anointing of the ill for health and strength is one type of spiritual unction.
  - Before the baptism, the oil must be blessed for the unction.


* [[https://wordsinasentence.com/unctuous-in-a-sentence/][Unctuous]]

  =not expressing true feelings; pretending to display true feelings=

  - Find me a politician without an unctuous personality, and I’ll pay you a million bucks! 
  - Nicky’s unctuous demeanor got on everyone’s nerves.
  - Turned off by the unctuous compliments, the woman turned down the man’s offer of a drink. 
  - His unctuous hand gestures let everyone know he was upset about the encounter.
  - His impression of the president was unctuous and poorly done.
  - When Janice walked into her party, she pretended to be surprised with an unctuous performance. 
  - Harrison’s unctuous behavior made him seem as if he had spent every moment of his life in the theater.


* [[https://wordsinasentence.com/undaunted-in-a-sentence/][Undaunted]]

  =not intimidated or discouraged by a difficulty or danger=

  - Soldiers seemed undaunted by the mission and bravely marched into battle.
  - Although the task was large, the builders were undaunted and looked forward to the challenge of constructing the pyramid.
  - Undaunted railroad workers were fearless in the face of dangerous explosions and terrible work conditions.
  - Undaunted, the teacher marched into the chaotic classroom and gained control of the situation.


* [[https://wordsinasentence.com/undecided-in-a-sentence/][Undecided]]

  =unsure; In doubt=

  - The senior was undecided on his major and needed more time to think about what career path he would choose.
  - Weeks before their wedding, the undecided couple still couldn’t figure out where they wanted to go on their honey moon.
  - I was once undecided on gay marriage, but now I am sure that I support a person’s right to love whomever they wish.
  - The supervisor was undecided on his next career move and wondered if he should stay with his current company or take another decision.


* [[https://wordsinasentence.com/undefined-in-a-sentence/][Undefined]]

  =unclear; vague=

  - The rules were undefined, leaving many employees to break them without even knowing.
  - Camera recording showed a shadowy, undefined figure running from the building and into the woods.
  - The Director of Operations role seemed undefined since even the director himself didn’t know what his exact job was.
  - Working on vague, undefined projects can lead to unclear goals and confusion between group members.


* [[https://wordsinasentence.com/undeniable-in-a-sentence/][Undeniable]]

  =clearly true; a fact that can’t be denied=

  - The young artist has an undeniable talent for painting that is recognized by everyone at his school.
  - Wooed by the woman’s undeniable charm, the love-struck man could not deny that she has a magical appeal.
  - The fact that the thief stole the ring was undeniable, but he tried to lie to police anyway.
  - Speaking with undeniable confidence, the pastor was able to convince his listeners that every word he said was true.


* [[https://wordsinasentence.com/undeniably-in-a-sentence/][Undeniably]]

  =emphasizing that something is clearly true and can’t be denied=

  - Data shows that our school is undeniably the best in the district.
  - Although evidence undeniably linked the man to the murder, a mistake by the police allowed him to go free.
  - While the champion boxer undeniably won the fight, many wondered if his win was rigged.
  - The ruthless woman was undeniably dangerous and was known for robbing men in their sleep once she earned their trust.


* [[https://wordsinasentence.com/under-the-weather-in-a-sentence/][Under the weather]]

  =used to describe being sick or overall feeling less than optimal=

  - I was feeling a bit under the weather, so I didn’t bother eating dinner that night with my sour stomach taken into account.
  - You may say that you feel under the weather if you have a cold or a fever, which often instill an overall sense of fatigue.
  - Nothing makes me feel more under the weather than being nauseous, because it makes me feel downright miserable.
  - My coworker was feeling under the weather today, so he called in sick to work and didn’t come in.


* [[https://wordsinasentence.com/underbrush-in-a-sentence/][Underbrush]]

  =shrubs, bushes, or small trees growing beneath large trees=

  - The thick underbrush covered the old tombstone, leaving it barely visible beneath the shrubs.
  - Wearing green and brown camouflage helped the hunter blend in with the large bushes and smaller underbrush.
  - Crashing through the underbrush, the rabbit darted away from the shrubs and into the open field.
  - A fire was set to clear the field of small trees and shrub-like underbrush that stopped the farmer’s planting.


* [[https://wordsinasentence.com/undercurrent-in-a-sentence/][Undercurrent]]

  =a current of water moving below the surface=

  - Although the river appears calm on top, a strong undercurrent under the water’s surface can drown even the most skilled swimmer.
  - A strong undercurrent just under the surface flowed against the tide.
  - An undercurrent is like a small stream or river within the larger water body itself.
  - The fast-moving undercurrent provided resistance and was difficult to swim against.


* [[https://wordsinasentence.com/underestimate-in-a-sentence/][Underestimate]]

  =to say that something is worth less than it really is=

  - The man made a mistake when he chose to underestimate the skill of the other player.
  - Weather forecasters try not to underestimate the power of storms and or leave people without any idea of possible destruction.
  - Garage sale workers often underestimate the price of art and sell it to cheap.
  - The preacher warned his church members not to underestimate the power of God or the devalue prayer.


* [[https://wordsinasentence.com/underfoot-in-a-sentence/][Underfoot]]

  =something positioned under one’s feet=

  - As the boys ran through the woods, the only thing you could hear was laughing and the crunching of the leaves underfoot.
  - The old boards underfoot creaked as I tiptoed through my room.
  - Snow underfoot caused the homeless hitchhiker’s toes to tingle from frostbite.
  - Howling in pain as glass crunched under foot, the girl wished that she had put shoes on before going outside.


* [[https://wordsinasentence.com/undergo-in-a-sentence/][Undergo]]

  =to experience; go through=

  - She had to undergo anesthesia for her operation.
  - In order to purchase the property, they had to undergo a lengthy application process.
  - After the war, the veteran would continue to undergo treatment for his PTSD.
  - Because he was recently diagnosed with diabetes, he would need to undergo daily insulin injections.


* [[https://wordsinasentence.com/undergrowth-in-a-sentence/][Undergrowth]]

  =plants, sprouts and bushes that develop beneath the primary taller foliage in a woodland=

  - While the trees hovered overhead, only the hikers walking on the floor of the Amazon Rainforest could observe the undergrowth growing close to the ground.
  - In order to see the stalk and trunk of the tall trees, the undergrowth was cut down so everyone could see every tree’s bark.
  - Undergrowth blanketed the Thompson National Forest’s ground since rain caused it to grow for months.
  - Since the forest ranger wanted a small area of the forest to be covered with undergrowth, he sporadically planted seeds in the soil so it would grow in a few years.


* [[https://wordsinasentence.com/underlie-in-a-sentence/][Underlie]]

  =to trigger; motivate=

  - I don’t understand all of the principles that underlie how a radio works, but I know a few things about sound waves.
  - Emotional issues can underlie overeating and fixing these problems can help one lose weight.
  - Anger and feelings of fear often underlie screaming episodes put on by toddlers.
  - Feeling about race and religion often underlie or motivate political decisions.


* [[https://wordsinasentence.com/underlying-in-a-sentence/][Underlying]]

  =triggering or motivating=

  - The underlying cause for most lung cancer is smoking.
  - Although it is not the only underlying problem, a rise in joblessness has brought on more crime.
  - Strokes can be triggered by underlying diseases such as diabetes.
  - An underlying computer process activated the virus and shut down all of the databases.


* [[https://wordsinasentence.com/undermine-in-a-sentence/][Undermine]]

  =to weaken, hinder, sabotage=

  - Chloe hoped that her allergies were not going to undermine her ability to perform in the recital.
  - When engineers came to examine the cracks in the structure of the building, they discovered that years of flooding had worked to undermine the foundation.
  - I had to cut down the beautiful willow tree because the roots were beginning to undermine the rock wall.
  - While Abby tried to be friends with the girls in the popular group, her twin brother was always trying to undermine her efforts by embarrassing her and saying dumb things.
  - During World War II, female broadcasters such as Tokyo Rose were employed by the Japanese to spread propaganda and undermine the morale of Allied troops.
  - The secret organization sent beautiful women to spy on members of the military and undermine their loyalty.
  - To undermine her opponent’s confidence, Vanessa started shouting a war whoop every time she served the ball.


* [[https://wordsinasentence.com/underneath-in-a-sentence/][Underneath]]

  =situated directly below=

  - The titanic was buried underneath the ocean’s surface for several decades.
  - Captain hook’s treasure is buried right underneath the red X.
  - In some places, burials cannot happen underneath the ground due to flooding or icing.
  - Underneath the book’s plain cover was an interesting story filled with bright pictures.


* [[https://wordsinasentence.com/underscore-in-a-sentence/][Underscore]]

  =to highlight=

  - When the teacher reviewed the essay with her student, she went out of her way to underscore the paper’s best features.
  - The lawyer will underscore his client’s good deeds by asking the town minister to testify about the man’s generosity.
  - Since we are studying prepositions, students should use a highlighter to underscore all the prepositions in the passage. 
  - The speaker showed the students pictures of car crashes to underscore the danger of driving under the influence. 


* [[https://wordsinasentence.com/understandable-in-a-sentence/][Understandable]]

  =something that is comprehensible, or able to be understood=

  - Because I am very good at math, the complicated nature of calculus is still understandable to me, even though it is not to my classmates.
  - For a rocket scientist, the nuances of rocket science are easily understandable, even though they are not to normal folk like us.
  - The language you speak is easily understandable to you, but to someone that speaks a different language it is not.
  - Nothing is more understandable to a human than human behavior and speech, but animals rarely understand more than what we train them to.


* [[https://wordsinasentence.com/understandably-in-a-sentence/][Understandably]]

  =reasonably so; as expected=

  - The cancer patient is understandably weak after many weeks of treatment.
  - Understandably, the wife was upset when she caught her husband cheating.
  - The children were understandably frightened, even though the monster wasn’t real.
  - Understandably, most customers will buy the product that is priced the lowest.


* [[https://wordsinasentence.com/understatement-in-a-sentence/][Understatement]]

  =presenting something as being smaller or worse than it actually is=

  - Saying he had gained a little weight was an understatement since he had put on thirty just last month.
  - To say that getting a home loan with bad credit is a small challenge would be a huge understatement.
  - Calling the affair a small mistake was an understatement the man’s wife would resent.
  - An understatement of the couple’s debt made their finances look much better than what they were.


* [[https://wordsinasentence.com/undertake-in-a-sentence/][Undertake]]

  =to commit oneself to an obligation=

  - Choosing to undertake the obligation of raising foster children was not a decision the woman took lightly.
  - The naïve woman did not realize how much work her offer to undertake glee club tryouts would bring. 
  - Without anyone to undertake the running of the operations, the sick business owner was forced to close the doors.
  - He knew that to undertake the task of class officer would be a huge responsibility.  


* [[https://wordsinasentence.com/undertaking-in-a-sentence/][Undertaking]]

  =a task that is taken on=

  - Getting a PhD while working fulltime is a huge undertaking, even for the most dedicated student.
  - A major IT undertaking is taking place at the corporation, with me overseeing the task.
  - Buying a home is an undertaking that must not be taken on lightly.
  - The design team is faced with undertaking a total redesign of the museum’s bottom level.


* [[https://wordsinasentence.com/undertone-in-a-sentence/][Undertone]]

  =a quality or feeling that is gentle or subdued=

  - When dying my hair, I have my stylist add a slight undertone of red to give it a different look.
  - The cereal has a gentle undertone of honey that adds to the flavor.
  - A faint undertone of jealousy was present in the congratulations, making it sound as if the sister wasn’t really happy about her brother’s new job.
  - The subtle blue undertone of the fabric made the dress look a little more navy than black.


* [[https://wordsinasentence.com/undertow-in-a-sentence/][Undertow]]

  =an underlying mood or feeling that is present just below the surface=

  - An undertow of grief swept over the widow as she laid her husband to rest.
  - Many people don’t realize that The Wizard of Oz is more than just a family movie and has a political undertow.
  - The fictional novel was written to entertain, but it also contains an undertow that encourages readers to think about their own happiness.
  - Most of the artist’s paintings have an undertow of sadness that can make you depressed just by looking at them.


* [[https://wordsinasentence.com/undesirability-in-a-sentence/][Undesirability]]

  =the quality of being unwanted or desired=

  - The product’s undesirability caused it to sit on the shelf week after week.
  - The rain coats’ undesirability is based on location, since not many people in the deserts of Arizona have a use for them.
  - Looking for a way to rid herself of her undesirability, the woman tried to woo her husband with fancy hair and makeup.
  - The southern chef was surprised by the undesirability of fried foods in health-conscious cities like Seattle.


* [[https://wordsinasentence.com/undeterred-in-a-sentence/][Undeterred]]

  =continuing to do something even in the face of obstacles or setbacks=

  - Undeterred by the evidence stacked against his client, the attorney continued to look evidence pointing to the real killer.
  - The focused student was undeterred by her roommates partying and focused on her books instead of drinks.
  - The bank robber was undeterred by the alarm system, making a mad dash for the money even with the police on his tail
  - Dr. Martin Luther King Jr. and the other marchers were undeterred by the crowd’s threats and marched on, even in the face of violence.


* [[https://wordsinasentence.com/undiminished-in-a-sentence/][Undiminished]]

  =not lessened; not made weaker=

  - Trees in front of the window need to be cut back so that the view of the lake is undiminished.
  - Even in his eighties, the man’s eyesight was undiminished and he could see as well as his grandson.
  - The worrisome woman went to the doctor to get medicine for her anxiety, but even with pills her fear was undiminished.
  - A little rain couldn’t stop the kids from having fun and their happiness was undiminished by the storm.


* [[https://wordsinasentence.com/undisputed-in-a-sentence/][Undisputed]]

  =certain; definite=

  - The vote count was undisputed until several people came forward saying the machines had been rigged.
  - The boxer was an undisputed champion until a youngster came along and grabbed his title.
  - As the undisputed fan favorite, the actor knew that no other case member could bring in the crowd like he could.
  - Only one, undisputed winner has come forward to claim the lottery prize.


* [[https://wordsinasentence.com/undistinguished-in-a-sentence/][Undistinguished]]

  =ordinary; unremarkable=

  - Sometimes the celebrity wished for an ordinary and undistinguished life where he wasn’t followed around constantly.
  - The Bears had an undistinguished season with no big wins or horrible losses.
  - Blending in with the crowd, the spy’s undistinguished look helped her look like an everyday worker.
  - After an undistinguished career as a waitress, the young woman decided to join the military and do something exceptional with her life.


* [[https://wordsinasentence.com/undo-in-a-sentence/][Undo]]

  =to reserve or cancel=

  - I tried to undo my typing mistake, but couldn’t get it to reverse.
  - The woman regretted cheating on her husband and wished she could undo her mistake.
  - The company tried to undo the t-shirt order and get their money back.
  - If you could undo your last chess move, you would have won the game.


* [[https://wordsinasentence.com/undone-in-a-sentence/][Undone]]

  =ruined; destroyed=

  - The Clippers hope of a championship was undone by their latest loss.
  - In a story, the bad guy usually celebrates a short-term victory but is undone in the end.
  - An earthquake left the city undone and the state in pieces.
  - Things became undone for the villain and she was completely ruined by the white light.


* [[https://wordsinasentence.com/undoubtedly-in-a-sentence/][Undoubtedly]]

  =without any doubt=

  - Undoubtedly, I have plans to attend my only daughter’s high school graduation.
  - Since Ginger is a gorgeous woman, she will undoubtedly find it easy to sell cars to the horny college males.
  - Undoubtedly, the government would have passed the law if it had benefited all American citizens.
  - The prison escapee undoubtedly realized he could not run forever so he turned himself in to the authorities.


* [[https://wordsinasentence.com/undue-in-a-sentence/][Undue]]

  =at a level that is extreme, not needed=

  - The daredevil likes to take undue risks and keeps himself in trouble.
  - Because of undue stress, the doctor decided to take a break from working at the hospital.
  - Giving her boss undue credit, the secretary ever mentioned to the staff that she was the one who sealed the deal.
  - Roger put undue pressure on himself to find a job this week and ended up getting sick from stress.


* [[https://wordsinasentence.com/undulate-in-a-sentence/][Undulate]]

  =move with a smooth wavelike motion=

  - The dancers’ movements were arranged so that they seemed to undulate like dolphins with the music.
  - Because the ice skater had practiced her movements so much, she seemed to undulate on the ice.
  - It is fun to watch the ocean waters undulate beneath our glass-bottom boat.
  - Following their dance teacher’s lead, the students undulate around the room in a curvy motion. 
  - Because the wind was not blowing, the lake waters did not undulate a great deal.
  - If you look closely, you can see the grass undulate in the breeze.
  - On the cruise, I watched several sea animals undulate in the ocean.


* [[https://wordsinasentence.com/unduly-in-a-sentence/][Unduly]]

  =done excessively; overly or out of proportion=

  - The teenage girl is unduly dependent on her mother and can’t even go to the bathroom by herself.
  - Although she was unduly fearful of the harmless dog, no one could convince the scared toddler that the pet wouldn’t hurt her.
  - Because his friends unduly influenced him, it seemed as if the boy could never make any decisions by himself.
  - My father is unduly pessimistic about life and pushes his overly negative views on everyone else.


* [[https://wordsinasentence.com/unearth-in-a-sentence/][Unearth]]

  =to uncover or discover=

  - At an estate sale, I was able to unearth some dresses from the 1920s that had been hidden in an old trunk.
  - The scientists were able to unearth several fossils from the bottom of the river bed.
  - I haven’t been able to unearth my grandmother’s recipe for pecan pie, but I did find out how she made peanut brittle.
  - Only the pirates know where to dig to unearth their buried treasure.


* [[https://wordsinasentence.com/unease-in-a-sentence/][Unease]]

  =a sense of anxiety or nervousness=

  - I had a sense of unease as I traveled through the dark forest, and every noise made wary of what could be lying I wait.
  - You may feel a bit of unease before your first interview with a potential employer, but try to make it so your nervousness isn’t obvious.
  - Most people feel a bit of unease when they are new at a school, but as soon as they find a friend they will be alright.
  - I experience unease every time I am about to give a presentation at school, but I get over it once I start.


* [[https://wordsinasentence.com/uneasy-in-a-sentence/][Uneasy]]

  =nervous; worried or overly anxious=

  - I always feel uneasy when I am in a dark building alone.
  - Filled with an uneasy feeling, the girl hoped that no one was following her home from school.
  - An anxious Little Red Riding hood walked a little quicker as the dark woods made her feel uneasy.
  - I was uneasy about my test results and only stopped feeling worried when I found out I had passed.


* [[https://wordsinasentence.com/unemployment-in-a-sentence/][Unemployment]]

  =being without a job=

  - Unemployment rates have gone up ever since the Nike company took their factory jobs out of the area.
  - The jobless builder hoped to find a contracting gig at the unemployment office.
  - I received unemployment payments for the three months that I was without a job.
  - By bringing in new jobs to the area, the mayor hopes that unemployment rates will go down.


* [[https://wordsinasentence.com/unencumbered-in-a-sentence/][Unencumbered]]

  =free of to move forward or advance=

  - Because she had her official transcripts, the woman was unencumbered to move on to any college she wanted.
  - The program’s funds were unencumbered and the director was able to spend the money on anything that was needed.
  - After the broken-down car was moved out of the road, the street was unencumbered and other motorists could drive past.
  - The inmate has been released from prison and is free to live an unencumbered lifestyle if he stays out of trouble.


* [[https://wordsinasentence.com/unequal-in-a-sentence/][Unequal]]

  =imbalanced or uneven=

  - Unequal leg lengths on desks can cause them to wobble around.
  - The wrestling match between the champion and the tiny wimp seemed like an unequal contest.
  - Unequal pay between men and women continues to be a problem, with men making at least 80 cents more on average.
  - Chores in the home seemed to be unbalanced, with only the oldest child having to do his equal share.


* [[https://wordsinasentence.com/unequivocal-in-a-sentence/][Unequivocal]]

  =unquestionably clear=

  - Since we raised over a million dollars for our charity, we considered the fundraiser to be an unequivocal success.
  - The laboratory experiment must be repeated because the results are not unequivocal.
  - The teacher was impressed by the gifted student’s unequivocal explanation of the complex subject.
  - With the election a few weeks away, the president announced his unequivocal support for all the candidates of his political party.
  - The tough gun law shows the government’s unequivocal position on unregistered firearms.
  - Without unequivocal evidence, the prosecutor will not be able to prove the defendant’s guilt.
  - To succeed on large class projects, students need unequivocal directions so they will not be confused by the sizable tasks.


* [[https://wordsinasentence.com/unerring-in-a-sentence/][Unerring]]

  =correct; unmistaken=

  - The accountant had an unerring for spotting mistakes in bank statements.
  - After years on the force, the detective had an unerring instinct that told him when someone was lying.
  - The musician’s unerring talent allowed him to always sing on key.
  - The photographer had an unerring eye that allowed her to capture the right moment.


* [[https://wordsinasentence.com/unethical-in-a-sentence/][Unethical]]

  =not having morals or honorable principles=

  - Unethical office practices caused the bad doctor to lose his job at the hospital.
  - Stealing is unethical and any person who does such a thing should be punished.
  - The court ruled that is wrong and unethical for the business owner to only hire his family members.
  - Cheating on tests is unethical and students who get caught will fail the class.


* [[https://wordsinasentence.com/uneven-in-a-sentence/][Uneven]]

  =not balanced or symmetrical=

  - Because the table legs were uneven, it rocked back and forth anytime something was placed on it.
  - The girl’s bangs are uneven and need to be lined up symmetrically.
  - Embarrassed by his uneven teeth, the boy asked his parents for braces to make them straight.
  - I tried to place my picture on my wall, but kept hanging the two nails in an uneven line.


* [[https://wordsinasentence.com/uneventful-in-a-sentence/][Uneventful]]

  =boring; ordinary=

  - My uneventful weekend was filled with nothing but yawns and the flipping of channels on the T.V.
  - Most nights of the police patrol were uneventful with no bad guys or high speed chases.
  - The boring Super Bowl was uneventful, with only one touchdown and two field goals happening the entire game.
  - Our flight seemed ordinary and uneventful until we hit a rough storm and begin to bounce around.


* [[https://wordsinasentence.com/unfair-in-a-sentence/][Unfair]]

  =wrong; unjust=

  - The store was unfair with its pricing and raised the cost of water and bread during the flood.
  - It is unfair for some workers to pay taxes and others to skip the payments.
  - The teacher was unfair to the students, treating some better than others.
  - Many believed that by hiring all of his family members, the manager was giving his sons an unfair advantage over other employees.


* [[https://wordsinasentence.com/unfathomable-in-a-sentence/][Unfathomable]]

  =impossible to comprehend or understand=

  - After five hours, we still could not figure out the unfathomable riddle. 
  - The elementary student looked at the physics book and found the work completely unfathomable.
  - Because George’s business plan was unfathomable, the bank refused to give him a loan.
  - Penny’s writing was so sloppy that it was unfathomable.
  - For some unfathomable reason, Kim refuses to leave her abusive husband.
  - The skills required to play modern video games are unfathomable to most parents.
  - Once upon a time, the idea of a laptop computer was unfathomable to some of the greatest minds in the world.


* [[https://wordsinasentence.com/unfavorable-in-a-sentence/][Unfavorable]]

  =poor or bad=

  - The odds of us being able to go to the ballgame are unfavorable since the weatherman is calling for heavy rain.
  - Even though the odds are unfavorable, I like to bid on the horse that rarely wins.
  - Unfavorable market conditions make it much harder to buy a house right now.
  - Because we set sail in unfavorable conditions, it stormed most of our trip.


* [[https://wordsinasentence.com/unfeasible-in-a-sentence/][Unfeasible]]

  =impractical; not realistic=

  - Paying for their son’s college seemed unfeasible, so they looked for another way to get funding.
  - It is unfeasible to hire more workers, but the mayor insists that we need the extra staff.
  - The party budget was unfeasible and had to be tweaked so it wouldn’t be so costly.
  - Parking in the city is so unfeasible, a trip to town often seems impractical.


* [[https://wordsinasentence.com/unfeigned-in-a-sentence/][Unfeigned]]

  =real; not pretense=

  - Because the woman truly loved her husband, her sorrow was unfeigned during the funeral. 
  - Most reality shows are scripted and are not unfeigned.
  - Since Jill is afraid of most insects, I knew her scream was unfeigned when she saw the giant spider.
  - It was obvious from Phil’s unfeigned shock he had known nothing about the surprise party. 


* [[https://wordsinasentence.com/unfettered-in-a-sentence/][Unfettered]]

  =not confined or restrained=

  - Once the bird was unfettered and out of the cage, it flew up into the sky.
  - Illegal drug sales go unfettered under the ignorant eyes of the crooked sheriff.
  - When Jack’s probation is over, he will be unfettered and can move throughout the country without restrictions.
  - Unfettered greed has led fuel companies to raise gasoline prices despite their abundant supplies.


* [[https://wordsinasentence.com/unflagging-in-a-sentence/][Unflagging]]

  =tireless and persistent=

  - The persistent reporter was unflagging and refused to give up on the story.
  - The teacher’s unflagging commitment to her students lead her to work tirelessly.
  - With unflagging criticism, the husband continued to nag and complain.
  - I couldn’t get rid of the unflagging nightmares that came back night after night.


* [[https://wordsinasentence.com/unflappable-in-a-sentence/][Unflappable]]

  =clear headed and serene during a catastrophe=

  - When a deadly tornado raced across town, many residents panicked but Miles remained unflappable and calmly lead his neighbors to shelter.
  - Firefighters must be unflappable during an emergency so that they can focus on putting out fires and rescuing those in danger.
  - The wedding planner remained unflappable even as she was informed that the caterer failed to show up and the flowers were wilted because panicking would make things worse.
  - Maya knew she had to be strong after her grandmother died, so she made phone calls, organized the funeral, and kept up an unflappable appearance even though she was crying inside.


* [[https://wordsinasentence.com/unfledged-in-a-sentence/][Unfledged]]

  =inexperienced; naïve=

  - The unfledged nurse had very little experience in hospice care.
  - Although he was unfledged, the football player planned to gain some experience during summer training.
  - The unfledged, first year college students knew nothing about physical science.
  - Although she was book smart, the unfledged woman was naïve to the ways of the world.


* [[https://wordsinasentence.com/unflinching-in-a-sentence/][Unflinching]]

  =unwavering even in difficult times=

  - The frightened dog’s unflinching gaze never left my face. 
  - Because Jared was unflinching about his decision to not have children, I knew he and I were not destined to be married.
  - The president looked into the camera in an unflinching manner and promised the terrorists they would be punished.
  - While Bill was smaller than the bully, he stared at his enemy with unflinching confidence.


* [[https://wordsinasentence.com/unfold-in-a-sentence/][Unfold]]

  =to develop or progress=

  - Watching the disaster unfold on television, the onlookers couldn’t believe how quickly the storm had grown.
  - Onlookers watched the fight unfold and only left when the police showed up.
  - The trick play continued to unfold on the field, developing into a winning touchdown.
  - It took some time for the child’s personality to unfold, but eventually she came out of her shell.


* [[https://wordsinasentence.com/unforeseen-in-a-sentence/][Unforeseen]]

  =unexpected; sudden=

  - An unforeseen storm approached and surprised the weathermen who had not called for rain.
  - Although it was an unforeseen circumstance, the man’s surprise illness seemed to have brought the family closer.
  - The couple’s wedding was an unforeseen surprise since no one even knew that they were engaged.
  - Taking the medicine had unforeseen side effects that were never expected, such as weight gain and headaches.


* [[https://wordsinasentence.com/unfortunate-in-a-sentence/][Unfortunate]]

  =used to describe an unlucky or ill-time situation or person=

  - The unfortunate woman seemed jinxed as she happened to step in front of the window right when a car ploughed through it.
  - It’s unfortunate that so many children will not get to go to the swim party because of the sudden storm.
  - Although unfortunate, there is nothing the store could do about the elderly man’s winning lottery ticket being stolen before he could cash it.
  - The unlucky woman viewed the loss of her car and home as just another unfortunate event in her life.


* [[https://wordsinasentence.com/unfortunately-in-a-sentence/][Unfortunately]]

  =used to expresses regret before giving bad news=

  - Unfortunately, there are no more tickets for the movie we want to see.
  - We have unfortunately received an eviction notice and must move before the 1st.
  - The police admitted that unfortunately, they have no leads or motive for the killing.
  - Unfortunately, there a traffic accident caused me to be late for the job interview.


* [[https://wordsinasentence.com/ungainly-in-a-sentence/][Ungainly]]

  =used to describe a person or movement that is clumsy or awkward=

  - Penguins are ungainly on land, always waddling around awkwardly on the ice.
  - The ungainly teenager was so awkward that he tripped over his own shoe laces daily.
  - Dropping glasses and plates several times in one night, the ungainly server quickly realized that she was too clumsy to be a waitress.
  - The girl’s date appeared ungainly as he stumbled over his words and awkwardly tripped over the carpet.


* [[https://wordsinasentence.com/ungrateful-in-a-sentence/][Ungrateful]]

  =not grateful; not expressing gratitude=

  - The man left a single dollar to his ungrateful son in his will.
  - Despite receiving great service, the ungrateful diners left no tip.
  - It is impossible for dogs to be ungrateful, but cats might be another story.
  - The ungrateful little girl threw a tantrum in the store for the bike she wanted knowing her mother didn’t have money to buy it.


* [[https://wordsinasentence.com/unguent-in-a-sentence/][Unguent]]

  =a greasy salve that is used to heal wounds=

  - Rubbing the unguent across the patient’s wound, the nurse hoped the salve would speed up the healing.
  - A thick unguent was used to heal the baby’s diaper rash.
  - Even though the unguent helps close cuts, the salve doesn’t work with deep wounds.
  - The pale cream unguent was used as an ointment for sunburn.


* [[https://wordsinasentence.com/unhallowed-in-a-sentence/][Unhallowed]]

  =unholy=

  - Unhallowed talk is not allowed in the holy sanctuary.
  - Walking over unhallowed ground, the priest did a few Hail Mary’s to protect himself from anything ungodly.
  - The spirits in the house were unhallowed and their evil presence haunted the children.
  - At Halloween, the unhallowed ghosts roamed around the town, spooking people with their eerie noises.


* [[https://wordsinasentence.com/unhappy-in-a-sentence/][Unhappy]]

  =displeased; upset=

  - The couple’s unhappy marriage led to heated arguments and a divorce.
  - I was unhappy with my test results and asked to see a different doctor.
  - Even though I was unhappy at work, I stayed there for a paycheck.
  - The mother was unhappy with her son’s grades and grounded him until they got better.


* [[https://wordsinasentence.com/unheeded-in-a-sentence/][Unheeded]]

  =ignored or not paid attention to=

  - The doctor’s unheeded warnings about the dangers of smoking seemed to go in one ear and out the other.
  - Now, the man wished he had taken his mother’s unheeded advice and never married his gold-digging wife.
  - When warnings to evacuate go unheeded, those who ignored the storm warnings often end up hurt.
  - Unfortunately, the battered woman’s cries for help went unheeded and no one cared to listen until it was too late.


* [[https://wordsinasentence.com/unhinged-in-a-sentence/][Unhinged]]

  =deranged; emotionally or mentally disturbed=

  - Ever since her son died, the distraught woman has been emotionally unhinged.
  - The unhinged woman was convinced that her pet snake was really her deceased husband in a new form.
  - Playing a crazy character, the actor had to practice acting looney and walking around totally unhinged.
  - Without her medicine, the mental patient is unhinged and can’t see reality.


* [[https://wordsinasentence.com/unhurt-in-a-sentence/][Unhurt]]

  =not hurt, injured, or damaged in any way=

  - Although the toddler was unhurt, the fall down the stairs scared his parents.
  - Both drivers were unhurt so there was no need for an ambulance to come to the crash site.
  - The boxer’s left hand was unhurt, but her right hand was sore from too many punches.
  - I tried to play like I was unhurt so that my parents wouldn’t take me to the doctor.


* [[https://wordsinasentence.com/unicameral-in-a-sentence/][Unicameral]]

  =a government that has only one legislative house or chamber as opposed to two=

  - Nebraska is the only U.S. state with a unicameral legislature, meaning it doesn’t have a separate house and senate.
  - Half of the world’s nations are unicameral and have only one legislative body.t.
  - The U.S. and Mexico are bicameral and have two legislative chambers while China has a unicameral government.
  - Many countries prefer a unicameral government system since having only one legislature means bills pass easily.


* [[https://wordsinasentence.com/unicellular-in-a-sentence/][Unicellular]]

  =an organism (such as protozoa, some algae or spores) that are made of only one cell=

  - A simple creature that has only one cell with no nucleus is called unicellular.
  - Bacteria are unicellular and tiny, making their singular-celled bodies invisible to the naked eye.
  - A protozoon is an animal-like being that is unicellular, meaning it doesn’t have more than one cell in its body.
  - Unicellular organisms have been on Earth for over three billion years and many have evolved into creatures with more than one cell.


* [[https://wordsinasentence.com/unicorn-in-a-sentence/][Unicorn]]

  =a mythical creature that resembles a horse and has one horn in the center of its head=

  - The horse-like unicorn is said to be the holder of all truth that can pierce the heart of a liar with its horn.
  - Dating back to the 5th century B.C, the first depiction of a unicorn included its white body and multi-colored horn in the center of its head.
  - Some unicorns are drawn as having wings, while most of the mythological creatures looked like horses with horned foreheads.
  - Greek writers included unicorns in natural history books because they believed these horned, flying horses were real.


* [[https://wordsinasentence.com/unicycle-in-a-sentence/][Unicycle]]

  =a bicycle with only one wheel=

  - Riding on a unicycle, the circus clown did tricks on its one wheel.
  - It is much more difficult to balance on a unicycle than it is on a two-wheeled bike.
  - The crowd cheered as the basketball player rode his one-wheeled unicycle down the court.
  - Mounting his unicycle, the magician amused his audience with his one-wheeled transportation.


* [[https://wordsinasentence.com/unidirectional-in-a-sentence/][Unidirectional]]

  =operating or moving in one direction=

  - With the unidirectional model, all the gears turn in the same direction.
  - The unidirectional microphone is only sensitive to sounds coming from one direction.
  - Using unidirectional tunnels, some of the slaves were able to escape to the north.
  - Traveling down the unidirectional road, the driver quickly realized she was driving the opposite direction down a one-way!


* [[https://wordsinasentence.com/unification-in-a-sentence/][Unification]]

  =merger or union of more than one thing=

  - Unification of the school system means that students on both sides of town will now go to the same school.
  - After the companies’ unification, workers from both factories were called to a meeting about the merger.
  - The men decided on unification so that they could work together and take out their common enemy.
  - Even though unification was the goal, it didn’t seem that the parents would ever be connected with their children again.


* [[https://wordsinasentence.com/unified-in-a-sentence/][Unified]]

  =made into one=

  - The couple made a unified decision to buy the house they both liked the best.
  - Although they didn’t always agree, the team members were unified during their games.
  - MLK lead a unified movement with the help of several smaller civil rights groups.
  - With all of the workers banning together, a unified strike will take place tomorrow.


* [[https://wordsinasentence.com/unifoliate-in-a-sentence/][Unifoliate]]

  =having only one, compound leaf=

  - Because the plant’s leaf was single, it is described as unifoliate.
  - After pulling the single leaf off the stem of the unifoliate branch, the scientist studied the foliage.
  - The gardener explained that some plants are unifoliate and only have one, compound leaflet.
  - A single leaf on each stem made the unifoliate plant look unique.


* [[https://wordsinasentence.com/uniform-in-a-sentence/][Uniform]]

  =identical clothing worn by people of the same workplace, organization, or school=

  - The student wished she could ditch school uniform and show her unique clothing style.
  - Noticing the man’s police uniform and badge, the pedestrian waived to him for help.
  - Everyone who works at the restaurant must wear the same navy blue uniform.
  - I had hoped my new uniform would be red, but instead my boss ordered khaki pants and green shirts for everyone.


* [[https://wordsinasentence.com/uniformity-in-a-sentence/][Uniformity]]

  =the state of overall sameness or being identical in every way=

  - Uniformity between the twins’ clothes made it to where even their own parents couldn’t tell them apart.
  - The uniformity of the neighborhood’s cookie-cutter houses made it hard to tell whose house was whose.
  - School principals believe that uniformity of the students’ clothing can reduce bullying since all the children will look identical.
  - Bringing uniformity to the way we bake our cupcakes will sell cupcakes to customers who value sameness.


* [[https://wordsinasentence.com/unify-in-a-sentence/][Unify]]

  =to unite things or make pieces whole=

  - Giving a speech about how important it is for all races to work together, MLK was able to unify the groups.
  - The company’s CEO called a multi-department meeting to talk about ways to unify each section and work together.
  - A war was fought to unify the north and south into one nation again.
  - The couple decided that their marriage was too fractured to unify and ended up getting a divorce last year.


* [[https://wordsinasentence.com/unilateral-in-a-sentence/][Unilateral]]

  =performed only by one side=

  - Since the legislators were slow to act on the issue, the president used his executive powers to make a unilateral solution.
  - Too often, my husband makes unilateral decisions without seeking my advice.
  - The president did not know his authority was unilateral and that he needed the board’s consent to make company changes. 
  - While the Democrats favored the unilateral proposal, the Republicans strongly opposed the plan.
  - My headache is unilateral because the pain only occurs on one side of my head. 
  - After Dick had a stroke, he suffered from unilateral paralysis and could only control the muscles on the right side of his body. 
  - The shareholders did not agree with the company leaders’ unilateral decision to merge with a bigger firm.


* [[https://wordsinasentence.com/unimaginable-in-a-sentence/][Unimaginable]]

  =something that is difficult to believe=

  - After the devastating storm left the area, people were left with unimaginable damage.
  - When the baby was diagnosed with cancer, her family felt the unimaginable had happened.
  - Onlookers found it unimaginable that a mermaid could climb out of the sea and walk on land.
  - Unimaginable amounts of money are spent on sending bombs to other countries.


* [[https://wordsinasentence.com/unimpeachable-in-a-sentence/][Unimpeachable]]

  =completely trustworthy and reliable=

  - Most of the voters saw the candidate as unimpeachable and completely trusted his every word.
  - At first the president seemed unimpeachable, but recently there have been reports that add a shadow of doubt to his trustworthiness.
  - The unimpeachable athletes appeared to be both flawless and faultless.
  - Although many believe the judge to be both blameless and unimpeachable, some people think she is not as honorable as she seems.


* [[https://wordsinasentence.com/unimpeded-in-a-sentence/][Unimpeded]]

  =free of any restrictions or obstacles=

  - After getting a permit from the city, the unimpeded workers were free to build the home.
  - It took some time to get approval, but now my company is unimpeded and can take on as many contracts as possible.
  - The unimpeded stream flowed freely through the woods and was free of any obstacles.
  - Moving down the field, the football player ran unimpeded for a fifty-yard touchdown.


* [[https://wordsinasentence.com/unimportant-in-a-sentence/][Unimportant]]

  =trivial and of no great concern=

  - The janitor’s job might seem unimportant, but the school could not function without this essential position.
  - As an overthinker, the woman spends lots of time worrying about things that are unimportant.
  - Spending several hours in the unimportant meeting was a total waste of the work day.
  - I usually skip through the unimportant commercials until I get to the vital programming, like the news.


* [[https://wordsinasentence.com/uninhabitable-in-a-sentence/][Uninhabitable]]

  =not able to be lived in or on=

  - Because it is near a nuclear test site, the island is now uninhabitable by people.
  - The moldy home was uninhabitable and had to be demolished by the state to keep people from living there.
  - After the earthquake, many of the ruined homes were made uninhabitable.
  - Most of the dense forest area was inhabitable to people, but home to many different animals.


* [[https://wordsinasentence.com/uninhabited-in-a-sentence/][Uninhabited]]

  =having no people living there=

  - Jaco Island is uninhabited because the locals think it is sacred land that no one should live on.
  - Many parts of the rainforest that were once uninhabited are now hold villages.
  - The wild, uninhabited land is reserved and houses cannot be built there.
  - Because of the icy weather and frozen land, much of Alaska is empty and uninhabited.


* [[https://wordsinasentence.com/uninhibited-in-a-sentence/][Uninhibited]]

  =outgoing; not reserved=

  - The camp counselor encouraged uninhibited participation and wanted the campers to be spontaneous.
  - Uninhibited conversations are encouraged during therapy since candid talk can help you process your feelings.
  - The actress was the most uninhibited person on stage and her open and unrestrained nature always shined through.
  - Young children are usually uninhibited and naturally outgoing.


* [[https://wordsinasentence.com/uninitiated-in-a-sentence/][Uninitiated]]

  =without specific knowledge or experience=

  - The uninitiated students had trouble understanding the advanced concepts of physics.
  - Because the new choir was uninitiated, they had a hard time singing the difficult song.
  - For the uninitiated, the piano piece was too challenging to attempt.
  - The only people who applied for the job were uninitiated workers with no background in sales.


* [[https://wordsinasentence.com/unintelligible-in-a-sentence/][Unintelligible]]

  =making no sense; not understandable=

  - The babbling baby let out an unintelligible wail as she toddled down the hallway.
  - Wearing a long turban and speaking a language that was unintelligible to the natives, the mysterious woman seemed to have appeared out of nowhere.
  - Twins sometimes have a secret language only they understand that is unintelligible to others.
  - The boy’s unintelligible handwriting looked like chicken scratch, causing him to receive poor grades in school.


* [[https://wordsinasentence.com/unintended-in-a-sentence/][Unintended]]

  =accidental; not intentional=

  - Testifying in court caused an unintended consequence to the salesman’s reputation.
  - Although the insult was unintended, the boy’s jokes hurt his friend’s feelings.
  - The medicine can cause unintended side effects that are worse than the original problem.
  - Since the pregnancy was unintended, the young woman was scared about her future.


* [[https://wordsinasentence.com/uninterested-in-a-sentence/][Uninterested]]

  =not concerned; indifferent=

  - Although she acts uninterested, the teenager really does enjoy spending time with her younger sister.
  - The boy is uninterested in school and rarely does his homework or takes part in class.
  - At first the kid was uninterested in boxing, but now he enjoys sparring in the ring.
  - The uninterested look on the reader’s face let the librarian know she might need a more engaging book.


* [[https://wordsinasentence.com/union-in-a-sentence/][Union]]

  =a marriage=

  - The elderly couple’s union had lasted for over fifty years.
  - Even though they never officially tied the knot, the couple had a strong union.
  -  Shortly after their union, the newlyweds decided to purchase a new home.
  - Standing as a symbol of the couple’s union, the husband placed the ring on his bride’s finger.


* [[https://wordsinasentence.com/unique-in-a-sentence/][Unique]]

  =without match; distinct=

  - Kate’s unique hairstyle captured everyone’s attention.
  - In order for a movie to interest me, it must have a unique plot and tell a story I have never heard. 
  - The shirt is not unique because the manufacturer has created millions of shirts just like it.
  - Because the restaurant sells food items from twelve different countries, it has a unique menu.


* [[https://wordsinasentence.com/unison-in-a-sentence/][Unison]]

  =the condition of being in agreement or occurring at the same time=

  - Because the singers sung in unison, it sounded like only one person was performing.
  - Pay attention and cut when I cut because if the wires are not sliced in unison the bomb will explode. 
  - As if they were part of a mirror image, the twin boys scratched their heads in unison.
  - Twins think alike so it is not uncommon for them to respond to questions in unison.


* [[https://wordsinasentence.com/unit-in-a-sentence/][Unit]]

  =one part of component=

  - The complex has over sixty apartments, but only one unit is available to rent this month.
  - Each unit in the hospital has its own set of nurses and doctors that keep that particular section running.
  - An air conditioning unit is just one small part of the overall heating and cooling system.
  - One small unit of the police task force is being stationed at the border while the rest continue their missions.


* [[https://wordsinasentence.com/unitary-in-a-sentence/][Unitary]]

  =relating to one single unit=

  - Those unitary officers are the one allowed to stop drivers in this area.
  - A unitary counsel was created to oversee all educational decisions in the region.
  - Even though the troop is on a unitary mission, they may work on other tasks together later.
  - The unitary state is ruled by a single government that has the power to make all decisions.


* [[https://wordsinasentence.com/unite-in-a-sentence/][Unite]]

  =to join more than one thing together=

  - If we are to win the war, our soldiers must unite and face the enemy.
  - All the plant’s workers chose to unite in a protest against the company.
  - Even if we unite and are on one accord, it is very unlikely that we would win against the tough team.
  - The students were able to unite and come up with a great idea for the group project.


* [[https://wordsinasentence.com/united-in-a-sentence/][United]]

  =connected together=

  - The United States are separate but connected by a single, federal government.
  - In front of their children, the parents always take a connected and united stand.
  - Most of the villagers are united in their feelings that the increased taxes are unfair.
  - United at last, the family members were so happy to be back together again.


* [[https://wordsinasentence.com/unity-in-a-sentence/][Unity]]

  =being in harmony or full agreement=

  - During the civil rights era, protestors called for unity and peace in which blacks and whites could live together.
  - Unity of the tribes could not happen because they spoke different languages and had many different customs.
  - The female workers stood in unity and demanded equal pay for equal work on their jobs.
  - National unity is nowhere in sight since the Democratic and Republican parties can’t seem to agree on anything.


* [[https://wordsinasentence.com/universal-in-a-sentence/][Universal]]

  =relating to everyone in the world=

  - The universal remote is said to work for any kind of television set.
  - Universal ideas like love and kindness are found in books throughout the world.
  - The death penalty used to a universal punishment, but today, many countries see it as cruel and barbaric.
  - Universal greed has caused all the world’s leaders to put profit over the people.


* [[https://wordsinasentence.com/universe-in-a-sentence/][Universe]]

  =the world; earth.=

  - Many predicted the end of the universe in 1999, but the world kept on spinning.
  - Astronomers study our universe as well as the planets around us.
  - During the 1960s, Americans and the Russians were in a race to send a man orbiting around our universe.
  - Explorers continue to look for life outside our universe but have yet to find it.


* [[https://wordsinasentence.com/university-in-a-sentence/][University]]

  =a college or academic institution=

  - Professors at the university teach many different courses including biology and world geography.
  - To be accepted to the university, you must have strong grades and passing test scores.
  - Although I didn’t plan to stay on campus, I visited the university dorm just to see if I would be comfortable living and studying there.
  - The cost of attending a private university is unaffordable for most first-year college students.


* [[https://wordsinasentence.com/unjust-in-a-sentence/][Unjust]]

  =not fair, just or right=

  - He believed the sentence was unjust and planned to appeal.
  - When they assumed she didn’t study for the exams, her parents proved they were unjust.
  - An unjust system could never rule fairly.
  - Our teacher was unjust in giving out equal punishment.


* [[https://wordsinasentence.com/unkempt-in-a-sentence/][Unkempt]]

  =not clean or tidy=

  - An unkempt appearance was the least of the homeless man’s worries. 
  - Since Jack has not had a hair cut in six months, he looks somewhat unkempt. 
  - Excessive littering has turned this once clean soccer park into an unkempt field.
  - After being locked in the dungeon for two years, the prisoner looked pale and unkempt.
  - The unkempt garden was filled with weeds.
  - As soon as the cleaners walked into the unkempt house, they knew it would take all day to clean the residence. 
  - Because the neglected children had been denied food and locked in an attic for a week, they were unkempt and hungry. 


* [[https://wordsinasentence.com/unkind-in-a-sentence/][Unkind]]

  =mean; cruel=

  - Girls on the playground often say cruel and unkind things to those they see as weak.
  - Cinderella’s unkind sisters made her do all of the chores and would not let her go to the ball.
  - The witch came across as unkind, but she simply didn’t know how to show her goodness.
  - We practice niceness, so being unkind is not allowed in our classroom.


* [[https://wordsinasentence.com/unknown-in-a-sentence/][Unknown]]

  =something that is still a mystery or uncertain=

  - An unknown substance was found on the bottom of the scientist’s fossil discovery.
  - The name of the victim is unknown since he had no driver’s license on him at the time of his death.
  - An unknown creature has washed up on the shore and scared several of the villagers.
  - The cause of the plague used to be unknown, but now science has proven that it was carried by fleas on rats.


* [[https://wordsinasentence.com/unleash-in-a-sentence/][Unleash]]

  =to set free from a restraint=

  - After I went to unleash the dog who had been chained to his cage for years, the dog attacked the first person it saw and ran away.
  - Following our trip to the park, I will unleash the dog once we get inside the fence so it can run free.
  - Since the owner decided to unleash her dog on the street, it was only a matter of minutes before it ran a few hundred feet in front of a car.
  - When the criminal darted into an abandoned building from the police, the officer warned that if he didn’t come out he would unleash the trained dog to capture him.


* [[https://wordsinasentence.com/unless-in-a-sentence/][Unless]]

  =used to show an exception=

  - Unless you turn in your homework, you will not pass this course.
  - The attorney is prepared to take the case all the way to trial unless a plea deal is struck.
  - Unless you pay your fee by tomorrow, you will not be allowed to attend camp.
  - Unless there has been a change in the forecast, it will rain all of tomorrow afternoon.


* [[https://wordsinasentence.com/unlike-in-a-sentence/][Unlike]]

  =different from; dissimilar=

  - Unlike her glamorous mother, the tomboy preferred tennis shoes over heels.
  - Unlike its neighbor to the south, Canada has universal health care.
  - It is very unlike my mother not to call me when she gets home from work.
  - Unlike Sacramento, Seattle does not have an NBA team.


* [[https://wordsinasentence.com/unlikely-in-a-sentence/][Unlikely]]

  =not very likely to happen; questionable=

  - It is very unlikely that I will win the lotto, but I still like to play.
  - Dodging the hurricane was unlikely, however the homeowners still held out hope that it would die down before reaching the shore.
  - The police officer explained that it is very unlikely for a drug dog to hit on a vehicle and not find any drugs there.
  - The court found it unlikely that the suspect would take a plea deal, but offered one anyway.


* [[https://wordsinasentence.com/unload-in-a-sentence/][Unload]]

  =to unpack or drop off=

  - Movers helped me unload my furniture and even aided me in putting the beds back together.
  - A special ramp is needed to unload the rest of the heavy boxes from the back of the truck.
  - My grandmother likes to unload all her problems on me when I come over to visit on Saturdays.
  - Requesting several strong men to help unload the trailer, the farmer tried to think of an easier way to unpack all the goods.


* [[https://wordsinasentence.com/unlucky-in-a-sentence/][Unlucky]]

  =having or bringing bad luck or fortune=

  - Friday the 13th is said to be an unlucky day that brings bad fortune.
  - The unlucky bingo player missed the big jackpot by only one number.
  - Although black cats are considered unlucky, my kitty Midnight has brought me nothing but good days.
  - The business man couldn’t decide if he was just unlucky or simply destined to fail.


* [[https://wordsinasentence.com/unmarred-in-a-sentence/][Unmarred]]

  =free from blemishes or stains=

  - Babe Ruth’s ball was surprisingly unmarred, having almost no marks or blemishes.
  - The beautiful statue would have remained unmarred if angry villagers hadn’t scratched and beat it.
  - Although the ring was advertised as unmarred, it had a few scratches on the outside of the band.
  - Fresh drinks were poured into shiny, unmarred glasses that didn’t have a single scratch on them.


* [[https://wordsinasentence.com/unmentionable-in-a-sentence/][Unmentionable]]

  =forbidden or taboo=

  - After my father left my mother, his name was unmentionable in our home.
  - Stillbirth is a common occurrence but an unmentionable subject in most doctors’ offices.
  - The racist word was ruled unmentionable and outlawed by both of my parents.
  - In many cultures, rape is unmentionable and must be dealt with internally without family discussion.


* [[https://wordsinasentence.com/unmistakable-in-a-sentence/][Unmistakable]]

  =unique; easily recognizable=

  - The smell of rotting flesh is unmistakable and can even be recognized by those who have never been around a dead body before.
  - Bright red hair and deep freckles made the model unmistakable in the sea of people.
  - The sound of fear in the victim’s voice was unmistakable as she told her story to the judge.
  - Chocolate has a unique and unmistakable scent that can tempt even the strongest dieter.


* [[https://wordsinasentence.com/unmitigated-in-a-sentence/][Unmitigated]]

  =in its entirety; complete=

  - Since we raised over a million dollars during the telethon, we considered the fundraiser to be an unmitigated success.
  - The plane crash was an unmitigated catastrophe that ended the lives of nearly two hundred people. 
  - When the bank robber killed the hostages, it was obvious the negotiation had been an unmitigated disaster.
  - The banquet will be an unmitigated fiasco if the caterer does not arrive soon.


* [[https://wordsinasentence.com/unnatural-in-a-sentence/][Unnatural]]

  =abnormal; strange=

  - The peculiar woman’s bright orange hair looked so unnatural.
  - It sounds strange when the singer raises her voice to an unnatural pitch.
  - The eccentric woman’s family knows she acts weirdly, but they ignore most of her unnatural behavior.
  - Talking with an unnatural southern accent, the New Jersey native seemed bizarre to her new neighbors.


* [[https://wordsinasentence.com/unnecessary-in-a-sentence/][Unnecessary]]

  =something that is not needed=

  - Checking on her baby all through the night was unnecessary, but the woman felt better if she did it anyway.
  - Buying new curtains is unnecessary since we already have nice blinds hanging from the windows.
  - The husband found ironing clothes unnecessary, but his wife refused to let him leave the house with a wrinkled shirt.
  - A large moving truck is unnecessary, but we might need a small trailer to load the couch onto.


* [[https://wordsinasentence.com/unnerve-in-a-sentence/][Unnerve]]

  =to make someone lose confidence; to discourage=

  - In an effort to unnerve his foe, the politician brought up some of the less honorable things he had done in the past during their debate.
  - Many ancient armies loosed a mighty war cry before a charge in an effort to unnerve their foes and make them lose morale.
  - The horrors of chemical warfare were quite likely to unnerve troops during the Great War, as no one wanted to suffer from a noxious poison.
  - My school rival tried to unnerve me during my class presentation, but I ignored him and continued to give my speech with confidence.


* [[https://wordsinasentence.com/unnerving-in-a-sentence/][Unnerving]]

  =causing fear, anxiety, or loss of courage=

  - As her voice trembled and hands shook, the speaker realized just how unnerving it can be to talk to such a large crowd.
  - Basic training was unnerving for the soldier’s worried family since they weren’t allowed to see or talk to him for several weeks.
  - The whole process of going after her rapist was unnerving and caused the victim to lose courage.
  - Eerie and unnerving noises traveled through the cabin, scaring the already anxious campers who had been telling ghost stories.


* [[https://wordsinasentence.com/unobserved-in-a-sentence/][Unobserved]]

  =not seen; overlooked=

  - The robbers went unobserved through the forest, never being spotted by the frantic search party.
  - An unobserved runner was almost hit by a distracted driver speeding by.
  - Several distant planets went overlooked for years until a new telescope made them viewable.
  - The darkness of the alley allowed the robber to commit his crime unobserved.


* [[https://wordsinasentence.com/unobtrusive-in-a-sentence/][Unobtrusive]]

  =not obvious=

  - The reclusive man wanted to be buried in an unobtrusive area of the cemetery so people would not walk around his grave.
  - Since I do not trust my daughter, I have unobtrusive cameras in my house so I can secretly monitor her behavior when I am not home.
  - Burglars will have difficulty locating the unobtrusive device that controls the home’s security system. 
  - Gail came close to missing her interstate exit because of the unobtrusive sign that was partially hidden by the tree branches.
  - Although the famous actor hoped to remain unobtrusive in the movie theater, he was recognized by several of his fans.
  - I need a covering to make the cords from my computer and printer unobtrusive so my office will look neater.
  - While the celebrity travels with a security team, she usually asks her bodyguards to walk in an unobtrusive manner behind her. 


* [[https://wordsinasentence.com/unofficial-in-a-sentence/][Unofficial]]

  =not for sure or officially confirmed by the organization in charge=

  - It’s still unofficial, but I am pretty sure the company chose me for the job.
  - An unofficial number of children have been reported missing, but we have not received exact numbers from the police.
  - The election was called on an unofficial count and we will have to wait until morning for the final results.
  - A quick, unofficial count revealed that several of the stores products are missing from the shelves.


* [[https://wordsinasentence.com/unorthodox-in-a-sentence/][Unorthodox]]

  =nontraditional=

  - Not wearing the school uniform in the Christian school is viewed as unorthodox behavior.
  - My husband has an unorthodox habit of eating spaghetti with a spoon. 
  - Despite Mitch’s unorthodox upbringing in the monastery, he was still able to socialize well in a public school environment.
  - I left the church after the minister started preaching unorthodox sermons about disliking people of different races.


* [[https://wordsinasentence.com/unpalatable-in-a-sentence/][Unpalatable]]

  =unpleasant to the taste=

  - Forgetting the sugar caused the baker to create a fine-looking but unpalatable cake.
  - The sizzling fajitas looked delicious, but one bite proved them unpalatable. 
  - Being unpalatable helps the monarch butterfly avoid being eaten by predators. 
  - The unpalatable steak might have been edible if it had been cooked longer.   


* [[https://wordsinasentence.com/unparalleled-in-a-sentence/][Unparalleled]]

  =without comparison=

  - The hotel is the city's best because it offers unparalleled services not provided by other area hotels.
  - Because James’ ability to sell cars is unparalleled, he has been named salesman of the month five times in a row.
  - The athlete earns over five million dollars a year because of his unparalleled skill in basketball. 
  - With an unparalleled number of tourists attending the Olympics, the city is concerned about not having enough hotel rooms. 


* [[https://wordsinasentence.com/unperceived-in-a-sentence/][Unperceived]]

  =not noticed or recognized by the senses (sight, smell, taste, touch, hearing.)=

  - The smell of the fire blazing through their home went unperceived by the sleeping family.
  - The deep wound was unperceived by the nurse, but was found during a deeper exam.
  - An unperceived flaw in the computer was not noticed by the inventor, but was discovered later by a hacker.
  - Unperceived treasures lay hidden just beneath the sand that the clueless pirates were sitting on.


* [[https://wordsinasentence.com/unperturbed-in-a-sentence/][Unperturbed]]

  =not concerned, worried, or disturbed=

  - The unperturbed husband did not seem to care about his cheating wife or her string of affairs.
  - During the traffic crash, the drunk driver was unperturbed and wasn’t worried about his injuries or going to jail.
  - Unperturbed by his recent job loss, the confident nurse was sure he would find a new gig soon.
  - Didn’t you find it strange that the widow seemed unperturbed and unbothered by his wife’s death?


* [[https://wordsinasentence.com/unpleasant-in-a-sentence/][Unpleasant]]

  =unsavory, distasteful, or disgusting=

  - The unpleasant smell of rotten eggs crept out of the trash and hit my nose like a ton of bricks.
  - I gagged as I tried to pretend that my mom’s meatloaf didn’t have an unpleasant taste.
  - Although the smell of the perfume was unpleasant, it wasn’t the most revolting thing I had every smelled.
  - Biting into the burger, the unsavory and unpleasant taste was the first sign that the meat might have been ruined.


* [[https://wordsinasentence.com/unprecedented-in-a-sentence/][Unprecedented]]

  =previously never experienced or seen=

  - Before the storm, there was an unprecedented demand for food supplies that left many stores empty.
  - Since Mrs. Johnson did not have high expectations for Hank, she was shocked by his unprecedented interest in his math grade.
  - The Internet has erased distance and given people unprecedented access to each other.
  - Even the police department is shocked by the unprecedented amount of crime occurring in our small town. 
  - The queen’s reign of fifty years is unprecedented because no monarch has ever been on the throne for so long.
  - When oil refineries suddenly halted production, gas prices reached unprecedented rates that shocked economists.
  - Jane took an unprecedented step in history when she became the first female firefighter in our town.


* [[https://wordsinasentence.com/unpredictable-in-a-sentence/][Unpredictable]]

  =describes something that is uncertain and not able to be predicted or foretold=

  - The unpredictable weather was sunny one day and rainy the next.
  - Because her behavior was so unpredictable, the woman’s family never knew if she would be happy or sad.
  - Unpredictable test questions meant that teachers couldn’t predict if their students would do well or not.
  - Crime in the area is unpredictable and varies from no offenses to robbery and murder.


* [[https://wordsinasentence.com/unprepossessing-in-a-sentence/][Unprepossessing]]

  =looking plain or ordinary=

  - The unprepossessing bookshelf looked like any other bookstand, giving no hint of what lay behind its novels.
  - An unprepossessing rug, shaggy and plain, hid its magic beneath its ordinary-looking tassels.
  - A wardrobe makeover would help the young woman replace her outdated and unprepossessing clothing in an attractive collection.
  - The gate was rusty and unprepossessing, its lack of appeal making it a bad fit for the lovely mansion it led to.


* [[https://wordsinasentence.com/unpretentious-in-a-sentence/][Unpretentious]]

  =not attempting to impress others with intelligence, money, style, importance, etc; modest=

  - The girl next door portrayed herself in an unpretentious way so that she was beautiful without striving for attention.
  - Her unpretentious niece would wear simple clothing and she would do her own hair which made her friends jealous of her.
  - As the upstanding young man entered the room, his unpretentious nature led everyone to believe that he did not take time to consider his appearance
  - When the nonprofit club catered to helping the homeless, the unpretentious club donated money and time anonymously.


* [[https://wordsinasentence.com/unprincipled-in-a-sentence/][Unprincipled]]

  =lacking a moral code=

  - The unprincipled banker failed to handle the transactions ethically.
  - His reputation as an unprincipled businessman stopped the contractor from getting new clients.
  - The woman’s unprincipled demeanor earned her the reputation as a scoundrel.
  - An unprincipled salesman and his bad deals caused the whole company to go under.


* [[https://wordsinasentence.com/unpromising-in-a-sentence/][Unpromising]]

  =lackluster and unlikely to gain success=

  - Her hopes of graduating were unpromising after she failed her final exams.
  - As the day week before prom approached, her odds of getting asked to the dance were particularly unpromising.
  - When votes from California and Florida came in during the 2016 presidential race, it was unpromising that Hilary Clinton would win.
  - When the investor saw that his stocks dropped by 200%, he knew that his chances of making a profit were unpromising.


* [[https://wordsinasentence.com/unpropitious-in-a-sentence/][Unpropitious]]

  =not favorable of likely to produce a good result=

  - The candidate’s unpropitious speak is unlikely to win him any votes.
  - Off to an unpropitious start, it doesn’t seem if the business will make enough money to keep its doors open.
  - With unpropitious weather approaching, it is unlikely that we will be able to mow all of the lawns today.
  - My mother-in-law arrived at an unpropitious time and caused a huge argument between my husband and me.


* [[https://wordsinasentence.com/unproven-in-a-sentence/][Unproven]]

  =not proved=

  - Your alien abduction claim is unproven and seems extremely unlikely.


* [[https://wordsinasentence.com/unpunctual-in-a-sentence/][Unpunctual]]

  =not happening or doing something on time=

  - Unpunctual guests were not allowed to enter after arriving at the event two hours late.
  - The unpunctual student was given detention for coming to class late.
  - Always unpunctual, the frazzled White Rabbit hurried around Wonderland in a panicked state.
  - Our neighborhood mailman is always unpunctual and rarely brings the mail on time.


* [[https://wordsinasentence.com/unquestionably-in-a-sentence/][Unquestionably]]

  =certain; not able to be disputed=

  - The doctor will unquestionably perform the surgery, the only thing in question is the date.
  - Michael Jordan is unquestionably the best basketball player to ever live.
  - The battle was unquestionable a victor for the Union, however many lives were lost from both sides.
  - Doctors confirmed that drinking too many energy drinks was unquestionably linked to the man’s untimely death.


* [[https://wordsinasentence.com/unravel-in-a-sentence/][Unravel]]

  =to cause something to separate or come apart=

  - The tassels on the end of the rug have started to unravel and will need to be replaced.
  - After months of investigating, police finally had proof that the suspect was lying and his tale began to unravel.
  - We had to unravel the rope to make it long enough to reach across the bridge.
  - Clues from the crime scene may help us unravel the mystery and solve the case.


* [[https://wordsinasentence.com/unreal-in-a-sentence/][Unreal]]

  =unbelievable, incredible=

  - Winning the lottery is an unreal experience that most will only dream of.
  - Traveling at ungodly speeds, the racecar zoomed through the streets in an unreal fashion.
  - Walking up the mansion gates, the reporter couldn’t help but stare at the unreal the estate.
  - The model’s incredible skin seemed unreal and glowed with a brightness that the agent had never seen before.


* [[https://wordsinasentence.com/unreasonable-in-a-sentence/][Unreasonable]]

  =extreme or excessive=

  - The costs to rent a car in the city are unreasonable and make buying one seem cheaper.
  - Although the hotel’s rates are unreasonable, I like the location and usually end up paying their excessive fees.
  - Many of the requirements to work for the company seem unreasonable, especially the lie detector and hair follicle tests.
  - The prices of the knockoff purses are unreasonable since they are set just as high as the name brand ones.


* [[https://wordsinasentence.com/unredressed-in-a-sentence/][Unredressed]]

  =refers to a wrong or injustice that has not been righted=

  - The girl’s unredressed murder still bothers her family since the killer has never been caught.
  - The bill is still unredressed and the company is yet to pay the builder for finishing his home.
  - Several unredressed tragedies have happened in the city with no one being held responsible.
  - The unredressed injustice was ignored by most news outlets, with no one seeming to care about what went wrong.


* [[https://wordsinasentence.com/unrelenting-in-a-sentence/][Unrelenting]]

  =refusing to yield or compromise=

  - The unrelenting storm continued to destroy the area and seemed as if it would never end.
  - My mother’s stare was unrelenting, her never-ending gaze always letting me know that she would not give in.
  - Unrelenting text messages kept pouring in from the woman’s stalker who refused to give up.
  - Ninety minutes of unrelenting training left the boxer extremely tired.


* [[https://wordsinasentence.com/unreliable-in-a-sentence/][Unreliable]]

  =not able to be trusted or depended on=

  - Since Ms. Watson proved she was unreliable to do her job, I would never call on her when I needed a substitute.
  - As a constant liar, the brother become an unreliable source for his mother to ask him questions about what happened.
  - After several new employees would arrive tardy to work due to car troubles, I realized I would never hire an applicant if they had unreliable transportation.
  - My unreliable friend forgot to pick me up for work as she had promised, but I should have expected that since this has happened in the past.


* [[https://wordsinasentence.com/unremitting-in-a-sentence/][Unremitting]]

  =continuing without any type of interruption or decrease in intensity=

  - Jim and Edith could not agree upon a divorce settlement because of their unremitting anger towards each other.
  - During the summer months, the unremitting heat always causes a massive increase in power bills.
  - Several months before the election, the mayor’s political rival launched an unremitting campaign against him.
  - After Barbara realized her knee pain was unremitting, she decided to have surgery to avoid suffering forever. 
  - Recovering from heart surgery seemed to be an unremitting struggle for my grandfather.
  - The man eventually confessed during the detective’s unremitting questioning.
  - Because of unremitting pressure from the city council, the police chief finally stepped down from office.


* [[https://wordsinasentence.com/unrepentant-in-a-sentence/][Unrepentant]]

  =showing no regret for one has done wrong=

  - Even after being sentenced for his crimes, the smug kidnapper was unrepentant.
  - My son is always unrepentant for his wrongdoing, even when he is caught red-handed.
  - The unrepentant shoplifter refused to admit what she did was wrong.
  - Making excuses for the affair, the unrepentant husband refused to admit the affair was his fault and not caused by his wife.


* [[https://wordsinasentence.com/unrequited-in-a-sentence/][Unrequited]]

  =not given back=

  - I started to cry when I learned my love was unrequited.
  - After the boy discovered his adoration was unrequited, he attempted suicide.
  - Many songs have been written about unrequited love and its related heartache. 
  - When the actor announced his marriage, thousands of females realized their love would remain unrequited forever.


* [[https://wordsinasentence.com/unrest-in-a-sentence/][Unrest]]

  =a state of uneasiness, restlessness, or agitation=

  - Unrest in the country began to grow after the leader began to censor what the newspapers could publish.
  - Chaos and unrest filled the city as the number of shooting victims continued to rise.
  - Constant arguments between the husband and wife caused a feeling of unrest to move through the house.
  - Fighting and unrest in the war-torn Middle East has gone on for decades.


* [[https://wordsinasentence.com/unruffled-in-a-sentence/][Unruffled]]

  =composed; self-controlled=

  - Even when the children won’t listen to her, the calm teacher remains composed and unruffled.
  - The speaker tried to remain unruffled as the rude crowd yelled insults at him.
  - My husband was unruffled by the break-in, but it scared me senseless!
  - I hoped that my unruffled appearance would convince the interviewer that I could remain calm under pressure.


* [[https://wordsinasentence.com/unruly-in-a-sentence/][Unruly]]

  =disruptive behavior that is wild and out of control=

  - Police were sent to stop the unruly drunks from throwing bottles at cars passing by.
  - Although they were a little unruly, the rowdy teenagers insisted they didn’t want any trouble.
  - Angered and unruly fans blocked the stadium exit when their team lost the playoff game.
  - The principal had to be called to calm the unruly freshman who were throwing paper airplanes and running all around the classroom.


* [[https://wordsinasentence.com/unsafe-in-a-sentence/][Unsafe]]

  =dangerous; risky=

  - Moving into the unsafe neighborhood required the renters to get both a gun and a security system.
  - Even though riding a motorcycle can be unsafe, I enjoy the thrill of barreling down the highway on a Harley.
  - The unsafe medicine was removed from stores after it started making people sick.
  - Our father explained that riding in a boat without a life jacket is not smart but unsafe.


* [[https://wordsinasentence.com/unsatisfactory-in-a-sentence/][Unsatisfactory]]

  =not satisfying or good enough=

  - An unsatisfactory number of people signed up for the play so it had to be cancelled.
  - The assistant was told that her work was poor and unsatisfactory during her meeting with her unhappy boss.
  - I thought I would enjoy eating at the restaurant, but instead found the food bland and the service unsatisfactory.
  - The student failed his end of course test and received a score of unsatisfactory.


* [[https://wordsinasentence.com/unsatisfied-in-a-sentence/][Unsatisfied]]

  =not pleased or happy with something=

  - The editor was unsatisfied with the writer’s work and asked her to make several changes.
  - Because there was little food left on the buffet, I left the restaurant feeling irritated and unsatisfied.
  - Even though I was unsatisfied with my housekeeper’s cleaning skills, I decided to let her keep her job.
  - The caring nurse worked hard to make sure that her patients were content and never unsatisfied.


* [[https://wordsinasentence.com/unsavory-in-a-sentence/][Unsavory]]

  =unpleasant to smell or taste=

  - Catching a whiff of the unsavory smell, Hannah quickly remembered that she had forgotten to take out the trash before leaving for vacation.
  - Although it had an unsavory taste, the starving peasant scarfed down the motley soup. 
  - Brown and lumpy, the porridge looked unsavory but the taste was quite delectable. 
  - When asked to give a review of the unappetizing diner, the only word she could think of to describe the fish was ‘unsavory’.


* [[https://wordsinasentence.com/unscathed-in-a-sentence/][Unscathed]]

  =untouched or not damaged=

  - Despite the vase’s tumble from the shelf, it is unscathed. 
  - It was a miracle Jim survived the car wreck completely unscathed.
  - Somehow, the lone soldier made it across enemy lines unscathed.
  - It was strange how the fire destroyed most of the city but left the church unscathed. 
  - In the trashcan, the homeless man found unscathed cans of food that were suitable for eating.
  - Jan hoped her expensive furniture would make it through the cross-country move unscathed.
  - While my home remained unscathed after the hurricane, my neighbor’s house was destroyed.


* [[https://wordsinasentence.com/unscrupulous-in-a-sentence/][Unscrupulous]]

  =unconcerned about doing what is right=

  - The unscrupulous teacher offered to raise her student’s grade if he gave her one hundred dollars.
  - When the unscrupulous insurance salesman sold me the policy, he did not tell me it would not be active for six months.
  - The unscrupulous drug company lied about the benefits of its new drug.
  - During the experiment, the unscrupulous scientist conducted drug tests on monkeys.
  - The unscrupulous ticket scalper sold me fake tickets.
  - Last month, several unscrupulous stockbrokers used insider knowledge to make gigantic personal trades.
  - My neighbor is an unscrupulous woman who pretends to be a psychic in order to con trusting people.


* [[https://wordsinasentence.com/unseemly-in-a-sentence/][Unseemly]]

  =not in good taste=

  - William acted in an unseemly manner when he wore his pajamas to his mother’s funeral.
  - According to psychiatrists, child predators have an unseemly interest in young people.
  - It will look unseemly if you file an insurance claim on the day your husband is murdered.
  - When my mother remarried two days after her divorce was finalized, everyone said her behavior was unseemly.


* [[https://wordsinasentence.com/unseen-in-a-sentence/][Unseen]]

  =hidden or out of sight=

  - Waldo remained unseen in the picture until one of the kids finally spotted him.
  - Unseen forces were working behind the scenes to rig the election.
  - The robber stayed hidden in the alley, remaining unseen until the cops had driven past.
  - Even though you can’t view them with the naked eye, unseen germs can still make you sick.


* [[https://wordsinasentence.com/unselfish-in-a-sentence/][Unselfish]]

  =generous and willing to put other needs or wants before one’s own=

  - The kidney donor’s unselfish gift helped the sick man stay alive for several more years.
  - Giving a child up for adoption is an unselfish act since the mother often cares more about her child’s needs than her own feelings.
  - My teammate was unselfish and gave up her chance at a win to come back and help me up when I fell.
  - The unselfish gambler shared most of her winnings with her family members and those who were in need.


* [[https://wordsinasentence.com/unsheathed-in-a-sentence/][Unsheathed]]

  =pulled a knife or sword out from its covering=

  - The warrior unsheathed the blade, raised it above his head and plunged it towards the enemy.
  - After he unsheathed his large sword, the soldier prepared to sharpen it for battle.
  - The cowboy unsheathed his knife and threatened the town sheriff with his weapon.
  - Samurai fighters were trained to use their shard swords once they had unsheathed them form their coverings.


* [[https://wordsinasentence.com/unsightly-in-a-sentence/][Unsightly]]

  =ugly; hideous=

  - Cinderella’s unsightly stepsisters were so ugly that their own reflections scared them.
  - The unsightly witch was covered with hairy warts that only added to her unattractiveness.
  - Unsightly stains covered the dingy carpet, making it look nasty and uninviting.
  - When the bandit flashed his unsightly smile, his crooked green teeth spooked his horse.


* [[https://wordsinasentence.com/unsolicited-in-a-sentence/][Unsolicited]]

  =not welcome or invited=

  - The new mother wished she could stop family members from giving unsolicited advice on how to care for her baby.
  - When unsolicited applications come into the store, we stick them in a file and look at them when we are hiring.
  - The man set up his email so that unsolicited emails and sales messages would go directly to a trash folder.
  - An unsolicited salesman arrived at our door out of the blue in an attempt to sell us an overpriced vacuum cleaner.


* [[https://wordsinasentence.com/unstable-in-a-sentence/][Unstable]]

  =not balanced or steady=

  - The unstable chair crashed to the floor when the heavy farmer leaned back in it.
  - Lately the weather has been very unsteady, with scorching heat one day and a snow storm the next.
  - The foster kid’s unstable and unsteady life caused him to live in over twenty different homes before he was twelve.
  - An unstable marriage can cause a lot of anger, especially for the partner who wishes the relationship was balanced and steady.


* [[https://wordsinasentence.com/unstinting-in-a-sentence/][Unstinting]]

  =generously giving=

  - The man showed his unstinting support of the business by writing several checks during hard times.
  - Michelle Obama is known for her generous and unstinting support of military families.
  - Haitian hurricane survivors thanked the volunteer doctors for their unstinting commitment to the sick.
  - Mother Teresa was unstinting, giving so much of her money and time to help the poor.


* [[https://wordsinasentence.com/unsubstantial-in-a-sentence/][Unsubstantial]]

  =lacking firmness or strength=

  - It wasn’t until he fell from the cliff that the rock climber realized his unsubstantial rope was too thin for the climb.
  - The boy’s unsubstantial body does not possess enough strength to play sports.
  - A slight breeze blew through, but the unsubstantial wind wasn’t strong enough to cool us off.
  - Please do not place the heavy box on the unsubstantial table, as it might collapse.


* [[https://wordsinasentence.com/unsubstantiated-in-a-sentence/][Unsubstantiated]]

  =not supported by evidence or proof=

  - His unsubstantiated claim of being related to royalty could not be taken seriously, as he had no proof to support it.
  - While some people believe that there is an alternate reality for every possible outcome, this belief cannot be proven and is therefore unsubstantiated.
  - Many TV fans put forth unsubstantiated theories of what they think will happen in their favorite shows, but they are usually disappointed by reality.
  - While it is entirely possible that sentient aliens exist elsewhere in the galaxy, that belief is currently unsubstantiated, with no evidence to back it up.


* [[https://wordsinasentence.com/unsullied-in-a-sentence/][Unsullied]]

  =untainted; pure=

  - The groom was happy to discover his wife was an unsullied virgin on their wedding night.
  - Because the cocaine is unsullied, it will fetch a high price on the drug market.
  - Janice pays all her bills on time so her credit score is unsullied.
  - On our vacation, we went to an isolated island that was unsullied by tourist attractions. 


* [[https://wordsinasentence.com/unsure-in-a-sentence/][Unsure]]

  =not certain, having doubts about a situation=

  - Because she was unsure of the answer, the puzzled girl didn’t raise her hand in class.
  - The lost motorists were unsure of which route to take and ended up driving in circles.
  - Rachel is unsure of her pants size and will need to try a few pairs on.
  - If you are unsure of your bank balance, you can call the hotline and they will tell you the exact amount.


* [[https://wordsinasentence.com/unsurpassed-in-a-sentence/][Unsurpassed]]

  =unmatched or better than any other=

  - The chef’s culinary skill was unsurpassed by any of the mediocre cooks in the kitchen.
  - With the Falcons taking on an unsurpassed lead, it seemed as if there was no way the Patriots could come back for a win.
  - There were lots of smart children in the class, but the new student’s intelligence was unsurpassed by any of his classmates.
  - The pianist’s musical achievements are unmatched, unsurpassed by any other musician.


* [[https://wordsinasentence.com/unsuspecting-in-a-sentence/][Unsuspecting]]

  =being naïve and unaware, especially of the presence of danger=

  - The unsuspecting driver never expected to be carjacked in the middle of a busy roadway.
  - Creeping up behind the couch, the boy jumped out and scared his unsuspecting mother.
  - Unsuspecting investors who fell for the scam did not realize that they would probably never see their money again.
  - The unsuspecting tenant was shocked to find out that her new apartment was filled with black mold.


* [[https://wordsinasentence.com/untenable-in-a-sentence/][Untenable]]

  =not capable of being supported or maintained=

  - The losing debate team had an untenable argument.
  - Since Jack and Jill felt that marriage was untenable, they decided to get a divorce.
  - Atheists do not believe in the idea of a God because they see no proof of the untenable theory. 
  - Even after family therapy, the two sisters were unable to save their untenable relationship. 
  - The mayor’s proposal is untenable and will not gain the support of the city council. 
  - After the police realized Amanda’s alibi was untenable, they arrested her for murder. 
  - The medical student found it impossible to maintain his untenable habit of sleeping only three hours each night.


* [[https://wordsinasentence.com/untenanted-in-a-sentence/][Untenanted]]

  =describes a house or room that has no one living in it (vacant)=

  - Because the home is untenanted, the landlord has plenty of time to fix up the vacant property.
  - The rental company decided to raise the rent on the untenanted house before leasing it again.
  - It is likely that the house will remain untenanted until the landlord fixes some of the major issues that make it unlivable.
  - The roommates advertised the untenanted room on Craigslist in hopes that someone would move in.


* [[https://wordsinasentence.com/untidy-in-a-sentence/][Untidy]]

  =messy and unorganized=

  - A maid is needed to help the clean the untidy home.
  - Our untidy children scatter their toys and clothes all through their bedrooms.
  - The bathroom is untidy and needs to be cleaned right away.
  - Before he can go to his friend’s house, the boy must help his mother clean up the untidy living room.


* [[https://wordsinasentence.com/until-in-a-sentence/][Until]]

  =before (a specified time)=

  - I cannot go home from the hospital until my doctor gives the okay.
  - The teacher told the children that they could not leave until they cleaned up their mess.
  - Even if I get the job, I will not be able to start working until next Wednesday.
  - We will not send out our wedding invitations until we hear back from the church.


  - The president's untimely death has thrown the country into chaos.
  - An untimely frost in mid-April damaged the delicate blossoms.
  - The statement said the family mourned the untimely passing of their son, brother, father and uncle.
  - In a motion, the defendants countered that they acted fairly and that the plaintiffs’ claims were untimely because they were brought years later.


* [[https://wordsinasentence.com/unto-in-a-sentence/][Unto]]

  =an old form of the word “to”=

  - Do unto others as you would like them to do unto you.
  - “I come unto you with a sign from the Lord,” said the angel.
  - Unto whom much is given, much is required.
  - Seeing the rose petals, Romeo hoped that they would lead him unto Juliet.


* [[https://wordsinasentence.com/untoward-in-a-sentence/][Untoward]]

  =inappropriate=

  - Janice ignored the holiness of her environment and behaved in an untoward manner in church.
  - As soon as my daughter realized her peers were acting untoward at the party, she left because she did not want to get in trouble.
  - My mother told me never to accept drinks from strangers because they may have untoward intentions.
  - When my husband drinks too much, he has the tendency to act uncomfortably untoward.


* [[https://wordsinasentence.com/untrammeled-in-a-sentence/][Untrammeled]]

  =free; not limited or restricted=

  - The captured lion longed for the days when he lived untrammeled in the wide-open grasslands.
  - Allowing the dictator’s power to go untrammeled is dangerous and someone needs to put it in check.
  - The river’s untrammeled waters traveled wherever they wished until the levy was put in to restrict them.
  - As a bachelor, the footloose and fancy free man enjoyed his untrammeled life.


* [[https://wordsinasentence.com/untrue-in-a-sentence/][Untrue]]

  =false; wrong=

  - The rumor was untrue, but a lot of people believed the lie.
  - Most of the stories in the magazine are false or untrue.
  - Most of the events in the fairy tale are simply untrue.
  - Tweets about the crime are untrue and should be deleted.


* [[https://wordsinasentence.com/unused-in-a-sentence/][Unused]]

  =something new that has not been used before=

  - Please place any unused towels back on the rack for the next customer.
  - Unused ketchup packets are often thrown in the trash when they could be saved for later.
  - Because it has been unused for so many years, the ballpark looks rundown and ragged.
  - If any unused money is in your account, the bank will send you a check.


* [[https://wordsinasentence.com/unusual-in-a-sentence/][Unusual]]

  =rare or uncommon=

  - It isn’t unusual for the employee to take off from work since she likes to stay home at least once a week.
  - Unusual weather has caused most of the crops to die this summer.
  - It would be unusual for the boy to do his homework on time since he almost always waits to the last minute.
  - An unusual stone was found at the dig site and is being investigated by scientists.


* [[https://wordsinasentence.com/unusually-in-a-sentence/][Unusually]]

  =uncommonly; rarely happening=

  - Unusually hot weather meant that there was swimming but no snow in November.
  - My daughter was unusually quiet, so I knew she was doing something wrong.
  - Unusually strong winds swept through the area and knocked down many of the street signs.
  - The program was unusually slow and lasted a lot longer than most plays.


* [[https://wordsinasentence.com/unutterable-in-a-sentence/][Unutterable]]

  =to intense or horrible to be described with words=

  - The man lashed out in an unutterable rage that scared everyone in the parking lot.
  - Filled with unutterable grief, there were no words to describe how the mother felt upon losing her son.
  - As he buried his best friend Fido, the pet owner was filled with unutterable sadness.
  - Doctors in the war-torn town have witnessed unutterable things that can’t even be put into words.


* [[https://wordsinasentence.com/unvanquished-in-a-sentence/][Unvanquished]]

  =not beaten or defeated=

  - Athens agreed to leave the city unvanquished as long as Sparta agreed not to attack again.
  - The Lord agreed to leave Sodom and Gomorrah unvanquished and would not destroy the city if even a few good men were found there.
  - Unvanquished at the end of the boxing match, the champion raised his hands and celebrated another win.
  - Floyd Mayweather Jr. retired unvanquished, never having been beaten by another fighter.


* [[https://wordsinasentence.com/unveil-in-a-sentence/][Unveil]]

  =to reveal or show something=

  - Even when the children won’t listen to her, the calm teacher remains composed and unruffled.
  - During the meeting, the CEO will unveil his plans for the future of the company.
  - A big party will be held to that my parents can unveil their newest addition to the family.
  - The governor will unveil his plan for the state budget in a meeting with his team.


* [[https://wordsinasentence.com/unveiled-in-a-sentence/][Unveiled]]

  =revealed or showed something=

  - Eli Whitney unveiled a special machine to the crowd that would change the way that cotton was processed.
  - Although the whole plan wasn’t unveiled, the manager did show us the new schedule.
  - The corporation has unveiled a new product that is supposed to help women lose weight rapidly.
  - Although it has yet to be unveiled, scientists insist that they have discovered a cure for cancer.


* [[https://wordsinasentence.com/unwarranted-in-a-sentence/][Unwarranted]]

  =not deserved or justified=

  - Although the punishment seems unwarranted, the mother has the right to discipline her child as she sees fit.
  - Many believe the long jail sentence was unwarranted and should be reduced by several years.
  - Even though it is an unwarranted fear, I am always afraid of fish touching me while I swim in the water.
  - Placing cameras in the bathroom was an unwarranted invasion of privacy that cannot be justified.


* [[https://wordsinasentence.com/unwary-in-a-sentence/][Unwary]]

  =not cautious or aware of danger=

  - Although he should have been afraid of the wolf, the third pig seemed unwary.
  - The unwary gamblers lost their money when they carelessly put all their chips on 17 black.
  - The unwary woman naively never worried about getting robbed when she walked alone at night.
  - A kidnapper was easily able to lure the unwary child to his car using a bag of candy.


* [[https://wordsinasentence.com/unwavering-in-a-sentence/][Unwavering]]

  =never doubted; always steady and on course=

  - The runner was unwavering on his decision to run a marathon.
  - The teenager was trying to convince his unwavering parents to let him stay out past curfew.
  - When it came to being a successful student, she had unwavering determination.
  - The new mother was unwavering on her name choice for her newborn baby.


* [[https://wordsinasentence.com/unwieldy-in-a-sentence/][Unwieldy]]

  =hard to relocate because of its size=

  - The young boy found it difficult to hold the unwieldy ball because of its huge size.
  - Because the office paperwork has become unwieldy, the company is hiring a couple of temporary workers to help sort through the large stacks of paper.
  - The SUV is so unwieldy I cannot properly steer it on the tiny dirt road.
  - Since Frank is used to flying small jets, he found the commercial airliner a bit unwieldy under his control.
  - Did the stupid terrorist really think he was going to be able to take an unwieldy weapon like a bazooka through airport security?
  - The scrawny teenager could not push the unwieldy lawnmower around the yard.
  - Compared to the tiny mobile phones today, the original mobile phones were unwieldy and difficult to hold.


* [[https://wordsinasentence.com/unwind-in-a-sentence/][Unwind]]

  =to relax and let go of stress=

  - After a long day at work, the waitress needed to put her feet up and unwind.
  - Nothing helps me unwind like a good book and a relaxing glass of wine.
  - Meditation is a tool that can help one unwind and let go of stress.
  - My doctor insisted that my anxiety would go away if I would find relaxing activities to help me unwind.


* [[https://wordsinasentence.com/unwise-in-a-sentence/][Unwise]]

  =foolish; not smart=

  - Even though she was book smart, the foolish girl continued to make unwise money decisions.
  - The grasshopper was unwise and played all summer instead of storing food like the sensible ant.
  - By walking out in the middle of traffic, the now injured man made a very unwise decision.
  - An unwise investment caused the Wall Street millionaire to lose most of his money.


* [[https://wordsinasentence.com/unwitting-in-a-sentence/][Unwitting]]

  =ignorant or unaware=

  - The unwitting buyer has no clue what her interest rate is or how long she will have to pay on the loan.
  - Unwitting passengers sat clueless on the plane, never realizing that there was a problem with the engine.
  - At the party, the unwitting young woman was embarrassed to admit that she did not know who the Vice President was.
  - The unwitting witness was questioned several times before detectives realized that he knew nothing more about the crime.


* [[https://wordsinasentence.com/unwittingly-in-a-sentence/][Unwittingly]]

  =ignorantly or in a way that shows one is unaware=

  - Not realizing she was sick, the passenger unwittingly spread her cold to the man sitting next to her.
  - The ignorant workers unwittingly agreed to give up any money they had earned for staying late.
  - By checking yes in the box, the naïve young couple unwittingly allowed the company to search their credit report.
  - The little girl unwittingly let the sneaky kitten out the back door when she left for school.


* [[https://wordsinasentence.com/unwonted-in-a-sentence/][Unwonted]]

  =something not seen often; not ordinary=

  - Since Bill rarely came to church, even the priest was shocked by his unwonted appearance at the service.
  - Elizabeth was stunned speechless when her teenage daughter gave her an unwonted kiss in public.
  - Because Rick’s wife had just died, everyone was surprised by his unwonted happiness.
  - The paralyzed soldier is going to receive the highest military award for displaying unwonted courage.


* [[https://wordsinasentence.com/unworthy-in-a-sentence/][Unworthy]]

  =not fit or deserving=

  - The author is unworthy of the award because she copied her book from another writer’s ideas.
  - Although she was beautiful, the shy maiden felt unworthy of the king’s attention.
  - Because she lied on her application, the worker was ruled unworthy of the job.
  - The rich woman felt that the poor peasant was unworthy of marrying her son.


* [[https://wordsinasentence.com/unyielding-in-a-sentence/][Unyielding]]

  =not flexible; not easily moved or swayed=

  - My unyielding father refused to increase my allowance.
  - Because Jan has an unyielding commitment to the shelter, she will not stop working until we reach our fundraising goal.
  - We were confident in our belief the dam would remain unyielding and not fall to the pressure of the water.  
  - Even the prescription drugs could not eliminate my unyielding depression.


* [[https://wordsinasentence.com/up-to-date-in-a-sentence/][Up to date]]

  =modern; current=

  - My classroom has the most up to date computer systems out right now.
  - The buyer chose the car that had the most up to date stereo system and modern tech features.
  - Even though my phone is up to date, I hope to get an even newer one for my birthday.
  - While looking for a home, the couple decided they only wanted to view modern houses that were fully up to date.


* [[https://wordsinasentence.com/up-in-a-sentence/][Up]]

  =awake=

  - The farmer’s wife was up with the sun, making sure to feed the chickens before six each morning.
  - I was up most of the night with a bad tummy ache.
  - During his first week at boot camp, the soldier had a hard time staying up in the morning.
  - If you get up before I do, please get me out of bed.


* [[https://wordsinasentence.com/upbeat-in-a-sentence/][Upbeat]]

  =positive; cheerful=

  - The cheerleader’s upbeat attitude got the crowd excited.
  - I try to stay upbeat and refuse to let negative things bring down my mood.
  - Playing an upbeat song when you are sad can help you feel better.
  - As a motivational speaker, it was the man’s job to be cheerful and upbeat during his presentation.


* [[https://wordsinasentence.com/upbraid-in-a-sentence/][Upbraid]]

  =to harshly criticize=

  - Without a doubt, my parents are going to upbraid me for not passing any of my classes this semester.
  - Jim will often upbraid his wife for spending too much money at the mall.
  - Since Chad has already appeared in court twice for the same offense, he is expecting the judge to upbraid him before giving out a lengthy sentence.
  -  The police officer did not hesitate to upbraid the man for driving without insurance.
  - When Jack failed to meet his sales quota, he knew his boss was going to upbraid him about his lack of effort.
  - As long as I have a mother-in-law to point out my flaws, I never have to upbraid myself.
  - Ginger is afraid of her husband so she will only upbraid his faults when he is not present. 


* [[https://wordsinasentence.com/upbringing-in-a-sentence/][Upbringing]]

  =one’s childhood background=

  - The thief didn’t have the best upbringing and many of his bad habits date back to his childhood.
  - My husband and I have a similar upbringing as we both grew up in middle class families.
  - Studies suggest that your upbringing is one of the key ingredients for success as an adult.
  - Even though my friend had a very different upbringing than I did, we both had loving parents.


* [[https://wordsinasentence.com/update-in-a-sentence/][Update]]

  =to keep someone informed=

  - The doctor assured us that she would update us on dad’s progress every couple of hours.
  - During the meeting, the CEO asked his assistant to update him on the latest numbers.
  - If you will update me on the project, I will pass the information on to our manager.
  - After the vet got the test results in, he was able to update the family on the dog’s illness.


* [[https://wordsinasentence.com/upended-in-a-sentence/][Upended]]

  =turned or set something upside down=

  - The frantic woman upended her purse dumping all of the contents out in search of her keys.
  - My toddler upended the laundry basket and left clothing all over the floor.
  - During the wreck, the vehicle upended and landed upside down.
  - A new mayoral candidate upended the race, causing the whole election to be topsy-turvy.


* [[https://wordsinasentence.com/upheaval-in-a-sentence/][Upheaval]]

  =an abrupt disruption or change=

  - The sudden closing of the interstate exit is going to be an upheaval for local residents.
  - When the rebels tried to remove the dictator from power, their actions created an upheaval that left the country in chaos.  
  - The upheaval caused by the unexpected closing of the discount store left many workers without salaries to feed their families.
  - While the new highway lanes are being built, the upheaval is sure to make rush hour traffic worse than it normally is.


* [[https://wordsinasentence.com/uphold-in-a-sentence/][Uphold]]

  =to support or defend something=

  - The mother coddles her grown son and will always uphold him, even when what he is doing is wrong.
  - We expect visitors to uphold our country’s rules even if they don’t agree with them.
  - After thinking about it for several hours, the judge decided to uphold the first judge’s decision and send the inmate back to jail.
  - Those who did not uphold or support Jim Crow Laws of the south worked together to tear them down.


* [[https://wordsinasentence.com/upholstery-in-a-sentence/][Upholstery]]

  =materials used to cover furniture=

  - Leather upholstery was added to the seats of the car to give it a different look.
  - For the couch upholstery, the designer decided to go with fabric of a neutral color.
  - Changing the upholstery on your dining room chair seats will help it sell faster.
  - Because the cat scratched up the recliner’s upholstery, we will need to buy a new chair without claw marks on the leather.


* [[https://wordsinasentence.com/upkeep-in-a-sentence/][Upkeep]]

  =the process of keeping something in good condition=

  - Because our yard requires so much upkeep, we hired a landscaping company to keep it pretty.
  - Money donations are needed to pay for the upkeep of the run-down cemetery.
  - The homeowners won’t pay for upkeep of their properties, so the houses are beginning to deteriorate.
  - Changing the oil in your car is an upkeep expense that will help keep your vehicle’s engine in good condition.


* [[https://wordsinasentence.com/uplift-in-a-sentence/][Uplift]]

  =to inspire and encourage someone=

  - Nothing can uplift a sad child’s spirits like a two-scoop ice cream cone.
  - The encouraging songs that the choir sings can uplift one’s spirits like no other.
  - Giving a motivational speech to uplift the young students, the man used his words to inspire the children to be great.
  - Saying kind things to uplift a person will do more good than saying hurtful things to bring them down.


* [[https://wordsinasentence.com/upon-in-a-sentence/][Upon]]

  =a formal form of the word ‘on’=

  - Upon receipt of this document, please give me a call to let me know it has made it to you.
  - Upon the king’s arrival, several of the courtyard singers burst out into song.
  - My mother drew upon her mother’s knowledge of cooking to create a fabulous meal.
  - Late at night, the police happened upon a robbery that was taking place at the local bank.


* [[https://wordsinasentence.com/uppity-in-a-sentence/][Uppity]]

  =snobbish, self-absorbed, filled with self importance=

  - The elderly lady was an uppity woman who believed her breeding and social class made her better than others.
  - Mariah’s uppity boss always spoke about what a great job he did and how the company could not function without him.
  - Some people believe that women who belong to country clubs are uppity gossipers who look down on the middle class.
  - Her uppity sister-in-law was such a snob that she refused to buy anything but high-priced designer clothes.


* [[https://wordsinasentence.com/upright-in-a-sentence/][Upright]]

  =sitting or standing in a straight position=

  - I can never fall asleep if I am sitting in an upright position.
  - Hearing the noise in the hall way, the frightened woman quickly sat upright in her bed.
  - No matter how many times we sit the flagpole upright, it always ends up slanted.
  - The doctor claims that sitting with upright posture can help one avoid the back problems that come along with slumping.


* [[https://wordsinasentence.com/uproar-in-a-sentence/][Uproar]]

  =a situation in which many people are upset or angry=

  - Uproar over the art piece began after it was found to be a fake.
  - The president sparked an uproar when he shared top secret information with the Russians.
  - Even though the uproar is over, a few people are still upset about the scam.
  - The public uproar should have taught the airline company how to better handle upset customers.


* [[https://wordsinasentence.com/uproarious-in-a-sentence/][Uproarious]]

  =exceptionally funny=

  - The comedian’s jokes were so uproarious I laughed until my stomach began to hurt.
  - Throughout the uproarious movie, everyone in the theater was laughing.
  - Even the singer could not help but chuckle when she heard the uproarious parody of her hit tune. 
  - The tension at the party was broken when everyone started to laugh at Rick’s uproarious dance moves. 


* [[https://wordsinasentence.com/upset-in-a-sentence/][Upset]]

  =emotionally troubled or stressed=

  - News of her father’s death caused the girl to become very upset.
  - Many students were upset by the news that their beloved principal would not be returning.
  - I was upset when learning that I did not get the promotion but have since calmed down.
  - Seeing the puppy hurt on the side of the road made the kind-hearted driver feel sad and upset.


* [[https://wordsinasentence.com/upshot-in-a-sentence/][Upshot]]

  =the final or end result of an event or situation=

  - The upshot of the investigation is that the police will not face any charges.
  - The upshot of the program is that several of the students were able to graduate on time.
  - After the loan changes were made, the upshot was that more people qualified than in the past.
  - An insurance agent explained that the upshot of getting a speeding ticket is usually increased rates.


* [[https://wordsinasentence.com/upside-in-a-sentence/][Upside]]

  =a positive benefit; an advantage=

  - The only upside to staying in the crappy hotel is that the rooms are cheaper than any other place.
  - One upside to shopping online is that you can often get better deals than when shopping in store.
  - The upside to Facebook is that it helps keep you connected with family and friends who live far away.
  - The salesman tried to get me to buy the product, but couldn’t give me one upside or benefit.


* [[https://wordsinasentence.com/upward-in-a-sentence/][Upward]]

  =moving towards a higher place=

  - We continued to climb upward, only stopping when we reached the building’s top floor.
  - The firefighter became more nervous as he moved upward towards the top of the ladder.
  - Placing his cards upward, the poker player showed that he had two aces.
  - The ill child’s fever climbed upward and did not break until she was given medicine.


* [[https://wordsinasentence.com/urbane-in-a-sentence/][Urbane]]

  =marked by sophistication=

  - Henry is an urbane traveller who has visited over eighty countries.
  - When the urbane heiress walked through the hotel, the hotel manager promptly greeted her with a bouquet of roses. 
  - Everyone wants to know why the urbane city people have decided to move to our small town.
  - Unimpressed by urbane matters, my father yawned when my boyfriend started to talk about the price of his expensive suit. 
  - Brett is our best appliance salesman because his urbane personality can win over even the grouchiest female.
  - When Marsha goes to bars, she often smokes fancy cigarettes to make herself appear urbane.
  - Everything from the man’s tailored suit to his Italian shoes and expensive watch screamed urbane. 


* [[https://wordsinasentence.com/urbanity-in-a-sentence/][Urbanity]]

  =being suave and sophisticated=

  - The suave man’s urbanity made him a shoe-in with the young ladies as well as their mothers.
  - An air of urbanity surrounded the cultured gentleman as he told stories about meeting kings and dancing with queens.
  - My mother noticed the man’s urbanity and knew that he was from a sophisticated, well-to-do upbringing.
  - With a sense of polished urbanity, the suave prince showed off his refined dance skills at the ball.


* [[https://wordsinasentence.com/urbanization-in-a-sentence/][Urbanization]]

  =the process by which cities grow=

  - Urbanization of the town can only occur if large employers move into the area.
  - The map showed levels of urbanization in growing cities versus ones not showing much progress.
  - Rapid urbanization happened after several large groups of immigrants moved into the city.
  - Once covered with forests, urbanization of the area occurred through the building of factories and housing.


* [[https://wordsinasentence.com/urchin-in-a-sentence/][Urchin]]

  =a young child that runs through the streets in dirty clothing, behaving badly=

  - The little urchin ran through the streets of New York barefoot and looking for trouble.
  - Trying to be like the street urchin he saw on T.V., the little boy dressed himself in rags and ran through his room as if he were in an alley.
  - The orphan had turned into a street urchin and made mischief as a pickpocket downtown.
  - During the mid-1800s, the ragged boy lived as an urchin in the city’s poorest slums.


* [[https://wordsinasentence.com/urge-in-a-sentence/][Urge]]

  =to strongly persuade=

  - Even though my wife hates crowded events, I tried to urge her to go to the career fair because it would help her get a job.
  - “Disloyal friends will try to urge you to do something bad because they want to get you in trouble, but please refrain from doing those things,” the mother pleaded with her teenager.
  - When Sally would constantly urge her friends to join her soccer team, her pleadings grew irritating to them.
  - Fitness commercials will urge people to join their gym by promising them that they will lose weight in a matter of a few weeks.


* [[https://wordsinasentence.com/urgency-in-a-sentence/][Urgency]]

  =a state requiring quick action=

  - The urgency of the situation required an ambulance to be called right away.
  - Moving with a sense of urgency, the officer sped towards the scene of the accident.
  - Lawmakers knew the urgency of the situation meant a quick decision was needed.
  - Because the town faced some urgency to fix the water issues, they asked the city workers to work over the weekend.


* [[https://wordsinasentence.com/urgent-in-a-sentence/][Urgent]]

  =very important and needing immediate attention=

  - The bill collector left an urgent message in hopes that the debtor would call her back right away.
  - On the news, the mother of the missing child gave out an urgent plea for the return of her son.
  - My boss insists that the project is urgent and asks that we complete it by midnight.
  - The surgery is urgent as the patient will not live through the night without it.


* [[https://wordsinasentence.com/urgently-in-a-sentence/][Urgently]]

  =in a way that requires quick action=

  - The telegram was sent urgently to quickly warn the other ship of the iceberg.
  - Scientists are working urgently to find a way to find a cure for the HIV epidemic.
  - An operation is urgently needed if the car crash victim is to survive.
  - Because current treatments are not working, new cancer medicines are urgently needed.


* [[https://wordsinasentence.com/ursine-in-a-sentence/][Ursine]]

  =resembling or relating to a bear=

  - The hairy man resembled a grizzly and was as tall as any ursine in the woods.
  - Growling at the campers, the ursine creature sounded like a bear but looked like a wolf. 
  - The weird looking specimen was in ursine form with the body of a bear but the face of a man.
  - Both the Three Little Bears and Winnie the Pooh have an ursine connection.


* [[https://wordsinasentence.com/usage-in-a-sentence/][Usage]]

  =the action of something being used=

  - The usage of a car allows us humans to travel great distances in a short amount of time, something that has helped us develop as a civilization quickly.
  - The usage of an aircraft allows people to travel from one end of the earth to the other in a matter of days, a concept once completely alien to people of the past.
  - If there’s one thing my college professor really hates, it’s the usage of cell phones by his students during his lecture.
  - Most people don’t like getting up to change the channel on the television, so they appreciate the usage of a remote to make it easier.


* [[https://wordsinasentence.com/useful-in-a-sentence/][Useful]]

  =helpful; handy=

  - My grandmother expects all children to be useful and help with household chores.
  - Our handyman is the most useful employee on the farm.
  - An electric mixer is useful when baking a cake since it mixes the batter much faster than you could by hand.
  - When traveling around the city, a color-coded map of Paris might be useful.


* [[https://wordsinasentence.com/usefully-in-a-sentence/][Usefully]]

  =in a way that is beneficial or helpful=

  - The man must take medicine for his failing kidneys to function usefully.
  - If you do not have any of the gear needed to play football, there is no way for you to usefully participate.
  - I hope that my wife spends some of her pay usefully instead of blowing it all on things we don’t need.
  - The salesman showed the couple a compact vehicle in which the back seat could be usefully folded down for storage.


* [[https://wordsinasentence.com/useless-in-a-sentence/][Useless]]

  =not having value or purpose=

  - If you won’t take the medicine that he gives you, going to the doctor is useless.
  - Wearing rain boots was useless since the flood water was up to our hips.
  - The online researcher felt that her computer was useless without the internet.
  - The garage sale box was full of useless stuff that no one in our family can use.


* [[https://wordsinasentence.com/usher-in-a-sentence/][Usher]]

  =a guide that shows someone to their seats=

  - Guiding the man and women to their table, the usher let the couple know that their waiter would be there soon.
  - The church usher comes to service early to help visitors find a pew.
  - After poking around for a few minutes, my sister and I asked an usher to help us find two seats in the dark theater.
  - A wedding usher was brought in to walk guests down the aisle and to their assigned seating.


* [[https://wordsinasentence.com/usual-in-a-sentence/][Usual]]

  =normal; typical=

  - We will give up our usual trip to the beach for a vacation to somewhere exotic.
  - Will you arrive at the usual time or will you come later this afternoon?
  - The mother’s usual approach for getting the baby didn’t sleep didn’t work, so she had to try something different.
  - A group of bankers gathered for their weekly meeting at their usual café.


* [[https://wordsinasentence.com/usually-in-a-sentence/][Usually]]

  =normally; typically=

  - The woman usually cooks at home to save money, but tonight has decided to splurge on takeout. 
  - We usually walk to work but sometimes take a cab when it is raining.
  - The usually full parking lot was strangely empty last Saturday and Sunday evening.
  - Because she is usually chatty, it seems odd that our neighbor didn’t speak to us this morning.


* [[https://wordsinasentence.com/usufruct-in-a-sentence/][Usufruct]]

  =a law legal right by one person over the property of another=

  - The man’s will gives his wife 30 year usufruct, but after that the house would go to his children.
  - Usufruct lands in the area are worked and lived on by one family but legally owned by another.
  - When the man dies, the usufruct will disappear and ownership of the land will go back to his aunt.
  - In Louisiana, Usufruct is a real right to property owned by another for a limited period of time.


* [[https://wordsinasentence.com/usurp-in-a-sentence/][Usurp]]

  =to take over; to seize or use something without authority=

  - Since Lisa could not attend the dance, Marie had plans to usurp the title of homecoming queen.  
  - After the king dies, his brother will usurp the throne from the prince. 
  - While the dictator had no legal power, he felt it was his right to usurp the government’s position. 
  - The president does not usurp his position because he is elected by the people.
  - Is your ambition driving you to usurp your boss?
  - Since no one knew his twin brother was dead, Roger had no problem when he tried to usurp his brother’s extravagant lifestyle.  
  - The adorable pony will usurp you of all your carrots if you stand too close to him.


* [[https://wordsinasentence.com/usury-in-a-sentence/][Usury]]

  =the act of lending money at ridiculously excessive rates of interest=

  - When borrowing money, check the interest rate for usury because you do not want to pay an extreme rate of interest.
  - Rick refused the loan offer because the terms outdid usury and forced him to pay a sixty percent interest rate on the loan.
  - While Pat was only a teenager, she understood usury and applied a hefty interest rate to the loans she gave her brother.
  - The dishonest lender's usury caused hundreds of people to lose their homes when they failed to meet the high interest payments. 
  - When Ann was applying for a credit card, I told her to avoid usury by not accepting a card with a steep rate of interest.
  - People with poor credit often have no choice but to accept the usury offered by high interest rate lenders.
  - After noticing the credit card’s usury, Tad sought legal advice on obtaining a refund of his excessive interest payments. 


* [[https://wordsinasentence.com/utensil-in-a-sentence/][Utensil]]

  =a tool with a particular use, especially in a kitchen or house=

  - The only thing needed to seal the deal is a writing utensil to sign the check.
  - I’m sure each utensil in the chef’s kitchen serves a purpose, but most of them are foreign to me.
  - After shining each utensil, the maid make sure to place the silverware back neatly in the cabinet.
  - A whisk is a useful kitchen utensil that makes it much easier to stir cake batter while baking.


* [[https://wordsinasentence.com/uterus-in-a-sentence/][Uterus]]

  =the pear-shaped organ of a woman in which a baby forms before being born=

  - The fertility doctor explained to the woman that she could not carry a baby in her uterus because it is unusually shaped.
  - Once the fertilized egg is implanted in the woman’s uterus, she becomes pregnant.
  - A uterus, or a womb, is the organ that allows mammals to grow fetuses inside the body.
  - As the pregnancy continues, the mother’s pear-sized uterus stretches to hold the growing baby.


* [[https://wordsinasentence.com/utilitarian-in-a-sentence/][Utilitarian]]

  =useful and not simply for appearance=

  - Because Ann sees her car only as a utilitarian asset that transports her, she is not concerned about its appearance.
  - The bed is comfortable and also includes utilitarian features like drawers and bookshelves.
  - Since April is a flight attendant and travels often, her apartment has a utilitarian design that allows her to efficiently perform her chores. 
  - The utilitarian house is designed to accommodate a man who is paralyzed from the waist down.


* [[https://wordsinasentence.com/utility-in-a-sentence/][Utility]]

  =useful and able to perform several different functions=

  - The utility vehicle was designed to carry loads more efficiently than other types of trucks.
  - A utility knife has many purposes and is often used to dice, chop, or mince.
  - Buying a utility trailer is a company must since we can use it to store, haul, and show craft related products.
  - In my grandmother’s house, the utility room is a catch-all area used to store all of the things she doesn’t use on a day to day basis.


* [[https://wordsinasentence.com/utilization-in-a-sentence/][Utilization]]

  =the use of something, usually in a practical way=

  - For max utilization of the space, we need to buy compact storage containers.
  - Capacity utilization is at 75 percent meaning 25 percent of the warehouse is still waiting to be filled.
  - Because he oversees equipment utilization, it is the manager’s job to make sure all of the company’s tools are being used for production.
  - Changes in utilization of the workers means that we will no longer have too many clerks in the front and none in the back.


* [[https://wordsinasentence.com/utilize-in-a-sentence/][Utilize]]

  =to use something, usually in a practical way=

  - If you utilize your time wisely, you will be able to finish all of your chores by lunch.
  - The disorganized woman didn’t know how to utilize her space, so her house stayed cluttered.
  - If the company would utilize all of the parts they have in storage, they could save money on the ordering of new ones.
  - A new schedule is being made to utilize the workers more efficiently and make sure that no one is at work when they are not needed.


* [[https://wordsinasentence.com/utmost-in-a-sentence/][Utmost]]

  =greatest; ultimate=

  - For a secret service agent, it is of the utmost importance that the President remains safe.
  - In the NFL, the utmost achievement for a team is to win the Super Bowl.
  - For a spy, secrecy is of the utmost importance.
  - The man clenched his fist, his patience tested to the utmost limit.
  - According to their Hippocratic Oath, it is of the utmost importance that a doctor never does harm.
  - In that moment, it was of the utmost importance to the paramedic that he save this child’s life.
  - If you hope to make a good impression, you must treat your host with the utmost respect.


* [[https://wordsinasentence.com/utopia-in-a-sentence/][Utopia]]

  =a perfect world=

  - In Jane’s utopia, everyone would wait on her and call her Princess Jane.
  - This world is not a utopia because it contains too much crime and starvation.
  - In a utopia, there is plenty of food and water for everyone.
  - The book’s main setting is a utopia in which everyone is satisfied with what he or she has.
  - Although Sheila loved her neighbors, sometimes she wished she lived in a utopia where she was not awakened every morning by the sound of a lawn mower. 
  - Why are you calling this imperfect world filled with hatred and violence a utopia? 
  - For his class project, Jim created a diorama of his dream world, his utopia. 


* [[https://wordsinasentence.com/utter-in-a-sentence/][Utter]]

  =total or complete=

  - The billionaire’s utter lack of arrogance makes him very approachable.
  - Since my son showed an utter disregard for others by driving recklessly, he no longer has a license. 
  - The accident caused Tina to have an utter loss of memory.
  - Because Linda is very clumsy, she is an utter failure as a waitress.


* [[https://wordsinasentence.com/utterance-in-a-sentence/][Utterance]]

  =spoken word; something that someone says=

  - Every utterance coming from the mouth of the accused thief made the king even more angry.
  - The angry wife ignored her husband’s every utterance, rudely pretending that she didn’t hear him speaking.
  - The baby’s first real utterance was the word “dada.”
  - After being kidnapped, the victim’s every utterance was muffled by the duct tape wrapped around her mouth.


* [[https://wordsinasentence.com/uxorious-in-a-sentence/][Uxorious]]

  =describes a man who shows great (often extreme) submission or fondness towards his wife=

  - The uxorious husband catered to his wife’s every whim, cooking her dinner at night and running her bath water in the morning.
  - Doting and uxorious, my husband shows his fondness of me through gifts and acts of service.
  - The other husbands at the poker game couldn’t believe how submissive the uxorious husband was to his wife.
  - My aunt has her uxorious husband wrapped around her finger as he answers to her every beck and call no matter the time of day.


