* [[https://wordsinasentence.com/xenophile-in-a-sentence/][Xenophile]]

  =a xenophile is a person attracted to foreign people and customs=

  - The American professor is a xenophile particularly interested in Roman cathedrals.
  - Interested in French cuisine, the British xenophile traveled to France for a cooking class.
  - Fascinated by Greek architecture, the Spanish xenophile researched Greek architects.
  - As a xenophile attracted to Mayan ruins, the American spent the summer in Chichen Itza, Cancun.


* [[https://wordsinasentence.com/xenophobia-in-a-sentence/][Xenophobia]]

  =a dread or dislike of anything or anyone foreign, especially people from other cultures and races=

  - Shane’s xenophobia prevents him from going to social events where there are people he does not know. 
  - If xenophobia did not exist, racism would not exist because people would not dislike others because of their differences.
  - The boy’s xenophobia arose when he watched a black man kill his mother.
  - As a foreign aid volunteer, you should not have a case of xenophobia that hinders you from socializing with people.


* [[https://wordsinasentence.com/xeric-in-a-sentence/][Xeric]]

  =an area or climate that gets a very low volume of water and is often extremely dry=

  - The xeric environment of the desert makes it difficult for plants that require a substantial amount of water to grow.
  - Grandma wished she could grow beautiful, red roses or bright pink tulips in her garden, but the xeric climate of Arizona was too hot and dry for the plants to survive.
  - Egypt has a xeric environment where people survive in dry, warm conditions with limited water supplies.
  - The lost man searched the empty, xeric land for water but all he found were tumbleweeds, cacti, and rattlesnakes.


* [[https://wordsinasentence.com/xylem-in-a-sentence/][Xylem]]

  =plant tissue that carries water and minerals from the roots to the leaves=

  - Xylem carried water from the root of the plant to the very center of the leaf.
  - Without xylem, the plant would have no tissue to bring nutrients from its bottom to its top.
  - Not only is water and minerals moved up to the leaf through the plants xylem, so is bacteria.
  - Serving as transport tissue, the rose’s xylem moves water from the bottom of the vase up to its green leaves.


