* [[https://wordsinasentence.com/yahoo-in-a-sentence/][Yahoo]]

  =a rude, coarse and wild person=

  - One day in her classroom, Ms. Howard determined that the yahoo in class needed to be punished for talking back to her in a rowdy way.
  - Every time the mother and her two-year old son went to the grocery store, her yahoo would turn into a different child throwing a temper tantrum and being completely out of control.
  - Jails often contain at least one yahoo who has to be isolated due to his behavior being hazardous to himself, the officers in the jail and the other prisoners. 
  - The emergency room physician says every yahoo who came through the ER usually screams obscenities, cries uncontrollably and tells elaborate lies about their injuries.


* [[https://wordsinasentence.com/yammer-in-a-sentence/][Yammer]]

  =to excessively complain about something=

  - Her grandfather liked to yammer on and on about how things were better back in the old days.
  - Mike yearned for the day when his wife wouldn’t yammer on about cooking, cleaning, and countless other little annoyances.
  - Milena listened to her friends yammer for at least 30 minutes about how much homework they had.
  - She got so sick of listening to her brother yammer about how unfair it was that she got more money than him for Christmas that she threw a twenty-dollar bill at him.


* [[https://wordsinasentence.com/yank-in-a-sentence/][Yank]]

  =to pull something quickly=

  - The robber tried to yank the man’s briefcase from his hand, but didn’t pull hard enough.
  - You have to yank the chain inside the toilet to stop it from running.
  - The company tried to yank older workers into the tech world by providing them with intense computer classes.
  - Both boys tried to yank down the balloons that were penned up in the party hall.


* [[https://wordsinasentence.com/yarn-in-a-sentence/][Yarn]]

  =to tell a long and unlikely story=

  - The old man loved to yarn on and on about the old days, where he was supposedly some sort of hero of great fame and renown.
  - Most everyone knows someone that tends to yarn incessantly about their alleged feats and accomplishments without any evidence.
  - Many people like to yarn around a campfire, spinning fantastic tales and stories that probably aren’t true but nevertheless fun to listen to.
  - Someone that likes to yarn on about unlikely tales is either a pathological liar or a great storyteller.


* [[https://wordsinasentence.com/yearn-in-a-sentence/][Yearn]]

  =to have a deep desire for something or someone=

  - When my sister was pregnant, all she did was yearn for chocolate ice cream and French fries.
  - I yearn to travel as a senior citizen because I never went anywhere in my younger days.
  - If you yearn to expand your taste buds, you should try food from a different culture.
  - Sometimes, the young nun would yearn to dance to rock and roll music.


* [[https://wordsinasentence.com/yeast-in-a-sentence/][Yeast]]

  =a single-celled, microscopic fungi used in many food items, nutrition, and even bio-fuels=

  - It’s hard to believe that yeast, a common fungus, is used to make something as delicious as pizza dough.
  - When yeast converts sugar into alcohol, it produces bubbly champagne and perfectly fermented beer.
  - Despite being a one-celled fungus, yeast has many nutritional values like protein, vitamin B, and several other minerals.
  - Many women take yeast capsules as a supplement or sprinkle it in place of their parmesan cheese to increase their vitamin intake and help grow stronger nails.


* [[https://wordsinasentence.com/yellow-journalism-in-a-sentence/][Yellow Journalism]]

  =fake news that is not based on fact but exaggerations=

  - The paper published a piece of yellow journalism that was nothing but exaggerated facts.
  - Believing the article to be nothing more than yellow journalism, the editor decided not to publish the fake piece.
  - The celebrity insisted at the tabloid tale was yellow journalism, only published to tarnish his good name.
  - Real reporters base their articles on facts, not made-up yellow journalism mumbo jumbo.


* [[https://wordsinasentence.com/yellow-journalism-in-a-sentence-2/][Yellow Journalism]]

  =journalism that exaggerates distorts or exploits the news to attract readers=

  - In the 1800s, Spain and the US were pushed into war because of yellow journalism that exaggerated the facts.
  - Yellow journalism often presents itself with an untrue story that is supposed to be funny goes viral on the internet.
  - Attention grabbing but untrue, the yellow journalism piece attracted millions of readers across the globe.
  - Accused of publishing yellow journalism, the writer was appalled that people would think his work exploited the poor.


* [[https://wordsinasentence.com/yeoman-in-a-sentence/][Yeoman]]

  =a farmer long-ago who owned a small amount of land=

  - The yeoman was plowing the field on his master’s land.
  - The arranged marriage was between the yeoman and a neighboring farmer’s daughter.
  - Because he was born to a yeoman, it was likely that he would grow up to farm the same land.
  - The yeoman was slowly saving his money so he could purchase his own farm.


* [[https://wordsinasentence.com/yes-in-a-sentence/][Yes]]

  =given as a positive or agreeing answer when asked a question=

  - Yes, I can sell you two new pairs of shoes for the rice of one.
  - If you say yes to another piece of cake, I will bring you one.
  - When my mother says “yes”, my father says “no way.”
  - The happy girl said yes to buying her dream dress.


* [[https://wordsinasentence.com/yesteryear-in-a-sentence/][Yesteryear]]

  =a point in the past, usually thought of in a nostalgic way=

  - Grandma frequently talked about the beauty of yesteryear when gas was less than a dollar and she could buy a handful of candy for a quarter. 
  - The Amish people live in yesteryear where technology is unheard of and everything is made by hand.
  - Games of yesteryear like jacks, yoyos, and backgammon have recently come back in style.
  - Historical reenactments recreate scenes from yesteryear.


* [[https://wordsinasentence.com/yield-in-a-sentence/][Yield]]

  =to bow out=

  - Since I do not know a great deal about the subject, I will yield this question to my well-informed colleague.
  - The congressman has decided to stop speaking and will now yield the floor to the vice-president.
  - When making a right at the light, you must yield to drivers who are in the turning lane.
  - The debater refuses to yield the podium to his challenger. 


* [[https://wordsinasentence.com/yoga-in-a-sentence/][Yoga]]

  =an ancient art based on a harmonizing system of development for the body, mind, and spirit through breathing exercises and exercise=

  - Yoga is a combination of three things: various postures, breathing patterns and mindful meditation.
  - Relaxing yoga and meditation techniques can be carried out in the comfort of your own home.
  - Yoga classes are being held to teach students the basics of how to harmonize one’s body, mind, and spirit.
  - Yoga is more than just doing poses, the ancient art involves structured breathing and the centering of one’s mind.


* [[https://wordsinasentence.com/yoke-in-a-sentence/][Yoke]]

  =an attachment for two animals side by side with a bar across the top of their necks and each loop around their heads=

  - Pioneers put their oxen’s heads through the rings of the yoke with the attached straps stretched up to the wagon.
  - In order to plow his field, a yoke around the horses’ heads made it easier for the farmer to lead his team straight down the rows of crops.
  - After the yoke was fixed around the heads of the animals, they were led away from the rest of the pack.
  - A small yoke was used for the two lead dogs in the dog sled race allowing them to run together.


* [[https://wordsinasentence.com/yonder-in-a-sentence/][Yonder]]

  =in a distant, indicated place; over there=

  - The creek is about a mile or so yonder.
  - It was hard to make out the mountain top up yonder, due to the heavy fog that had settled in.
  - The sheep escaped while the shepherd slept to grab a drink from the creek that flows out yonder.
  - Heading out yonder, Kevin came face to face with a lion that had been sleeping in the bushes.


* [[https://wordsinasentence.com/yore-in-a-sentence/][Yore]]

  =a very long time ago=

  - In the days of yore, the Internet did not exist.
  - My grandmother often talks about her life of yore as a small girl.
  - As a retiring teacher, I often recall the days of yore when a chalkboard was the main method of displaying lessons.
  - The walk through the recreated slave ship took us back to a period of yore that made most of us feel sad.


* [[https://wordsinasentence.com/youth-in-a-sentence/][Youth]]

  =young people (usually considered a group)=

  - Several teenagers started a church youth group where they can pray and study.
  - While coaching the youth little league team, Liam enjoyed helping kids learn to play ball.
  - Youth are allowed to attend the event, but they cannot enter areas that are for adults only.
  - A youth movement is underway to strengthen the young people’s interest in government.


* [[https://wordsinasentence.com/yule-in-a-sentence/][Yule]]

  =an old term for the Christmas holiday=

  - The Yule holiday is when we set up trees in our homes and decorate them with ornaments and lights.
  - Our favorite holiday is Yule, in which we give presents to our loved ones and enjoy the winter weather.
  - If you live in an extremely warm locale your yule holiday may include Santa Claus but will likely not include snow.
  - No one really uses the term ‘yule’ to refer to Christmas anymore, but that is what the holiday was once called.


* [[https://wordsinasentence.com/yuletide-in-a-sentence/][Yuletide]]

  =an old term for the Christmas season=

  - Yuletide is a time in which we celebrate Christmas, but for a lot of people that season is mostly just about presents and snow.
  - You will know when Yuletide is coming based on how many Christmas cartoons are beginning to come on television.
  - The Yuletide season is my favorite, since it includes presents, snow, and of course Christmas, which is the best holiday of all.
  - I cannot imagine how some people could dislike the Yuletide season, considering how great and wonderful Christmas is.


